-- ============================================================================
-- DROP AND CREATE TABLES (drop-all mode) - Clean slate + Normalized schema
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Tables: 3
-- Total Raw Fields: 12
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
-- Generated by rulebook-to-postgres tool
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Employees: Table: Employees — people who submit expense reports or review them.
-- ----------------------------------------------------------------------------
CREATE TABLE employees (
  employee_id                         TEXT                 PRIMARY KEY,
  first_name                          TEXT                ,
  last_name                           TEXT                ,
  email_address                       TEXT                ,                     -- Used as the click-to-login identity.
  role                                TEXT                ,                     -- employee | manager | finance
  budget_limit                        NUMERIC                                   -- Per-report ceiling above which reports are flagged over-budget. Applies to submitters; reviewers (manager/finance) can be left null.
);
COMMENT ON TABLE employees IS 'Table: Employees — people who submit expense reports or review them.';
COMMENT ON COLUMN employees.email_address IS 'Used as the click-to-login identity.';
COMMENT ON COLUMN employees.role IS 'employee | manager | finance';
COMMENT ON COLUMN employees.budget_limit IS 'Per-report ceiling above which reports are flagged over-budget. Applies to submitters; reviewers (manager/finance) can be left null.';

-- ----------------------------------------------------------------------------
-- ExpenseReports: Table: ExpenseReports — one submission, containing many line items.
-- ----------------------------------------------------------------------------
CREATE TABLE expense_reports (
  expense_report_id                   TEXT                 PRIMARY KEY,
  name                                TEXT                ,                     -- Short title of the report.
  employee                            TEXT                ,                     -- Submitter.
  approval_status                     TEXT                                      -- pending | approved | rejected
);
COMMENT ON TABLE expense_reports IS 'Table: ExpenseReports — one submission, containing many line items.';
COMMENT ON COLUMN expense_reports.name IS 'Short title of the report.';
COMMENT ON COLUMN expense_reports.employee IS 'Submitter.';
COMMENT ON COLUMN expense_reports.approval_status IS 'pending | approved | rejected';

-- ----------------------------------------------------------------------------
-- ExpenseItems: Table: ExpenseItems — individual line items on a report.
-- ----------------------------------------------------------------------------
CREATE TABLE expense_items (
  expense_item_id                     TEXT                 PRIMARY KEY,
  name                                TEXT                ,                     -- Short description of the expense.
  expense_report                      TEXT                ,                     -- Parent report.
  amount                              NUMERIC                                   -- Dollar amount of this line item.
);
COMMENT ON TABLE expense_items IS 'Table: ExpenseItems — individual line items on a report.';
COMMENT ON COLUMN expense_items.name IS 'Short description of the expense.';
COMMENT ON COLUMN expense_items.expense_report IS 'Parent report.';
COMMENT ON COLUMN expense_items.amount IS 'Dollar amount of this line item.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- ExpenseReports
CREATE INDEX IF NOT EXISTS idx_expense_reports_employee ON expense_reports (employee);

-- ExpenseItems
CREATE INDEX IF NOT EXISTS idx_expense_items_expense_report ON expense_items (expense_report);

-- 2 FK index(es) declared.
