-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 形状: Table: 形状
-- ----------------------------------------------------------------------------
INSERT INTO 形状 (形状id, 名称)
VALUES ('2', '形状2') ON CONFLICT (形状id) DO NOTHING;

INSERT INTO 形状 (形状id, 名称)
VALUES ('1', '形状1') ON CONFLICT (形状id) DO NOTHING;

INSERT INTO 形状 (形状id, 名称)
VALUES ('3', '形状3') ON CONFLICT (形状id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- 边: Table: 边
-- ----------------------------------------------------------------------------
INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('3', '3', '比', 14, 180) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('1', '1', '比', 4, 53) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('2', '2', '迪', 5, 90) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('2', '2', '阿', 5, 90) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('1', '1', '阿', 3, 37) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('1', '1', '西', 5, 90) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('3', '3', '阿', 14, 180) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('2', '2', '西', 5, 90) ON CONFLICT (边id) DO NOTHING;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('2', '2', '比', 5, 90) ON CONFLICT (边id) DO NOTHING;

