-- ============================================================================
-- UPDATE EFFORTLESS SCHEMA - the derived layer, rebuilt from the rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres. DO NOT EDIT — regenerated every build.
--
-- SAFE IN PRODUCTION. This file never drops a table, never drops a column,
-- and never deletes row data. It brings any database in line with the
-- rulebook that shipped in this same commit.
--
-- Views, calc_*/get_* functions and RLS policies hold NO data: they are a
-- pure function of the rulebook. They are dropped and recreated here rather
-- than migrated. Do NOT hand-write a migration that recreates a view or a
-- calc_* function — re-run this file instead.
--
-- A hand-authored migration is needed ONLY for table/column changes that
-- step 1 below cannot infer, and it should contain nothing else.
-- ============================================================================

BEGIN;
SET timezone = 'UTC';

-- === 1. Additive schema: missing tables and columns ========================
-- CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS only. Never drops.

-- ============================================================================
-- DROP AND CREATE TABLES (drop-all mode) - Clean slate + Normalized schema
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Tables: 5
-- Total Raw Fields: 27
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
-- Generated by rulebook-to-postgres tool
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Users: Login identities for the demo (stub auth).
-- ----------------------------------------------------------------------------
CREATE TABLE users (
  user_id                             TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  email                               TEXT                ,
  role                                TEXT                ,                     -- trainer | client | admin
  display_name                        TEXT                
);
COMMENT ON TABLE users IS 'Login identities for the demo (stub auth).';
COMMENT ON COLUMN users.role IS 'trainer | client | admin';

-- ----------------------------------------------------------------------------
-- Trainers: Personal trainers who log sessions and bill clients.
-- ----------------------------------------------------------------------------
CREATE TABLE trainers (
  trainer_id                          TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  email                               TEXT                ,
  full_name                           TEXT                ,
  hourly_rate                         NUMERIC                                   -- Default $/hour charged to clients.
);
COMMENT ON TABLE trainers IS 'Personal trainers who log sessions and bill clients.';
COMMENT ON COLUMN trainers.hourly_rate IS 'Default $/hour charged to clients.';

-- ----------------------------------------------------------------------------
-- Clients: Trainer's clients.
-- ----------------------------------------------------------------------------
CREATE TABLE clients (
  client_id                           TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  email                               TEXT                ,
  full_name                           TEXT                ,
  trainer                             TEXT                
);
COMMENT ON TABLE clients IS 'Trainer''s clients.';

-- ----------------------------------------------------------------------------
-- Invoices: An invoice bundles one or more sessions billed to a client.
-- ----------------------------------------------------------------------------
CREATE TABLE invoices (
  invoice_id                          TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  client                              TEXT                ,
  issue_date                          TIMESTAMPTZ         ,
  due_date                            TIMESTAMPTZ         ,
  tax_rate                            NUMERIC             ,                     -- Decimal (e.g. 0.08 = 8%).
  discount_amount                     NUMERIC             ,
  paid_amount                         NUMERIC             
);
COMMENT ON TABLE invoices IS 'An invoice bundles one or more sessions billed to a client.';
COMMENT ON COLUMN invoices.tax_rate IS 'Decimal (e.g. 0.08 = 8%).';

-- ----------------------------------------------------------------------------
-- Sessions: A logged training session. The atomic line item that rolls up into an invoice.
-- ----------------------------------------------------------------------------
CREATE TABLE sessions (
  session_id                          TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  client                              TEXT                ,
  session_date                        TIMESTAMPTZ         ,
  duration_hours                      NUMERIC             ,
  rate_override                       NUMERIC             ,                     -- If > 0, overrides the trainer's HourlyRate for this session.
  notes                               TEXT                ,
  invoice                             TEXT                
);
COMMENT ON TABLE sessions IS 'A logged training session. The atomic line item that rolls up into an invoice.';
COMMENT ON COLUMN sessions.rate_override IS 'If > 0, overrides the trainer''s HourlyRate for this session.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Clients
CREATE INDEX IF NOT EXISTS idx_clients_trainer ON clients (trainer);

-- Invoices
CREATE INDEX IF NOT EXISTS idx_invoices_client ON invoices (client);

-- Sessions
CREATE INDEX IF NOT EXISTS idx_sessions_client ON sessions (client);
CREATE INDEX IF NOT EXISTS idx_sessions_invoice ON sessions (invoice);

-- 4 FK index(es) declared.


-- === 2/3. Drop the derived layer ==========================================
-- Views first (they depend on functions), then functions leaf-up through the
-- DAG. CASCADE handles the dependency order Postgres knows about; the
-- explicit ordering handles calc_* functions that call other calc_*.
DO $drop_derived$
DECLARE r RECORD; v_views INT := 0; v_fns INT := 0;
BEGIN
    -- 2. Views (depend on functions, so they go first).
    FOR r IN (
        SELECT table_name FROM information_schema.views
         WHERE table_schema = 'public' AND table_name LIKE 'vw\_%'
           AND obj_description(
                 (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass, 'pg_class')
               IS DISTINCT FROM 'effortless:hand-maintained'
    ) LOOP
        EXECUTE 'DROP VIEW IF EXISTS public.' || quote_ident(r.table_name) || ' CASCADE';
        v_views := v_views + 1;
    END LOOP;

    -- 3. Functions, leaf-up through the DAG. A calc_* may call another
    --    calc_*, so depth-ordering avoids dependency errors.
    FOR r IN (
        WITH fn AS (
            SELECT p.oid, p.proname,
                   pg_get_function_identity_arguments(p.oid) AS args,
                   p.prosrc
              FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'public'
               AND (p.proname LIKE 'calc\_%' OR p.proname LIKE 'get\_%')
               AND COALESCE(obj_description(p.oid, 'pg_proc'), '')
                   IS DISTINCT FROM 'effortless:hand-maintained'
        )
        -- callers before callees: a function whose body names another
        -- generated function is an interior node and must go first.
        SELECT f.proname, f.args,
               (SELECT count(*) FROM fn c
                 WHERE c.oid <> f.oid AND f.prosrc LIKE '%' || c.proname || '%') AS depth
          FROM fn f
         ORDER BY depth DESC, f.proname
    ) LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS public.' || quote_ident(r.proname)
                || '(' || r.args || ') CASCADE';
        v_fns := v_fns + 1;
    END LOOP;

    RAISE NOTICE 'derived layer dropped: % views, % functions', v_views, v_fns;
END
$drop_derived$;


-- === 4. Static reference data =============================================
-- (no tables marked IsStatic — nothing to upsert)

-- === 5. Recreate calc_*/get_* functions ===================================
-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_trainers_total_sessions
-- Field: Trainers.TotalSessions
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_trainers_total_sessions(p_trainer_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM sessions WHERE calc_sessions_trainer(session_id) = (SELECT NULLIF(trainer_id, '') FROM trainers WHERE trainer_id = p_trainer_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_trainers_total_billed
-- Field: Trainers.TotalBilled
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_trainers_total_billed(p_trainer_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_invoices_total(invoice_id))::numeric), 0) FROM invoices WHERE calc_invoices_trainer(invoice_id) = p_trainer_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_trainers_total_outstanding
-- Field: Trainers.TotalOutstanding
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_trainers_total_outstanding(p_trainer_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_invoices_balance(invoice_id))::numeric), 0) FROM invoices WHERE calc_invoices_trainer(invoice_id) = p_trainer_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_clients_trainer_name
-- Field: Clients.TrainerName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Trainers

CREATE OR REPLACE FUNCTION calc_clients_trainer_name(p_client_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM trainers WHERE trainer_id = (SELECT trainer FROM clients WHERE client_id = p_client_id));
$$ LANGUAGE sql STABLE;

-- calc_clients_trainer_email
-- Field: Clients.TrainerEmail
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Email from related Trainers

CREATE OR REPLACE FUNCTION calc_clients_trainer_email(p_client_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email::text FROM trainers WHERE trainer_id = (SELECT trainer FROM clients WHERE client_id = p_client_id));
$$ LANGUAGE sql STABLE;

-- calc_clients_trainer_hourly_rate
-- Field: Clients.TrainerHourlyRate
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: HourlyRate from related Trainers

CREATE OR REPLACE FUNCTION calc_clients_trainer_hourly_rate(p_client_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT hourly_rate::numeric FROM trainers WHERE trainer_id = (SELECT trainer FROM clients WHERE client_id = p_client_id));
$$ LANGUAGE sql STABLE;

-- get_trainers_name
-- Helper function: Get Name from Trainers by TrainerId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_trainers_name(p_trainer_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM trainers WHERE trainer_id = p_trainer_id);
$$ LANGUAGE sql STABLE;

-- get_trainers_email
-- Helper function: Get Email from Trainers by TrainerId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_trainers_email(p_trainer_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email FROM trainers WHERE trainer_id = p_trainer_id);
$$ LANGUAGE sql STABLE;

-- get_trainers_full_name
-- Helper function: Get FullName from Trainers by TrainerId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_trainers_full_name(p_trainer_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name FROM trainers WHERE trainer_id = p_trainer_id);
$$ LANGUAGE sql STABLE;

-- get_trainers_hourly_rate
-- Helper function: Get HourlyRate from Trainers by TrainerId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_trainers_hourly_rate(p_trainer_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT hourly_rate FROM trainers WHERE trainer_id = p_trainer_id);
$$ LANGUAGE sql STABLE;

-- calc_clients_session_count
-- Field: Clients.SessionCount
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_clients_session_count(p_client_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM sessions WHERE client = (SELECT NULLIF(client_id, '') FROM clients WHERE client_id = p_client_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_clients_total_invoiced
-- Field: Clients.TotalInvoiced
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_clients_total_invoiced(p_client_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_invoices_total(invoice_id))::numeric), 0) FROM invoices WHERE client = p_client_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_clients_outstanding_balance
-- Field: Clients.OutstandingBalance
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_clients_outstanding_balance(p_client_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_invoices_balance(invoice_id))::numeric), 0) FROM invoices WHERE client = p_client_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_clients_overdue_count
-- Field: Clients.OverdueCount
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_clients_overdue_count(p_client_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM invoices WHERE client = (SELECT NULLIF(client_id, '') FROM clients WHERE client_id = p_client_id) AND calc_invoices_is_overdue(invoice_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_clients_status
-- Field: Clients.Status
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_clients_status(p_client_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN (calc_clients_overdue_count(p_client_id))::NUMERIC > 0 THEN ('Overdue')::text ELSE (CASE WHEN (calc_clients_outstanding_balance(p_client_id))::NUMERIC > 0 THEN ('Has Balance')::text ELSE ('Paid Up')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_invoices_client_name
-- Field: Invoices.ClientName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Clients

CREATE OR REPLACE FUNCTION calc_invoices_client_name(p_invoice_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM clients WHERE client_id = (SELECT client FROM invoices WHERE invoice_id = p_invoice_id));
$$ LANGUAGE sql STABLE;

-- calc_invoices_client_email
-- Field: Invoices.ClientEmail
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Email from related Clients

CREATE OR REPLACE FUNCTION calc_invoices_client_email(p_invoice_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email::text FROM clients WHERE client_id = (SELECT client FROM invoices WHERE invoice_id = p_invoice_id));
$$ LANGUAGE sql STABLE;

-- calc_invoices_trainer
-- Field: Invoices.Trainer
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Trainer from related Clients

CREATE OR REPLACE FUNCTION calc_invoices_trainer(p_invoice_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT trainer::text FROM clients WHERE client_id = (SELECT client FROM invoices WHERE invoice_id = p_invoice_id));
$$ LANGUAGE sql STABLE;

-- calc_invoices_trainer_name
-- Field: Invoices.TrainerName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: TrainerName from related Clients

CREATE OR REPLACE FUNCTION calc_invoices_trainer_name(p_invoice_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_clients_trainer_name((SELECT client FROM invoices WHERE invoice_id = p_invoice_id));
$$ LANGUAGE sql STABLE;

-- get_clients_name
-- Helper function: Get Name from Clients by ClientId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_clients_name(p_client_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM clients WHERE client_id = p_client_id);
$$ LANGUAGE sql STABLE;

-- get_clients_email
-- Helper function: Get Email from Clients by ClientId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_clients_email(p_client_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email FROM clients WHERE client_id = p_client_id);
$$ LANGUAGE sql STABLE;

-- get_clients_full_name
-- Helper function: Get FullName from Clients by ClientId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_clients_full_name(p_client_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name FROM clients WHERE client_id = p_client_id);
$$ LANGUAGE sql STABLE;

-- calc_invoices_subtotal
-- Field: Invoices.Subtotal
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_invoices_subtotal(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_sessions_line_total(session_id))::numeric), 0) FROM sessions WHERE invoice = p_invoice_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_invoices_tax_amount
-- Field: Invoices.TaxAmount
-- Type: calculated | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_invoices_tax_amount(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_subtotal(p_invoice_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT tax_rate FROM invoices WHERE invoice_id = p_invoice_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_invoices_grace_days
-- Field: Invoices.GraceDays
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_invoices_grace_days(p_invoice_id TEXT)
RETURNS INTEGER AS $$
  SELECT (45)::integer;
$$ LANGUAGE sql STABLE;

-- calc_invoices_days_since_due_date
-- Field: Invoices.DaysSinceDueDate
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_invoices_days_since_due_date(p_invoice_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((CURRENT_TIMESTAMP::date - (SELECT due_date::timestamptz FROM invoices WHERE invoice_id = p_invoice_id)::date))::integer;
$$ LANGUAGE sql STABLE;

-- calc_invoices_days_past_due
-- Field: Invoices.DaysPastDue
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_invoices_days_past_due(p_invoice_id TEXT)
RETURNS INTEGER AS $$
  SELECT (GREATEST(0, (COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_days_since_due_date(p_invoice_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_grace_days(p_invoice_id)) AS v) __safe_numeric), 0))))::integer;
$$ LANGUAGE sql STABLE;

-- calc_invoices_late_fee
-- Field: Invoices.LateFee
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_invoices_late_fee(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN (calc_invoices_days_past_due(p_invoice_id))::NUMERIC > 0 THEN (15)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_invoices_total
-- Field: Invoices.Total
-- Type: calculated | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_invoices_total(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_subtotal(p_invoice_id)) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_tax_amount(p_invoice_id)) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_late_fee(p_invoice_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT discount_amount FROM invoices WHERE invoice_id = p_invoice_id)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_invoices_balance
-- Field: Invoices.Balance
-- Type: calculated | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_invoices_balance(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_invoices_total(p_invoice_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT paid_amount FROM invoices WHERE invoice_id = p_invoice_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_invoices_is_paid
-- Field: Invoices.IsPaid
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_invoices_is_paid(p_invoice_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_invoices_balance(p_invoice_id))::NUMERIC <= 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_invoices_is_overdue
-- Field: Invoices.IsOverdue
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_invoices_is_overdue(p_invoice_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((NOT (calc_invoices_is_paid(p_invoice_id)) AND (calc_invoices_days_past_due(p_invoice_id))::NUMERIC > 0));
$$ LANGUAGE sql STABLE;

-- calc_invoices_status
-- Field: Invoices.Status
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_invoices_status(p_invoice_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_invoices_is_paid(p_invoice_id) THEN ('Paid')::text ELSE (CASE WHEN calc_invoices_is_overdue(p_invoice_id) THEN ('Overdue')::text ELSE ('Open')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_sessions_client_name
-- Field: Sessions.ClientName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Clients

CREATE OR REPLACE FUNCTION calc_sessions_client_name(p_session_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM clients WHERE client_id = (SELECT client FROM sessions WHERE session_id = p_session_id));
$$ LANGUAGE sql STABLE;

-- calc_sessions_trainer
-- Field: Sessions.Trainer
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Trainer from related Clients

CREATE OR REPLACE FUNCTION calc_sessions_trainer(p_session_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT trainer::text FROM clients WHERE client_id = (SELECT client FROM sessions WHERE session_id = p_session_id));
$$ LANGUAGE sql STABLE;

-- calc_sessions_client_hourly_rate
-- Field: Sessions.ClientHourlyRate
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: TrainerHourlyRate from related Clients

CREATE OR REPLACE FUNCTION calc_sessions_client_hourly_rate(p_session_id TEXT)
RETURNS NUMERIC AS $$
  SELECT calc_clients_trainer_hourly_rate((SELECT client FROM sessions WHERE session_id = p_session_id));
$$ LANGUAGE sql STABLE;

-- calc_sessions_invoice_name
-- Field: Sessions.InvoiceName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Name from related Invoices

CREATE OR REPLACE FUNCTION calc_sessions_invoice_name(p_session_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name::text FROM invoices WHERE invoice_id = (SELECT invoice FROM sessions WHERE session_id = p_session_id));
$$ LANGUAGE sql STABLE;

-- get_invoices_name
-- Helper function: Get Name from Invoices by InvoiceId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_invoices_name(p_invoice_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM invoices WHERE invoice_id = p_invoice_id);
$$ LANGUAGE sql STABLE;

-- get_invoices_issue_date
-- Helper function: Get IssueDate from Invoices by InvoiceId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_invoices_issue_date(p_invoice_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT issue_date FROM invoices WHERE invoice_id = p_invoice_id);
$$ LANGUAGE sql STABLE;

-- get_invoices_due_date
-- Helper function: Get DueDate from Invoices by InvoiceId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_invoices_due_date(p_invoice_id TEXT)
RETURNS TIMESTAMPTZ AS $$
  SELECT (SELECT due_date FROM invoices WHERE invoice_id = p_invoice_id);
$$ LANGUAGE sql STABLE;

-- get_invoices_tax_rate
-- Helper function: Get TaxRate from Invoices by InvoiceId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_invoices_tax_rate(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT tax_rate FROM invoices WHERE invoice_id = p_invoice_id);
$$ LANGUAGE sql STABLE;

-- get_invoices_discount_amount
-- Helper function: Get DiscountAmount from Invoices by InvoiceId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_invoices_discount_amount(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT discount_amount FROM invoices WHERE invoice_id = p_invoice_id);
$$ LANGUAGE sql STABLE;

-- get_invoices_paid_amount
-- Helper function: Get PaidAmount from Invoices by InvoiceId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_invoices_paid_amount(p_invoice_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT paid_amount FROM invoices WHERE invoice_id = p_invoice_id);
$$ LANGUAGE sql STABLE;

-- calc_sessions_effective_rate
-- Field: Sessions.EffectiveRate
-- Type: calculated | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_sessions_effective_rate(p_session_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN ((SELECT rate_override FROM sessions WHERE session_id = p_session_id))::NUMERIC > 0 THEN ((SELECT rate_override FROM sessions WHERE session_id = p_session_id))::text ELSE (calc_sessions_client_hourly_rate(p_session_id))::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_sessions_line_total
-- Field: Sessions.LineTotal
-- Type: calculated | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_sessions_line_total(p_session_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_sessions_effective_rate(p_session_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT duration_hours FROM sessions WHERE session_id = p_session_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_sessions_is_billed
-- Field: Sessions.IsBilled
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_sessions_is_billed(p_session_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (NOT ((((SELECT NULLIF(invoice, '') FROM sessions WHERE session_id = p_session_id)) IS NULL OR ((SELECT NULLIF(invoice, '') FROM sessions WHERE session_id = p_session_id))::text = '')))::boolean;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================



-- === 6. Custom functions (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 7. Recreate vw_* views ===============================================
-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 5
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_sessions CASCADE;
DROP VIEW IF EXISTS vw_invoices CASCADE;
DROP VIEW IF EXISTS vw_clients CASCADE;
DROP VIEW IF EXISTS vw_trainers CASCADE;
DROP VIEW IF EXISTS vw_users CASCADE;

-- ----------------------------------------------------------------------------
-- vw_users: Login identities for the demo (stub auth).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_users CASCADE;
CREATE VIEW vw_users WITH (security_invoker = ON) AS
SELECT
  t.user_id,
  t.name,
  t.email,
  t.role,                                                                       -- trainer | client | admin
  t.display_name
FROM users t;

-- ----------------------------------------------------------------------------
-- vw_trainers: Personal trainers who log sessions and bill clients.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_trainers CASCADE;
CREATE VIEW vw_trainers WITH (security_invoker = ON) AS
SELECT
  t.trainer_id,
  t.name,
  t.email,
  t.full_name,
  t.hourly_rate,                                                                -- Default $/hour charged to clients.
  calc_trainers_total_sessions(t.trainer_id) AS total_sessions,
  calc_trainers_total_billed(t.trainer_id) AS total_billed,
  calc_trainers_total_outstanding(t.trainer_id) AS total_outstanding
FROM trainers t;

-- ----------------------------------------------------------------------------
-- vw_clients: Trainer's clients.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_clients CASCADE;
CREATE VIEW vw_clients WITH (security_invoker = ON) AS
SELECT
  t.client_id,
  t.name,
  t.email,
  t.full_name,
  t.trainer,
  calc_clients_trainer_name(t.client_id) AS trainer_name,
  calc_clients_trainer_email(t.client_id) AS trainer_email,
  calc_clients_trainer_hourly_rate(t.client_id) AS trainer_hourly_rate,
  calc_clients_session_count(t.client_id) AS session_count,
  calc_clients_total_invoiced(t.client_id) AS total_invoiced,
  calc_clients_outstanding_balance(t.client_id) AS outstanding_balance,
  calc_clients_overdue_count(t.client_id) AS overdue_count,
  calc_clients_status(t.client_id) AS status
FROM clients t;

-- ----------------------------------------------------------------------------
-- vw_invoices: An invoice bundles one or more sessions billed to a client.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_invoices CASCADE;
CREATE VIEW vw_invoices WITH (security_invoker = ON) AS
SELECT
  t.invoice_id,
  t.name,
  t.client,
  calc_invoices_client_name(t.invoice_id) AS client_name,
  calc_invoices_client_email(t.invoice_id) AS client_email,
  calc_invoices_trainer(t.invoice_id) AS trainer,
  calc_invoices_trainer_name(t.invoice_id) AS trainer_name,
  t.issue_date,
  t.due_date,
  t.tax_rate,                                                                   -- Decimal (e.g. 0.08 = 8%).
  t.discount_amount,
  t.paid_amount,
  calc_invoices_subtotal(t.invoice_id) AS subtotal,
  calc_invoices_tax_amount(t.invoice_id) AS tax_amount,
  calc_invoices_grace_days(t.invoice_id) AS grace_days,                         -- Grace period (in days) after the DueDate before an invoice is considered late.
  calc_invoices_days_since_due_date(t.invoice_id) AS days_since_due_date,       -- Raw whole days from DueDate to now (can be negative if not yet due).
  calc_invoices_days_past_due(t.invoice_id) AS days_past_due,                   -- Whole days past DueDate after the GraceDays window; 0 inside the grace window.
  calc_invoices_late_fee(t.invoice_id) AS late_fee,                             -- $15 flat fee once an invoice is past the 45-day grace period.
  calc_invoices_total(t.invoice_id) AS total,
  calc_invoices_balance(t.invoice_id) AS balance,
  calc_invoices_is_paid(t.invoice_id) AS is_paid,
  calc_invoices_is_overdue(t.invoice_id) AS is_overdue,                         -- True only after the GraceDays window has elapsed.
  calc_invoices_status(t.invoice_id) AS status
FROM invoices t;

-- ----------------------------------------------------------------------------
-- vw_sessions: A logged training session. The atomic line item that rolls up into an invoice.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_sessions CASCADE;
CREATE VIEW vw_sessions WITH (security_invoker = ON) AS
SELECT
  t.session_id,
  t.name,
  t.client,
  calc_sessions_client_name(t.session_id) AS client_name,
  calc_sessions_trainer(t.session_id) AS trainer,
  calc_sessions_client_hourly_rate(t.session_id) AS client_hourly_rate,
  t.session_date,
  t.duration_hours,
  t.rate_override,                                                              -- If > 0, overrides the trainer's HourlyRate for this session.
  t.notes,
  calc_sessions_effective_rate(t.session_id) AS effective_rate,
  calc_sessions_line_total(t.session_id) AS line_total,
  t.invoice,
  calc_sessions_invoice_name(t.session_id) AS invoice_name,
  calc_sessions_is_billed(t.session_id) AS is_billed
FROM sessions t;



-- === 8. Custom views (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 9. Custom RLS (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- NOTE: the RBAC policy layer is generated by
-- effortless-rbac-to-postgres-policies as
-- drop-update-effortless-postgres-policies.sql. It follows this same
-- drop-and-recreate model and must run AFTER this file, because policies
-- reference the columns and views rebuilt above.

-- === 10. Custom data (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

COMMIT;
