#!/usr/bin/env python3
"""
Generates Rails seed data from an Effortless rulebook.

Generates one .rb file per table with Model.create() calls for each row in the rulebook data.
Also generates a main db/seeds.rb that loads all seed files.

Usage:
  ERB_RULEBOOK_PATH=/path/to/rulebook.json ERB_OUTPUT_DIR=/path/to/rails python rulebook-to-rails-seeds.py
"""

import json
import os
import sys
import re
from pathlib import Path


def to_snake_case(name: str) -> str:
    """Convert PascalCase to snake_case."""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def main():
    rulebook_path = os.environ.get('ERB_RULEBOOK_PATH')
    output_dir = os.environ.get('ERB_OUTPUT_DIR')

    if not rulebook_path or not output_dir:
        print("Error: ERB_RULEBOOK_PATH and ERB_OUTPUT_DIR must be set", file=sys.stderr)
        sys.exit(1)

    with open(rulebook_path) as f:
        rulebook = json.load(f)

    Path(f"{output_dir}/db/seeds").mkdir(parents=True, exist_ok=True)

    for table_name, table_data in rulebook.items():
        if table_name.startswith('_'):
            continue

        schema = table_data.get('schema', [])
        data = table_data.get('data', [])

        if not data:
            continue

        # Only seed raw fields (not calculated/lookup/aggregation)
        raw_fields = [f for f in schema if f['type'] == 'raw']

        if not raw_fields:
            continue

        seeds_code = generate_seeds(table_name, to_snake_case(table_name), raw_fields, data)
        seeds_file = f"{output_dir}/db/seeds/{to_snake_case(table_name)}.rb"

        with open(seeds_file, 'w') as f:
            f.write(seeds_code)
        print(f"Generated {seeds_file}")

    # Generate main seeds.rb loader
    seeds_main = """# This file loads all entity-specific seeds.
# Generated by rulebook-to-rails-seeds.py

Dir[File.join(__dir__, 'seeds', '*.rb')].each { |file| load file }
"""
    with open(f"{output_dir}/db/seeds.rb", 'w') as f:
        f.write(seeds_main)
    print(f"Generated {output_dir}/db/seeds.rb")


def ruby_literal(value) -> str:
    """Render a Python value as a Ruby literal for a seed statement."""
    if value is None:
        return 'nil'
    if isinstance(value, bool):
        return 'true' if value else 'false'
    if isinstance(value, (int, float)):
        return repr(value)
    # String: single-quote and escape backslashes + single quotes.
    s = str(value).replace('\\', '\\\\').replace("'", "\\'")
    return f"'{s}'"


def generate_seeds(table_name: str, snake_name: str, raw_fields: list, data: list) -> str:
    """Generate Rails seeds.

    Writes go to the BASE table (never the vw_ view, which is read-only — the
    view IS the contract for reads). We insert through the connection so we
    don't depend on a writable model existing, and so calculated columns are
    left to the view to derive.
    """
    code = f"# Seed data for {table_name}\n"
    code += "# Generated by rulebook-to-rails-seeds.py\n"
    code += "# Inserts into the base table; computed columns are derived by vw_%s.\n\n" % snake_name
    code += "conn = ActiveRecord::Base.connection\n"

    for row in data:
        cols = []
        vals = []
        for field in raw_fields:
            field_name = field['name']
            attr_name = to_snake_case(field_name)
            if field_name in row:
                cols.append(attr_name)
                vals.append(ruby_literal(row[field_name]))

        if cols:
            col_list = ', '.join(cols)
            # Quote each value through the connection at runtime, then build the
            # VALUES list. Idempotent via ON CONFLICT DO NOTHING.
            val_list = ', '.join(f"conn.quote({v})" for v in vals)
            code += (
                f"conn.execute(\"INSERT INTO {snake_name} ({col_list}) "
                f"VALUES (#{{[{val_list}].join(', ')}}) ON CONFLICT DO NOTHING\")\n"
            )

    return code


if __name__ == '__main__':
    main()
