-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 7
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_treatment_rankings CASCADE;
DROP VIEW IF EXISTS vw_stratum_summaries CASCADE;
DROP VIEW IF EXISTS vw_case_cells CASCADE;
DROP VIEW IF EXISTS vw_strata CASCADE;
DROP VIEW IF EXISTS vw_treatments CASCADE;
DROP VIEW IF EXISTS vw_studies CASCADE;
DROP VIEW IF EXISTS vw_loops CASCADE;

-- ----------------------------------------------------------------------------
-- vw_loops: Table: Loops — the 10-loop build plan, carried as a first-class entity inside the model. Each row documents what new concept is introduced and why.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_loops CASCADE;
CREATE VIEW vw_loops WITH (security_invoker = ON) AS
SELECT
  t.loop_id,                                                                    -- Unique identifier: loop-01 through loop-10.
  calc_loops_name(t.loop_id) AS name,                                           -- Display label.
  t.title,                                                                      -- Short title for what this loop adds to the domain model.
  t.status,                                                                     -- planned | in-progress | complete
  t.new_concept,                                                                -- The new first-class domain concept introduced this loop.
  t.domain_question,                                                            -- The natural-language question this loop's concept answers FROM the domain data.
  t.mock_data_note,                                                             -- What the seed data is designed to show.
  t.next_suggestion                                                             -- Suggestion for the next loop, written after witnessing the DAG at this loop's end.
FROM loops t;

-- ----------------------------------------------------------------------------
-- vw_studies: Table: Studies — a clinical or empirical study comparing two or more treatments for a condition, with patient cases stratified by a confounding variable. The top-level entity in the domain.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_studies CASCADE;
CREATE VIEW vw_studies WITH (security_invoker = ON) AS
SELECT
  t.study_id,                                                                   -- Unique slug for this study (e.g. kidney-1986, berkeley-1973).
  calc_studies_name(t.study_id) AS name,                                        -- Display label, mirrors StudyId.
  t.title,                                                                      -- Human-readable title of the study.
  t.source,                                                                     -- Citation or description of the original data source.
  t.source_url,                                                                 -- URL to the original source.
  calc_studies_total_cases(t.study_id) AS total_cases,                          -- Total number of cases (trials) across all CaseCells in this study.
  calc_studies_cell_count(t.study_id) AS cell_count                             -- Number of CaseCell rows for this study.
FROM studies t;

-- ----------------------------------------------------------------------------
-- vw_treatments: Table: Treatments — the interventions being compared within a study. Each treatment belongs to one study.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_treatments CASCADE;
CREATE VIEW vw_treatments WITH (security_invoker = ON) AS
SELECT
  t.treatment_id,                                                               -- Unique slug (e.g. kidney-1986-A, kidney-1986-B).
  calc_treatments_name(t.treatment_id) AS name,                                 -- Display label.
  t.study,                                                                      -- FK to the parent Study.
  t.treatment_label,                                                            -- Short label used in CaseCells and comparisons (e.g. A, B).
  t.description,                                                                -- Plain-language description of what this treatment is.
  calc_treatments_total_cases(t.treatment_id) AS total_cases,                   -- Total cases for this treatment across all strata.
  calc_treatments_total_successes(t.treatment_id) AS total_successes,           -- Total successes for this treatment across all strata.
  calc_treatments_pooled_success_rate(t.treatment_id) AS pooled_success_rate    -- Pooled (across all strata) success rate for this treatment: TotalSuccesses / TotalCases.
FROM treatments t;

-- ----------------------------------------------------------------------------
-- vw_strata: Table: Strata — the subdivisions of patients within a study by the value of the confounding variable (e.g. stone size). Each stratum belongs to one study.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_strata CASCADE;
CREATE VIEW vw_strata WITH (security_invoker = ON) AS
SELECT
  t.stratum_id,                                                                 -- Unique slug (e.g. kidney-1986-small, kidney-1986-large).
  calc_strata_name(t.stratum_id) AS name,                                       -- Display label.
  t.study,                                                                      -- FK to the parent Study.
  t.stratum_label,                                                              -- Short label used in CaseCells (e.g. small, large, dept-A).
  t.description,                                                                -- Plain-language description of what defines this stratum.
  calc_strata_total_cases(t.stratum_id) AS total_cases                          -- Total cases in this stratum across all treatments.
FROM strata t;

-- ----------------------------------------------------------------------------
-- vw_case_cells: Table: CaseCells — the raw leaves of the DAG. One row per (study, stratum, treatment) combination recording the aggregate count of successes and total cases. Every derived fact in the model traces back to these numbers. Nothing above this row is a raw input.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_case_cells CASCADE;
CREATE VIEW vw_case_cells WITH (security_invoker = ON) AS
SELECT
  t.case_cell_id,                                                               -- Unique slug (e.g. kidney-1986-small-A).
  calc_case_cells_name(t.case_cell_id) AS name,                                 -- Display label.
  t.study,                                                                      -- FK to the parent Study.
  t.stratum_label,                                                              -- The stratum this cell belongs to (matches Strata.StratumLabel).
  t.treatment_label,                                                            -- The treatment applied in this cell (matches Treatments.TreatmentLabel).
  t.successes,                                                                  -- Number of patients in this cell who had a successful outcome. RAW INPUT — never derived.
  t.cases,                                                                      -- Total number of patients in this cell. RAW INPUT — never derived.
  calc_case_cells_cell_success_rate(t.case_cell_id) AS cell_success_rate        -- Success rate within this cell: Successes / Cases. The first derived fact in the DAG.
FROM case_cells t;

-- ----------------------------------------------------------------------------
-- vw_stratum_summaries: Table: StratumSummaries — one row per (study, stratum, treatment). Computes the success rate WITHIN each stratum for each treatment. This is the stratified view that contradicts the pooled conclusion when a Simpson's Paradox reversal is present. Each row belongs to both a Stratum and a Treatment in the same Study.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_stratum_summaries CASCADE;
CREATE VIEW vw_stratum_summaries WITH (security_invoker = ON) AS
SELECT
  t.stratum_summary_id,                                                         -- Unique slug (e.g. kidney-1986-small-A).
  calc_stratum_summaries_name(t.stratum_summary_id) AS name,                    -- Display label.
  t.study,                                                                      -- FK to the parent Study.
  t.stratum_label,                                                              -- Which stratum (matches Strata.StratumLabel).
  t.treatment_label,                                                            -- Which treatment (matches Treatments.TreatmentLabel).
  calc_stratum_summaries_stratum_successes(t.stratum_summary_id) AS stratum_successes,-- Total successes in this (stratum, treatment) cell for this study.
  calc_stratum_summaries_stratum_cases(t.stratum_summary_id) AS stratum_cases,  -- Total cases in this (stratum, treatment) cell for this study.
  calc_stratum_summaries_stratum_success_rate(t.stratum_summary_id) AS stratum_success_rate,-- Success rate within this stratum for this treatment: StratumSuccesses / StratumCases. The true per-stratum picture.
  calc_stratum_summaries_stratum_successes_a(t.stratum_summary_id) AS stratum_successes_a,-- Successes for treatment A in this (study, stratum) — used to determine the per-stratum winner.
  calc_stratum_summaries_stratum_cases_a(t.stratum_summary_id) AS stratum_cases_a,-- Cases for treatment A in this (study, stratum).
  calc_stratum_summaries_stratum_rate_a(t.stratum_summary_id) AS stratum_rate_a,-- Success rate for treatment A in this stratum.
  calc_stratum_summaries_stratum_successes_b(t.stratum_summary_id) AS stratum_successes_b,-- Successes for treatment B in this (study, stratum).
  calc_stratum_summaries_stratum_cases_b(t.stratum_summary_id) AS stratum_cases_b,-- Cases for treatment B in this (study, stratum).
  calc_stratum_summaries_stratum_rate_b(t.stratum_summary_id) AS stratum_rate_b,-- Success rate for treatment B in this stratum.
  calc_stratum_summaries_stratum_winner(t.stratum_summary_id) AS stratum_winner -- Which treatment wins in this stratum: 'A' if StratumRateA > StratumRateB, else 'B'. Used by TreatmentRankings to detect paradox.
FROM stratum_summaries t;

-- ----------------------------------------------------------------------------
-- vw_treatment_rankings: Table: TreatmentRankings — one row per treatment-pair comparison within a study. Derives the pooled winner, the per-stratum winner, and the IsReversal boolean. The paradox emerges here as a derived fact: IsReversal is true when the pooled winner and the per-stratum winner disagree.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_treatment_rankings CASCADE;
CREATE VIEW vw_treatment_rankings WITH (security_invoker = ON) AS
SELECT
  t.treatment_ranking_id,                                                       -- Unique slug (e.g. kidney-1986-A-vs-B).
  calc_treatment_rankings_name(t.treatment_ranking_id) AS name,                 -- Display label.
  t.study,                                                                      -- FK to the parent Study.
  t.treatment_a,                                                                -- Label for the first treatment in the comparison (matches Treatments.TreatmentLabel).
  t.treatment_b,                                                                -- Label for the second treatment in the comparison.
  calc_treatment_rankings_total_cases_a(t.treatment_ranking_id) AS total_cases_a,-- Total cases for TreatmentA across all strata in this study.
  calc_treatment_rankings_total_successes_a(t.treatment_ranking_id) AS total_successes_a,-- Total successes for TreatmentA across all strata.
  calc_treatment_rankings_pooled_rate_a(t.treatment_ranking_id) AS pooled_rate_a,-- Pooled success rate for TreatmentA: TotalSuccessesA / TotalCasesA.
  calc_treatment_rankings_total_cases_b(t.treatment_ranking_id) AS total_cases_b,-- Total cases for TreatmentB across all strata.
  calc_treatment_rankings_total_successes_b(t.treatment_ranking_id) AS total_successes_b,-- Total successes for TreatmentB across all strata.
  calc_treatment_rankings_pooled_rate_b(t.treatment_ranking_id) AS pooled_rate_b,-- Pooled success rate for TreatmentB: TotalSuccessesB / TotalCasesB.
  calc_treatment_rankings_pooled_winner(t.treatment_ranking_id) AS pooled_winner,-- Which treatment wins when strata are ignored: the one with the higher pooled rate.
  calc_treatment_rankings_stratum_count(t.treatment_ranking_id) AS stratum_count,-- Number of strata in this study. Counted from StratumSummaries filtered to TreatmentA rows (one row per stratum).
  calc_treatment_rankings_strata_won_by_a(t.treatment_ranking_id) AS strata_won_by_a,-- Number of strata where A wins: count StratumSummaries rows whose TreatmentLabel=TreatmentA AND StratumWinner=TreatmentA. These are the one-per-stratum sentinel rows.
  calc_treatment_rankings_strata_won_by_b(t.treatment_ranking_id) AS strata_won_by_b,-- Number of strata where B wins: count StratumSummaries rows whose TreatmentLabel=TreatmentA AND StratumWinner=TreatmentB.
  calc_treatment_rankings_per_stratum_winner(t.treatment_ranking_id) AS per_stratum_winner,-- The treatment that wins in every stratum — 'A' if StrataWonByA = StratumCount, 'B' if StrataWonByB = StratumCount, else 'none' (no unanimous per-stratum winner).
  calc_treatment_rankings_is_reversal(t.treatment_ranking_id) AS is_reversal    -- TRUE when the pooled winner and the per-stratum winner disagree — i.e. Simpson's Paradox is present. FALSE otherwise. This is the paradox as a derived fact, not a modeled entity.
FROM treatment_rankings t;

