-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 8
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_wallpaper_designs CASCADE;
DROP VIEW IF EXISTS vw_placements CASCADE;
DROP VIEW IF EXISTS vw_regions CASCADE;
DROP VIEW IF EXISTS vw_vertex_figures CASCADE;
DROP VIEW IF EXISTS vw_tiling_prototiles CASCADE;
DROP VIEW IF EXISTS vw_tilings CASCADE;
DROP VIEW IF EXISTS vw_prototiles CASCADE;
DROP VIEW IF EXISTS vw_symmetry_groups CASCADE;

-- ----------------------------------------------------------------------------
-- vw_symmetry_groups: The wallpaper symmetry groups a tiling can belong to.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_symmetry_groups CASCADE;
CREATE VIEW vw_symmetry_groups WITH (security_invoker = ON) AS
SELECT
  t.symmetry_group_id,                                                          -- Stable id (IUC short notation, slugified).
  calc_symmetry_groups_name(t.symmetry_group_id) AS name,                       -- Mirrors the id.
  t.notation,                                                                   -- IUC / crystallographic short notation (e.g. 'p6m').
  t.orbifold,                                                                   -- Conway orbifold notation (e.g. '*632').
  t.display_name,                                                               -- Human-friendly name.
  t.description,                                                                -- What this wallpaper group is.
  calc_symmetry_groups_tiling_count(t.symmetry_group_id) AS tiling_count,       -- How many catalogued tilings have this symmetry group.
  t.lattice_type,                                                               -- Bravais lattice class: oblique | rectangular | rhombic | square | hexagonal.
  t.lattice_angle_deg,                                                          -- Angle (deg) between the two lattice basis vectors B1,B2.
  t.lattice_ratio,                                                              -- Length ratio |B2|/|B1| of the lattice basis.
  t.generators,                                                                 -- JSON array of non-identity coset-rep affine ops in fractional coords: {k,m:[a,b,c,d],t:[tx,ty]} mapping (u,v)->(a u+b v+tx, c u+d v+ty).
  t.rotation_order,                                                             -- Highest order of rotational symmetry (1,2,3,4,6).
  t.operation_count,                                                            -- Number of point-group coset reps including the identity (= motif copies per lattice cell).
  t.has_mirrors,                                                                -- Whether the group contains reflection (mirror) symmetry.
  t.has_glides,                                                                 -- Whether the group contains glide-reflection symmetry.
  calc_symmetry_groups_wallpaper_design_count(t.symmetry_group_id) AS wallpaper_design_count-- How many saved designs use this group.
FROM symmetry_groups t;

-- ----------------------------------------------------------------------------
-- vw_prototiles: The prototiles (regular polygons) available for tilings.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_prototiles CASCADE;
CREATE VIEW vw_prototiles WITH (security_invoker = ON) AS
SELECT
  t.prototile_id,                                                               -- Stable id.
  calc_prototiles_name(t.prototile_id) AS name,                                 -- Slug from display name.
  t.display_name,                                                               -- Human name (e.g. 'Equilateral Triangle').
  t.sides,                                                                      -- Number of edges of this regular polygon.
  t.edge_length,                                                                -- Edge length in unit cells (1.0 = unit edge).
  calc_prototiles_area(t.prototile_id) AS area,                                 -- Area of one tile (regular n-gon). Trig override lives in 02b-customize-functions.sql.
  calc_prototiles_interior_angle_deg(t.prototile_id) AS interior_angle_deg,     -- Interior angle in degrees of this regular polygon.
  calc_prototiles_vertex_angle_turns(t.prototile_id) AS vertex_angle_turns,     -- Fraction of a full turn occupied at one vertex by this tile.
  calc_prototiles_is_regular(t.prototile_id) AS is_regular,                     -- A regular polygon needs at least 3 sides.
  calc_prototiles_is_triangle(t.prototile_id) AS is_triangle,                   -- True when this prototile is a triangle (3 sides).
  calc_prototiles_is_square(t.prototile_id) AS is_square,                       -- True when this prototile is a square (4 sides).
  calc_prototiles_used_in_tilings_count(t.prototile_id) AS used_in_tilings_count-- How many catalogued tilings use this prototile.
FROM prototiles t;

-- ----------------------------------------------------------------------------
-- vw_tilings: Catalogued tilings of the plane.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_tilings CASCADE;
CREATE VIEW vw_tilings WITH (security_invoker = ON) AS
SELECT
  t.tiling_id,                                                                  -- Stable id.
  calc_tilings_name(t.tiling_id) AS name,                                       -- Slug.
  t.display_name,                                                               -- Human name (e.g. 'Hexagonal tiling').
  t.vertex_config,                                                              -- Vertex configuration / Schlafli symbol string (e.g. '3.4.6.4').
  t.kind,                                                                       -- 'regular' | 'semiregular' (Archimedean).
  t.is_edge_to_edge,                                                            -- Whether tiles meet edge-to-edge.
  t.symmetry_group,                                                             -- The wallpaper symmetry group of this tiling.
  calc_tilings_symmetry_notation(t.tiling_id) AS symmetry_notation,             -- Pulled symmetry notation for display.
  calc_tilings_distinct_prototile_count(t.tiling_id) AS distinct_prototile_count,-- How many distinct prototiles this tiling uses.
  calc_tilings_vertex_figure_count(t.tiling_id) AS vertex_figure_count,         -- How many distinct vertex figures this tiling has.
  calc_tilings_valid_vertex_figure_count(t.tiling_id) AS valid_vertex_figure_count,-- How many of its vertex figures close to 360deg.
  calc_tilings_is_regular_tiling(t.tiling_id) AS is_regular_tiling,             -- Regular tiling = built from a single prototile.
  calc_tilings_all_vertices_valid(t.tiling_id) AS all_vertices_valid,           -- True when every vertex figure of this tiling closes to a full turn.
  t.t1x,                                                                        -- X component of the first lattice translation vector (unit cells). Repeating the fundamental domain along T1 and T2 fills the plane.
  t.t1y,                                                                        -- Y component of the first lattice translation vector (unit cells).
  t.t2x,                                                                        -- X component of the second lattice translation vector (unit cells).
  t.t2y,                                                                        -- Y component of the second lattice translation vector (unit cells).
  calc_tilings_lattice_determinant(t.tiling_id) AS lattice_determinant,         -- Cross product T1 x T2. Equals the signed area of the fundamental domain (unit cell).
  calc_tilings_fundamental_domain_area(t.tiling_id) AS fundamental_domain_area, -- Area of the fundamental domain spanned by the two translation vectors.
  calc_tilings_has_lattice(t.tiling_id) AS has_lattice,                         -- True when the two translation vectors are present and linearly independent (span the plane).
  calc_tilings_does_tile_plane(t.tiling_id) AS does_tile_plane                  -- THE ULTIMATE QUESTION. Yes/no: does this tiling fill the plane? True iff every vertex figure closes to 360deg AND a non-degenerate lattice of translation vectors repeats the fundamental domain across the plane.
FROM tilings t;

-- ----------------------------------------------------------------------------
-- vw_tiling_prototiles: First-class junction: prototiles used by each tiling.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_tiling_prototiles CASCADE;
CREATE VIEW vw_tiling_prototiles WITH (security_invoker = ON) AS
SELECT
  t.tiling_prototile_id,                                                        -- Stable id.
  calc_tiling_prototiles_name(t.tiling_prototile_id) AS name,                   -- Composite name.
  t.tiling,                                                                     -- The tiling.
  t.prototile,                                                                  -- A prototile used by that tiling.
  t.count_at_vertex,                                                            -- How many of this prototile meet at a typical vertex.
  calc_tiling_prototiles_prototile_sides(t.tiling_prototile_id) AS prototile_sides,-- Sides of the referenced prototile.
  calc_tiling_prototiles_prototile_interior_angle(t.tiling_prototile_id) AS prototile_interior_angle-- Interior angle of the referenced prototile.
FROM tiling_prototiles t;

-- ----------------------------------------------------------------------------
-- vw_vertex_figures: First-class vertex figures; validity derived from angle sum = 360.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_vertex_figures CASCADE;
CREATE VIEW vw_vertex_figures WITH (security_invoker = ON) AS
SELECT
  t.vertex_figure_id,                                                           -- Stable id.
  calc_vertex_figures_name(t.vertex_figure_id) AS name,                         -- Composite name.
  t.tiling,                                                                     -- The tiling this vertex figure belongs to.
  t.config,                                                                     -- Vertex configuration at this vertex (e.g. '3.4.6.4').
  t.angle_sum_deg,                                                              -- Sum of interior angles meeting at this vertex (degrees).
  calc_vertex_figures_turns_at_vertex(t.vertex_figure_id) AS turns_at_vertex,   -- Angle sum as a fraction of a full turn.
  calc_vertex_figures_angle_gap_deg(t.vertex_figure_id) AS angle_gap_deg,       -- Distance from a full 360deg turn.
  calc_vertex_figures_is_valid(t.vertex_figure_id) AS is_valid                  -- Valid vertex figure: interior angles close to a full turn.
FROM vertex_figures t;

-- ----------------------------------------------------------------------------
-- vw_regions: Bounded patches of the plane to be tiled.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_regions CASCADE;
CREATE VIEW vw_regions WITH (security_invoker = ON) AS
SELECT
  t.region_id,                                                                  -- Stable id.
  calc_regions_name(t.region_id) AS name,                                       -- Slug.
  t.display_name,                                                               -- Human name.
  t.width,                                                                      -- Region width in unit cells.
  t.height,                                                                     -- Region height in unit cells.
  t.target_tiling,                                                              -- Which catalogued tiling this region is trying to realize.
  calc_regions_area(t.region_id) AS area,                                       -- Total area of the region.
  calc_regions_placement_count(t.region_id) AS placement_count,                 -- How many tiles have been placed in this region.
  calc_regions_covered_area(t.region_id) AS covered_area,                       -- Sum of placed-tile areas (counts overlaps twice — see CoveragePct).
  calc_regions_overlap_count(t.region_id) AS overlap_count,                     -- How many placed tiles are flagged as overlapping a neighbour.
  calc_regions_coverage_pct(t.region_id) AS coverage_pct,                       -- Covered area as a percentage of region area.
  calc_regions_is_fully_covered(t.region_id) AS is_fully_covered,               -- Whether placed tiles cover at least the whole region area.
  calc_regions_is_clean_tiling(t.region_id) AS is_clean_tiling                  -- Fully covered with no overlaps = a clean tiling of the region.
FROM regions t;

-- ----------------------------------------------------------------------------
-- vw_placements: Individual tile placements within a region.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_placements CASCADE;
CREATE VIEW vw_placements WITH (security_invoker = ON) AS
SELECT
  t.placement_id,                                                               -- Stable id.
  calc_placements_name(t.placement_id) AS name,                                 -- Composite name.
  t.region,                                                                     -- The region this tile is placed in.
  t.prototile,                                                                  -- The prototile being placed.
  t.x,                                                                          -- X coordinate of the tile's anchor (unit cells).
  t.y,                                                                          -- Y coordinate of the tile's anchor (unit cells).
  t.rotation_deg,                                                               -- Rotation of the tile in degrees.
  t.is_overlapping,                                                             -- Flag: this placement overlaps a neighbour (authored/validated).
  calc_placements_tile_area(t.placement_id) AS tile_area,                       -- Area of the placed prototile (for coverage rollups).
  calc_placements_tile_sides(t.placement_id) AS tile_sides,                     -- Sides of the placed prototile.
  calc_placements_region_width(t.placement_id) AS region_width,                 -- Width of the containing region.
  calc_placements_region_height(t.placement_id) AS region_height,               -- Height of the containing region.
  calc_placements_is_inside_region(t.placement_id) AS is_inside_region          -- Whether the anchor sits within the region bounds.
FROM placements t;

-- ----------------------------------------------------------------------------
-- vw_wallpaper_designs: User-authored wallpaper designs: a fundamental-domain motif (drawn strokes) replicated under a chosen symmetry group.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_wallpaper_designs CASCADE;
CREATE VIEW vw_wallpaper_designs WITH (security_invoker = ON) AS
SELECT
  t.wallpaper_design_id,                                                        -- Stable id.
  calc_wallpaper_designs_name(t.wallpaper_design_id) AS name,                   -- Slug.
  t.display_name,                                                               -- Human name for this design.
  t.symmetry_group,                                                             -- The wallpaper group whose symmetry replicates the motif.
  t.strokes,                                                                    -- JSON array of polylines drawn in the fundamental domain, in fractional cell coords: [{color,width,points:[[u,v],...]},...].
  t.stroke_color,                                                               -- Default stroke color (hex) for new strokes.
  t.background_color,                                                           -- Fill color (hex) behind the tiling.
  calc_wallpaper_designs_group_notation(t.wallpaper_design_id) AS group_notation,-- IUC notation of the chosen group.
  calc_wallpaper_designs_group_orbifold(t.wallpaper_design_id) AS group_orbifold,-- Orbifold notation of the chosen group.
  calc_wallpaper_designs_group_lattice_type(t.wallpaper_design_id) AS group_lattice_type,-- Lattice class of the chosen group.
  calc_wallpaper_designs_group_rotation_order(t.wallpaper_design_id) AS group_rotation_order,-- Highest rotation order of the chosen group.
  calc_wallpaper_designs_group_operation_count(t.wallpaper_design_id) AS group_operation_count-- Motif copies per cell for the chosen group.
FROM wallpaper_designs t;

