-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 1
-- ============================================================================

-- ----------------------------------------------------------------------------
-- vw_customers: Table: Customers
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
CREATE OR REPLACE VIEW vw_customers WITH (security_invoker = ON) AS
SELECT
  t.customer_id,
  t.name,
  t.current_color,                                                              -- The current color assigned to this customer (e.g. red, green, yellow, blue)
  calc_customers_is_approved(t.customer_id) AS is_approved,
  t.notes
FROM customers t;

