-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 1
-- Total Raw Fields: 2
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- HelloWhos: The smallest complete rulebook: an id, a display name, and a rule that derives a greeting from it.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS hello_whos (
  hello_who_id                        TEXT                 PRIMARY KEY
);
ALTER TABLE hello_whos ADD COLUMN IF NOT EXISTS name TEXT;
COMMENT ON TABLE hello_whos IS 'The smallest complete rulebook: an id, a display name, and a rule that derives a greeting from it.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- (no FK fields detected in rulebook)
