-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- ERB BUILD PARAMETERS (docs/ERB-BUILD-PARAMETERS.md)
-- erbBlankLogic=coerce, erbDateDiff=calendar, erbDateTimeText=iso8601, erbTimezone=UTC, erbWholeNumber=by-field-type
-- ============================================================================

CREATE OR REPLACE FUNCTION erb_build_parameters()
RETURNS JSONB AS $$
  SELECT '{"erbBlankLogic":"coerce","erbDateDiff":"calendar","erbDateTimeText":"iso8601","erbTimezone":"UTC","erbWholeNumber":"by-field-type"}'::jsonb;
$$ LANGUAGE sql IMMUTABLE;

-- A timestamp inside text, per erbDateTimeText, in erbTimezone. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_datetime_text(ts TIMESTAMPTZ)
RETURNS TEXT AS $$
  SELECT CASE WHEN ts IS NULL THEN '' ELSE
    to_char(ts AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS')
    || CASE WHEN (EXTRACT(MICROSECONDS FROM ts)::bigint % 1000000) <> 0 THEN rtrim(to_char(ts AT TIME ZONE 'UTC', '.US'), '0') ELSE '' END
    || CASE WHEN o.off < 0 THEN '-' ELSE '+' END || lpad((abs(o.off) / 3600)::text, 2, '0') || ':' || lpad(((abs(o.off) % 3600) / 60)::text, 2, '0')
  END
  FROM (SELECT EXTRACT(EPOCH FROM ((ts AT TIME ZONE 'UTC') - (ts AT TIME ZONE 'UTC')))::integer AS off) o;
$$ LANGUAGE sql STABLE;

-- A date inside text: YYYY-MM-DD. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_date_text(d DATE)
RETURNS TEXT AS $$
  SELECT COALESCE(to_char(d, 'YYYY-MM-DD'), '');
$$ LANGUAGE sql IMMUTABLE;

-- A number inside text: the shortest exact form, no trailing .0 (2, 2.5). Blank renders ''.
CREATE OR REPLACE FUNCTION erb_number_text(n NUMERIC)
RETURNS TEXT AS $$
  SELECT CASE WHEN n IS NULL THEN ''
              WHEN n::text LIKE '%.%' THEN rtrim(rtrim(n::text, '0'), '.')
              ELSE n::text END;
$$ LANGUAGE sql IMMUTABLE;


-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_hello_whos_introduction
-- Field: HelloWhos.Introduction
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_hello_whos_introduction(p_hello_who_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT('Hello ', (SELECT NULLIF(name, '') FROM hello_whos WHERE hello_who_id = p_hello_who_id), '!!!'))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

