-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 1
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_hello_whos CASCADE;

-- ----------------------------------------------------------------------------
-- vw_hello_whos: The smallest complete rulebook: an id, a display name, and a rule that derives a greeting from it.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_hello_whos CASCADE;
CREATE VIEW vw_hello_whos WITH (security_invoker = ON) AS
SELECT
  t.hello_who_id,
  t.name,
  calc_hello_whos_introduction(t.hello_who_id) AS introduction
FROM hello_whos t;

