@startuml

object "jane.smith-email.com" as Customers_0 {
  CustomerId = "jane-smith-email-com"
  EmailAddress = "jane.smith@email.com"
  FirstName = "Bob"
  LastName = "Smith"
}

object "john.doe-email.com" as Customers_1 {
  CustomerId = "john-doe-email-com"
  EmailAddress = "john.doe@email.com"
  FirstName = "Jimmy"
  LastName = "Doe"
}

object "emily.jones-email.com" as Customers_2 {
  CustomerId = "emily-jones-email-com"
  EmailAddress = "emily.jones@email.com"
  FirstName = "Mary"
  LastName = "Jones"
}

@enduml