"""Evidence for theme E (loop-10): governance of the model itself and of the procedures it holds.

(kind, target, justification). Validity is computed by ClaimEvidence.IsValid from Postgres
measurements; nothing here asserts coverage by itself. Seeded breaches named below are kept
as evidence (see tools/loops/loop10_governance.py ROWS).
"""


def fld(target, why):
    return ("Field", target, why)


def tbl(target, why):
    return ("Table", target, why)


def q(target, why):
    return ("RoleQuestion", target, why)


def prof(target, why):
    return ("OntologyProfile", target, why)


def meth(target, why):
    return ("KnowledgeMethod", target, why)


EVIDENCE = {
    # ---------------------------------------------------------------- pkm-1
    "pkm1-c33": [fld("DriftObservations.DriftCause", "Each drift observation records what drove the process to change: a shifting requirement, a new technology (the press-7 retrofit) or competitive pressure (a faster close calendar).")],
    "pkm1-p09": [fld("ModelChangeLogEntries.CannotBeAudited", "Fires on a change log entry that names no author or belongs to no schema release or instance data version: the bulk-loaded OperatingTemperature property and the hotfix-channel data load with no recorded author. Encoded knowledge that carries no version or no author is exactly what cannot be audited.")],
    "pkm1-p27": [fld("GovernedModels.IsNeglectedAndDrifting", "Fires on the production deployment family: no steward activity for over ninety days while an open practice mismatch is recorded. That is a representation left ungoverned while it degrades away from how the process runs.")],
    "pkm1-p30": [fld("GovernedModels.HasOpenPracticeDrift", "Makes knowledge that no longer matches practice detectable per model: true for production deployment (SRE verification not in the register) and lockout/tagout (night shift still using the 2019 shutdown step), false where drift was resolved or never observed.")],
    "pkm1-p32": [fld("RulebookTables.IsUnsecuredGovernanceRecord", "Fires on governance tables no access policy controls (every loop-10 governance table), and not on governance tables that carry row-level policies (Requirements, Exceptions, AuthorityBoundaries). Uncontrolled access to the records of who may change process knowledge is the breach.")],
    "pkm1-p33": [fld("RulebookTables.LacksSemanticTypeConvention", "The model's stated convention is that every table carries a SemanticTypeIri column; this counts that column in the field census and fires on tables that break the convention (for example OntologyProfiles, SemanticMappings, RulebookReleases).")],
    "pkm1-p34": [fld("RulebookReleases.ReleasedDespiteFailedValidation", "Fires on release 0.10.0, which shipped the RoleAssignments domain narrowing although its acceptance validation run failed two tests; releases whose runs passed read false.")],
    "pkm1-p35": [fld("RulebookReleases.IsUntaggedRelease", "Fires on release 0.8.2, which has no version-control commit or tag; every other governed release records its commit, so version control of the model is checked release by release.")],
    "pkm1-q14": [q("aq-pkm1-q14", "The process steward's question is answered by DriftObservations.IsOpenPracticeMismatch, which names each representation (procedure version) observed not to match how the process runs and still unresolved.")],
    # ---------------------------------------------------------------- pkm-2
    "pkm2-c101": [tbl("DriftObservations", "Each row is an observed case of encoded knowledge falling out of step with practice, with how it was detected, what caused it and whether it was resolved.")],
    "pkm2-p55": [fld("GovernedModels.PipelineNotContinuous", "Counts governance controls over collection, organization and encoding that run continuously; fires on the close family (encoding is a quarterly batch) and on deployment and press changeover, not on lockout/tagout or workforce policy where all three run continuously.")],
    "pkm2-p60": [fld("ModelProposals.EnteredWithoutQualityCheck", "Fires on candidates committed to the model without a passing quality check: the wiki-extracted hotfix assignment and the legacy import's domain/range assertion. Checked candidates read false.")],
    "pkm2-p61": [fld("ModelProposals.CommittedWithoutExpertReview", "Fires when a proposed addition became authoritative with no human expert review: an AI competency question committed unreviewed, a disjointness axiom 'reviewed' only by the assistant, and two commits nobody reviewed.")],
    "pkm2-p62": [fld("ModelChangeRequests.AcceptedWithoutStructuralCheck", "Fires on modeling changes accepted with no passing automated structural consistency check (the ControlKinds rename and the classifier upgrade handled as a modeling change); changes whose validation runs passed the structural check read false.")],
    "pkm2-p63": [fld("ModelChangeRequests.AcceptedWithoutVocabularyCheck", "Fires on modeling changes accepted without a passing automated approved-vocabulary check, including the disjointness change whose run skipped that check while passing the structural one.")],
    "pkm2-p64": [fld("RulebookReleases.IsReleaseWithoutRecordedChanges", "Fires on release 0.10.2, which shipped with no change log entry, so what changed in it is not on record; every other release after the first has logged changes.")],
    "pkm2-p65": [fld("ModelChangeLogEntries.CannotBeRolledBack", "Fires on the ControlKinds rename entry, which recorded no prior-state commit; the others record one, and entry le-16 shows a rollback of le-07 actually performed from its recorded state.")],
    "pkm2-p66": [fld("ModelChangeRequests.LifecycleChangeByUnauthorizedAgent", "Fires when a procedure definition is created, modified or retired on the approval of someone who is neither the model's steward nor its authority: the press-7 changeover retired by a technician. The mixer-2 variant created with the safety officer's approval reads false.")],
    "pkm2-p67": [fld("ModelChangeRequests.ApprovedOverUnresolvedObjection", "Fires on the human/software disjointness change, approved while the safety officer's objection remained unresolved; the RoleAssignments narrowing, whose objection was resolved by the authority first, reads false.")],
    "pkm2-p68": [fld("RulebookReleases.PublishedWithoutApproval", "Fires on release 0.8.2, published with no recorded approval; the other releases name their approver.")],
    "pkm2-p79": [fld("GovernedModels.IsNotKeptCurrent", "Fires on models that are unmaintained or whose documentation describes a release they are no longer at (the PKO rulebook's alignment and changelog documents, the unmaintained deployment, close and press families); lockout/tagout and workforce policy read false.")],
    "pkm2-q34": [q("aq-pkm2-q34", "Answered by GovernedModels.IsProcedureWithoutChangeAuthority and the current authority lookups: it names who holds authority over each procedure family and flags the press-7 changeover, where nobody does.")],
    "pkm2-q35": [q("aq-pkm2-q35", "Answered by ModelProposals.IsOnlyProposed, which separates committed knowledge from candidates still only proposed.")],
    "pkm2-q36": [q("aq-pkm2-q36", "Answered by ModelProposals.ReviewedByAgent with ApproverUnknown flagging committed knowledge no approver stands behind.")],
    "pkm2-q37": [q("aq-pkm2-q37", "Answered by ModelProposals.AdoptedInRelease / AdoptedInDataVersion, with CommittedOutsideAnyVersion flagging knowledge approved in no version.")],
    # ---------------------------------------------------------------- pkm-3
    "pkm3-c26": [fld("ProcessDesignDecisions.Rationale", "A durable record of each design decision behind a procedure commitment and the reason for it, such as capping zero-energy verification at two attempts.")],
    "pkm3-p24": [fld("ProcessDesignDecisions.IsCommitmentWithoutRationale", "Fires on the lockout commitment to escalate night-shift residual energy to the deputy, recorded with no reason; the verification cap and the deployment risk gate carry their rationale and read false.")],
    "pkm3-p25": [fld("ProcedureVersions.IsLiveWithoutRecordedDecisions", "Fires on live procedure versions with no design decision recorded alongside them (close, policy, conveyor maintenance, press changeover, forklift inspection); lockout 2.0.0 and deployment 3.2.0 have decisions recorded with the procedure and read false.")],
    "pkm3-p31": [fld("GovernedModels.IsUnmanageableUndocumentedWork", "Fires on the press-7 changeover family, whose work exists only as a PDF with no specified steps; families documented into the register read false. Work never absorbed into the knowledge system cannot be managed.")],
    "pkm3-q05": [q("aq-pkm3-q05", "Answered by ProcessDesignDecisions.Rationale, with IsRecordedAfterTheFact flagging a decision whose why was written down weeks after it was made.")],
    # ---------------------------------------------------------------- pkm-4
    "pkm4-c10": [tbl("CompetencyQuestionSetEntries", "Each governed model's competency question set, the questions that guided its development, with the original baseline marked.")],
    "pkm4-c11": [tbl("QualityCriteria", "The eight stated quality criteria: accuracy, clarity, adaptability, completeness, computational efficiency, conciseness, consistency and organizational fitness.")],
    "pkm4-c18": [fld("ModelDocuments.DocumentKind", "The model's development materials, typed as requirements, version notes, documentation and evaluation materials.")],
    "pkm4-c19": [fld("StakeholderQuestions.UseCase", "Questions adopters raise through the model's issue tracker, each recording the adopter's use case (release audit, HR onboarding, AI evaluation pipeline) alongside the feedback.")],
    "pkm4-c88": [fld("RulebookReleases.PreviousRelease", "Each release row is the model as a versioned published artifact: version (RulebookVersion), prior version (PreviousRelease), issue date, licence, permanent identifier and publication status.")],
    "pkm4-p11": [fld("SemanticMappings.ReinventsStandardTerm", "Fires on extension terms minted although a reused standard already has the term (TermDefinitions duplicates skos:definition, QualityCriteria duplicates dqv:Dimension); every other mapping reads false.")],
    "pkm4-p19": [fld("RulebookReleases.ReleasedWithoutConsistencyCheck", "Fires on governed releases no machine consistency check confirmed consistent (0.8.x, 0.10.0 whose check reported inconsistency, 0.10.2); 0.9.0, 0.10.1 and 1.0.0 were confirmed and read false.")],
    "pkm4-p20": [fld("RulebookReleases.IsNotScoredAgainstCriteria", "Fires on releases not scored against every stated quality criterion; release 1.0.0 was scored on all eight and reads false.")],
    "pkm4-p21": [fld("RulebookReleases.ReleasedWithoutCqTaskTest", "Fires on releases never tested by running their competency questions as tasks; 0.9.0, 0.10.0 and 1.0.0 were and read false.")],
    "pkm4-p22": [fld("RulebookReleases.WellFormedButRequirementsUnshown", "Fires on release 0.10.1, which passed its validation runs but was never shown to answer its requirement questions: well formed, not shown to satisfy requirements.")],
    "pkm4-p24": [fld("GovernedModels.RequirementsSpecIncomplete", "Fires when a model's requirements specification lacks its purpose, its intended users or its competency questions (deployment, workforce policy, press, vocabulary); the PKO rulebook, lockout and close specifications are complete.")],
    "pkm4-p26": [fld("SemanticMappings.IsNonResolvableTermIri", "Fires on every extension term published under a urn: identifier that cannot be looked up or linked; terms mapped to HTTP IRIs read false. This witnesses the prescription failing for the model's own extension terms.")],
    "pkm4-p27": [fld("GovernedModels.IsUnmaintained", "Fires on models with no maintenance activity for more than ninety days after release (deployment, close, press changeover); models the steward keeps updating read false.")],
    "pkm4-p28": [fld("RulebookReleases.IsLongReleaseCycle", "Fires on release 0.8.1, which came 76 days after 0.8.0 instead of in a short cycle; the other releases followed within weeks.")],
    "pkm4-p29": [fld("RulebookReleases.IsReleasedWithoutLicenceOrPermanentId", "Fires on release 0.8.0, published with no licence; every later release states its licence and permanent identifier.")],
    "pkm4-p30": [fld("GovernedModels.LacksLifecycleStageControl", "Fires on procedure families missing a governance control over capture, stewardship, retrieval or use (deployment has only collection and use; press has none); lockout, close and policy cover every stage.")],
    "pkm4-p31": [fld("GovernedModels.GovernanceLapsed", "Fires on the close control categories vocabulary, which was chartered and whose governance then lapsed: management treated as a finished project instead of a standing capability.")],
    "pkm4-p32": [fld("ModelCharters.AdoptedTemplateWithoutAdaptation", "Fires on the deployment charter, copied from the corporate charter template with no local adaptation; the lockout charter used the same template and fitted it to shift-based work, so it reads false.")],
    "pkm4-s10": [meth("LinkedOpenTerms", "Applied through MethodApplications rows: the requirements specification of the PKO rulebook (purpose, users, competency question baseline) and its post-release maintenance.")],
    "pkm4-s15": [prof("pko-core-2.0.0", "The PKO core profile records its licence as CC BY 4.0 and carries the model's exact PKO mappings.")],
    "pkm4-s16": [prof("pko-core-2.0.0", "The PKO core profile's version IRI is the w3id permanent identifier https://w3id.org/pko/2.0.0, and the profile carries the model's exact PKO mappings.")],
    "pkm4-s17": [prof("vann", "VANN maps RulebookReleases.NamespacePrefix to vann:preferredNamespacePrefix.")],
    "pkm4-s18": [prof("bibo", "BIBO maps RulebookReleases.Status to bibo:status.")],
    "pkm4-s19": [prof("schema-org", "schema.org maps RulebookReleases.FundingNote to schema:funding.")],
    "pkm4-p44": [fld("SemanticMappings.ReinventsStandardTerm", "Fires on extension terms minted although a reused standard already defines the term, which is ontology work failing to reuse an existing ontology; terms that reuse the standard read false.")],
    # ---------------------------------------------------------------- ont-4: concepts
    "ont4-c01": [tbl("DriftObservations", "Each row records a gap observed between a deployed model and the organization it describes.")],
    "ont4-c02": [tbl("ChangeAuthorityRules", "One rule per model and layer stating which role may change it, who approves, when, and through which process.")],
    "ont4-c03": [fld("ChangeAuthorityRules.BreakageResponse", "Each rule states the defined response when a change of that kind breaks the model, such as rolling back to the prior-state commit and notifying every consumer.")],
    "ont4-c05": [tbl("ModelExpansionRequests", "Requests from HR, the AI systems team and internal audit to model new workflows, with the decision on whether they fit the schema.")],
    "ont4-c06": [tbl("ExternalDependencyRevisions", "Revisions and deprecations published by reused standards (PROV-O errata, a DCAT term revision, a PKO patch) that the steward must track.")],
    "ont4-c07": [fld("RoleAssignments.SupersedesAssignment", "The risk classifier role's 2.4.1 assignment supersedes the 2.4.0 one: AI agents filling a role replaced by new model versions, kept as data.")],
    "ont4-c13": [fld("Agents.VersionOrEmploymentKey", "AI agents are individual Agents rows carrying their model version (risk classifier 2.4.0, 2.4.1, 2.5.0; ontology assistant 1.2.0).")],
    "ont4-c14": [fld("ModelChangeLogEntries.ChangeLayer", "Every logged change is typed as a schema, instance, vocabulary or documentation change, keeping the schema layer distinct from instance data.")],
    "ont4-c16": [fld("GovernedModels.CurrentRelease", "The PKO rulebook declares the release it is currently at (pko-release-1.0.0) in its own governance metadata.")],
    "ont4-c17": [fld("RulebookReleases.DeclaredScale", "Each release is declared a patch, minor or major release (or the initial cut), with its major, minor and patch numbers.")],
    "ont4-c18": [fld("ModelCharters.StewardResponsibilities", "Each charter names a steward role responsible for the model's health and writes down that responsibility.")],
    "ont4-c19": [fld("ModelCharters.AuthorityApprovalScope", "Each charter names the authority role and states its approval scope over schema, vocabulary and instance changes, detailed per layer in ChangeAuthorityRules.")],
    "ont4-c20": [tbl("ModelChangeLogEntries", "Change log rows carrying the change, its rationale, the motivating question (through its change request), terms affected, release version and date.")],
    "ont4-c21": [fld("ModelChangeRequests.StatedNeed", "Every change request begins from a stated need.")],
    "ont4-c22": [fld("ModelChangeRequests.MotivationKind", "Types the motivating question as an existing question the model now fails or a new question the organization needs.")],
    "ont4-c23": [tbl("ChangeImpactFindings", "What each impact assessment found a change does to instance data, inferences, query results and coverage.")],
    "ont4-c24": [tbl("DomainCoverageAreas", "The domain coverage model consulted during impact assessment: required areas and the table covering each.")],
    "ont4-c25": [tbl("ExpectedInferenceChecks", "Expected logical consequences the validation suite checks: an inference chain, the field it lands in and the value it must produce.")],
    "ont4-c26": [fld("ModelChangeRequests.Classification", "Each change is classified as a data operation or a modeling change.")],
    "ont4-c28": [fld("RoleAssignments.ValidTo", "Superseded assignments are kept as versioned assertions with a validity period, such as risk classifier 2.4.0 ending on 2026-01-10.")],
    "ont4-c29": [tbl("CompetencyQuestionReviews", "Periodic reviews of each model's competency question set with their outcomes.")],
    "ont4-c30": [fld("CompetencyQuestionSetEntries.IsOriginalBaseline", "Marks the original competency questions as a fixed baseline, kept apart from questions added later (the documentation-lag question).")],
    "ont4-c31": [fld("CompetencyQuestionSetEntries.Status", "A question can be marked DeprecationCandidate, as the CFO's outgrown close question is.")],
    "ont4-c38": [fld("TermDefinitions.Excludes", "Class definitions state what the class includes, what it excludes, and where it sits among neighboring terms.")],
    "ont4-c39": [fld("ModelProposals.IsAiCandidate", "Distinguishes candidates an AI agent produced from human commitments; CommittedByAgent records who made the commitment.")],
    "ont4-c53": [tbl("StalenessQueryRuns", "Runs of the staleness query over workflow last-modified dates, with threshold, result and whether it reached the steward.")],
    "ont4-c54": [fld("StakeholderQuestions.TriageOutcome", "Unanswerable stakeholder questions are triaged into more data, a minor schema extension or a structural change.")],
    # ---------------------------------------------------------------- ont-4: prescriptions
    "ont4-p02": [fld("ModelExpansionRequests.FitDecisionContradictsConceptFit", "Fires on internal audit's request, decided to fit the existing schema although its finding severity scale has no covering table; the HR request (every concept covered) and the AI pipeline request (decided to need new terms) read false.")],
    "ont4-p08": [fld("Agents.IsAiAgentWithoutModelVersion", "Fires on the wiki extractor, an AI agent registered with no model version identifier; every other AI agent carries one.")],
    "ont4-p09": [fld("ModelCharters.ControlsPrecedeOwnership", "Fires on the deployment family, whose change control policy was adopted in June 2025 while its first owner was named in February 2026; the other first charters were in place when controls began.")],
    "ont4-p10": [fld("ModelCharters.ConflatesStewardAndAuthority", "Fires on the first lockout charter, which named the knowledge engineer role as both steward and authority so the two responsibilities were never defined apart; the superseding charter separates them.")],
    "ont4-p11": [fld("ModelCharters.IsDriftWatchLapsed", "Fires on charters in force whose steward has not watched for drift in more than ninety days (deployment, close); stewards who watched recently read false.")],
    "ont4-p12": [fld("ExternalDependencyRevisions.IsUntrackedRevision", "Fires on the DCAT keyword guidance revision, untracked for over two months although the model maps to DCAT; the tracked PROV-O errata and the nine-day-old PKO patch read false.")],
    "ont4-p13": [fld("StakeholderQuestions.IsUnansweredPastDue", "Fires on the safety officer's retrofit question, unanswered for a month; the other users' questions got a response within days.")],
    "ont4-p14": [fld("ModelDocuments.IsBehindCurrentRelease", "Fires on PKO-ALIGNMENT.md and the changelog, which still describe 0.10.x while the model is at 1.0.0; the README and loop documents are current.")],
    "ont4-p15": [fld("RulebookReleases.SuiteLagsRelease", "Fires on releases that added schema with no validation-suite update by the steward (0.8.0, 0.10.1); 0.9.0 was accompanied by a suite update.")],
    "ont4-p16": [fld("ModelChangeRequests.StewardOwnChangeUnreviewed", "Fires on the steward's own ControlKinds rename and disjointness change, beyond minor scope and never reviewed by the authority; the steward's additive property change is minor and reads false.")],
    "ont4-p17": [fld("ModelCharters.IsStewardUnwritten", "Fires on the deployment charter, whose steward has no written responsibilities; every other charter writes them down.")],
    "ont4-p18": [fld("ModelCharters.IsAuthorityScopeUnstated", "Fires on the first PKO rulebook charter, which named an authority with no stated approval scope; later charters state it.")],
    "ont4-p19": [fld("ModelChangeLogEntries.IsUnexplainedModification", "Fires on schema and instance modifications logged with no rationale (the seeded close executions and the bulk-loaded property); other modifications carry their rationale.")],
    "ont4-p20": [fld("ModelCharters.IsAuthorityOutsideDomainOwner", "Fires when authority rests with a function other than the one owning the modeled domain (the first PKO charter's finance authority over a corporate model, the first lockout charter's corporate authority over the plant); superseding charters moved authority to the owning function.")],
    "ont4-p21": [fld("ModelCharters.IsNamedButUnexercised", "Fires on the deployment charter in force: its steward has recorded no activity. Charters whose stewards act and whose authorities decide read false.")],
    "ont4-p22": [fld("ModelCharters.IsSanctionedDualHolding", "True on the 35-person People Operations charter, where one person holds both distinct steward and authority roles without a committee; false where the roles are held by different people or merged into one role.")],
    "ont4-p23": [fld("ModelChangeRequests.PlacementNotDecidedByAuthority", "Fires on the RoleAssignments narrowing, raised by the release manager but with how and where it is implemented decided by the steward instead of the authority; the class removal's placement was decided by the authority.")],
    "ont4-p24": [fld("RulebookReleases.PatchAltersLogicalModel", "Fires on patch release 0.8.2, which widened a property range instead of touching only documentation, labels and comments; patch 0.8.1 changed only labels and data and reads false.")],
    "ont4-p25": [fld("RulebookReleases.MinorIsNotBackwardCompatible", "Fires on minor releases 0.10.0 (a class rename and an invalidating range change) and 0.10.1 (a disjointness axiom making individuals inconsistent); minor 0.9.0 was purely additive.")],
    "ont4-p26": [fld("RulebookReleases.ClassRemovalWithoutMajor", "Fires on 0.10.0, which renamed a class in a minor release; 1.0.0 removed a class as a major release and reads false.")],
    "ont4-p27": [fld("RulebookReleases.InvalidatingDomainRangeWithoutMajor", "Fires on 0.10.0, whose RoleAssignments domain narrowing invalidated an existing assignment in a minor release; 1.0.0's invalidating status range change was major.")],
    "ont4-p28": [fld("RulebookReleases.InconsistentDisjointnessWithoutMajor", "Fires on 0.10.1, where the human/software disjointness axiom made the plant organization agent inconsistent in a minor release.")],
    "ont4-p29": [fld("RulebookReleases.BreakingReleaseWithUnrevalidatedConsumers", "Fires on breaking releases that left consumers not re-validated: 0.10.0 (none) and 1.0.0 (the risk classifier's grounding context); 0.10.1 re-validated every consumer.")],
    "ont4-p30": [fld("RulebookReleases.BreakingReleaseWithoutMigrationPlan", "Fires on breaking release 0.10.0, which shipped with no migration plan; 0.10.1 and 1.0.0 carry one.")],
    "ont4-p31": [fld("RulebookReleases.IsUndocumentedVersionDecision", "Fires on 0.10.0, whose version increment records no rationale and no decider; the other releases document the versioning decision.")],
    "ont4-p32": [fld("RulebookReleases.IsUnannouncedToDependents", "Fires on 0.8.2 (only two of four consumers told) and 0.10.2 (nobody told); other releases were announced to every dependent consumer.")],
    "ont4-p33": [fld("ModelChangeLogEntries.IsInstanceChangeInSchemaRelease", "Fires on the seeded close executions shipped inside schema release 0.8.1; later instance loads were versioned as instance data versions and read false.")],
    "ont4-p34": [fld("ModelChangeRequests.IsMisrouted", "Compares each change's route with the rule for its layer: fires on the OperatingTemperature property, a schema change pushed through data operations; instance changes through data operations and schema changes through governance read false.")],
    "ont4-p35": [fld("ModelChangeLogEntries.IsSchemaChangeWithoutIncrement", "Fires on the bulk-loaded schema property that shipped in no semantic version; every other schema change belongs to a release.")],
    "ont4-p36": [fld("ReviewEvents.ReviewDidNotRefreshModified", "Fires on the close quarterly review held after the version's last-modified date without refreshing it; reviews that left the date current read false.")],
    "ont4-p37": [fld("ModelChangeLogEntries.SchemaChangeWithoutRequest", "Fires on schema changes made outside the change process with no change request (the initial load, the reviewer range widening and its revert); changes that went through a request read false.")],
    "ont4-p38": [fld("ModelChangeRequests.LacksMotivatingQuestion", "Fires on the disjointness change and the orientation survey request, which name no competency question; the rest are tied to one.")],
    "ont4-p39": [fld("ModelChangeRequests.UnmotivatedAndNotReturned", "Fires on the disjointness change, which had no competency question and went ahead; the orientation survey request without a question was returned for clarification and reads false.")],
    "ont4-p40": [fld("ModelChangeRequests.MissedInconsistentInstances", "Fires when instance data became inconsistent after deployment and the impact assessment identified none (the disjointness axiom, the status range restriction); the RoleAssignments narrowing's assessment did identify its inconsistent assignment.")],
    "ont4-p41": [fld("ModelChangeRequests.MissedAlteredInferences", "Fires when inferences changed after deployment with none identified by the assessment (the rename, the domain narrowing); the lockout class model's assessment identified its altered inference.")],
    "ont4-p42": [fld("ModelChangeRequests.MissedAlteredQueryResults", "Fires on the ControlKinds rename, which emptied the Procedure Register's control filter with no assessment having identified it; the classifier swap and class removal identified their altered queries up front.")],
    "ont4-p43": [fld("ModelChangeRequests.LeavesCoverageUnchecked", "Fires on accepted modeling changes never checked against the vocabulary layer and coverage model (the rename, the classifier upgrade handled as modeling); the others record the check.")],
    "ont4-p44": [fld("ModelChangeRequests.AcceptedWithoutTestRun", "Fires on modeling changes accepted without the validation suite ever being run with the change applied; ChangeValidationRuns.HasUninspectedFailures separately flags a run whose failures nobody inspected.")],
    "ont4-p45": [fld("ModelChangeRequests.StewardApprovalOutOfBounds", "Fires when a steward who is not also the authority approved a change beyond minor scope (the rename, the disjointness axiom, the status range restriction); the steward's approval of an additive property and a data load stays within bounds.")],
    "ont4-p46": [fld("ModelChangeRequests.AuthorityReviewSkipped", "Fires on accepted changes that alter existing elements, retire a definition or add disjointness with no authority review; the domain narrowing, vocabulary term and class removal were reviewed.")],
    "ont4-p47": [fld("ModelChangeRequests.IsMisclassifiedAgentSwap", "Fires on the 2.4.0 to 2.4.1 classifier upgrade, handled as a modeling change; the 2.5.0 trial swap was handled as a data operation.")],
    "ont4-p48": [fld("ModelChangeRequests.AiToHumanMoveWithoutComplianceReview", "Fires on moving production health verification to the SRE with no compliance consequences recorded; the night-shift verification move records them.")],
    "ont4-p49": [fld("ModelChangeRequests.AiToHumanMoveUnaudited", "Fires on the night-shift verification move, which records why but not when it took effect; the health verification move records both.")],
    "ont4-p50": [fld("RoleAssignments.PredecessorLacksValidityEnd", "Fires on the ontology authority assignment that supersedes the interim holder's assignment whose validity period was never closed; the classifier 2.4.1 assignment supersedes a properly closed one.")],
    "ont4-p51": [fld("CompetencyQuestionRuns.IsBaselineRegression", "Fires on the original agent-kind question, answerable at 0.9.0 and unanswerable at 0.10.0 after the domain narrowing: an original question the new version can no longer answer.")],
    "ont4-p52": [fld("RulebookReleases.CqCoverageDeclined", "Tracks competency question coverage per release and fires on 0.10.0, which answered 67% of its questions against 100% for 0.9.0.")],
    "ont4-p53": [fld("GovernedModels.CqReviewOverdue", "Fires on models whose question set has gone more than 92 days without review (close, deployment, press); the PKO rulebook, lockout, policy and vocabulary are within a quarter.")],
    "ont4-p54": [fld("StakeholderQuestions.UnanswerableWithoutScopeRequest", "Fires on unanswerable questions that never became a scope change request (classifier benchmarks, machine retrofits); the orientation survey question became one.")],
    "ont4-p55": [fld("CompetencyQuestionSetEntries.IrrelevantButStillActive", "Fires on the evidence-binding question review found no longer relevant but left active; the other outgrown close question was made a deprecation candidate.")],
    "ont4-p56": [fld("CompetencyQuestionRuns.IsUnfixedWrongAnswer", "Fires on the accountable-agent question answered wrongly at 1.0.0 with no defect raised; the documentation-lag question's wrong answer has a defect change request.")],
    "ont4-p64": [fld("ModelProposals.AiQuestionAdoptedUnvetted", "Fires on an AI-proposed question drawn from the engineering handbook that was adopted with no engineer vetting it; the vetted handbook question reads false.")],
    "ont4-p65": [fld("TermDefinitions.AiDraftAdoptedUnrevised", "Fires on the AI-drafted DriftObservations definition no person revised (its excludes says 'Nothing'); the AI-drafted ModelCharters definition was revised by the steward.")],
    "ont4-p66": [fld("ModelProposals.AiAlignmentDecidedByAi", "Fires on the prov:Activity alignment the assistant suggested and then committed itself; the p-plan alignment still awaits a person's decision.")],
    "ont4-p67": [fld("ModelProposals.AiAxiomWithoutHumanReview", "Fires on the AI-proposed human/software disjointness axiom whose only review was by the assistant itself.")],
    "ont4-p68": [fld("ModelProposals.AdoptionNotAnsweredByPerson", "Fires on AI output adopted by software (the prov alignment, the drift definition), where no person answers for the adoption.")],
    "ont4-p69": [fld("ModelProposals.HasNoHumanTouchpoint", "Fires on contributions proposed, reviewed and committed with no person at any stage (the legacy import's domain/range assertion, the AI definition committed by the extractor).")],
    "ont4-p84": [fld("StalenessQueryRuns.NotSurfacedToSteward", "Fires on the lockout staleness run that found the forklift inspection stale and never reached the steward; the PKO run's finding was surfaced the same day.")],
    "ont4-p85": [fld("ModelProposals.AiInstanceDataLoadedWithoutSteward", "Fires on the wiki-extracted hotfix assignment loaded after review by the release manager instead of the steward.")],
    "ont4-p86": [fld("StakeholderQuestions.IsMisroutedAfterTriage", "Fires on the contractor SMS consent question, triaged by the assistant as needing more data but sent through the governance route; the other triaged questions went to the process their outcome calls for.")],
    "ont4-p87": [fld("ModelChangeRequests.IntegrityDecidedWithoutHuman", "Fires on the disjointness change, whose integrity was checked only by the ontology assistant; schema changes with a person's integrity review read false.")],
    "ont4-p88": [fld("ModelChangeRequests.SkippedDisjointnessReview", "Fires on accepted schema changes never checked for disjointness violations (the rename, the bulk-loaded property).")],
    "ont4-p89": [fld("ModelChangeRequests.SkippedDomainInferenceReview", "Fires on accepted schema changes never checked for unintended domain inferences, including the disjointness change that had only a disjointness check.")],
    "ont4-p90": [fld("ModelChangeRequests.SkippedRangeReview", "Fires on accepted schema changes never checked for range inconsistencies, including the expected-duration properties checked for disjointness and domain but not range.")],
    "ont4-p91": [fld("ModelChangeRequests.AcceptedWithFailingSuite", "Fires on the RoleAssignments narrowing, accepted although its acceptance run failed two tests; changes whose full suite passed read false.")],
    "ont4-p92": [fld("Agents.IsUnclassifiedAgent", "Fires on the legacy import script, an agent classified as neither person nor software, so accountability for its commits cannot be answered from structure; every other agent is classified.")],
    "ont4-p93": [fld("ChangeValidationRuns.IsUnconfirmedConsistency", "Fires on validation runs that did not confirm the model free of logical inconsistency (two runs reporting inconsistency, one that never ran the check).")],
    "ont4-p94": [fld("ChangeValidationRuns.MissesExpectedInference", "Fires on the expected-duration run, where the expected documentation-lag inference chain was not produced; the lockout class model's run produced both its expected chains.")],
    "ont4-p95": [fld("RulebookTables.IsUnalignedToStandard", "Fires on tables with no exact or aligned mapping to any external standard, so outside systems cannot interpret them; tables mapped to PKO, PROV-O and the other reused standards read false.")],
    "ont4-p96": [fld("ModelChangeLogEntries.IsUntraceableBreakingChange", "Fires on the breaking changes in 0.10.0, whose versioning decision was never documented; breaking changes in 0.10.1 and 1.0.0 trace to a recorded decision.")],
    # ---------------------------------------------------------------- ont-4: competency questions
    "ont4-q03": [q("aq-ont4-q03", "Answered by AssignmentInstantChecks.HeldStepAtInstant with the assignment's agent version: on 2026-01-05 classifier 2.4.0 held deploy-02, on 2026-03-01 classifier 2.4.1.")],
    "ont4-q05": [q("aq-ont4-q05", "Answered by ProcedureVersions.IsUnmodifiedForTwelveMonths, which names the forklift inspection, unmodified since April 2025.")],
    "ont4-q09": [q("aq-ont4-q09", "Answered by ChangeImpactFindings of kind InconsistentInstance at assessment, rolled up as ModelChangeRequests.WouldMakeInstancesInconsistent.")],
    "ont4-q10": [q("aq-ont4-q10", "Answered by assessment-stage AlteredInference findings, rolled up as ModelChangeRequests.WouldAlterInferences.")],
    "ont4-q11": [q("aq-ont4-q11", "Answered by assessment-stage AlteredQueryResult findings, rolled up as ModelChangeRequests.WouldAlterQueryResults.")],
    "ont4-q12": [q("aq-ont4-q12", "Answered by CompetencyQuestionRuns re-run per release against the original baseline, with RulebookReleases.HasBaselineRegression naming the version that regressed.")],
    "ont4-q13": [q("aq-ont4-q13", "Answered by StakeholderQuestions.IsUnanswerableToday: a stakeholder question no competency question of the model answers.")],
    "ont4-q14": [q("aq-ont4-q14", "Answered by StakeholderQuestions.TriageOutcome with NeedsStructuralChange and IsUntriagedUnanswerable.")],
    "ont4-q15": [q("aq-ont4-q15", "Answered by GovernedModels.CurrentStewardAgent through the charter in force, with HasNoCurrentSteward flagging models nobody stewards.")],
    "ont4-q16": [q("aq-ont4-q16", "Answered by GovernedModels.CurrentAuthorityAgent, with HasNoCurrentAuthority flagging models nobody holds authority over.")],
    "ont4-q17": [q("aq-ont4-q17", "Answered by ModelChangeRequests.ApprovedByAgent, with IsAcceptedWithoutNamedApprover flagging accepted changes nobody approved on record.")],
    "ont4-q18": [q("aq-ont4-q18", "Answered by ModelChangeLogEntries.Rationale and its motivating question, with RationaleWithoutQuestion flagging a rationale no question stands behind.")],
    "ont4-q19": [q("aq-ont4-q19", "Answered by ModelChangeRequests.TargetRelease and the log's ReleaseVersion, with DeployedWithoutTargetRelease flagging a deployed schema change in no release.")],
    "ont4-q20": [q("aq-ont4-q20", "Answered by ModelChangeRequests of operation MoveStepToHuman: EffectiveAt says when and StatedNeed says why, flagged by IsAiToHumanMove.")],
    "ont4-q25": [q("aq-ont4-q25", "Answered by RulebookReleases.IsDeclaredCurrentRelease against GovernedModels.CurrentRelease: the model is at 1.0.0.")],
    "ont4-q29": [q("aq-ont4-q29", "Answered by CoverageGap findings against the DomainCoverageAreas model, rolled up as ModelChangeRequests.WouldLeaveCoverageIncomplete.")],
    "ont4-q30": [q("aq-ont4-q30", "Answered by ModelChangeRequests.MotivatingQuestion and MotivationKind, with MotivatedByFailingQuestion separating repairs from growth.")],
    # ---------------------------------------------------------------- ont-4: standards
    "ont4-s02": [meth("SemanticVersioning", "Applied by a MethodApplications row to RulebookReleases, whose declared patch/minor/major scale is checked against version numbers and change log contents.")],
    "ont4-s04": [prof("prov-o", "PROV-O maps agents and activities throughout, and loop 10 aligns ModelChangeLogEntries to prov:Activity, ChangedByAgent to prov:wasAssociatedWith and ApprovedByAgent to prov:wasAttributedTo.")],
    "ont4-s07": [prof("spin-sparql", "Impact-assessment queries are stored as SPARQL text in ChangeImpactFindings.DetectedByQuery, mapped to sp:text.")],
    "ont4-s13": [prof("owl-2-ontology-annotations", "RulebookReleases.RulebookVersion maps to owl:versionInfo, with owl:priorVersion and owl:versionIRI for the prior release and permanent identifier.")],
    # ---------------------------------------------------------------- ont-4: illustrations
    "ont4-i01": [fld("DriftObservations.WentUndetectedByPassingSuite", "Fires on the deployment drift: release 0.10.1 passed all its validation, yet the drift was found only by an expert's wrong answer. The resolved isolation-map drift caught by the suite reads false.")],
    "ont4-i02": [fld("GovernedModels.DegradationHiddenUntilWrongAnswer", "Fires on the deployment family: its drift surfaced only when the release manager noticed a wrong answer, and its question set was never periodically reviewed.")],
    "ont4-i03": [fld("GovernedModels.IsOwnerlessPastAYear", "Fires on the press-7 changeover family, registered in June 2024 and ownerless ever since; its procedure now exists only as a PDF and is being retired.")],
    "ont4-i10": [fld("ModelExpansionRequests.IsCrossFunctionExpansion", "Fires on HR's request to model its onboarding workflows in the corporate model (and the AI team's), not on internal audit's request from the owning function.")],
    "ont4-i11": [fld("ModelExpansionRequests.RequiresSchemaExtension", "Fires on the AI systems team's evaluation pipeline, whose benchmark suite concept has no table (and on audit's severity scale); HR onboarding fits existing tables.")],
    "ont4-i14": [fld("RulebookReleases.IsIncrementInconsistentWithScale", "Computes the expected next number from the previous release and the declared patch/minor/major scale (x.y.z+1, x.y+1.0, x+1.0.0) and fires on 0.10.1, declared minor but numbered as a patch.")],
    "ont4-i15": [fld("CompetencyQuestionSetEntries.IsOutgrownBaselineQuestion", "Fires on two of leadership's original close questions from March 2025, found no longer relevant after more than a year; the CFO's sign-off question still fits.")],
    "ont4-i19": [fld("ModelProposals.AwaitsEngineerVetting", "Fires on the assistant's handbook-derived candidate question about who is escalated to when a release approval stalls, not yet vetted by an engineer.")],
    "ont4-i20": [fld("ModelProposals.IsPendingAlignmentDecision", "Fires on the assistant's suggestion that ProcedureVersions specialize p-plan:Plan, a provenance plan class, awaiting a person's modeling decision.")],
    "ont4-i21": [fld("ModelChangeRequests.DomainChangeSpreadWrongInferences", "Fires on the RoleAssignments domain narrowing, whose altered accountability inferences surfaced in deployment queries.")],
    "ont4-i22": [fld("ModelChangeRequests.IntuitiveDisjointnessBrokeIndividuals", "Fires on the human/software disjointness axiom added with no motivating question, which made the plant organization agent inconsistent.")],
    "ont4-i26": [fld("ModelProposals.AwaitsStewardApproval", "Fires on the hotfix workflow steps the wiki extractor parsed from a newly written wiki page, proposed and awaiting approval.")],
    "ont4-i28": [fld("ModelCharters.StewardIsOutsideTooling", "Fires on the first PKO rulebook charter, stewarded by People Operations; the model moved to the knowledge engineer, who owns the build and publication tooling.")],
    "ont4-i29": [fld("CompetencyQuestionSetEntries.ServesEveryGovernanceUse", "Fires on questions that served as scoping tool, acceptance criterion, test driver and governance instrument in turn (the multi-step question, the CFO sign-off question).")],
    "ont4-i30": [fld("DriftObservations.DriftFollowsCleanRelease", "Fires on drift observed after releases that passed every acceptance validation (0.9.0, 0.10.1); drift after the failed 0.10.0 release and drift with no release reference read false.")],
}
