"""Evidence for theme A (loop-06): the PKO class model, lockout/tagout and the governed deployment.

(kind, target, justification). Validity is computed by ClaimEvidence.IsValid from Postgres
measurements; nothing here asserts coverage by itself.
"""


def fld(target, why):
    return ("Field", target, why)


def tbl(target, why):
    return ("Table", target, why)


def q(target, why):
    return ("RoleQuestion", target, why)


def prof(target, why):
    return ("OntologyProfile", target, why)


def proc(target, why):
    return ("Procedure", target, why)


EVIDENCE = {
    # ---------------------------------------------------------------- pkm-1
    "pkm1-c01": [fld("Procedures.CalledByStepCount", "Counts the steps of other procedures that invoke this one, so a procedure's interaction with other processes is recorded alongside its Purpose, not only its steps.")],
    "pkm1-c02": [fld("StepTransitions.Condition", "Every alternative and fallback transition states the condition under which the procedure leaves its usual path.")],
    "pkm1-c03": [tbl("ProcedureOutcomeCriteria", "Each row is a success or failure criterion for a procedure, with its polarity and statement.")],
    "pkm1-c17": [fld("StepVariables.SourceVariable", "Links each input to the output of the step that produces it, so what a step takes in is tied to what another step puts out.")],
    "pkm1-c18": [fld("Steps.ProcedureVersion", "Steps is the process-step class; every row belongs to a procedure version.")],
    "pkm1-c19": [fld("Agents.AgentKind", "Agents is the actor class, typed as human, AI agent, automated pipeline or organization.")],
    "pkm1-c20": [fld("Resources.ResourceKind", "Resources is the resource class, typed as document, media, page, dataset and so on.")],
    "pkm1-c21": [fld("StepConditions.ConditionKind", "StepConditions is the condition class: preconditions, postconditions and invariants on steps.")],
    "pkm1-c22": [fld("ProcedureExecutions.Outcome", "Each execution records how it turned out, the outcome class the ontology names.")],
    "pkm1-c23": [fld("StepTransitions.TransitionKind", "A Next transition is the precedes relationship between two steps.")],
    "pkm1-c24": [fld("Steps.PrerequisiteStep", "A step names the step it requires to be complete first: the requires relationship.")],
    "pkm1-c25": [fld("Steps.OutputVariableCount", "Counts the output variables a step produces: the produces relationship.")],
    "pkm1-c26": [tbl("StepRequirements", "Each row binds a step to a requirement that governs it: the governed-by relationship.")],
    "pkm1-c27": [fld("Steps.ExpertiseLevel", "A descriptive attribute on each step: the expertise level it is intended for, alongside its duration and control kind.")],
    "pkm1-c29": [fld("ProcedureExecutions.Facility", "Execution rows are the instance layer: one organization's actual runs at named facilities, above the procedure specifications.")],
    "pkm1-c31": [fld("StepExecutions.StepPrerequisite", "Each step execution carries the prerequisite its step depends on, which a deliverable must wait for.")],
    "pkm1-p16": [fld("ProcedureVersions.RestsOnNotationOnly", "Fires for a version whose steps came over from a diagram with no ontology type (the 2019 lockout checklist), where the notation alone gives nothing a reasoner can interpret.")],
    "pkm1-q01": [q("aq-pkm1-q01", "Asks which steps make up each process and which procedures exist only as a document.")],
    "pkm1-q02": [q("aq-pkm1-q02", "Asks which procedures and steps use each resource.")],
    "pkm1-q03": [q("aq-pkm1-q03", "Asks which issues coincided with a checked condition that did not hold.")],
    "pkm1-q04": [q("aq-pkm1-q04", "Asks what must be complete before each step and whether any step ran first.")],
    "pkm1-q10": [q("aq-pkm1-q10", "Asks which work is blocked because its prerequisite has not completed.")],
    "pkm1-i01": [fld("Steps.IsOnReworkLoop", "The weekly routine loops back on a decision; this loop-4 witness fires for steps a transition cycle returns to, which is how the model represents a decision that loops back.")],
    "pkm1-i02": [fld("StepExecutions.RanBeforePrerequisiteCompleted", "Fires for the hotfix rollout that ran before its approval prerequisite completed: a plan whose deliverable depended on an unmet prerequisite.")],

    # ---------------------------------------------------------------- pkm-2
    "pkm2-c41": [fld("RulebookTables.OrganizationLevel", "Every catalogued table is classified as conceptual, structural or contextual, the three levels the article organizes knowledge at.")],
    "pkm2-c42": [fld("Steps.ProcedureVersion", "Steps are activity sequences within a procedure version aimed at the procedure's purpose.")],
    "pkm2-c43": [fld("Steps.StepKind", "Atomic steps are the discrete units of work.")],
    "pkm2-c44": [fld("StepExecutions.ExecutedByAgent", "Every step execution names the human or computational agent that performed it.")],
    "pkm2-c45": [fld("Steps.RequiredLockCount", "Counts the locks a step consumes as required resources; tools and protective equipment are recorded the same way.")],
    "pkm2-c46": [fld("StepExecutions.GeneratedEntityCount", "Counts the entities a step execution generated: the artifacts it produced.")],
    "pkm2-c47": [fld("StepConditions.Statement", "Each condition states a state that enables or constrains a step.")],
    "pkm2-c48": [fld("ProcedureExecutions.Outcome", "Each execution records its outcome, the result that signals success or failure.")],
    "pkm2-c49": [fld("StepTransitions.TransitionKind", "Next transitions order steps; the inverse reading is recorded in RelationTypes.")],
    "pkm2-c50": [fld("ProcedureVersions.OverlapsRelationCount", "Counts overlaps relations among a version's steps; notifying staff overlaps the shutdown in lockout.")],
    "pkm2-c51": [fld("Steps.ParentStep", "A sub-step records the multi-step it is part of.")],
    "pkm2-c52": [fld("ProcedureVersions.EnablesRelationCount", "Counts enables relations; a verified zero-energy state enables maintenance.")],
    "pkm2-c53": [fld("ProcedureVersions.PreventsRelationCount", "Counts prevents relations; an applied lock prevents anyone else restoring energy.")],
    "pkm2-c54": [fld("Steps.PrerequisiteStep", "A step names the step it requires.")],
    "pkm2-c55": [fld("StepExecutions.ExecutedByAgent", "Each step execution is performed by a named agent.")],
    "pkm2-c56": [fld("Steps.AssignedRole", "Each step names the role responsible for it.")],
    "pkm2-c57": [tbl("StepRequirements", "Each row binds a step to a requirement that governs it.")],
    "pkm2-c58": [fld("ProcedureExecutions.ExecutedOnMachine", "Executions are instances placed in the framework: a specific run of a procedure on a specific machine by a specific agent.")],
    "pkm2-c60": [fld("Procedures.CalledByStepCount", "Lockout runs inside conveyor maintenance; the count records how many steps nest this procedure.")],
    "pkm2-c61": [fld("Steps.ChildStepCount", "Counts the sub-steps an activity is broken into; isolation has three.")],
    "pkm2-c88": [fld("Steps.PreconditionCount", "Counts a step's preconditions.")],
    "pkm2-c89": [fld("Steps.PostconditionCount", "Counts a step's postconditions.")],
    "pkm2-c90": [fld("Steps.InvariantCount", "Counts the invariants that must hold throughout a step.")],
    "pkm2-c91": [fld("FailureModes.Response", "Each failure mode states what goes wrong and the response to it.")],
    "pkm2-c92": [fld("DecisionPoints.DecidingFactors", "Each decision point states its question and the factors that drive it.")],
    "pkm2-p22": [fld("ActivityRelations.UsesUndefinedRelationType", "Fires for the relation linked by 'blocks', a type a technician proposed and nobody ratified, while every other relation uses a defined type.")],
    "pkm2-q19": [q("aq-pkm2-q19", "Asks what sub-activities make up a step.")],
    "pkm2-q20": [q("aq-pkm2-q20", "Asks what larger process a procedure runs inside.")],
    "pkm2-q22": [q("aq-pkm2-q22", "Asks what must be true before a step and whether anyone proceeded when it was not.")],
    "pkm2-q23": [q("aq-pkm2-q23", "Asks what must hold after a step.")],
    "pkm2-q24": [q("aq-pkm2-q24", "Asks what must stay true throughout a step and whether it broke.")],
    "pkm2-q25": [q("aq-pkm2-q25", "Asks a step's failure modes and the response to each.")],
    "pkm2-q26": [q("aq-pkm2-q26", "Asks what factors decide each decision point.")],
    "pkm2-q27": [q("aq-pkm2-q27", "Asks the order steps must run in and whether it was followed.")],
    "pkm2-s12": [prof("dmn-1-3", "DMN is a declared profile; DecisionPoints map to dmn:Decision and carry a DMN decision key.")],

    # ---------------------------------------------------------------- pkm-3
    "pkm3-c03": [fld("StepTransitions.TransitionKind", "Transitions order the recurring tasks of a procedure whose Purpose states the value it produces.")],
    "pkm3-c16": [fld("LifecycleStatuses.VersionUseCount", "Counts procedure versions in each status; approved versions are the standardized, repeatable procedures improvement builds on.")],
    "pkm3-p26": [fld("Procedures.HasNoExplicitSteps", "Fires for the press die changeover, a procedure that exists only as a PDF with no specified step, while every other procedure has an explicit representation.")],
    "pkm3-q01": [q("aq-pkm3-q01", "Asks whether a procedure specifies steps, order, conditions and exception handling.")],

    # ---------------------------------------------------------------- pkm-4
    "pkm4-c01": [fld("StepExecutions.ExecutionVersion", "Executions link to the specification they enact while remaining separate rows from it.")],
    "pkm4-c02": [fld("Steps.PreconditionCount", "Steps record their preconditions alongside duration, required locks and equipment, and the accountable role, within the transition order.")],
    "pkm4-c03": [fld("ProcedureVersions.FallbackStep", "A version declares its fallback step; lockout falls back to escalation and re-isolation.")],
    "pkm4-c04": [fld("ProcedureTargets.HandlingFailureModeCount", "Counts the documented handling for an unusually configured machine target; press 7 has its accumulator handling.")],
    "pkm4-c05": [fld("Steps.DangerCueCount", "Counts the cues on a step that call for escalating at once.")],
    "pkm4-c06": [fld("OntologyProfiles.MappingCount", "The PKO core module is a declared profile whose semantic mappings cover procedures, steps and executions; its mapping count holds the number of model terms mapped to it.")],
    "pkm4-c07": [tbl("Machines", "Machines, with their machine types, energy sources, locks, protective equipment and regulatory frameworks, are the industry module's manufacturing concepts; each maps to a pko-industry term.")],
    "pkm4-c08": [fld("ProcedureExecutions.Observations", "Each execution records its executor, date, what was noticed and its outcome.")],
    "pkm4-c14": [fld("Steps.CueCount", "Counts the indicators, sounds and confirmations a practitioner reads during a step.")],
    "pkm4-c15": [fld("Resources.ComplianceRecordFor", "A document names the regulated procedure it is kept as a compliance record for, separate from that procedure's specified steps.")],
    "pkm4-c16": [fld("DecisionPoints.Question", "Decision points record the conditions under which a different branch applies.")],
    "pkm4-c20": [fld("Procedures.ProcedureType", "Every procedure has a type.")],
    "pkm4-c21": [tbl("ProcedureTargets", "Each row is a thing a procedure is about: a machine, a data system, a population or a service.")],
    "pkm4-c22": [fld("Procedures.TemplateProcedure", "Lockout instantiates the corporate lockout template.")],
    "pkm4-c23": [tbl("ProcedureAdoptions", "Each row is an organization adopting a procedure.")],
    "pkm4-c24": [fld("ProcedureVersions.VersionNumber", "Every version carries a version number.")],
    "pkm4-c25": [fld("ProcedureVersions.NewVersionMotivation", "Versions record why they were created.")],
    "pkm4-c26": [fld("ProcedureVersions.ChangelogDescription", "Versions carry a changelog description.")],
    "pkm4-c27": [tbl("ProcedureVersionLinks", "Each row links a previous version to its next version.")],
    "pkm4-c28": [fld("Procedures.CurrentVersionKey", "Each procedure names its current version.")],
    "pkm4-c29": [fld("LifecycleStatuses.IsPkoStatus", "The status scheme holds the PKO procedure statuses draft, validation, approval, approved, deprecated and archived.")],
    "pkm4-c30": [fld("ProcedureStatusChanges.ToStatus", "Each change of status records the status it moved from and to.")],
    "pkm4-c31": [fld("ProcedureStatusChanges.ProcedureExecution", "A change of status can attach to an execution; the paused lockout run records one.")],
    "pkm4-c32": [fld("ProcedureStatusChanges.ChangeKind", "Each change records its kind: create, modify, extract, validate, approve or archive.")],
    "pkm4-c33": [fld("ProcedureStatusChanges.ChangedByAgent", "Each change records the agent who made it.")],
    "pkm4-c34": [fld("LifecycleStatuses.BroaderStatus", "Procedure statuses and execution statuses both specialize the general Status concept.")],
    "pkm4-c35": [fld("ProcedureVersions.ExpectedDurationUnit", "Versions carry an expected duration value with its temporal unit.")],
    "pkm4-c36": [fld("Steps.ProcedureVersion", "Every step records the procedure version (the plan) it belongs to.")],
    "pkm4-c37": [fld("ProcedureVersions.FirstStep", "Versions declare their first step.")],
    "pkm4-c38": [fld("ProcedureVersions.FallbackStep", "Versions declare their fallback step.")],
    "pkm4-c39": [fld("Steps.Description", "Steps carry a title, an identifier and a description.")],
    "pkm4-c40": [fld("Steps.StepNumber", "Steps carry a step number.")],
    "pkm4-c41": [fld("Steps.MinRepetitions", "Steps carry a minimum repetition count.")],
    "pkm4-c42": [fld("Steps.MaxRepetitions", "Steps carry a maximum repetition count.")],
    "pkm4-c43": [tbl("StepTransitions", "Transitions record each step's following and preceding step.")],
    "pkm4-c44": [fld("StepTransitions.IsRecoveryPath", "Identifies the alternative and fallback transitions, the alternative following and preceding steps.")],
    "pkm4-c45": [fld("Steps.ParentStep", "A sub-step records the multi-step it sits in, and a multi-step is itself a step row.")],
    "pkm4-c46": [fld("Steps.FirstChildStep", "A multi-step names its own first sub-step.")],
    "pkm4-c47": [fld("Steps.VerifiesStep", "A verification step is a step row that points back to the step it checks.")],
    "pkm4-c48": [tbl("StepTools", "Each row is a tool a step requires.")],
    "pkm4-c49": [tbl("StepActions", "Each row is an action a step requires.")],
    "pkm4-c50": [tbl("StepFunctions", "Each row is a function a step requires.")],
    "pkm4-c51": [fld("Steps.InputVariableCount", "Counts the input variables a step declares.")],
    "pkm4-c52": [fld("Steps.OutputVariableCount", "Counts the output variables a step declares.")],
    "pkm4-c53": [fld("ExecutionEntities.StepVariable", "Each used or generated entity names the declared variable it corresponds to.")],
    "pkm4-c54": [fld("Steps.ExpertiseLevel", "Steps name the expertise level they are intended for.")],
    "pkm4-c55": [tbl("StepResources", "Each row is a resource a step references.")],
    "pkm4-c56": [fld("Steps.RemedyForError", "Escalation and re-isolation is the remedy step for residual stored energy.")],
    "pkm4-c57": [fld("LifecycleStatuses.ExecutionUseCount", "Counts executions holding each PKO execution status; in progress, completed, paused and cancelled are all in use.")],
    "pkm4-c58": [fld("ProcedureExecutions.StartedAt", "Executions record their start and end times.")],
    "pkm4-c59": [fld("ProcedureExecutions.ParticipantCount", "Counts the agents associated with an execution besides its executor.")],
    "pkm4-c60": [fld("ProcedureExecutions.ConfirmedByAgent", "Executions name the agent who confirmed them.")],
    "pkm4-c61": [fld("ProcedureExecutions.Title", "Executions carry their own title, description and identifier.")],
    "pkm4-c62": [fld("StepExecutions.Step", "Each step execution belongs to a procedure execution and names the step it executed.")],
    "pkm4-c63": [fld("StepExecutions.PreviousStepExecution", "Step executions name the step execution that ran before them.")],
    "pkm4-c64": [fld("StepExecutions.UsedEntityCount", "Counts the entities a step execution used.")],
    "pkm4-c65": [fld("StepExecutions.GeneratedEntityCount", "Counts the entities a step execution generated.")],
    "pkm4-c66": [fld("UserFeedback.FeedbackOnProcedure", "Feedback records separate remarks on the procedure and on the execution, with its giver and time.")],
    "pkm4-c67": [fld("UserQuestions.AddressedByResource", "Question occurrences record the asker, the time and the resource that addresses the question.")],
    "pkm4-c68": [fld("IssueOccurrences.IssueCause", "Issue occurrences record cause, solution, the agent who hit them and when.")],
    "pkm4-c69": [fld("Errors.ErrorCode", "Errors carry a code, a cause and a description, and issue occurrences point to them.")],
    "pkm4-c70": [fld("Agents.IsOrganizationAgent", "An organization can act as an agent; the plant is recorded as one.")],
    "pkm4-c71": [fld("Agents.AgentKind", "Agents are typed as persons or as software (AI agents and automated pipelines).")],
    "pkm4-c72": [fld("RoleAssignments.ForProcedureVersion", "A role held in time ties an agent to a role, to the procedure version it is held for, and to a validity period.")],
    "pkm4-c73": [fld("Resources.CatalogEntryFor", "The lockout procedure's catalog entry is a resource that names the procedure it catalogs and carries resource metadata.")],
    "pkm4-c74": [fld("Resources.Description", "Resources carry a title, identifier and description.")],
    "pkm4-c75": [fld("Resources.Language", "Resources carry their language.")],
    "pkm4-c76": [fld("Resources.CreatedAt", "Resources carry created and modified dates.")],
    "pkm4-c77": [fld("Resources.Keywords", "Resources carry keywords.")],
    "pkm4-c78": [fld("Resources.ExternalUri", "Resources carry their access URL.")],
    "pkm4-c79": [fld("Resources.Format", "Resources carry their media type.")],
    "pkm4-c80": [fld("Resources.ModifiedByAgent", "Resources record their creator and last modifier.")],
    "pkm4-c81": [fld("Resources.ExtractedFromResource", "The lockout specification records the SOP it was extracted from.")],
    "pkm4-c82": [fld("Resources.ResourceKind", "Resources are typed as document, media and page, among others.")],
    "pkm4-c83": [tbl("ProcedureResources", "Each row is a resource a procedure version references.")],
    "pkm4-c84": [fld("FAQs.Answer", "FAQs carry a question and an answer.")],
    "pkm4-c85": [tbl("FaqCategories", "Each row is an FAQ category.")],
    "pkm4-c86": [tbl("FaqTargets", "Each row is an FAQ target.")],
    "pkm4-c87": [fld("FAQs.Resource", "An FAQ names its own catalog entry as a resource.")],
    "pkm4-p01": [fld("StepExecutions.ExecutesStepOfOtherVersion", "Fires for the night-shift run that recorded a step from the 2019 specification inside an execution of version 2.0.0: specification and execution merged instead of linked.")],
    "pkm4-p02": [fld("ProcedureVersions.HasNoExceptionHandling", "Fires for versions that encode only the normative path, with no exception, fallback or alternative, such as the 2019 lockout checklist.")],
    "pkm4-p03": [fld("ProcedureVersions.DocumentLagsPractice", "Fires when the documents a version rests on have not changed through months of changes to the version: the deployment runbook lags the procedure by half a year.")],
    "pkm4-p09": [fld("ProcedureVersions.IsInconsistentAcrossShifts", "Fires for lockout 2.0.0, which the day shift runs cleanly and the night shift ran with deviations.")],
    "pkm4-p10": [fld("ProcedureAdoptions.IsAdoptionModeUnstated", "Fires for the plant's adoption of the deployment procedure, which nobody recorded as as-is, extended or reference.")],
    "pkm4-p13": [fld("AuthoringSubmissions.IsExpertAuthoredConforming", "Fires for the veteran technician's capture-form submission that validated against the PKO profile without any ontology training; the knowledge engineer's submission does not count.")],
    "pkm4-p14": [fld("AuthoringSubmissions.IsNonConformingAccepted", "Fires for the conveyor maintenance submission that failed profile validation and was accepted anyway.")],
    "pkm4-p33": [fld("ProcedureExecutions.ClaimsCompletionWithoutAllSteps", "Fires for the hotfix deployment marked completed with the approval and health-check steps never run, which is what confirming completion must catch.")],
    "pkm4-p41": [fld("Steps.HasInstructionOnly", "Fires for steps that carry only their one-line instruction with no condition, cue, failure mode, decision or captured knowledge, and not for lockout's verification step.")],
    "pkm4-p42": [fld("ProcedureVersions.MixesHumanAndSoftwareSteps", "Fires for versions that mix human steps with software or AI steps, such as the deployment with its AI risk classifier and human release gate, and not for all-human lockout.")],
    "pkm4-q01": [q("aq-pkm4-q01", "Asks which regulation requires a procedure, its compliance document and its regulatory requirements.")],
    "pkm4-q02": [q("aq-pkm4-q02", "Asks which danger cues call for escalation and whether each observed one was escalated.")],
    "pkm4-q03": [q("aq-pkm4-q03", "Asks for the fallback and the handling of unusually configured equipment.")],
    "pkm4-q04": [q("aq-pkm4-q04", "Asks who ran an execution, who took part, and its observations and outcome.")],
    "pkm4-q05": [q("aq-pkm4-q05", "Asks whether an execution was completed and confirmed step by step.")],
    "pkm4-q06": [q("aq-pkm4-q06", "Asks for the current version and its motivation.")],
    "pkm4-q07": [q("aq-pkm4-q07", "Asks which issues occurred and whether they were solved.")],
    "pkm4-q08": [q("aq-pkm4-q08", "Asks which resource or FAQ addresses a practitioner's question.")],
    "pkm4-q09": [q("aq-pkm4-q09", "Asks whether execution differs between shifts or facilities.")],
    "pkm4-q10": [q("aq-pkm4-q10", "Asks which step comes first and next and whether the declared first step matches the flow.")],
    "pkm4-q11": [q("aq-pkm4-q11", "Asks whether the specified order ever puts a step before the step it depends on.")],
    "pkm4-q12": [q("aq-pkm4-q12", "Asks which cues show a step did not fully take effect.")],
    "pkm4-q15": [q("aq-pkm4-q15", "Asks what status changes a procedure went through, when and by whom.")],
    "pkm4-q16": [q("aq-pkm4-q16", "Asks which step remedies an error and which errors have none.")],
    "pkm4-q17": [q("aq-pkm4-q17", "Asks what tools, locks, protective equipment, actions and functions a step needs.")],
    "pkm4-s01": [prof("pko-core-2.0.0", "PKO core 2.0.0 is a declared profile with exact mappings.")],
    "pkm4-s02": [prof("pko-industry-2.0.0", "PKO industry 2.0.0 is a declared profile with exact mappings for machines, energy sources, locks and protective equipment.")],
    "pkm4-s03": [prof("p-plan", "P-Plan is a declared profile; steps and variables map to it.")],
    "pkm4-s04": [prof("dcat-3", "DCAT is a declared profile; resource keywords map to dcat:keyword.")],
    "pkm4-s05": [prof("dcterms", "DCMI terms is a declared profile; resource language, format, creator and step descriptions map to it.")],
    "pkm4-s06": [prof("owl-time", "OWL-Time is a declared profile; expected duration value and unit map to it.")],
    "pkm4-s07": [prof("pro", "PRO is a declared profile; roles held in time map to it.")],
    "pkm4-s08": [prof("m4ing", "Metadata4Ing is a declared profile; tools map to it.")],
    "pkm4-s09": [prof("adms-2", "ADMS is a declared profile; procedure version status maps to adms:status.")],
    "pkm4-s11": [prof("prov-o", "PROV-O is a declared profile; execution entities and participants map to it.")],
    "pkm4-x01": [proc("lockout-tagout", "Lockout/tagout has a compliance SOP, a workshop-built version with exceptions and cues, and recorded executions by veteran, night-shift and new technicians.")],
    "pkm4-i01": [fld("ProcedureTargets.IsUnhandledNonStandardTarget", "Machine procedures must carry equipment-specific handling; this fires for the converted mixer that no documented handling covers, and not for the press whose retrofit is handled.")],
    "pkm4-i03": [fld("StepExecutions.ExecutesStepOfOtherVersion", "A lockout specification set against one technician's lockout of it on a given night: the witness fires where that run strayed onto a different specification.")],
    "pkm4-i04": [fld("Steps.HasInstructionOnly", "The document line that only says to cut power is a step with its instruction and none of the judgment; this fires for exactly such steps.")],

    # ---------------------------------------------------------------- ont-4
    "ont4-c27": [fld("StepExecutions.SemanticTypeIri", "Step executions are typed pko:StepExecution, a specialization of prov:Activity.")],
    "ont4-c36": [fld("Steps.ReachableStepCount", "Counts every step reachable from a step along the closure of the ordering chain.")],
    "ont4-c45": [fld("Steps.AssignedRole", "Each workflow step names the role responsible for executing it.")],
    "ont4-q07": [q("aq-ont4-q07", "Asks which agent is accountable for each step right now.")],
    "ont4-q08": [q("aq-ont4-q08", "Asks whether the accountable agent is a person, software or an organization.")],
    "ont4-q28": [q("aq-ont4-q28", "Asks which steps come after a step anywhere along the ordering chain.")],
    "ont4-x01": [proc("production-deployment", "The deployment procedure has a release approval gate held by the release manager, with the VP of engineering as a separate role, and recorded executions.")],
    "ont4-x02": [proc("production-deployment", "The deployment procedure's AI risk classifier has a 2.5.0 candidate whose upgrade the model can assess against recorded executions.")],
    "ont4-x03": [proc("production-deployment", "The classifier assignment moved from 2.4.0 to 2.4.1 on 2026-01-10 with the earlier assignment kept; recorded executions on 2026-01-05 and 2026-03-01 were run by the version then in force.")],
    "ont4-x04": [proc("production-deployment", "The deployment procedure is the executed workflow on which a step's hand-off between AI and human execution is recorded.")],
    "ont4-x05": [proc("production-deployment", "The deployment procedure's release gate depends on the release manager assignment that must be updated before the next recorded deployment.")],
}
