"""Loop 12 (theme G): the social side of collection.

Process knowledge lives in people, communities, plants and systems before it lives in documents. The
articles ask who holds which know-how, who knows where it is held, who bridges communities and
translates their vocabularies, what a source withholds and why, whether collection negotiates power and
builds trust, whether knowledge survives the people who carry it, whether mentoring has time, whether
sharing is rewarded, and whether solved problems stay solved.

The plant carries the apprenticeship story: Tomas Reyes (since 1994) retires on 2026-09-30 with his
accumulator bleed-down know-how untransferred while three new technicians start at once. Engineering
carries the turnover story: a departed SRE's health-check judgment was never captured, the release
checklist went stale, and a contractor's cache fix was never written down, so the bug came back.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from rulebook_edit import agg, calc, idx, lookup, raw, rel  # noqa: E402

EXT = "urn:effortless:pko-extension#"
PROV = "http://www.w3.org/ns/prov#"
EV = "eval-current"

LOOP = {
    "WitnessLoopId": "loop-12",
    "LoopNumber": 12,
    "Title": "Loop 12: the social side of collection: holders, brokers, communities, trust and turnover",
    "Premise": "Loops 6 to 11 gave the model procedures, executions, role assignments with departures, a broker "
               "network, communities of practice and a sourcing audit. What the model still could not say was who "
               "carries each piece of know-how (a person, a facility or a system), how it travels, who bridges "
               "communities and translates their vocabularies, what a source withholds under which power dynamic, "
               "whether departments disagree about the same process, whether mentors have time and sharers are "
               "rewarded, and whether knowledge and solved problems survive staff turnover. This loop adds each of "
               "those, with seeded breaches on the lockout and deployment scenarios.",
}

KE, STEWARD, AUTH, OPS, RELEASE, VP, HR = ("knowledge-engineer", "process-steward", "knowledge-authority",
                                          "plant-operations-manager", "release-manager", "vp-engineering",
                                          "hr-policy-owner")


def T(name, desc, area, *fields):
    return (name, desc, area, list(fields))


def pk(name):
    return raw(name, "string", "Stored identifier.", nullable=False)


def iri():
    return raw("SemanticTypeIri", "string", "Semantic type IRI.")


def as_of():
    return [rel("EvaluationContext", "EvaluationContexts", "The instant the row is judged against."),
            lookup("AsOfInstant", "datetime", "The modeled evaluation instant.",
                   idx("EvaluationContexts", "AsOfInstant", "EvaluationContext"))]


def F(table, *names):
    return [f"{table}.{n}" for n in names]


def _rows(cols, *values, iri_=None):
    out = []
    for v in values:
        row = dict(zip(cols, v))
        if iri_ is not None:
            row["SemanticTypeIri"] = iri_
        out.append(row)
    return out


AGENTS = [
    {"AgentId": "walter-grieg", "DisplayName": "Walter Grieg", "AgentKind": "Human", "Organization": "acme-plant",
     "ContactAddress": "walter.grieg@example.com", "VersionOrEmploymentKey": "press-setter-1979", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "bea-okonkwo", "DisplayName": "Bea Okonkwo", "AgentKind": "Human", "Organization": "acme-plant",
     "ContactAddress": "bea.okonkwo@example.com", "VersionOrEmploymentKey": "technician-2026b", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "carlos-mendez", "DisplayName": "Carlos Mendez", "AgentKind": "Human", "Organization": "acme-plant",
     "ContactAddress": "carlos.mendez@example.com", "VersionOrEmploymentKey": "technician-2026c", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "anil-kapoor", "DisplayName": "Anil Kapoor", "AgentKind": "Human", "Organization": "tidewater-dev-services",
     "ContactAddress": "anil.kapoor@example.com", "VersionOrEmploymentKey": "contract-developer-2024", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "petra-lindqvist", "DisplayName": "Petra Lindqvist", "AgentKind": "Human", "Organization": "northfield-conveyor",
     "ContactAddress": "petra.lindqvist@example.com", "VersionOrEmploymentKey": "drives-specialist-2014", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "joao-ferreira", "DisplayName": "Joao Ferreira", "AgentKind": "Human", "Organization": "baxter-hydraulics",
     "ContactAddress": "joao.ferreira@example.com", "VersionOrEmploymentKey": "servo-technician-2011", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "nina-sorensen", "DisplayName": "Nina Sorensen", "AgentKind": "Human", "Organization": None,
     "ContactAddress": "nina.sorensen@example.com", "VersionOrEmploymentKey": "school-leaver-2025", "SemanticTypeIri": "prov:Agent"},
]


KHC = "KnowHowCarriers"
TABLES = [
    T(KHC,
      "One piece of an organization's process know-how and what carries it: a person, a facility or a system, with the "
      "community it belongs to, the forms it is held in, and how long it took to build.", "social-knowledge",
      pk("KnowHowCarrierId"),
      calc("Name", "string", "Display name.", '={{Topic}} & " / " & {{CarrierKind}}'),
      raw("Topic", "string", "What the know-how is about."),
      rel("Organization", "Organizations", "The organization whose know-how this is."),
      rel("Procedure", "Procedures", "The procedure the know-how serves."),
      rel("CommunityOfPractice", "CommunitiesOfPractice", "The community in which the know-how circulates."),
      raw("CarrierKind", "string", "Person, Facility or System."),
      rel("HolderAgent", "Agents", "The person who carries it, when the carrier is a person."),
      rel("HolderFacility", "Facilities", "The plant that carries it in its layout and equipment, when the carrier is a facility."),
      raw("KnowHowKind", "string", "WhatFails, Diagnosis, Improvisation or Refinement: the kind of practitioner know-how."),
      raw("IsInWrittenProcedure", "boolean", "TRUE when the know-how is written into a procedure."),
      raw("IsTrainedSkill", "boolean", "TRUE when the know-how is carried as trained skill of seasoned workers."),
      raw("WorkMedium", "string", "Physical or Digital work."),
      raw("HeldSince", "datetime", "When the carrier began to hold the know-how."),
      rel("BuildsOnKnowHow", KHC, "Know-how about a related component or system this know-how depends on."),
      raw("IsInPublicReferences", "boolean", "TRUE when the know-how can be found in public references."),
      raw("ReplacementPlan", "string", "How the organization plans to replace the know-how if lost: PublicReference, AiGeneration, Apprenticeship, or blank."),
      *as_of(),
      lookup("HolderIsStillEngaged", "boolean", "Whether the holding person still holds a current role.",
             idx("Agents", "IsStillEngaged", "HolderAgent")),
      lookup("HolderServiceStartedAt", "datetime", "When the holder began service.", idx("Agents", "ServiceStartedAt", "HolderAgent")),
      lookup("HolderDepartureAt", "datetime", "The holder's planned or actual departure.", idx("Agents", "DepartureAt", "HolderAgent")),
      calc("DaysUntilHolderDeparture", "integer", "Days from the evaluation instant to the holder's departure; negative once gone.",
           '=IF({{HolderDepartureAt}} = "", 99999, DATETIME_DIFF({{HolderDepartureAt}}, {{AsOfInstant}}, "days"))'),
      calc("DaysServedToAsOf", "integer", "Days of service up to the evaluation instant.",
           '=IF({{HolderServiceStartedAt}} = "", 0, DATETIME_DIFF({{AsOfInstant}}, {{HolderServiceStartedAt}}, "days"))'),
      calc("DaysServedToDeparture", "integer", "Days of service up to departure.",
           '=IF(OR({{HolderServiceStartedAt}} = "", {{HolderDepartureAt}} = ""), 0, DATETIME_DIFF({{HolderDepartureAt}}, {{HolderServiceStartedAt}}, "days"))'),
      calc("HolderTenureYears", "number", "Years the holder practised: to departure when gone, else to the evaluation instant.",
           '=ROUND(IF(AND({{HolderDepartureAt}} <> "", {{DaysUntilHolderDeparture}} < 0), {{DaysServedToDeparture}}, {{DaysServedToAsOf}}) / 365, 1)'),
      calc("IsVeteranHeld", "boolean", "TRUE when a person with ten or more years of practice carries the know-how.",
           '=AND({{HolderAgent}} <> "", {{HolderTenureYears}} >= 10)'),
      calc("IsHolderLeavingSoon", "boolean", "TRUE when the holder leaves within 120 days of the evaluation instant.",
           '=AND({{HolderDepartureAt}} <> "", {{DaysUntilHolderDeparture}} >= 0, {{DaysUntilHolderDeparture}} <= 120)'),
      agg("TransferCount", "integer", "Recorded transfers of this know-how to someone else.",
          "=COUNTIFS(KnowledgeTransfers!{{KnowHow}}, {{KnowHowCarrierId}})"),
      agg("RepositoryEntryCount", "integer", "Repository entries that capture this know-how.",
          "=COUNTIFS(KnowledgeRepositoryEntries!{{KnowHow}}, {{KnowHowCarrierId}})"),
      agg("SourceRelationshipCount", "integer", "Collection relationships with this holder on this procedure.",
          "=COUNTIFS(SourceRelationships!{{SourceAgent}}, {{HolderAgent}}, SourceRelationships!{{Procedure}}, {{Procedure}})"),
      calc("IsHeldInBothForms", "boolean", "TRUE when the know-how is at once a written procedure and trained skill.",
           "=AND({{IsInWrittenProcedure}}, {{IsTrainedSkill}})"),
      calc("IsHeldByCurrentPractitioner", "boolean", "TRUE when a person who still holds a role carries the know-how.",
           '=AND({{HolderAgent}} <> "", {{HolderIsStillEngaged}} = TRUE)'),
      calc("IsUntransferredVeteranKnowHow", "boolean", "TRUE when a serving veteran carries know-how never transferred or captured.",
           "=AND({{IsVeteranHeld}}, {{HolderIsStillEngaged}} = TRUE, {{TransferCount}} = 0, {{RepositoryEntryCount}} = 0)"),
      calc("IsAtRiskOfImminentLoss", "boolean", "TRUE when untransferred veteran know-how belongs to someone leaving within 120 days.",
           "=AND({{IsUntransferredVeteranKnowHow}}, {{IsHolderLeavingSoon}})"),
      calc("IsHeldOnlyByDeparted", "boolean", "TRUE when the only carrier has left and the know-how was neither transferred nor captured.",
           '=AND({{HolderAgent}} <> "", {{HolderIsStillEngaged}} = FALSE, {{TransferCount}} = 0, {{RepositoryEntryCount}} = 0)'),
      calc("IsHeldByDepartedHolder", "boolean", "TRUE when the person who carried the know-how has left.",
           '=AND({{HolderAgent}} <> "", {{HolderIsStillEngaged}} = FALSE)'),
      calc("IsCaptured", "boolean", "TRUE when a repository entry captures the know-how.", "={{RepositoryEntryCount}} > 0"),
      calc("MustBeRelearnedIfHolderLeaves", "boolean", "TRUE when a serving holder's know-how has nothing captured for a successor.",
           '=AND({{HolderAgent}} <> "", {{HolderIsStillEngaged}} = TRUE, {{RepositoryEntryCount}} = 0)'),
      calc("IsOverlookedLivingHolder", "boolean", "TRUE when uncaptured know-how has a serving holder no collection relationship has approached.",
           '=AND({{HolderAgent}} <> "", {{HolderIsStillEngaged}} = TRUE, {{RepositoryEntryCount}} = 0, {{SourceRelationshipCount}} = 0)'),
      calc("TransferStopsWithoutVeteran", "boolean", "TRUE when veteran know-how has only been passed person to person with nothing captured, so the next newcomer still needs the veteran.",
           "=AND({{IsVeteranHeld}}, {{HolderIsStillEngaged}} = TRUE, {{TransferCount}} > 0, {{RepositoryEntryCount}} = 0)"),
      lookup("DependencyCommunity", "string", "The community of the know-how this builds on.",
             idx(KHC, "CommunityOfPractice", "BuildsOnKnowHow", "KnowHowCarrierId")),
      calc("BuildsOnSameCommunityKnowHow", "boolean", "TRUE when the know-how depends on related know-how concentrated in the same community.",
           '=AND({{BuildsOnKnowHow}} <> "", {{CommunityOfPractice}} <> "", {{DependencyCommunity}} = {{CommunityOfPractice}})'),
      calc("LostAccumulationYears", "number", "Years of practice lost with a departed sole carrier; zero otherwise.",
           "=IF({{IsHeldOnlyByDeparted}}, {{HolderTenureYears}}, 0)"),
      calc("IsDelegatedToUnfitSource", "boolean", "TRUE when the plan is to replace the know-how from public references or AI generation although it is not in public references.",
           '=AND(OR({{ReplacementPlan}} = "PublicReference", {{ReplacementPlan}} = "AiGeneration"), {{IsInPublicReferences}} = FALSE)'),
      iri()),
    T("KnowledgeTransfers",
      "One occasion on which know-how passed from one person to another, and the channel it travelled through.", "social-knowledge",
      pk("KnowledgeTransferId"),
      calc("Name", "string", "Display name.", '={{KnowHow}} & " via " & {{Channel}}'),
      rel("KnowHow", KHC, "The know-how that passed."),
      rel("FromAgent", "Agents", "Who passed it on."),
      rel("RecipientAgent", "Agents", "Who received it, when one person did."),
      raw("Channel", "string", "Document, TrainingProgram, Mentoring, PersonalRelationship, Collaboration, DesignProductionIteration, EmployerChange or AmbientExposure."),
      rel("CommunityOfPractice", "CommunitiesOfPractice", "The community the transfer took place in."),
      raw("OccurredAt", "datetime", "When the transfer took place."),
      raw("OnAllocatedTime", "boolean", "TRUE when the transfer was done on time the organization allotted for it."),
      lookup("FromOrganization", "string", "The giver's organization.", idx("Agents", "Organization", "FromAgent")),
      lookup("RecipientRoleCount", "integer", "Current role assignments the recipient holds.",
             idx("Agents", "CountOfCurrentRoleAssignments", "RecipientAgent")),
      calc("IsTraditionalChannel", "boolean", "TRUE for the traditional channels: documents, training programs and mentoring.",
           '=OR({{Channel}} = "Document", {{Channel}} = "TrainingProgram", {{Channel}} = "Mentoring")'),
      calc("IsSocialNetworkChannel", "boolean", "TRUE for relationships, collaboration, design-production iteration and people changing employers.",
           '=OR({{Channel}} = "PersonalRelationship", {{Channel}} = "Collaboration", {{Channel}} = "DesignProductionIteration", {{Channel}} = "EmployerChange")'),
      calc("IsAmbientAbsorptionByNonPractitioner", "boolean", "TRUE when someone holding no role absorbed the know-how by living among the trade.",
           '=AND({{RecipientAgent}} <> "", {{Channel}} = "AmbientExposure", {{RecipientRoleCount}} = 0)'),
      iri()),
    T("KnowledgeRepositoryEntries",
      "Captured procedural knowledge kept in a repository: who wrote it, whose know-how it records, for whom, whether it came "
      "back from executing the work, and whether it is kept current.", "social-knowledge",
      pk("KnowledgeRepositoryEntryId"),
      calc("Name", "string", "Display name.", "={{Title}}"),
      raw("Title", "string", "Entry title."),
      rel("Procedure", "Procedures", "The procedure the entry documents."),
      rel("KnowHow", KHC, "The know-how the entry captures, when it captures a recorded carrier's know-how."),
      rel("AuthorAgent", "Agents", "Who wrote the entry."),
      rel("SourceExpert", "Agents", "Whose expertise the entry records."),
      raw("CreditsSourceExpert", "boolean", "TRUE when the entry names and credits the source expert."),
      raw("WrittenForAudience", "string", "LaterColleagues (written as part of the craft) or ComplianceAudit."),
      raw("AuthoredOnAllocatedTime", "boolean", "TRUE when the writing was done on time the organization allotted for it."),
      rel("FedFromExecution", "ProcedureExecutions", "The execution whose experience the entry wrote back."),
      raw("CreatedAt", "datetime", "When the entry was created."),
      raw("LastUpdatedAt", "datetime", "When the entry was last revised."),
      raw("ReviewIntervalDays", "integer", "How often the entry must be revised to stay current."),
      *as_of(),
      lookup("AuthorIsStillEngaged", "boolean", "Whether the author still holds a role.", idx("Agents", "IsStillEngaged", "AuthorAgent")),
      lookup("AuthorAgentKind", "string", "The author's kind.", idx("Agents", "AgentKind", "AuthorAgent")),
      lookup("OwnerOrganization", "string", "The organization that owns the procedure.", idx("Procedures", "OwnerOrganization", "Procedure")),
      calc("DaysSinceUpdated", "integer", "Days since the last revision.",
           '=IF({{LastUpdatedAt}} = "", 0, DATETIME_DIFF({{AsOfInstant}}, {{LastUpdatedAt}}, "days"))'),
      calc("IsStale", "boolean", "TRUE when the entry has gone longer than its review interval without revision.",
           "=AND({{ReviewIntervalDays}} > 0, {{DaysSinceUpdated}} > {{ReviewIntervalDays}})"),
      calc("IsExecutionFeedback", "boolean", "TRUE when the entry wrote back what an execution taught.", '={{FedFromExecution}} <> ""'),
      calc("IsMachineAuthored", "boolean", "TRUE when an AI agent or pipeline wrote the entry.",
           '=AND({{AuthorAgent}} <> "", OR({{AuthorAgentKind}} = "AIAgent", {{AuthorAgentKind}} = "AutomatedPipeline"))'),
      calc("OutlivesAuthorTenure", "boolean", "TRUE when the entry is still current although its author has left.",
           '=AND({{AuthorAgent}} <> "", {{AuthorIsStillEngaged}} = FALSE, {{IsStale}} = FALSE)'),
      calc("IsUncreditedExpertKnowHow", "boolean", "TRUE when an entry records another person's expertise without crediting them.",
           '=AND({{SourceExpert}} <> "", {{SourceExpert}} <> {{AuthorAgent}}, {{CreditsSourceExpert}} = FALSE)'),
      iri()),
    T("CommunityMemberships",
      "A person's membership of a community of practice, whether they belong to a different organization, and whether "
      "they are a specialist others consult.", "social-knowledge",
      pk("CommunityMembershipId"),
      calc("Name", "string", "Display name.", '={{Agent}} & " in " & {{CommunityOfPractice}}'),
      rel("CommunityOfPractice", "CommunitiesOfPractice", "The community."),
      rel("Agent", "Agents", "The member."),
      raw("IsSpecialist", "boolean", "TRUE when the member is a specialist others in the community consult."),
      raw("JoinedAt", "datetime", "When the member joined."),
      lookup("MemberOrganization", "string", "The member's organization.", idx("Agents", "Organization", "Agent")),
      lookup("CommunityOrganization", "string", "The organization hosting the community.",
             idx("CommunitiesOfPractice", "Organization", "CommunityOfPractice", "CommunityOfPracticeId")),
      calc("IsExternalMember", "boolean", "TRUE when the member works for a different organization than the community's host.",
           '=AND({{MemberOrganization}} <> "", {{MemberOrganization}} <> {{CommunityOrganization}})'),
      iri()),
    T("SourceRelationships",
      "The standing relationship between a knowledge engineer and a knowledge source on one procedure: the power dynamic, "
      "what was negotiated, the state of trust, and what the source withholds and why.", "social-knowledge",
      pk("SourceRelationshipId"),
      calc("Name", "string", "Display name.", '={{KnowledgeEngineer}} & " with " & {{SourceAgent}}'),
      rel("KnowledgeEngineer", "Agents", "The knowledge engineer collecting."),
      rel("SourceAgent", "Agents", "The knowledge source."),
      rel("Procedure", "Procedures", "The procedure the knowledge serves."),
      raw("SourceStanding", "string", "The source's standing relative to the engineer (SeniorVeteran, Peer, Manager)."),
      raw("PowerDynamic", "string", "Balanced, SourceOutranksEngineer, SupervisorPresent or JobSecurityThreat."),
      raw("NegotiatedAgreement", "string", "What was negotiated with the source about how their knowledge is collected and used."),
      raw("TrustLevel", "string", "Low, Building or Established."),
      raw("TrustBuildingPractice", "string", "What the engineer does to build trust with the source."),
      raw("WithholdingObserved", "boolean", "TRUE when the source was seen to hold information back."),
      raw("WithholdingMotive", "string", "Why the source holds information back (status, job security)."),
      raw("StartedAt", "datetime", "When the relationship began."),
      calc("IsUnnegotiatedPowerGap", "boolean", "TRUE when a power imbalance shapes the relationship and nothing was negotiated.",
           '=AND({{PowerDynamic}} <> "", {{PowerDynamic}} <> "Balanced", {{NegotiatedAgreement}} = "")'),
      calc("IsExtractiveRelationship", "boolean", "TRUE when trust is not established and no trust-building practice is recorded.",
           '=AND({{TrustLevel}} <> "", {{TrustLevel}} <> "Established", {{TrustBuildingPractice}} = "")'),
      iri()),
    T("DepartmentProcessAccounts",
      "The account a stakeholder department gives of a process, the interest shaping it, any conflicting account from another "
      "department, and the practice used to resolve the disagreement.", "social-knowledge",
      pk("DepartmentProcessAccountId"),
      calc("Name", "string", "Display name.", '={{Department}} & " on " & {{Procedure}}'),
      rel("Procedure", "Procedures", "The process accounted for."),
      rel("Department", "Organizations", "The stakeholder department."),
      rel("StakeholderAgent", "Agents", "Who speaks for the department."),
      raw("EngagedAt", "datetime", "When the department was engaged in shaping the process knowledge; blank if never."),
      raw("AccountSummary", "string", "The department's account of the process."),
      raw("ShapingInterest", "string", "The departmental interest that shapes the account."),
      rel("ConflictsWithAccount", "DepartmentProcessAccounts", "Another account of the same process this one contradicts."),
      raw("ResolutionPractice", "string", "The practice used to resolve the disagreement."),
      raw("ResolvedAt", "datetime", "When the disagreement was resolved."),
      lookup("ConflictingDepartment", "string", "The department giving the contradicting account.",
             idx("DepartmentProcessAccounts", "Department", "ConflictsWithAccount", "DepartmentProcessAccountId")),
      calc("IsAwaitingEngagement", "boolean", "TRUE when the stakeholder department has not been engaged.", '={{EngagedAt}} = ""'),
      calc("IsConflictingAccount", "boolean", "TRUE when another department gives a contradicting account of the same process.",
           '=AND({{ConflictsWithAccount}} <> "", {{ConflictingDepartment}} <> {{Department}})'),
      calc("IsUnresolvedDisagreement", "boolean", "TRUE when a cross-department conflict has no resolution practice.",
           '=AND({{IsConflictingAccount}}, {{ResolutionPractice}} = "")'),
      iri()),
    T("ProblemOccurrences",
      "One occurrence of a recurring work problem: who solved it, whether the solution was recorded, and the earlier "
      "occurrence of the same problem.", "social-knowledge",
      pk("ProblemOccurrenceId"),
      calc("Name", "string", "Display name.", '={{ProblemSignature}} & " / " & {{ProblemOccurrenceId}}'),
      raw("ProblemSignature", "string", "The recognizable problem."),
      rel("Procedure", "Procedures", "The procedure in which it occurred."),
      raw("OccurredAt", "datetime", "When it occurred."),
      rel("SolvedByAgent", "Agents", "Who solved it."),
      raw("SolvedAt", "datetime", "When it was solved; blank while open."),
      rel("SolutionEntry", "KnowledgeRepositoryEntries", "The repository entry recording the solution."),
      rel("PriorOccurrence", "ProblemOccurrences", "The earlier occurrence of the same problem."),
      lookup("SolverIsStillEngaged", "boolean", "Whether the solver still holds a role.", idx("Agents", "IsStillEngaged", "SolvedByAgent")),
      calc("IsSolved", "boolean", "TRUE once the occurrence was solved.", '={{SolvedAt}} <> ""'),
      lookup("PriorWasSolved", "boolean", "Whether the earlier occurrence was solved.",
             idx("ProblemOccurrences", "IsSolved", "PriorOccurrence", "ProblemOccurrenceId")),
      lookup("PriorSolutionEntry", "string", "The earlier occurrence's recorded solution.",
             idx("ProblemOccurrences", "SolutionEntry", "PriorOccurrence", "ProblemOccurrenceId")),
      lookup("PriorSolver", "string", "Who solved the earlier occurrence.",
             idx("ProblemOccurrences", "SolvedByAgent", "PriorOccurrence", "ProblemOccurrenceId")),
      lookup("PriorSolverIsStillEngaged", "boolean", "Whether the earlier solver still holds a role.",
             idx("ProblemOccurrences", "SolverIsStillEngaged", "PriorOccurrence", "ProblemOccurrenceId")),
      calc("IsSolvedWithoutRecordedSolution", "boolean", "TRUE when the problem was solved and the solution was not recorded.",
           '=AND({{IsSolved}}, {{SolutionEntry}} = "")'),
      calc("HasBeenSolvedBefore", "boolean", "TRUE when an earlier occurrence of the same problem was solved.",
           '=AND({{PriorOccurrence}} <> "", {{PriorWasSolved}} = TRUE)'),
      calc("HasConsultableSpecialist", "boolean", "TRUE when whoever solved the earlier occurrence still holds a role and can be consulted.",
           '=AND({{HasBeenSolvedBefore}}, {{PriorSolver}} <> "", {{PriorSolverIsStillEngaged}} = TRUE)'),
      calc("IsRelearnedSolvedProblem", "boolean", "TRUE when a problem solved before came back and its earlier fix had not been recorded.",
           '=AND({{HasBeenSolvedBefore}}, {{PriorSolutionEntry}} = "")'),
      calc("IsTurnoverRegression", "boolean", "TRUE when an unrecorded fix came back after the person who made it left.",
           '=AND({{IsRelearnedSolvedProblem}}, {{PriorSolver}} <> "", {{PriorSolverIsStillEngaged}} = FALSE)'),
      iri()),
    T("OnboardingRecords",
      "A new starter learning a procedure: when they started, when they reached proficiency, and whether they learned from "
      "captured, formalized knowledge.", "social-knowledge",
      pk("OnboardingRecordId"),
      calc("Name", "string", "Display name.", '={{NewStarter}} & " on " & {{Procedure}}'),
      rel("NewStarter", "Agents", "The new starter."),
      rel("Procedure", "Procedures", "The procedure being learned."),
      raw("StartedAt", "datetime", "When onboarding started."),
      raw("ProficientAt", "datetime", "When the starter was signed off as proficient; blank while learning."),
      raw("UsedCapturedKnowledge", "boolean", "TRUE when the starter learned from formalized repository knowledge."),
      *as_of(),
      calc("IsProficient", "boolean", "TRUE once signed off.", '={{ProficientAt}} <> ""'),
      calc("DaysToProficiency", "integer", "Days from start to proficiency.",
           '=IF(OR({{StartedAt}} = "", {{ProficientAt}} = ""), 0, DATETIME_DIFF({{ProficientAt}}, {{StartedAt}}, "days"))'),
      calc("DaysSinceStart", "integer", "Days from start to the evaluation instant.",
           '=IF({{StartedAt}} = "", 99999, DATETIME_DIFF({{AsOfInstant}}, {{StartedAt}}, "days"))'),
      calc("IsRecentStart", "boolean", "TRUE when the starter began within 180 days of the evaluation instant.",
           "=AND({{DaysSinceStart}} >= 0, {{DaysSinceStart}} <= 180)"),
      lookup("ProcedureRepositoryEntryCount", "integer", "Repository entries for the procedure.",
             idx("Procedures", "RepositoryEntryCount", "Procedure")),
      lookup("ProcedureDepartedOnlyCount", "integer", "Know-how of the procedure held only by people who left.",
             idx("Procedures", "DepartedOnlyKnowHowCount", "Procedure")),
      calc("IsStartingFromNothing", "boolean", "TRUE when a newcomer joins a procedure whose previous holders left and nothing was captured.",
           "=AND({{ProcedureRepositoryEntryCount}} = 0, {{ProcedureDepartedOnlyCount}} > 0)"),
      iri()),
    T("SharingRecognitions",
      "Incentives and credit an organization gives people for sharing process knowledge.", "social-knowledge",
      pk("SharingRecognitionId"),
      calc("Name", "string", "Display name.", '={{RecognitionKind}} & ": " & {{RecognizedAgent}}'),
      rel("RecognizedAgent", "Agents", "Who was recognized."),
      rel("Organization", "Organizations", "The organization giving the recognition."),
      raw("RecognitionKind", "string", "TeachingAward, PeerAward, PromotionCredit or Bonus."),
      raw("ForContribution", "string", "The sharing that was rewarded."),
      raw("AwardedAt", "datetime", "When it was awarded."),
      iri()),
    T("CapabilityDeclines",
      "When an organization's training-and-retention cycle began to decline at one stage (facility investment, engineer "
      "training, upkeep of how-to-make knowledge) and the decline of the stage before it.", "social-knowledge",
      pk("CapabilityDeclineId"),
      calc("Name", "string", "Display name.", '={{Organization}} & ": " & {{Stage}}'),
      rel("Organization", "Organizations", "The organization."),
      raw("Stage", "string", "FacilityInvestment, EngineerTraining or KnowHowUpkeep."),
      raw("DeclineStartedAt", "datetime", "When the decline started."),
      rel("PrecedingStageDecline", "CapabilityDeclines", "The decline of the stage that feeds this one."),
      raw("Evidence", "string", "What shows the decline."),
      lookup("PrecedingStage", "string", "The stage of the preceding decline.",
             idx("CapabilityDeclines", "Stage", "PrecedingStageDecline", "CapabilityDeclineId")),
      lookup("PrecedingDeclineStartedAt", "datetime", "When the preceding decline started.",
             idx("CapabilityDeclines", "DeclineStartedAt", "PrecedingStageDecline", "CapabilityDeclineId")),
      calc("FollowsPrecedingStageDecline", "boolean", "TRUE when training declined after facility investment, or upkeep after training.",
           '=AND({{PrecedingStageDecline}} <> "", {{PrecedingDeclineStartedAt}} < {{DeclineStartedAt}}, '
           'OR(AND({{Stage}} = "EngineerTraining", {{PrecedingStage}} = "FacilityInvestment"), '
           'AND({{Stage}} = "KnowHowUpkeep", {{PrecedingStage}} = "EngineerTraining")))'),
      iri()),
]

FIELDS = {
    "Agents": [
        raw("ServiceStartedAt", "datetime", "When the person began practising in the organization."),
        raw("DepartureAt", "datetime", "The person's planned or actual departure."),
        raw("ProtectedMentoringHoursPerWeek", "number", "Weekly hours protected from production work for mentoring."),
        agg("CommunityCount", "integer", "Communities of practice the agent belongs to.",
            "=COUNTIFS(CommunityMemberships!{{Agent}}, {{AgentId}})"),
        calc("IsBoundarySpanner", "boolean", "TRUE when the agent belongs to two or more communities of practice.", "={{CommunityCount}} >= 2"),
        agg("SnaIdentificationCount", "integer", "Network analyses that identified the agent as a connector.",
            "=COUNTIFS(MethodApplications!{{IdentifiedBroker}}, {{AgentId}})"),
        calc("IsUnidentifiedBoundarySpanner", "boolean", "TRUE when a person connecting communities was never found by a network analysis.",
             "=AND({{IsBoundarySpanner}}, {{SnaIdentificationCount}} = 0)"),
        agg("LocatedKnowHowCount", "integer", "Know-how held by someone else that the agent, as broker, can point seekers to.",
            "=COUNTIFS(KnowledgeBrokerLinks!{{Broker}}, {{AgentId}}, KnowledgeBrokerLinks!{{LocatesOtherHolder}}, TRUE)"),
        agg("RequiredMentoringHoursPerWeek", "number", "Weekly hours the agent's active mentorships need.",
            "=SUMIFS(Mentorships!{{ExpectedWeeklyHours}}, Mentorships!{{MentorAgent}}, {{AgentId}}, Mentorships!{{IsActive}}, TRUE)"),
        calc("LacksTimeToMentor", "boolean", "TRUE when a mentor's protected hours fall short of what their active mentorships need.",
             "=AND({{RequiredMentoringHoursPerWeek}} > 0, {{ProtectedMentoringHoursPerWeek}} < {{RequiredMentoringHoursPerWeek}})"),
        agg("TransfersGivenCount", "integer", "Times the agent passed know-how on.",
            "=COUNTIFS(KnowledgeTransfers!{{FromAgent}}, {{AgentId}})"),
        agg("RecognitionCount", "integer", "Recognitions the agent received for sharing.",
            "=COUNTIFS(SharingRecognitions!{{RecognizedAgent}}, {{AgentId}})"),
        calc("IsUnrewardedSharer", "boolean", "TRUE when someone who repeatedly passes know-how on has never been recognized for it.",
             "=AND({{TransfersGivenCount}} >= 2, {{RecognitionCount}} = 0)"),
    ],
    "CommunitiesOfPractice": [
        rel("OwnVocabulary", "Vocabularies", "The vocabulary the community speaks."),
        raw("Norms", "string", "The community's working norms."),
        raw("Origin", "string", "Grassroots, Mandated or PurchasedPlatform."),
        raw("OpenApprenticeshipPlaces", "integer", "Apprenticeship places on offer."),
        raw("IsColocatedTrade", "boolean", "TRUE when the trade is concentrated in one place."),
        calc("HasOwnVocabularyAndNorms", "boolean", "TRUE when the community has its own vocabulary and stated norms.",
             '=AND({{OwnVocabulary}} <> "", {{Norms}} <> "")'),
        agg("SharingEventCount", "integer", "Know-how transfers inside the community.",
            "=COUNTIFS(KnowledgeTransfers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}})"),
        calc("IsMandatedWithoutSharingNorm", "boolean", "TRUE when a community was mandated or bought and no sharing happens in it.",
             '=AND({{Origin}} <> "", {{Origin}} <> "Grassroots", {{SharingEventCount}} = 0)'),
        agg("InterconnectedKnowHowCount", "integer", "Know-how in the community that builds on related know-how in the same community.",
            "=COUNTIFS(KnowHowCarriers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, KnowHowCarriers!{{BuildsOnSameCommunityKnowHow}}, TRUE)"),
        agg("PhysicalKnowHowCount", "integer", "Know-how about physical work.",
            '=COUNTIFS(KnowHowCarriers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, KnowHowCarriers!{{WorkMedium}}, "Physical")'),
        agg("DigitalKnowHowCount", "integer", "Know-how about digital work.",
            '=COUNTIFS(KnowHowCarriers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, KnowHowCarriers!{{WorkMedium}}, "Digital")'),
        agg("PersonCarriedKnowHowCount", "integer", "Know-how carried by people.",
            '=COUNTIFS(KnowHowCarriers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, KnowHowCarriers!{{CarrierKind}}, "Person")'),
        calc("SpansPhysicalAndDigitalWithHumans", "boolean", "TRUE when the community's know-how spans physical and digital work and people still carry it.",
             "=AND({{PhysicalKnowHowCount}} > 0, {{DigitalKnowHowCount}} > 0, {{PersonCarriedKnowHowCount}} > 0)"),
        agg("ExternalMemberCount", "integer", "Members from other organizations.",
            "=COUNTIFS(CommunityMemberships!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, CommunityMemberships!{{IsExternalMember}}, TRUE)"),
        agg("SpecialistMemberCount", "integer", "Specialists among the members.",
            "=COUNTIFS(CommunityMemberships!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, CommunityMemberships!{{IsSpecialist}}, TRUE)"),
        agg("EmployerMoveCount", "integer", "Know-how carried by people changing employers inside the community.",
            '=COUNTIFS(KnowledgeTransfers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, KnowledgeTransfers!{{Channel}}, "EmployerChange")'),
        calc("IsCrossFirmPracticeCluster", "boolean", "TRUE when members from several firms share practice, people move between firms, and specialists are at hand.",
             "=AND({{ExternalMemberCount}} >= 2, {{EmployerMoveCount}} >= 1, {{SpecialistMemberCount}} >= 1)"),
        agg("RecentApprenticeshipCount", "integer", "Apprenticeships started in the community within three years.",
            "=COUNTIFS(Mentorships!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, Mentorships!{{IsRecentApprenticeship}}, TRUE)"),
        calc("IsCirculationEndingForLackOfApprentices", "boolean", "TRUE when know-how circulates by people moving between firms but offered apprenticeships go unfilled.",
             "=AND({{EmployerMoveCount}} >= 1, {{OpenApprenticeshipPlaces}} > 0, {{RecentApprenticeshipCount}} = 0)"),
        agg("AmbientAbsorptionCount", "integer", "Know-how absorbed by non-practitioners living among the trade.",
            "=COUNTIFS(KnowledgeTransfers!{{CommunityOfPractice}}, {{CommunityOfPracticeId}}, KnowledgeTransfers!{{IsAmbientAbsorptionByNonPractitioner}}, TRUE)"),
        calc("HasAmbientTradeKnowHow", "boolean", "TRUE when a trade concentrated in one place passes know-how even to people who do not practise it.",
             "=AND({{IsColocatedTrade}}, {{AmbientAbsorptionCount}} >= 1)"),
    ],
    "Mentorships": [
        *as_of(),
        raw("MentorshipForm", "string", "Mentoring or Apprenticeship."),
        raw("EmployerWorkerObligation", "string", "The obligations between employer and worker that make the training worth investing in."),
        raw("ExpectedWeeklyHours", "number", "Weekly mentor hours the mentorship needs."),
        calc("IsActive", "boolean", "TRUE when the mentorship runs at the evaluation instant.",
             '=AND({{ValidFrom}} <> "", {{ValidFrom}} <= {{AsOfInstant}}, OR({{ValidTo}} = "", {{ValidTo}} >= {{AsOfInstant}}))'),
        calc("DaysSinceStarted", "integer", "Days since the mentorship began.",
             '=IF({{ValidFrom}} = "", 99999, DATETIME_DIFF({{AsOfInstant}}, {{ValidFrom}}, "days"))'),
        calc("IsRecentApprenticeship", "boolean", "TRUE for an apprenticeship started within three years.",
             '=AND({{MentorshipForm}} = "Apprenticeship", {{DaysSinceStarted}} >= 0, {{DaysSinceStarted}} <= 1095)'),
    ],
    "KnowledgeBrokerLinks": [
        rel("PointsToKnowHow", KHC, "The know-how the broker points the seeker to."),
        lookup("PointedHolder", "string", "Who carries that know-how.", idx(KHC, "HolderAgent", "PointsToKnowHow", "KnowHowCarrierId")),
        calc("LocatesOtherHolder", "boolean", "TRUE when the broker knows where know-how is held by someone other than themselves.",
             '=AND({{PointsToKnowHow}} <> "", {{PointedHolder}} <> "", {{PointedHolder}} <> {{Broker}})'),
        rel("SeekerVocabulary", "Vocabularies", "The vocabulary the seeker's community speaks."),
        raw("SeekerWording", "string", "The seeker's word for the topic."),
        rel("HolderVocabulary", "Vocabularies", "The vocabulary of the community holding the know-how."),
        raw("HolderWording", "string", "The holding community's word for the topic."),
        calc("TranslationBetweenVocabularies", "string", "The broker's translation between the two communities' words; blank when none was needed.",
             '=IF(AND({{SeekerVocabulary}} <> "", {{HolderVocabulary}} <> "", {{SeekerVocabulary}} <> {{HolderVocabulary}}), '
             'CONCAT({{SeekerWording}}, " (", {{SeekerVocabulary}}, ") = ", {{HolderWording}}, " (", {{HolderVocabulary}}, ")"), "")'),
    ],
    "MethodApplications": [
        rel("IdentifiedBroker", "Agents", "A connector between groups that a network analysis identified."),
    ],
    "Organizations": [
        agg("DepartedHolderKnowHowCount", "integer", "Know-how whose carrier has left.",
            "=COUNTIFS(KnowHowCarriers!{{Organization}}, {{OrganizationId}}, KnowHowCarriers!{{IsHeldByDepartedHolder}}, TRUE)"),
        agg("LostDepartedKnowHowCount", "integer", "Know-how that left with its carrier, neither transferred nor captured.",
            "=COUNTIFS(KnowHowCarriers!{{Organization}}, {{OrganizationId}}, KnowHowCarriers!{{IsHeldOnlyByDeparted}}, TRUE)"),
        calc("RetainedDepartedKnowHowPercent", "number", "Share of departed carriers' know-how the organization kept.",
             "=IF({{DepartedHolderKnowHowCount}} = 0, 100, ROUND(100 * ({{DepartedHolderKnowHowCount}} - {{LostDepartedKnowHowCount}}) / {{DepartedHolderKnowHowCount}}, 0))"),
        calc("MemoryLeavesWithStaff", "boolean", "TRUE when some know-how of people who left was not retained.",
             "=AND({{DepartedHolderKnowHowCount}} > 0, {{RetainedDepartedKnowHowPercent}} < 100)"),
        agg("CapturedOwnKnowHowCount", "integer", "The organization's own know-how captured in its repository.",
            "=COUNTIFS(KnowHowCarriers!{{Organization}}, {{OrganizationId}}, KnowHowCarriers!{{IsCaptured}}, TRUE)"),
        agg("DocumentationEntryCount", "integer", "Repository entries for the organization's procedures.",
            "=COUNTIFS(KnowledgeRepositoryEntries!{{OwnerOrganization}}, {{OrganizationId}})"),
        agg("UnallocatedDocumentationCount", "integer", "Entries written outside allotted time.",
            "=COUNTIFS(KnowledgeRepositoryEntries!{{OwnerOrganization}}, {{OrganizationId}}, KnowledgeRepositoryEntries!{{AuthoredOnAllocatedTime}}, FALSE)"),
        agg("TransferGivenCount", "integer", "Transfers given by the organization's people.",
            "=COUNTIFS(KnowledgeTransfers!{{FromOrganization}}, {{OrganizationId}})"),
        agg("UnallocatedTransferCount", "integer", "Transfers given outside allotted time.",
            "=COUNTIFS(KnowledgeTransfers!{{FromOrganization}}, {{OrganizationId}}, KnowledgeTransfers!{{OnAllocatedTime}}, FALSE)"),
        calc("TreatsKnowledgeWorkAsUnvalued", "boolean", "TRUE when most documentation and knowledge transfer happens outside the time the organization allots.",
             "=AND({{DocumentationEntryCount}} + {{TransferGivenCount}} > 0, "
             "2 * ({{UnallocatedDocumentationCount}} + {{UnallocatedTransferCount}}) > {{DocumentationEntryCount}} + {{TransferGivenCount}})"),
        agg("PersonCarriedKnowHowCount", "integer", "Know-how carried by people.",
            '=COUNTIFS(KnowHowCarriers!{{Organization}}, {{OrganizationId}}, KnowHowCarriers!{{CarrierKind}}, "Person")'),
        agg("FacilityCarriedKnowHowCount", "integer", "Know-how carried by plants.",
            '=COUNTIFS(KnowHowCarriers!{{Organization}}, {{OrganizationId}}, KnowHowCarriers!{{CarrierKind}}, "Facility")'),
        agg("SystemCarriedKnowHowCount", "integer", "Know-how carried by systems.",
            '=COUNTIFS(KnowHowCarriers!{{Organization}}, {{OrganizationId}}, KnowHowCarriers!{{CarrierKind}}, "System")'),
        calc("HoldsKnowHowInPeoplePlantsAndSystems", "boolean", "TRUE when the organization's how-to-build knowledge is carried at once by people, plants and systems.",
             "=AND({{PersonCarriedKnowHowCount}} > 0, {{FacilityCarriedKnowHowCount}} > 0, {{SystemCarriedKnowHowCount}} > 0)"),
        agg("StagedDeclineCount", "integer", "Capability declines that followed the decline of the preceding stage.",
            "=COUNTIFS(CapabilityDeclines!{{Organization}}, {{OrganizationId}}, CapabilityDeclines!{{FollowsPrecedingStageDecline}}, TRUE)"),
        calc("ErodedInStages", "boolean", "TRUE when facility investment, then engineer training, then how-to-make upkeep declined in sequence.",
             "={{StagedDeclineCount}} >= 2"),
    ],
    "Procedures": [
        agg("RepositoryEntryCount", "integer", "Repository entries documenting the procedure.",
            "=COUNTIFS(KnowledgeRepositoryEntries!{{Procedure}}, {{ProcedureId}})"),
        agg("StaleEntryCount", "integer", "Repository entries past their review interval.",
            "=COUNTIFS(KnowledgeRepositoryEntries!{{Procedure}}, {{ProcedureId}}, KnowledgeRepositoryEntries!{{IsStale}}, TRUE)"),
        agg("DepartedOnlyKnowHowCount", "integer", "Know-how of the procedure held only by people who left.",
            "=COUNTIFS(KnowHowCarriers!{{Procedure}}, {{ProcedureId}}, KnowHowCarriers!{{IsHeldOnlyByDeparted}}, TRUE)"),
        calc("HasDecayedTransferChannel", "boolean", "TRUE when the procedure's documentation has gone stale or some of its know-how is held only by people who left.",
             "=OR({{StaleEntryCount}} > 0, {{DepartedOnlyKnowHowCount}} > 0)"),
        agg("ExecutionFeedbackEntryCount", "integer", "Repository entries that wrote back what an execution taught.",
            "=COUNTIFS(KnowledgeRepositoryEntries!{{Procedure}}, {{ProcedureId}}, KnowledgeRepositoryEntries!{{IsExecutionFeedback}}, TRUE)"),
        calc("IsExecutedWithoutFeedbackLoop", "boolean", "TRUE when the procedure is executed and nothing from execution was written back into its documentation.",
             "=AND({{ExecutionCount}} > 0, {{ExecutionFeedbackEntryCount}} = 0)"),
        agg("MachineAuthoredEntryCount", "integer", "Repository entries written by AI agents or pipelines.",
            "=COUNTIFS(KnowledgeRepositoryEntries!{{Procedure}}, {{ProcedureId}}, KnowledgeRepositoryEntries!{{IsMachineAuthored}}, TRUE)"),
        agg("PractitionerRelationshipCount", "integer", "Collection relationships with practitioners on the procedure.",
            "=COUNTIFS(SourceRelationships!{{Procedure}}, {{ProcedureId}})"),
        calc("IsCapturedByAutomationAlone", "boolean", "TRUE when the procedure's knowledge was captured by machines and no practitioner was engaged.",
             "=AND({{MachineAuthoredEntryCount}} > 0, {{PractitionerRelationshipCount}} = 0)"),
        agg("UnengagedStakeholderCount", "integer", "Stakeholder departments never engaged in shaping the procedure's knowledge.",
            "=COUNTIFS(DepartmentProcessAccounts!{{Procedure}}, {{ProcedureId}}, DepartmentProcessAccounts!{{IsAwaitingEngagement}}, TRUE)"),
        calc("HasUnengagedStakeholder", "boolean", "TRUE when a stakeholder department of the procedure has not been engaged.",
             "={{UnengagedStakeholderCount}} > 0"),
        agg("RecentStarterCount", "integer", "New starters on the procedure within 180 days.",
            "=COUNTIFS(OnboardingRecords!{{Procedure}}, {{ProcedureId}}, OnboardingRecords!{{IsRecentStart}}, TRUE)"),
        agg("UntransferredVeteranKnowHowCount", "integer", "Veteran know-how never transferred or captured.",
            "=COUNTIFS(KnowHowCarriers!{{Procedure}}, {{ProcedureId}}, KnowHowCarriers!{{IsUntransferredVeteranKnowHow}}, TRUE)"),
        agg("DepartingVeteranKnowHowCount", "integer", "Untransferred veteran know-how whose holder leaves soon.",
            "=COUNTIFS(KnowHowCarriers!{{Procedure}}, {{ProcedureId}}, KnowHowCarriers!{{IsAtRiskOfImminentLoss}}, TRUE)"),
        calc("HasTransferShortfallExposure", "boolean", "TRUE when a wave of three or more new starters meets untransferred veteran know-how, or a departing veteran leaves know-how untransferred.",
             "=OR(AND({{RecentStarterCount}} >= 3, {{UntransferredVeteranKnowHowCount}} > 0), {{DepartingVeteranKnowHowCount}} > 0)"),
        agg("ProficientWithCaptureCount", "integer", "Proficient starters who learned from captured knowledge.",
            "=COUNTIFS(OnboardingRecords!{{Procedure}}, {{ProcedureId}}, OnboardingRecords!{{IsProficient}}, TRUE, OnboardingRecords!{{UsedCapturedKnowledge}}, TRUE)"),
        agg("ProficientWithoutCaptureCount", "integer", "Proficient starters who learned without captured knowledge.",
            "=COUNTIFS(OnboardingRecords!{{Procedure}}, {{ProcedureId}}, OnboardingRecords!{{IsProficient}}, TRUE, OnboardingRecords!{{UsedCapturedKnowledge}}, FALSE)"),
        agg("DaysWithCaptureTotal", "integer", "Total days to proficiency with captured knowledge.",
            "=SUMIFS(OnboardingRecords!{{DaysToProficiency}}, OnboardingRecords!{{Procedure}}, {{ProcedureId}}, OnboardingRecords!{{IsProficient}}, TRUE, OnboardingRecords!{{UsedCapturedKnowledge}}, TRUE)"),
        agg("DaysWithoutCaptureTotal", "integer", "Total days to proficiency without captured knowledge.",
            "=SUMIFS(OnboardingRecords!{{DaysToProficiency}}, OnboardingRecords!{{Procedure}}, {{ProcedureId}}, OnboardingRecords!{{IsProficient}}, TRUE, OnboardingRecords!{{UsedCapturedKnowledge}}, FALSE)"),
        calc("AvgDaysToProficiencyWithCapture", "number", "Average days to proficiency with captured knowledge.",
             "=IF({{ProficientWithCaptureCount}} = 0, 0, ROUND({{DaysWithCaptureTotal}} / {{ProficientWithCaptureCount}}, 1))"),
        calc("AvgDaysToProficiencyWithoutCapture", "number", "Average days to proficiency without captured knowledge.",
             "=IF({{ProficientWithoutCaptureCount}} = 0, 0, ROUND({{DaysWithoutCaptureTotal}} / {{ProficientWithoutCaptureCount}}, 1))"),
        calc("FormalizationDoesNotEaseOnboarding", "boolean", "TRUE when starters who learned from captured knowledge took at least as long as those who did not.",
             "=AND({{ProficientWithCaptureCount}} > 0, {{ProficientWithoutCaptureCount}} > 0, {{AvgDaysToProficiencyWithCapture}} >= {{AvgDaysToProficiencyWithoutCapture}})"),
    ],
}

QUESTIONS = [
    ("aq-pkm2-q06", KE,
     "Who actually holds each piece of our process know-how right now: which person, plant or system, in which form, and is that person still here?",
     "Collection that follows the org chart misses the people, plants and systems where the know-how really sits.",
     F(KHC, "Topic", "Organization", "Procedure", "CommunityOfPractice", "CarrierKind", "HolderAgent", "HolderFacility", "KnowHowKind",
       "IsInWrittenProcedure", "IsTrainedSkill", "EvaluationContext", "AsOfInstant", "HolderIsStillEngaged", "IsHeldInBothForms",
       "IsHeldByCurrentPractitioner")),
    ("aq-pkm2-q07", KE,
     "When a technician asks where some know-how lives, who can point them to the person who holds it, without holding it themselves?",
     "Brokers know where knowledge is held; that meta-knowledge is how seekers find holders across the organization.",
     F("KnowledgeBrokerLinks", "PointsToKnowHow", "PointedHolder", "LocatesOtherHolder") + F("Agents", "LocatedKnowHowCount")),
    ("q12-ke-vocabulary-translation", KE,
     "Which communities speak their own vocabulary under their own norms, and where does a broker translate between their words?",
     "Production says line stop where maintenance says energy isolation; without translation the two talk past each other.",
     F("KnowledgeBrokerLinks", "SeekerVocabulary", "SeekerWording", "HolderVocabulary", "HolderWording", "TranslationBetweenVocabularies")
     + F("CommunitiesOfPractice", "OwnVocabulary", "Norms", "HasOwnVocabularyAndNorms")),
    ("aq-pkm2-q08", STEWARD,
     "Which departments give conflicting accounts of the same process, and what interest shapes each account?",
     "A procedure written from one department's account silently takes a side in a disagreement nobody resolved.",
     F("DepartmentProcessAccounts", "Procedure", "Department", "StakeholderAgent", "AccountSummary", "ShapingInterest",
       "ConflictsWithAccount", "ConflictingDepartment", "IsConflictingAccount")),
    ("q12-steward-disagreement-resolution", STEWARD,
     "Where departments disagree about a process, have we used a resolution practice, or is the conflict still open?",
     "An unresolved disagreement resurfaces at every execution as a judgment call made under pressure.",
     F("DepartmentProcessAccounts", "ResolutionPractice", "ResolvedAt", "IsUnresolvedDisagreement")),
    ("q12-steward-stakeholder-engagement", STEWARD,
     "Which of our procedures have a stakeholder department that was never engaged in shaping the knowledge?",
     "Knowledge shaped without the people it binds is neither complete nor accepted.",
     F("DepartmentProcessAccounts", "EngagedAt", "IsAwaitingEngagement") + F("Procedures", "UnengagedStakeholderCount", "HasUnengagedStakeholder")),
    ("q12-steward-knowledge-decay", STEWARD,
     "Which procedures depend on documentation that has gone stale, or on know-how held only by people who have left?",
     "Documents, training and mentoring decay; unless decay is detected, the register looks complete while it is not.",
     F("KnowledgeRepositoryEntries", "Title", "Procedure", "KnowHow", "AuthorAgent", "CreatedAt", "LastUpdatedAt", "ReviewIntervalDays",
       "EvaluationContext", "AsOfInstant", "DaysSinceUpdated", "IsStale")
     + F(KHC, "IsHeldOnlyByDeparted", "TransferCount", "RepositoryEntryCount")
     + F("Procedures", "RepositoryEntryCount", "StaleEntryCount", "DepartedOnlyKnowHowCount", "HasDecayedTransferChannel")),
    ("q12-ke-social-holders", KE,
     "Is there uncaptured know-how held by someone still here whom no collection effort has approached?",
     "Process knowledge is distributed across a social network; collection that ignores who holds it socially misses it.",
     F(KHC, "SourceRelationshipCount", "IsOverlookedLivingHolder")
     + F("SourceRelationships", "KnowledgeEngineer", "SourceAgent", "Procedure", "SourceStanding", "StartedAt")),
    ("q12-ke-network-analysis", KE,
     "Who connects our communities of practice, and did a network analysis find them, or are some connectors invisible to us?",
     "People who bridge groups know things no single practitioner does; they are found by network analysis, not by title.",
     F("CommunityMemberships", "CommunityOfPractice", "Agent", "IsSpecialist", "JoinedAt", "MemberOrganization", "CommunityOrganization",
       "IsExternalMember")
     + F("Agents", "CommunityCount", "IsBoundarySpanner", "SnaIdentificationCount", "IsUnidentifiedBoundarySpanner")
     + F("MethodApplications", "IdentifiedBroker")),
    ("q12-ke-negotiation", KE,
     "Where a power imbalance shapes what a source will tell me, have I negotiated how their knowledge is collected and used?",
     "Collection is a negotiation; ignoring rank, supervisors in the room or job-security fears gets a sanitized account.",
     F("SourceRelationships", "PowerDynamic", "NegotiatedAgreement", "IsUnnegotiatedPowerGap")),
    ("q12-ke-source-trust", KE,
     "With which sources is trust not established, and am I doing anything to build it?",
     "Sources withhold to protect status or job security; only trust built over time changes what they share.",
     F("SourceRelationships", "TrustLevel", "TrustBuildingPractice", "WithholdingObserved", "WithholdingMotive", "IsExtractiveRelationship")),
    ("q12-authority-direct-engagement", AUTH,
     "Which procedures did we capture only by machine, without engaging a single practitioner?",
     "Automation can summarize manuals; it cannot collect what practitioners know and never wrote down.",
     F("KnowledgeRepositoryEntries", "AuthorAgentKind", "IsMachineAuthored")
     + F("Procedures", "MachineAuthoredEntryCount", "PractitionerRelationshipCount", "IsCapturedByAutomationAlone")),
    ("q12-authority-expertise-credit", AUTH,
     "Which repository entries record someone's expertise without crediting them?",
     "Expertise that goes uncredited stops being offered.",
     F("KnowledgeRepositoryEntries", "SourceExpert", "CreditsSourceExpert", "IsUncreditedExpertKnowHow")),
    ("q12-vp-memory-intact", VP,
     "As people leave, how much of what they knew did we keep, and does the repository outlive its authors?",
     "Organizational memory that walks out with each departure has to be rebuilt by every successor.",
     F("Organizations", "DepartedHolderKnowHowCount", "LostDepartedKnowHowCount", "RetainedDepartedKnowHowPercent",
       "MemoryLeavesWithStaff", "CapturedOwnKnowHowCount")
     + F(KHC, "IsHeldByDepartedHolder", "IsCaptured") + F("KnowledgeRepositoryEntries", "AuthorIsStillEngaged", "OutlivesAuthorTenure")),
    ("q12-ops-feedback-loop", OPS,
     "Which procedures do we execute without anything learned in execution being written back into their documentation?",
     "Without a feedback loop from doing the work, procedural knowledge cannot be captured or kept current.",
     F("KnowledgeRepositoryEntries", "FedFromExecution", "IsExecutionFeedback")
     + F("Procedures", "ExecutionFeedbackEntryCount", "IsExecutedWithoutFeedbackLoop")),
    ("q12-vp-culture-values-documentation", VP,
     "Do we give people time for documentation and knowledge transfer, or does most of it happen on their own time?",
     "A culture that values documentation budgets for it; one that does not gets it only from goodwill until goodwill runs out.",
     F("KnowledgeRepositoryEntries", "WrittenForAudience", "AuthoredOnAllocatedTime", "OwnerOrganization")
     + F("KnowledgeTransfers", "OnAllocatedTime", "FromOrganization")
     + F("Organizations", "DocumentationEntryCount", "UnallocatedDocumentationCount", "TransferGivenCount",
         "UnallocatedTransferCount", "TreatsKnowledgeWorkAsUnvalued")),
    ("aq-pkm3-q06", RELEASE,
     "Has the problem in front of me been solved before?",
     "Solving a problem again from scratch wastes the time the first fix cost and repeats its risks.",
     F("ProblemOccurrences", "ProblemSignature", "Procedure", "OccurredAt", "SolvedByAgent", "SolvedAt", "PriorOccurrence",
       "IsSolved", "PriorWasSolved", "HasBeenSolvedBefore")),
    ("aq-pkm3-q09", RELEASE,
     "Who handled this problem last time, and are they still here to consult?",
     "A specialist who solved it before is the fastest route to a fix, but only while they remain.",
     F("ProblemOccurrences", "SolverIsStillEngaged", "PriorSolver", "PriorSolverIsStillEngaged", "HasConsultableSpecialist")),
    ("q12-release-record-solutions", RELEASE,
     "Which solved problems have no recorded solution, and which came back because the earlier fix was never written down?",
     "A fix that lives only in the solver's head is lost the day the solver moves on.",
     F("ProblemOccurrences", "SolutionEntry", "PriorSolutionEntry", "IsSolvedWithoutRecordedSolution", "IsRelearnedSolvedProblem")),
    ("q12-vp-turnover-regression", VP,
     "Did a fixed bug come back after the team that fixed it turned over?",
     "When a contractor team turns over without recorded fixes, successors start over and old bugs return.",
     F("ProblemOccurrences", "IsTurnoverRegression")),
    ("aq-pkm3-q10", VP,
     "If the current team left tomorrow, which of their know-how is captured for a successor and which would have to be relearned?",
     "Succession is decided by what is written down before people leave, not after.",
     F(KHC, "MustBeRelearnedIfHolderLeaves")),
    ("aq-pkm4-q14", OPS,
     "Which know-how is held only by veterans who have not passed it on, and are any of them about to leave?",
     "A veteran's retirement date is a deadline for transferring what only they know.",
     F(KHC, "HolderServiceStartedAt", "HolderDepartureAt", "DaysUntilHolderDeparture", "DaysServedToAsOf", "DaysServedToDeparture",
       "HolderTenureYears", "IsVeteranHeld", "IsHolderLeavingSoon", "IsUntransferredVeteranKnowHow", "IsAtRiskOfImminentLoss")
     + F("Agents", "ServiceStartedAt", "DepartureAt")),
    ("q12-ops-onboarding-wave", OPS,
     "Where would a wave of new starters, or a departing veteran, leave know-how untransferred?",
     "Shadowing one veteran does not scale to three new technicians at once, nor survive the veteran's retirement.",
     F("OnboardingRecords", "NewStarter", "Procedure", "StartedAt", "EvaluationContext", "AsOfInstant", "DaysSinceStart", "IsRecentStart")
     + F("Procedures", "RecentStarterCount", "UntransferredVeteranKnowHowCount", "DepartingVeteranKnowHowCount", "HasTransferShortfallExposure")),
    ("q12-ops-veteran-unavailable", OPS,
     "Would passing this know-how to the next newcomer still work if the veteran who holds it were unavailable?",
     "Know-how passed only person to person needs the veteran every time.",
     F("KnowledgeTransfers", "KnowHow", "FromAgent", "RecipientAgent", "Channel", "CommunityOfPractice", "OccurredAt",
       "IsTraditionalChannel", "IsSocialNetworkChannel")
     + F(KHC, "TransferStopsWithoutVeteran")),
    ("q12-ops-formalization-onboarding", OPS,
     "Do starters who learn from our captured knowledge actually become proficient faster than those who do not?",
     "Formalized knowledge that does not shorten onboarding is not doing its job; the measurement says so.",
     F("OnboardingRecords", "ProficientAt", "UsedCapturedKnowledge", "IsProficient", "DaysToProficiency")
     + F("Procedures", "ProficientWithCaptureCount", "ProficientWithoutCaptureCount", "DaysWithCaptureTotal", "DaysWithoutCaptureTotal",
         "AvgDaysToProficiencyWithCapture", "AvgDaysToProficiencyWithoutCapture", "FormalizationDoesNotEaseOnboarding")),
    ("q12-vp-incoming-team", VP,
     "Is any newcomer joining a procedure whose previous holders left with nothing captured, so they start from nothing?",
     "An incoming team should inherit the work, not relearn it.",
     F("OnboardingRecords", "ProcedureRepositoryEntryCount", "ProcedureDepartedOnlyCount", "IsStartingFromNothing")),
    ("q12-ops-mentor-time", OPS,
     "Do the veterans mentoring our apprentices have protected time for it?",
     "Mentoring squeezed around production work is the first thing dropped when the line is busy.",
     F("Agents", "ProtectedMentoringHoursPerWeek", "RequiredMentoringHoursPerWeek", "LacksTimeToMentor")
     + F("Mentorships", "EvaluationContext", "AsOfInstant", "MentorshipForm", "EmployerWorkerObligation", "ExpectedWeeklyHours", "IsActive")),
    ("q12-hr-sharing-rewarded", HR,
     "Who repeatedly shares know-how and has never been recognized or rewarded for it?",
     "Sharing that is expected but never recognized becomes unpaid extra work, and stops.",
     F("SharingRecognitions", "RecognizedAgent", "Organization", "RecognitionKind", "ForContribution", "AwardedAt")
     + F("Agents", "TransfersGivenCount", "RecognitionCount", "IsUnrewardedSharer")),
    ("q12-authority-culture-grows", AUTH,
     "Which of our communities were mandated or bought rather than grown, and does anyone actually share in them?",
     "A knowledge culture cannot be purchased with a platform or ordered into being; it grows where sharing is already the norm.",
     F("CommunitiesOfPractice", "Origin", "SharingEventCount", "IsMandatedWithoutSharingNorm")),
    ("q12-authority-not-public-or-ai", AUTH,
     "Are we planning to replace know-how from public references or AI generation that those sources do not contain?",
     "The procedural knowledge an organization runs on is its own; it is not in public references and a model cannot generate it.",
     F(KHC, "IsInPublicReferences", "ReplacementPlan", "IsDelegatedToUnfitSource", "HeldSince", "LostAccumulationYears")),
    ("q12-ke-knowledge-network", KE,
     "Does our know-how build on related know-how in the same community, and does it span physical and digital work with people in the loop?",
     "Know-how about related components compounds when concentrated in one community; scattered, it fragments.",
     F(KHC, "WorkMedium", "BuildsOnKnowHow", "DependencyCommunity", "BuildsOnSameCommunityKnowHow")
     + F("CommunitiesOfPractice", "InterconnectedKnowHowCount", "PhysicalKnowHowCount", "DigitalKnowHowCount",
         "PersonCarriedKnowHowCount", "SpansPhysicalAndDigitalWithHumans")),
    ("q12-ops-practice-cluster", OPS,
     "Is there a cluster where several firms share engineering practice, people move between firms, and specialists are at hand?",
     "Such a cluster is where process knowledge compounds; our suppliers' know-how reaches us through it.",
     F("CommunitiesOfPractice", "ExternalMemberCount", "SpecialistMemberCount", "EmployerMoveCount", "IsCrossFirmPracticeCluster")),
    ("q12-ops-apprentice-intake", OPS,
     "In clusters where know-how circulates as people move between firms, are the apprenticeship places being filled?",
     "Circulation needs new people entering the trade; when apprenticeships go unfilled the circulation ends with the last generation.",
     F("CommunitiesOfPractice", "OpenApprenticeshipPlaces", "RecentApprenticeshipCount", "IsCirculationEndingForLackOfApprentices")
     + F("Mentorships", "DaysSinceStarted", "IsRecentApprenticeship")),
    ("q12-ops-ambient-trade", OPS,
     "Where a trade is concentrated in one place, does its know-how reach people who do not practise it?",
     "Ambient know-how is the deepest sign a trade has settled in a place, and a pool of future recruits.",
     F("CommunitiesOfPractice", "IsColocatedTrade", "AmbientAbsorptionCount", "HasAmbientTradeKnowHow")
     + F("KnowledgeTransfers", "RecipientRoleCount", "IsAmbientAbsorptionByNonPractitioner")),
    ("q12-ops-erosion-stages", OPS,
     "Did our training-and-retention cycle erode stage by stage: facility investment, then engineer training, then how-to-make upkeep?",
     "Each stage feeds the next; seeing the sequence tells us where rebuilding has to start.",
     F("CapabilityDeclines", "Organization", "Stage", "DeclineStartedAt", "PrecedingStageDecline", "Evidence", "PrecedingStage",
       "PrecedingDeclineStartedAt", "FollowsPrecedingStageDecline")
     + F("Organizations", "StagedDeclineCount", "ErodedInStages")),
    ("q12-ops-knowhow-carriers", OPS,
     "Is our how-to-build knowledge carried by people, plants and systems together, or by only some of them?",
     "Manufacturing know-how lives in the workforce, the plants and the systems doing the work; losing any carrier loses part of it.",
     F("Organizations", "PersonCarriedKnowHowCount", "FacilityCarriedKnowHowCount", "SystemCarriedKnowHowCount",
       "HoldsKnowHowInPeoplePlantsAndSystems")),
]


def _agent(aid, **kw):
    return {"AgentId": aid, **kw}


CD = "CapabilityDeclines"
ROWS = {
    "Organizations": _rows(["OrganizationId", "DisplayName", "OrganizationType", "ExternalIdentifier"],
                           ("acme-plant-production", "ACME Plant Production", "Department", "dept-311"),
                           ("acme-customer-support", "ACME Customer Support", "Department", "dept-412"),
                           ("tidewater-dev-services", "Tidewater Development Services (fictional)", "ServiceProvider", "prv-206"),
                           iri_=f"{PROV}Organization"),
    "RoleAssignments": _rows(["RoleAssignmentId", "Role", "Agent", "ValidFrom", "Reason", "Status", "EvaluationContext"],
                             ("ra12-tech-bea", "maintenance-technician", "bea-okonkwo", "2026-07-01T00:00:00-05:00",
                              "New technician, second of three spring and summer starters", "Active", EV),
                             ("ra12-tech-carlos", "maintenance-technician", "carlos-mendez", "2026-05-15T00:00:00-05:00",
                              "New technician, first of three spring and summer starters", "Active", EV),
                             iri_="http://purl.org/spar/pro/RoleInTime"),
    "Agents": [
        _agent("tomas-reyes", ServiceStartedAt="1994-06-01T00:00:00-05:00", DepartureAt="2026-09-30T17:00:00-05:00",
               ProtectedMentoringHoursPerWeek=4),
        _agent("devon-okafor", ProtectedMentoringHoursPerWeek=3),
        _agent("hana-kowalski", ServiceStartedAt="2009-08-03T00:00:00-05:00"),
        _agent("grace-holloway", ServiceStartedAt="2012-02-01T00:00:00-06:00"),
        _agent("dmitri-volkov", ServiceStartedAt="2014-05-01T00:00:00-05:00", DepartureAt="2026-07-03T17:00:00-05:00"),
        _agent("leo-marchetti", ServiceStartedAt="2026-01-01T00:00:00-06:00", DepartureAt="2026-06-30T17:00:00-05:00"),
        _agent("hector-ruiz", ServiceStartedAt="2022-03-01T00:00:00-06:00", DepartureAt="2024-12-31T17:00:00-06:00"),
        _agent("walter-grieg", ServiceStartedAt="1979-09-03T00:00:00-05:00", DepartureAt="2025-03-31T17:00:00-05:00"),
        _agent("ken-watanabe", ServiceStartedAt="2019-01-07T00:00:00-06:00"),
        _agent("lin-zhao", ServiceStartedAt="2004-09-01T00:00:00-05:00"),
        _agent("aisha-bello", ServiceStartedAt="2026-06-01T00:00:00-05:00"),
        _agent("bea-okonkwo", ServiceStartedAt="2026-07-01T00:00:00-05:00"),
        _agent("carlos-mendez", ServiceStartedAt="2026-05-15T00:00:00-05:00"),
        _agent("ravi-menon", ServiceStartedAt="2021-03-01T00:00:00-06:00"),
    ],
    "CommunitiesOfPractice": [
        {"CommunityOfPracticeId": "plant-maintenance-guild", "Label": "Plant Maintenance Guild", "Organization": "acme-plant",
         "StewardRole": "senior-maintenance-technician", "Purpose": "Keeps lockout, press and conveyor know-how moving between shifts.",
         "Cadence": "Weekly tool-crib huddle", "OwnVocabulary": "voc-lockout-activities",
         "Norms": "Every lockout deviation is talked through at the Friday huddle; nobody is blamed for asking.",
         "Origin": "Grassroots", "OpenApprenticeshipPlaces": 2, "IsColocatedTrade": False,
         "SemanticTypeIri": f"{EXT}CommunityOfPractice"},
        {"CommunityOfPracticeId": "release-engineering-guild", "Label": "Release Engineering Guild", "Organization": "acme-engineering",
         "StewardRole": "release-manager", "Purpose": "Shares rollout, rollback and health-verification practice.",
         "Cadence": "Fortnightly release review", "OwnVocabulary": "voc-release-activities",
         "Norms": "Every rollback gets a written note before the next release.", "Origin": "Grassroots",
         "OpenApprenticeshipPlaces": 0, "IsColocatedTrade": False, "SemanticTypeIri": f"{EXT}CommunityOfPractice"},
        {"CommunityOfPracticeId": "km-portal-community", "Label": "Knowledge Sharing Portal Community", "Organization": "acme-corp",
         "StewardRole": "knowledge-authority", "Purpose": "Community space created when the corporate knowledge portal was licensed.",
         "Cadence": "None", "Origin": "PurchasedPlatform", "OpenApprenticeshipPlaces": 0, "IsColocatedTrade": False,
         "SemanticTypeIri": f"{EXT}CommunityOfPractice"},
        {"CommunityOfPracticeId": "riverbend-press-cluster", "Label": "Riverbend Press and Hydraulics Cluster", "Organization": "acme-plant",
         "StewardRole": "plant-operations-manager", "Purpose": "Press, hydraulics and conveyor firms in the Riverbend valley sharing practice.",
         "Cadence": "Monthly supplier evening", "Origin": "Grassroots", "OpenApprenticeshipPlaces": 0, "IsColocatedTrade": True,
         "SemanticTypeIri": f"{EXT}CommunityOfPractice"},
        {"CommunityOfPracticeId": "eastvale-packaging-cluster", "Label": "Eastvale Packaging Machinery Cluster", "Organization": None,
         "StewardRole": None, "Purpose": "Packaging machinery builders whose technicians move between firms.",
         "Cadence": "Quarterly trade meeting", "Origin": "Grassroots", "OpenApprenticeshipPlaces": 4, "IsColocatedTrade": False,
         "SemanticTypeIri": f"{EXT}CommunityOfPractice"},
    ],
    "CommunityMemberships": _rows(["CommunityMembershipId", "CommunityOfPractice", "Agent", "IsSpecialist", "JoinedAt"],
                                  ("cm12-tomas-plant", "plant-maintenance-guild", "tomas-reyes", True, "2008-01-10T00:00:00-06:00"),
                                  ("cm12-lin-plant", "plant-maintenance-guild", "lin-zhao", False, "2021-05-01T00:00:00-05:00"),
                                  ("cm12-lin-portal", "km-portal-community", "lin-zhao", False, "2025-02-01T00:00:00-06:00"),
                                  ("cm12-ken-plant", "plant-maintenance-guild", "ken-watanabe", False, "2019-02-01T00:00:00-06:00"),
                                  ("cm12-ken-riverbend", "riverbend-press-cluster", "ken-watanabe", False, "2022-09-01T00:00:00-05:00"),
                                  ("cm12-petra-riverbend", "riverbend-press-cluster", "petra-lindqvist", True, "2016-03-01T00:00:00-06:00"),
                                  ("cm12-joao-riverbend", "riverbend-press-cluster", "joao-ferreira", False, "2019-06-01T00:00:00-05:00"),
                                  ("cm12-joao-eastvale", "eastvale-packaging-cluster", "joao-ferreira", False, "2011-04-01T00:00:00-05:00"),
                                  ("cm12-grace-release", "release-engineering-guild", "grace-holloway", True, "2016-01-01T00:00:00-06:00"),
                                  iri_=f"{EXT}CommunityMembership"),
    "Mentorships": [
        {"MentorshipId": "mentor-close-2026", "EvaluationContext": EV, "MentorshipForm": "Mentoring", "ExpectedWeeklyHours": 2},
        {"MentorshipId": "ms12-tomas-aisha", "CommunityOfPractice": "plant-maintenance-guild", "MentorAgent": "tomas-reyes",
         "LearnerAgent": "aisha-bello", "ValidFrom": "2026-06-01T00:00:00-05:00", "ValidTo": "2029-05-31T17:00:00-05:00",
         "LearningObjective": "Lockout, accumulator bleed-down and press setup by watching, supervised practice and guided correction.",
         "EvaluationContext": EV, "MentorshipForm": "Apprenticeship",
         "EmployerWorkerObligation": "Three-year indenture: acme-plant pays certification and guarantees a technician post; the apprentice commits to two years after.",
         "ExpectedWeeklyHours": 6, "SemanticTypeIri": f"{EXT}Mentorship"},
        {"MentorshipId": "ms12-tomas-bea", "CommunityOfPractice": "plant-maintenance-guild", "MentorAgent": "tomas-reyes",
         "LearnerAgent": "bea-okonkwo", "ValidFrom": "2026-07-01T00:00:00-05:00", "ValidTo": "2029-06-30T17:00:00-05:00",
         "LearningObjective": "Lockout and conveyor maintenance under supervision.", "EvaluationContext": EV,
         "MentorshipForm": "Apprenticeship",
         "EmployerWorkerObligation": "Three-year indenture with a guaranteed technician post.", "ExpectedWeeklyHours": 6,
         "SemanticTypeIri": f"{EXT}Mentorship"},
        {"MentorshipId": "ms12-walter-ken", "CommunityOfPractice": "plant-maintenance-guild", "MentorAgent": "walter-grieg",
         "LearnerAgent": "ken-watanabe", "ValidFrom": "2019-01-07T00:00:00-06:00", "ValidTo": "2022-01-07T17:00:00-06:00",
         "LearningObjective": "Press die setting and shim selection.", "EvidenceOfCompletion": "Signed off as press setter 2022-01-07.",
         "EvaluationContext": EV, "MentorshipForm": "Apprenticeship",
         "EmployerWorkerObligation": "Press setter apprenticeship with guaranteed post and a retention bonus at completion.",
         "ExpectedWeeklyHours": 5, "SemanticTypeIri": f"{EXT}Mentorship"},
        {"MentorshipId": "ms12-eastvale-2014", "CommunityOfPractice": "eastvale-packaging-cluster", "MentorAgent": "joao-ferreira",
         "LearnerAgent": "petra-lindqvist", "ValidFrom": "2014-09-01T00:00:00-05:00", "ValidTo": "2017-08-31T17:00:00-05:00",
         "LearningObjective": "Cartoner drive tuning.", "EvidenceOfCompletion": "Journeyman certificate 2017.",
         "EvaluationContext": EV, "MentorshipForm": "Apprenticeship",
         "EmployerWorkerObligation": "Cluster apprenticeship shared between member firms.", "ExpectedWeeklyHours": 5,
         "SemanticTypeIri": f"{EXT}Mentorship"},
    ],
    KHC: _rows(["KnowHowCarrierId", "Topic", "Organization", "Procedure", "CommunityOfPractice", "CarrierKind", "HolderAgent",
                "HolderFacility", "KnowHowKind", "IsInWrittenProcedure", "IsTrainedSkill", "WorkMedium", "HeldSince",
                "BuildsOnKnowHow", "IsInPublicReferences", "ReplacementPlan", "EvaluationContext"],
               ("khc12-tomas-bleed", "Hearing when the Press 7 accumulator has truly bled down", "acme-plant", "lockout-tagout",
                "plant-maintenance-guild", "Person", "tomas-reyes", None, "Diagnosis", False, True, "Physical",
                "1998-03-01T00:00:00-06:00", "khc12-plant-isolation", False, None, EV),
               ("khc12-plant-isolation", "Colour-coded isolation valves and tags built into the hall", "acme-plant", "lockout-tagout",
                "plant-maintenance-guild", "Facility", None, "plant-north", "Refinement", True, False, "Physical",
                "2008-06-01T00:00:00-05:00", None, False, None, EV),
               ("khc12-plc-interlock", "Restart sequence encoded in the Plant North PLC interlock logic", "acme-plant", "lockout-tagout",
                "plant-maintenance-guild", "System", None, None, "Refinement", True, False, "Digital",
                "2017-10-01T00:00:00-05:00", None, False, None, EV),
               ("khc12-walter-die", "Which die shims crack under the 400-tonne press", "acme-plant", "press-changeover",
                "plant-maintenance-guild", "Person", "walter-grieg", None, "WhatFails", True, True, "Physical",
                "1985-01-01T00:00:00-06:00", None, False, "Apprenticeship", EV),
               ("khc12-tomas-setup", "Improvised press setup when the changeover cart is out of service", "acme-plant", "press-changeover",
                "plant-maintenance-guild", "Person", "tomas-reyes", None, "Improvisation", False, True, "Physical",
                "2003-01-01T00:00:00-06:00", "khc12-walter-die", False, None, EV),
               ("khc12-ken-belt", "Diagnosing belt drift on the Plant South conveyor", "acme-plant", "conveyor-maintenance",
                "plant-maintenance-guild", "Person", "ken-watanabe", None, "Diagnosis", False, True, "Physical",
                "2020-04-01T00:00:00-05:00", None, False, "AiGeneration", EV),
               ("khc12-lin-forklift", "Forklift daily inspection checklist from the manufacturer", "acme-plant", "forklift-daily-inspection",
                None, "Person", "lin-zhao", None, "Refinement", True, False, "Physical",
                "2021-04-01T00:00:00-05:00", None, True, "PublicReference", EV),
               ("khc12-leo-health", "Which dashboard signals mean a rollout is degrading", "acme-engineering", "production-deployment",
                "release-engineering-guild", "Person", "leo-marchetti", None, "Diagnosis", False, True, "Digital",
                "2026-01-15T00:00:00-06:00", None, False, None, EV),
               ("khc12-hector-build", "Building release candidates by hand when CI is down", "acme-engineering", "production-deployment",
                "release-engineering-guild", "Person", "hector-ruiz", None, "Refinement", True, True, "Digital",
                "2022-03-01T00:00:00-06:00", None, False, None, EV),
               ("khc12-grace-gonogo", "Go/no-go judgment when the risk classifier and canary disagree", "acme-engineering",
                "production-deployment", "release-engineering-guild", "Person", "grace-holloway", None, "WhatFails", True, True,
                "Digital", "2016-01-01T00:00:00-06:00", None, False, None, EV),
               ("khc12-dmitri-triage", "Customer incident triage heuristics", "acme-engineering", "customer-incident-response",
                None, "Person", "dmitri-volkov", None, "Diagnosis", False, True, "Digital",
                "2015-01-01T00:00:00-06:00", None, False, None, EV),
               ("khc12-joao-servo", "Servo cam timing for high-speed press feeders", "baxter-hydraulics", None,
                "riverbend-press-cluster", "Person", "joao-ferreira", None, "Improvisation", False, True, "Physical",
                "2011-04-01T00:00:00-05:00", None, False, None, EV),
               ("khc12-petra-cartoner", "Cartoner drive tuning", "northfield-conveyor", None,
                "eastvale-packaging-cluster", "Person", "petra-lindqvist", None, "Refinement", False, True, "Physical",
                "2017-09-01T00:00:00-05:00", None, False, None, EV),
               iri_=f"{EXT}KnowHowCarrier"),
    "KnowledgeTransfers": _rows(["KnowledgeTransferId", "KnowHow", "FromAgent", "RecipientAgent", "Channel", "CommunityOfPractice",
                                 "OccurredAt", "OnAllocatedTime"],
                                ("kt12-walter-ken", "khc12-walter-die", "walter-grieg", "ken-watanabe", "Mentoring",
                                 "plant-maintenance-guild", "2020-06-01T00:00:00-05:00", True),
                                ("kt12-tomas-aisha", "khc12-tomas-setup", "tomas-reyes", "aisha-bello", "Mentoring",
                                 "plant-maintenance-guild", "2026-07-08T00:00:00-05:00", True),
                                ("kt12-lin-aisha-training", "khc12-plant-isolation", "lin-zhao", "aisha-bello", "TrainingProgram",
                                 "plant-maintenance-guild", "2026-06-03T00:00:00-05:00", True),
                                ("kt12-grace-leo-doc", "khc12-grace-gonogo", "grace-holloway", "leo-marchetti", "Document",
                                 "release-engineering-guild", "2026-01-15T00:00:00-06:00", False),
                                ("kt12-grace-ravi-pairing", "khc12-grace-gonogo", "grace-holloway", "ravi-menon", "Collaboration",
                                 "release-engineering-guild", "2026-03-10T00:00:00-06:00", False),
                                ("kt12-joao-move", "khc12-joao-servo", "joao-ferreira", None, "EmployerChange",
                                 "riverbend-press-cluster", "2019-06-01T00:00:00-05:00", True),
                                ("kt12-joao-petra-iteration", "khc12-joao-servo", "joao-ferreira", "petra-lindqvist",
                                 "DesignProductionIteration", "riverbend-press-cluster", "2026-02-10T00:00:00-06:00", True),
                                ("kt12-joao-nina-ambient", "khc12-joao-servo", "joao-ferreira", "nina-sorensen", "AmbientExposure",
                                 "riverbend-press-cluster", "2025-08-01T00:00:00-05:00", True),
                                ("kt12-petra-move", "khc12-petra-cartoner", "petra-lindqvist", None, "EmployerChange",
                                 "eastvale-packaging-cluster", "2023-04-01T00:00:00-05:00", True),
                                iri_=f"{EXT}KnowledgeTransfer"),
    "KnowledgeRepositoryEntries": _rows(
        ["KnowledgeRepositoryEntryId", "Title", "Procedure", "KnowHow", "AuthorAgent", "SourceExpert", "CreditsSourceExpert",
         "WrittenForAudience", "AuthoredOnAllocatedTime", "FedFromExecution", "CreatedAt", "LastUpdatedAt", "ReviewIntervalDays",
         "EvaluationContext"],
        ("kre12-loto-isolation-map", "Plant North isolation map annotations", "lockout-tagout", "khc12-plant-isolation", "lin-zhao",
         "tomas-reyes", True, "LaterColleagues", True, "exec-loto-0714-north-day", "2024-03-01T00:00:00-06:00",
         "2026-07-15T00:00:00-05:00", 365, EV),
        ("kre12-press7-bleed-fix", "Press 7 accumulator bleed stall: reseat the bleed valve before retrying", "lockout-tagout", None,
         "tomas-reyes", "tomas-reyes", True, "LaterColleagues", True, None, "2026-02-12T00:00:00-06:00",
         "2026-02-12T00:00:00-06:00", 365, EV),
        ("kre12-loto-quick-card", "Lockout quick reference card", "lockout-tagout", None, "lin-zhao", "ken-watanabe", False,
         "ComplianceAudit", True, None, "2026-04-01T00:00:00-05:00", "2026-04-01T00:00:00-05:00", 365, EV),
        ("kre12-build-runbook", "Hand-building a release candidate when CI is down", "production-deployment", "khc12-hector-build",
         "hector-ruiz", "hector-ruiz", True, "LaterColleagues", False, None, "2023-05-01T00:00:00-05:00",
         "2026-05-20T00:00:00-05:00", 365, EV),
        ("kre12-release-gonogo-notes", "Release go/no-go notes", "production-deployment", "khc12-grace-gonogo", "grace-holloway",
         "grace-holloway", True, "LaterColleagues", False, "exec-deploy-2026-01-05", "2025-01-10T00:00:00-06:00",
         "2026-01-06T00:00:00-06:00", 180, EV),
        ("kre12-cache-purge-fix", "Purge the CDN cache after a deploy that changes asset hashes", "production-deployment", None,
         "grace-holloway", "grace-holloway", True, "LaterColleagues", True, None, "2026-05-12T00:00:00-05:00",
         "2026-05-12T00:00:00-05:00", 365, EV),
        ("kre12-conveyor-ai-summary", "Conveyor maintenance summary generated from the vendor manuals", "conveyor-maintenance", None,
         "plant-copilot-1-2", None, False, "ComplianceAudit", True, None, "2026-07-02T00:00:00-05:00",
         "2026-07-02T00:00:00-05:00", 365, EV),
        ("kre12-close-fx-retro", "Q2 close retrospective: FX rate timing", "quarter-end-close", None, "devon-okafor", "devon-okafor",
         True, "LaterColleagues", True, "exec-close-2026-q2", "2026-07-03T00:00:00-05:00", "2026-07-03T00:00:00-05:00", 180, EV),
        iri_=f"{EXT}KnowledgeRepositoryEntry"),
    "SourceRelationships": _rows(
        ["SourceRelationshipId", "KnowledgeEngineer", "SourceAgent", "Procedure", "SourceStanding", "PowerDynamic",
         "NegotiatedAgreement", "TrustLevel", "TrustBuildingPractice", "WithholdingObserved", "WithholdingMotive", "StartedAt"],
        ("sr12-sam-tomas", "sam-adeyemi", "tomas-reyes", "lockout-tagout", "SeniorVeteran", "SourceOutranksEngineer",
         "Tomas reviews every draft before it circulates and is named as author of the bleed-down section.", "Established",
         "Drafts returned for correction within a day; credit by name.", False, None, "2025-11-01T00:00:00-05:00"),
        ("sr12-sam-ken", "sam-adeyemi", "ken-watanabe", "press-changeover", "Peer", "JobSecurityThreat", None, "Low",
         "Shares every transcript back for correction.", True,
         "Job security: fears that writing down his die-shim tricks makes him replaceable once the press line is automated.",
         "2026-05-10T00:00:00-05:00"),
        ("sr12-ines-grace", "ines-moreau", "grace-holloway", "production-deployment", "Manager", "SupervisorPresent",
         "Sessions held without the VP present; Grace approves any quote before it is used.", "Building", None, True,
         "Status: her go/no-go judgment is what makes her the release authority.", "2026-06-01T00:00:00-05:00"),
        ("sr12-sam-lin", "sam-adeyemi", "lin-zhao", "lockout-tagout", "Peer", "Balanced", None, "Established",
         "Joint walk-downs of every isolation point.", False, None, "2025-12-01T00:00:00-06:00"),
        iri_=f"{EXT}SourceRelationship"),
    "DepartmentProcessAccounts": _rows(
        ["DepartmentProcessAccountId", "Procedure", "Department", "StakeholderAgent", "EngagedAt", "AccountSummary",
         "ShapingInterest", "ConflictsWithAccount", "ResolutionPractice", "ResolvedAt"],
        ("dpa12-loto-maintenance", "lockout-tagout", "acme-plant", "tomas-reyes", "2026-03-02T09:00:00-06:00",
         "The accumulator bleed takes twenty minutes before zero-energy verification.", "Technician safety; no pressure to restart",
         "dpa12-loto-production", "Joint timed walk-down chaired by the plant safety officer", "2026-04-10T15:00:00-05:00"),
        ("dpa12-loto-production", "lockout-tagout", "acme-plant-production", "hana-kowalski", "2026-03-03T09:00:00-06:00",
         "The bleed is a five-minute step.", "Line uptime targets", "dpa12-loto-maintenance",
         "Joint timed walk-down chaired by the plant safety officer", "2026-04-10T15:00:00-05:00"),
        ("dpa12-deploy-engineering", "production-deployment", "acme-engineering", "grace-holloway", "2026-05-05T10:00:00-05:00",
         "Rollback is automatic and completes within ten minutes.", "Release velocity", "dpa12-deploy-support", None, None),
        ("dpa12-deploy-support", "production-deployment", "acme-customer-support", "leah-brooks", "2026-05-07T10:00:00-05:00",
         "Customers see errors for about an hour before a rollback is triggered.", "Customer-facing incident load",
         "dpa12-deploy-engineering", None, None),
        ("dpa12-deploy-compliance", "production-deployment", "acme-corp", "marcus-webb", None, None,
         "Change-control audit evidence", None, None, None),
        iri_=f"{EXT}DepartmentProcessAccount"),
    "ProblemOccurrences": _rows(
        ["ProblemOccurrenceId", "ProblemSignature", "Procedure", "OccurredAt", "SolvedByAgent", "SolvedAt", "SolutionEntry",
         "PriorOccurrence"],
        ("po12-cache-2025-03", "Stale CDN assets after a deploy", "production-deployment", "2025-03-18T10:00:00-05:00",
         "anil-kapoor", "2025-03-19T16:00:00-05:00", None, None),
        ("po12-cache-2026-05", "Stale CDN assets after a deploy", "production-deployment", "2026-05-11T10:00:00-05:00",
         "grace-holloway", "2026-05-12T12:00:00-05:00", "kre12-cache-purge-fix", "po12-cache-2025-03"),
        ("po12-cache-2026-07", "Stale CDN assets after a deploy", "production-deployment", "2026-07-14T17:00:00-05:00",
         None, None, None, "po12-cache-2026-05"),
        ("po12-bleed-2026-02", "Press 7 accumulator bleed stalls", "lockout-tagout", "2026-02-11T08:00:00-06:00",
         "tomas-reyes", "2026-02-11T11:00:00-06:00", "kre12-press7-bleed-fix", None),
        ("po12-bleed-2026-06", "Press 7 accumulator bleed stalls", "lockout-tagout", "2026-06-24T08:00:00-05:00",
         "aisha-bello", "2026-06-24T09:30:00-05:00", "kre12-press7-bleed-fix", "po12-bleed-2026-02"),
        iri_=f"{EXT}ProblemOccurrence"),
    "OnboardingRecords": _rows(
        ["OnboardingRecordId", "NewStarter", "Procedure", "StartedAt", "ProficientAt", "UsedCapturedKnowledge", "EvaluationContext"],
        ("ob12-aisha-loto", "aisha-bello", "lockout-tagout", "2026-06-01T00:00:00-05:00", "2026-06-22T00:00:00-05:00", True, EV),
        ("ob12-carlos-loto", "carlos-mendez", "lockout-tagout", "2026-05-15T00:00:00-05:00", None, True, EV),
        ("ob12-bea-loto", "bea-okonkwo", "lockout-tagout", "2026-07-01T00:00:00-05:00", None, False, EV),
        ("ob12-ken-loto", "ken-watanabe", "lockout-tagout", "2019-01-07T00:00:00-06:00", "2019-03-18T00:00:00-05:00", False, EV),
        ("ob12-ravi-deploy", "ravi-menon", "production-deployment", "2021-03-01T00:00:00-06:00", "2021-04-10T00:00:00-05:00", False, EV),
        ("ob12-leo-deploy", "leo-marchetti", "production-deployment", "2026-01-01T00:00:00-06:00", "2026-02-25T00:00:00-06:00", True, EV),
        ("ob12-leah-incident", "leah-brooks", "customer-incident-response", "2025-09-01T00:00:00-05:00",
         "2025-12-15T00:00:00-06:00", False, EV),
        iri_=f"{EXT}OnboardingRecord"),
    "SharingRecognitions": _rows(
        ["SharingRecognitionId", "RecognizedAgent", "Organization", "RecognitionKind", "ForContribution", "AwardedAt"],
        ("rec12-tomas-teaching", "tomas-reyes", "acme-plant", "TeachingAward",
         "Trained the plant's lockout apprentices and wrote the Press 7 bleed fix.", "2026-03-15T00:00:00-05:00"),
        ("rec12-joao-cluster", "joao-ferreira", "baxter-hydraulics", "PeerAward",
         "Shared servo timing practice across the Riverbend cluster.", "2026-02-20T00:00:00-06:00"),
        iri_=f"{EXT}SharingRecognition"),
    CD: _rows(["CapabilityDeclineId", "Organization", "Stage", "DeclineStartedAt", "PrecedingStageDecline", "Evidence"],
              ("cd12-plant-facility", "acme-plant", "FacilityInvestment", "2011-01-01T00:00:00-06:00", None,
               "Plant South tooling capital budget frozen."),
              ("cd12-plant-training", "acme-plant", "EngineerTraining", "2015-01-01T00:00:00-06:00", "cd12-plant-facility",
               "Process engineer rotation program cut."),
              ("cd12-plant-upkeep", "acme-plant", "KnowHowUpkeep", "2020-01-01T00:00:00-06:00", "cd12-plant-training",
               "Press line how-to-make binders no longer revised."),
              ("cd12-eng-training", "acme-engineering", "EngineerTraining", "2024-01-01T00:00:00-06:00", None,
               "Release engineering apprenticeship paused."),
              iri_=f"{EXT}CapabilityDecline"),
    "KnowledgeBrokerLinks": [
        {"KnowledgeBrokerLinkId": "kbl12-aisha-lin-bleed", "Seeker": "aisha-bello", "Broker": "lin-zhao", "Topic": "vt-hydraulic-bleed",
         "Frequency": "Often", "LastConsultedAt": "2026-07-10T09:00:00-05:00", "EvaluationContext": EV,
         "PointsToKnowHow": "khc12-tomas-bleed", "SemanticTypeIri": f"{EXT}KnowledgeBrokerLink"},
        {"KnowledgeBrokerLinkId": "kbl12-hana-lin-isolation", "Seeker": "hana-kowalski", "Broker": "lin-zhao", "Topic": "vt-isolation",
         "Frequency": "Sometimes", "LastConsultedAt": "2026-06-12T09:00:00-05:00", "EvaluationContext": EV,
         "PointsToKnowHow": "khc12-plant-isolation", "SeekerVocabulary": "voc-plant-quality", "SeekerWording": "line stop",
         "HolderVocabulary": "voc-lockout-activities", "HolderWording": "energy isolation", "SemanticTypeIri": f"{EXT}KnowledgeBrokerLink"},
        {"KnowledgeBrokerLinkId": "kbl12-leah-grace-rollback", "Seeker": "leah-brooks", "Broker": "grace-holloway", "Topic": "vt-rollback",
         "Frequency": "Often", "LastConsultedAt": "2026-07-01T09:00:00-05:00", "EvaluationContext": EV,
         "PointsToKnowHow": "khc12-grace-gonogo", "SeekerVocabulary": "voc-support-glossary", "SeekerWording": "outage",
         "HolderVocabulary": "voc-release-activities", "HolderWording": "rollback", "SemanticTypeIri": f"{EXT}KnowledgeBrokerLink"},
    ],
    "MethodApplications": [
        {"MethodApplicationId": "ma12-sna-plant", "KnowledgeMethod": "SocialNetworkAnalysis",
         "AppliedTo": "Who-asks-whom survey of Plant North technicians and supervisors, mapped as a network to find connectors between the maintenance guild and the portal community",
         "AppliedAt": "2026-05-20T00:00:00-05:00", "AppliedByAgent": "sam-adeyemi", "IdentifiedBroker": "lin-zhao",
         "SemanticTypeIri": f"{EXT}MethodApplication"},
    ],
}

MAPPINGS = [
    ("map12-kre-author", "KnowledgeRepositoryEntries.AuthorAgent", "property", f"{PROV}wasAttributedTo", "aligned", "prov-o",
     "Added by loop-12."),
    ("map12-kt-from", "KnowledgeTransfers.FromAgent", "property", f"{PROV}wasAssociatedWith", "aligned", "prov-o", "Added by loop-12."),
]
