"""Loop 11 (theme F): sourcing, the knowledge audit, the AI system registry and ground-truth routing.

Part III of the PKM series argues that process knowledge lives where the work is executed, so an
organization that sends execution out sends the knowledge with it, and it prescribes an audit of
knowledge held against knowledge needed, named gaps and dependencies, and provider relationships
that move knowledge back. The ontology governance essay treats the graph as the registry of AI
systems (versions, deployments, evaluations, attributed artifacts, the blast radius of an upgrade)
and as operational ground truth: once a pipeline routes approval notices from role assignments, a
stale assignment is an outage, so someone must own the update and finish it within a service level.

Every predicate here answers a question a sourcing manager, knowledge engineer, knowledge authority,
steward, release manager or VP of engineering asks. The deployment scenario of loop 6 carries the
ground-truth story: a hotfix release manager left before the 2026-07-14 hotfix and the approval
notice went to him; the SRE who took post-deployment health verification back from an AI health
checker left without a successor and the verification notice went to nobody.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from rulebook_edit import agg, calc, idx, lookup, raw, rel  # noqa: E402

EXT = "urn:effortless:pko-extension#"
PROV = "http://www.w3.org/ns/prov#"
DCT = "http://purl.org/dc/terms/"
EV = "eval-current"

LOOP = {
    "WitnessLoopId": "loop-11",
    "LoopNumber": 11,
    "Title": "Loop 11: sourcing, knowledge audit, the AI system registry and ground-truth routing",
    "Premise": "Loop 6 gave the model a governed production deployment with an AI risk classifier, role "
               "assignments with validity periods, and the artifacts each step produces and consumes. What "
               "the model still could not say was where the organization's process knowledge actually lives "
               "once execution is sent to providers, what an audit of held against needed knowledge finds, "
               "whether provider relationships move knowledge back, which AI systems the registry knows that "
               "the graph does not, what an agent upgrade touches, and whether the assignments that a "
               "deployment pipeline routes approval notices from were updated before the run that needed "
               "them. This loop adds each of those, with seeded breaches on the deployment scenario.",
}

SOURCING, KE, AUTH, STEWARD, RELEASE, VP = ("sourcing-manager", "knowledge-engineer", "knowledge-authority",
                                            "process-steward", "release-manager", "vp-engineering")

ROLES = [
    {"RoleId": SOURCING, "Label": "Strategic Sourcing Manager", "Organization": "acme-home-brands",
     "CurrentAgent": "claire-dubois", "Responsibility": "Decides which functions are retained and which are sent to providers, and negotiates provider terms.",
     "CurrentAssignment": "ra-sourcing-claire", "SemanticTypeIri": "http://purl.org/spar/pro/Role"},
    {"RoleId": "build-release-engineer", "Label": "Build and Release Engineer", "Organization": "acme-engineering",
     "CurrentAgent": None, "Responsibility": "Built and rolled out release candidates by hand before the CI pipeline took the work.",
     "CurrentAssignment": None, "SemanticTypeIri": "http://purl.org/spar/pro/Role"},
]

AGENTS = [
    {"AgentId": "claire-dubois", "DisplayName": "Claire Dubois", "AgentKind": "Human", "Organization": "acme-home-brands",
     "ContactAddress": "claire.dubois@example.com", "VersionOrEmploymentKey": "sourcing-2023", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "dmitri-volkov", "DisplayName": "Dmitri Volkov", "AgentKind": "Human", "Organization": "acme-engineering",
     "ContactAddress": "dmitri.volkov@example.com", "VersionOrEmploymentKey": "release-manager-2025", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "leo-marchetti", "DisplayName": "Leo Marchetti", "AgentKind": "Human", "Organization": "acme-engineering",
     "ContactAddress": "leo.marchetti@example.com", "VersionOrEmploymentKey": "sre-2026", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "kwame-asante", "DisplayName": "Kwame Asante", "AgentKind": "Human", "Organization": "acme-engineering",
     "ContactAddress": "kwame.asante@example.com", "VersionOrEmploymentKey": "rollout-operator-2025", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "hector-ruiz", "DisplayName": "Hector Ruiz", "AgentKind": "Human", "Organization": "acme-engineering",
     "ContactAddress": "hector.ruiz@example.com", "VersionOrEmploymentKey": "build-engineer-2022", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "ines-moreau", "DisplayName": "Ines Moreau", "AgentKind": "Human", "Organization": "acme-engineering",
     "ContactAddress": "ines.moreau@example.com", "VersionOrEmploymentKey": "ontologist-2026", "SemanticTypeIri": "prov:Agent"},
    {"AgentId": "health-check-ai-1-2-0", "DisplayName": "Health Check AI 1.2.0", "AgentKind": "AIAgent",
     "Organization": "acme-engineering", "ContactAddress": "health-check@example.com", "VersionOrEmploymentKey": "1.2.0",
     "SemanticTypeIri": "prov:SoftwareAgent"},
]


def T(name, desc, area, *fields):
    return (name, desc, area, list(fields))


def pk(name):
    return raw(name, "string", "Stored identifier.", nullable=False)


def iri():
    return raw("SemanticTypeIri", "string", "Semantic type IRI.")


def as_of():
    return [rel("EvaluationContext", "EvaluationContexts", "The instant the row is judged against."),
            lookup("AsOfInstant", "datetime", "The modeled evaluation instant.",
                   idx("EvaluationContexts", "AsOfInstant", "EvaluationContext"))]


TABLES = [
    # ------------------------------------------------------------------ sourcing and the knowledge audit
    T("SourcingFunctions",
      "Business functions an organization classifies as retained core or sends out for execution, with who executes "
      "them and who holds the knowledge of what is built and of how it is built.", "sourcing",
      pk("SourcingFunctionId"),
      calc("Name", "string", "Display name.", '={{ClientOrganization}} & ": " & {{Label}}'),
      raw("Label", "string", "The function."),
      rel("ClientOrganization", "Organizations", "The organization whose function this is."),
      rel("Procedure", "Procedures", "The modeled procedure that carries the function, when there is one."),
      raw("SourcingClass", "string", "RetainedCore, or SentOutExecution for a function classified as execution to be sent out."),
      raw("WorkNature", "string", "Transactional (routine) or ExpertiseHeavy (analytical, design or engineering judgment)."),
      raw("IsStrategicallyVital", "boolean", "TRUE when the organization cannot deliver its strategy without the function."),
      raw("DeliversOwnProduct", "boolean", "TRUE when the function is part of delivering the organization's own products."),
      rel("ExecutingOrganization", "Organizations", "The organization that actually performs the work."),
      rel("SpecificationHolder", "Organizations", "The party that holds what is to be built or delivered."),
      rel("MethodHolder", "Organizations", "The party that holds how it is built or performed."),
      raw("SourcedSince", "datetime", "When the current execution arrangement began."),
      raw("SourcingRationale", "string", "Why the function was placed where it is (CoreCompetencyFocus, CostReduction, Capability)."),
      calc("IsOutsourced", "boolean", "TRUE when an organization other than the client performs the work.",
           "={{ExecutingOrganization}} <> {{ClientOrganization}}"),
      calc("IsBusinessProcessOutsourcing", "boolean", "TRUE for routine transactional work performed by a provider.",
           '=AND({{IsOutsourced}}, {{WorkNature}} = "Transactional")'),
      calc("IsKnowledgeProcessOutsourcing", "boolean", "TRUE for expertise-heavy work performed by a provider, the kind that builds deep process knowledge.",
           '=AND({{IsOutsourced}}, {{WorkNature}} = "ExpertiseHeavy")'),
      calc("IsVitalExpertiseClassedNonCore", "boolean", "TRUE when strategically vital, expertise-heavy work is classified as execution to send out rather than retained core.",
           '=AND({{SourcingClass}} = "SentOutExecution", {{IsStrategicallyVital}}, {{WorkNature}} = "ExpertiseHeavy")'),
      calc("IsWhatHowSplit", "boolean", "TRUE when different parties hold what is to be built and how it is built.",
           "={{SpecificationHolder}} <> {{MethodHolder}}"),
      calc("IsMethodKnowledgeHeldOutside", "boolean", "TRUE when the knowledge of how the work is really performed is held by a party other than the client.",
           "={{MethodHolder}} <> {{ClientOrganization}}"),
      calc("ClaimsHowWithoutDoing", "boolean", "TRUE when the client declares it holds the method knowledge of a function a provider executes.",
           "=AND({{MethodHolder}} = {{ClientOrganization}}, {{IsOutsourced}})"),
      calc("IsVitalExpertiseProcess", "boolean", "TRUE for a strategically vital, expertise-heavy function.",
           '=AND({{IsStrategicallyVital}}, {{WorkNature}} = "ExpertiseHeavy")'),
      calc("IsOutsourcedVitalExpertiseProcess", "boolean", "TRUE for a strategically vital, expertise-heavy function a provider performs.",
           "=AND({{IsVitalExpertiseProcess}}, {{IsOutsourced}})"),
      agg("AuditItemCount", "integer", "Audit items comparing held and needed knowledge for this function.",
          "=COUNTIFS(KnowledgeAuditItems!{{SourcingFunction}}, {{SourcingFunctionId}})"),
      agg("DependencyCount", "integer", "Audit items that found knowledge the client relies on a provider for.",
          "=COUNTIFS(KnowledgeAuditItems!{{SourcingFunction}}, {{SourcingFunctionId}}, KnowledgeAuditItems!{{IsKnowledgeDependency}}, TRUE)"),
      agg("CoverageGapCount", "integer", "Audit items that found knowledge nobody available to the client holds.",
          "=COUNTIFS(KnowledgeAuditItems!{{SourcingFunction}}, {{SourcingFunctionId}}, KnowledgeAuditItems!{{IsCoverageGap}}, TRUE)"),
      agg("SpecificationAuditCount", "integer", "Audit items about specification knowledge.",
          '=COUNTIFS(KnowledgeAuditItems!{{SourcingFunction}}, {{SourcingFunctionId}}, KnowledgeAuditItems!{{KnowledgeKind}}, "Specification")'),
      agg("SpecificationShortfallCount", "integer", "Specification items where the client holds less than it needs.",
          '=COUNTIFS(KnowledgeAuditItems!{{SourcingFunction}}, {{SourcingFunctionId}}, KnowledgeAuditItems!{{KnowledgeKind}}, "Specification", KnowledgeAuditItems!{{HasInternalShortfall}}, TRUE)'),
      agg("MethodShortfallCount", "integer", "Method items where the client holds less than it needs.",
          '=COUNTIFS(KnowledgeAuditItems!{{SourcingFunction}}, {{SourcingFunctionId}}, KnowledgeAuditItems!{{KnowledgeKind}}, "Method", KnowledgeAuditItems!{{HasInternalShortfall}}, TRUE)'),
      agg("ProviderIpDocumentationCount", "integer", "Engagements for this function whose documentation stays the provider's property.",
          '=COUNTIFS(ProviderEngagements!{{SourcingFunction}}, {{SourcingFunctionId}}, ProviderEngagements!{{DocumentationOwnership}}, "ProviderIP")'),
      calc("DesignsWhatItCannotBuild", "boolean", "TRUE when a product-delivering function is performed by a provider that keeps the documentation, the client's audited specification knowledge is complete, and its method knowledge falls short.",
           "=AND({{DeliversOwnProduct}}, {{IsOutsourced}}, {{ProviderIpDocumentationCount}} > 0, {{SpecificationAuditCount}} > 0, {{SpecificationShortfallCount}} = 0, {{MethodShortfallCount}} > 0)"),
      calc("IsUnauditedFunction", "boolean", "TRUE when an outsourced or strategically vital function has never been audited for held against needed knowledge.",
           "=AND(OR({{IsOutsourced}}, {{IsStrategicallyVital}}), {{AuditItemCount}} = 0)"),
      agg("CaptureInitiativeCount", "integer", "Deliberate knowledge capture initiatives for this function.",
          "=COUNTIFS(KnowledgeCaptureInitiatives!{{SourcingFunction}}, {{SourcingFunctionId}})"),
      calc("IsUncapturedPriorityProcess", "boolean", "TRUE for a vital, expertise-heavy function that is outsourced or has a coverage gap and has no deliberate capture initiative.",
           "=AND({{IsVitalExpertiseProcess}}, OR({{IsOutsourced}}, {{CoverageGapCount}} > 0), {{CaptureInitiativeCount}} = 0)"),
      iri()),
    T("KnowledgeAudits", "Audits of the procedural knowledge an organization holds against what it needs.", "sourcing",
      pk("KnowledgeAuditId"),
      calc("Name", "string", "Display name.", '={{Organization}} & ": " & {{Title}}'),
      rel("Organization", "Organizations", "Audited organization."),
      raw("Title", "string", "Audit title."),
      raw("ConductedAt", "datetime", "When the audit was concluded."),
      rel("ConductedByAgent", "Agents", "Who led it."),
      raw("ProblemFraming", "string", "How the audit states its problem: KnowledgeDeficit, or CostEfficiency."),
      agg("FindingCount", "integer", "Items where held knowledge falls short of what is needed.",
          "=COUNTIFS(KnowledgeAuditItems!{{KnowledgeAudit}}, {{KnowledgeAuditId}}, KnowledgeAuditItems!{{HasInternalShortfall}}, TRUE)"),
      calc("TreatsDeficitAsCostProblem", "boolean", "TRUE when an audit finds knowledge shortfalls but frames them as a cost or efficiency problem instead of acknowledging a knowledge deficit.",
           '=AND({{FindingCount}} > 0, {{ProblemFraming}} <> "KnowledgeDeficit")'),
      iri()),
    T("KnowledgeAuditItems", "One knowledge area an audit assessed: the level needed, the level the client holds, and any provider that holds it.", "sourcing",
      pk("KnowledgeAuditItemId"),
      calc("Name", "string", "Display name.", '={{KnowledgeAudit}} & " / " & {{KnowledgeArea}}'),
      rel("KnowledgeAudit", "KnowledgeAudits", "Audit."),
      rel("SourcingFunction", "SourcingFunctions", "Function the knowledge belongs to."),
      raw("KnowledgeArea", "string", "What must be known."),
      raw("KnowledgeKind", "string", "Specification (what is built) or Method (how it is built)."),
      raw("NeededLevel", "integer", "Level needed: 0 none, 1 aware, 2 can perform with help, 3 can perform and teach."),
      raw("HeldInternalLevel", "integer", "Level the client's own people hold, on the same scale."),
      rel("ProviderHoldingKnowledge", "Organizations", "Provider that holds the knowledge, when one does."),
      raw("ProviderHeldLevel", "integer", "Level the provider holds."),
      raw("InternalHoldingTeamCount", "integer", "Internal teams that hold the knowledge at the needed level."),
      rel("NamedKnowledgeGap", "KnowledgeGaps", "The knowledge gap row that names this finding."),
      lookup("ClientOrganization", "string", "The audited organization.", idx("KnowledgeAudits", "Organization", "KnowledgeAudit")),
      calc("HasInternalShortfall", "boolean", "TRUE when the client holds less than it needs.", "={{HeldInternalLevel}} < {{NeededLevel}}"),
      calc("IsKnowledgeDependency", "boolean", "TRUE when the client falls short and relies on a provider that holds the knowledge at the needed level.",
           '=AND({{HasInternalShortfall}}, {{ProviderHoldingKnowledge}} <> "", {{ProviderHeldLevel}} >= {{NeededLevel}})'),
      calc("IsCoverageGap", "boolean", "TRUE when the client falls short and no provider available to it holds the knowledge either.",
           "=AND({{HasInternalShortfall}}, NOT({{IsKnowledgeDependency}}))"),
      calc("IsUnnamedFinding", "boolean", "TRUE when an audit found a gap or dependency and nobody recorded it as a named knowledge gap.",
           '=AND({{HasInternalShortfall}}, {{NamedKnowledgeGap}} = "")'),
      calc("IsSingleTeamSilo", "boolean", "TRUE when knowledge the client does hold sits with exactly one internal team.",
           "=AND({{HeldInternalLevel}} >= {{NeededLevel}}, {{InternalHoldingTeamCount}} = 1)"),
      iri()),
    T("KnowledgeCaptureInitiatives", "Deliberate efforts to capture the knowledge of a function, with the method used.", "sourcing",
      pk("KnowledgeCaptureInitiativeId"),
      calc("Name", "string", "Display name.", '={{SourcingFunction}} & " by " & {{KnowledgeMethod}}'),
      rel("SourcingFunction", "SourcingFunctions", "Function whose knowledge is captured."),
      rel("KnowledgeMethod", "KnowledgeMethods", "Capture method."),
      rel("LeadAgent", "Agents", "Who leads it."),
      raw("StartedAt", "datetime", "When it started."),
      raw("Status", "string", "Planned, Active or Completed."),
      iri()),
    T("KnowledgeWorkforcePositions", "Dedicated knowledge engineering, information architecture and ontology positions an organization budgets.", "sourcing",
      pk("KnowledgeWorkforcePositionId"),
      calc("Name", "string", "Display name.", '={{Organization}} & " " & {{Discipline}}'),
      rel("Organization", "Organizations", "Organization whose knowledge the position works on."),
      raw("Discipline", "string", "KnowledgeEngineer, InformationArchitect or Ontologist."),
      rel("Role", "Roles", "The modeled role, when there is one."),
      raw("Status", "string", "Filled, Open or NotBudgeted."),
      raw("OpenedAt", "datetime", "When the position was opened."),
      rel("FilledByAgent", "Agents", "Who holds it."),
      iri()),
    T("ProviderEngagements", "A client's relationship with a provider for one function, with the knowledge terms it carries.", "sourcing",
      pk("ProviderEngagementId"),
      calc("Name", "string", "Display name.", '={{ClientOrganization}} & " <- " & {{Provider}}'),
      rel("ClientOrganization", "Organizations", "Client."),
      rel("Provider", "Organizations", "Provider."),
      rel("SourcingFunction", "SourcingFunctions", "Function the provider performs."),
      raw("StartedAt", "datetime", "When the engagement started."),
      raw("TermMonths", "integer", "Contract term in months."),
      raw("Status", "string", "Active or Ended."),
      raw("DocumentationOwnership", "string", "ProviderIP when the documentation the provider produces stays its intellectual property; ClientOwned or Joint otherwise."),
      raw("KnowledgeDutyTerms", "string", "Any duty the provider carries to build up the client's knowledge; blank when there is none."),
      raw("ProviderTreatsKnowHowAsDifferentiator", "boolean", "TRUE when the provider positions its procedural know-how as its competitive differentiator."),
      raw("HasKnowledgeAccessClause", "boolean", "TRUE when the contract gives the client access to the process knowledge needed to run the operation."),
      raw("KnowledgeReturnPlan", "string", "How the knowledge comes back to the client; blank when nobody planned it."),
      calc("IsActive", "boolean", "TRUE for a running engagement.", '={{Status}} = "Active"'),
      agg("ReliedDependencyCount", "integer", "Audit findings where the client relies on this provider's knowledge.",
          "=COUNTIFS(KnowledgeAuditItems!{{ProviderHoldingKnowledge}}, {{Provider}}, KnowledgeAuditItems!{{ClientOrganization}}, {{ClientOrganization}}, KnowledgeAuditItems!{{IsKnowledgeDependency}}, TRUE)"),
      calc("IsUnplannedKnowledgeReturn", "boolean", "TRUE when the client relies on a provider's knowledge, the provider keeps the documentation as its property, and nobody planned how the knowledge comes back.",
           '=AND({{ReliedDependencyCount}} > 0, {{DocumentationOwnership}} = "ProviderIP", {{KnowledgeReturnPlan}} = "")'),
      calc("IsKnowledgeAccessUnsecured", "boolean", "TRUE when a running engagement is a knowledge dependency and the client has no contractual access to that knowledge.",
           "=AND({{IsActive}}, {{ReliedDependencyCount}} > 0, {{HasKnowledgeAccessClause}} = FALSE)"),
      agg("RequiredDeliverableCount", "integer", "Knowledge deliverables the engagement requires.",
          "=COUNTIFS(KnowledgeDeliverables!{{ProviderEngagement}}, {{ProviderEngagementId}})"),
      agg("ToClientRequiredCount", "integer", "Deliverables that move knowledge from the provider to the client.",
          '=COUNTIFS(KnowledgeDeliverables!{{ProviderEngagement}}, {{ProviderEngagementId}}, KnowledgeDeliverables!{{Direction}}, "ToClient")'),
      agg("ToClientDeliveredCount", "integer", "Delivered knowledge moving from provider to client.",
          '=COUNTIFS(KnowledgeDeliverables!{{ProviderEngagement}}, {{ProviderEngagementId}}, KnowledgeDeliverables!{{Direction}}, "ToClient", KnowledgeDeliverables!{{IsDelivered}}, TRUE)'),
      agg("ToProviderDeliveredCount", "integer", "Delivered knowledge moving from client to provider.",
          '=COUNTIFS(KnowledgeDeliverables!{{ProviderEngagement}}, {{ProviderEngagementId}}, KnowledgeDeliverables!{{Direction}}, "ToProvider", KnowledgeDeliverables!{{IsDelivered}}, TRUE)'),
      agg("JointDeliverableCount", "integer", "Knowledge assets the client and provider build jointly.",
          '=COUNTIFS(KnowledgeDeliverables!{{ProviderEngagement}}, {{ProviderEngagementId}}, KnowledgeDeliverables!{{Direction}}, "Joint")'),
      calc("LacksKnowledgeDeliverables", "boolean", "TRUE when a running engagement requires no knowledge deliverable at all.",
           "=AND({{IsActive}}, {{RequiredDeliverableCount}} = 0)"),
      calc("IsOneWayLearning", "boolean", "TRUE when a running engagement has knowledge deliverables but knowledge has actually moved in only one direction.",
           "=AND({{IsActive}}, {{RequiredDeliverableCount}} > 0, OR({{ToClientDeliveredCount}} = 0, {{ToProviderDeliveredCount}} = 0))"),
      calc("IsShortTermWithoutJointKnowledge", "boolean", "TRUE when a running engagement is contracted for under three years and builds no knowledge jointly.",
           "=AND({{IsActive}}, {{TermMonths}} < 36, {{JointDeliverableCount}} = 0)"),
      calc("ObligesKnowledgeFlowBack", "boolean", "TRUE when the engagement requires knowledge deliverables to the client and plans how the knowledge comes back.",
           '=AND({{ToClientRequiredCount}} > 0, {{KnowledgeReturnPlan}} <> "")'),
      iri()),
    T("KnowledgeDeliverables", "Explicit knowledge management deliverables an engagement requires, and the direction knowledge moves.", "sourcing",
      pk("KnowledgeDeliverableId"),
      calc("Name", "string", "Display name.", '={{ProviderEngagement}} & " " & {{Direction}} & ": " & {{Title}}'),
      rel("ProviderEngagement", "ProviderEngagements", "Engagement."),
      raw("Direction", "string", "ToClient, ToProvider or Joint."),
      raw("Title", "string", "Deliverable."),
      raw("DueAt", "datetime", "When due."),
      raw("DeliveredAt", "datetime", "When delivered; blank when not."),
      calc("IsDelivered", "boolean", "TRUE once delivered.", '={{DeliveredAt}} <> ""'),
      iri()),
    T("CorporateGovernancePrograms", "Governance programmes an organization runs, who sponsors them, and what their scope covers.", "sourcing",
      pk("CorporateGovernanceProgramId"),
      calc("Name", "string", "Display name.", "={{Label}}"),
      rel("Organization", "Organizations", "Organization."),
      raw("Label", "string", "Programme."),
      raw("SponsorDiscipline", "string", "The leadership discipline sponsoring it: Engineering or Legal."),
      raw("LaunchedAt", "datetime", "When launched."),
      raw("CoversCompliance", "boolean", "Scope includes regulatory compliance and legal risk."),
      raw("CoversDataQuality", "boolean", "Scope includes data quality."),
      raw("CoversInformationManagement", "boolean", "Scope includes information management."),
      raw("CoversKnowledgeManagement", "boolean", "Scope includes knowledge management."),
      calc("IsComplianceOnly", "boolean", "TRUE when a programme's scope is compliance and nothing else.",
           "=AND({{CoversCompliance}}, {{CoversDataQuality}} = FALSE, {{CoversInformationManagement}} = FALSE, {{CoversKnowledgeManagement}} = FALSE)"),
      iri()),
    T("RecordsRetentionPolicies", "Retention rules for classes of records, with what drives the retention period.", "sourcing",
      pk("RecordsRetentionPolicyId"),
      calc("Name", "string", "Display name.", '={{RecordClass}} & " / " & {{RetentionDriver}}'),
      rel("GovernanceProgram", "CorporateGovernancePrograms", "Programme that set the rule."),
      raw("RecordClass", "string", "Records the rule applies to."),
      raw("RetentionDriver", "string", "ComplianceRisk (keep only as long as legal exposure requires) or KnowledgeValue."),
      raw("RetentionYears", "integer", "Years records are kept."),
      raw("KnowledgeUsefulLifeYears", "integer", "Years the knowledge in those records stays in use (for example the service life of the product they describe)."),
      lookup("ProgramSponsorDiscipline", "string", "Discipline sponsoring the programme.",
             idx("CorporateGovernancePrograms", "SponsorDiscipline", "GovernanceProgram")),
      calc("IsLegalLedKnowledgeDestruction", "boolean", "TRUE when a legally sponsored programme sets a risk-driven retention period that destroys records while their knowledge is still in use.",
           '=AND({{ProgramSponsorDiscipline}} = "Legal", {{RetentionDriver}} = "ComplianceRisk", {{RetentionYears}} < {{KnowledgeUsefulLifeYears}})'),
      iri()),
    # ------------------------------------------------------------------ the AI system registry
    T("AiRegistryModelVersions", "Model versions supplied by the external AI system registry feed, described in Dublin Core terms.", "registry",
      pk("AiRegistryModelVersionId"),
      calc("Name", "string", "Display name.", '={{DcTitle}} & " " & {{DcHasVersion}}'),
      raw("RegistrySystem", "string", "The registry the record came from."),
      raw("DcIdentifier", "string", "dct:identifier: the identifier the graph uses for the agent individual."),
      raw("DcTitle", "string", "dct:title."),
      raw("DcCreator", "string", "dct:creator."),
      raw("DcDate", "datetime", "dct:date the version was issued."),
      raw("DcHasVersion", "string", "dct:hasVersion."),
      raw("DcDescription", "string", "dct:description."),
      raw("FeedReceivedAt", "datetime", "When the feed delivered the record."),
      agg("GraphIndividualCount", "integer", "Agent individuals in the graph carrying the registry identifier.",
          "=COUNTIFS(Agents!{{AgentId}}, {{DcIdentifier}})"),
      agg("LiveProductionDeploymentCount", "integer", "Deployments of this version live in production.",
          "=COUNTIFS(AiModelDeployments!{{ModelVersion}}, {{AiRegistryModelVersionId}}, AiModelDeployments!{{IsLiveInProduction}}, TRUE)"),
      calc("IsLiveButUnregisteredInGraph", "boolean", "TRUE when a model version runs in production and no agent individual in the graph represents it.",
           "=AND({{LiveProductionDeploymentCount}} > 0, {{GraphIndividualCount}} = 0)"),
      iri()),
    T("AiModelDeployments", "Deployment records for AI system versions, from the registry feed.", "registry",
      pk("AiModelDeploymentId"),
      calc("Name", "string", "Display name.", '={{ModelVersion}} & " @ " & {{Environment}}'),
      rel("ModelVersion", "AiRegistryModelVersions", "Deployed version."),
      raw("Environment", "string", "Production or Staging."),
      raw("DeployedAt", "datetime", "When deployed."),
      raw("RetiredAt", "datetime", "When retired; blank while running."),
      *as_of(),
      calc("IsLiveInProduction", "boolean", "TRUE for a production deployment running at the evaluation instant.",
           '=AND({{Environment}} = "Production", {{DeployedAt}} <= {{AsOfInstant}}, OR({{RetiredAt}} = "", {{RetiredAt}} > {{AsOfInstant}}))'),
      lookup("AgentIdentifier", "string", "Graph identifier of the deployed version.",
             idx("AiRegistryModelVersions", "DcIdentifier", "ModelVersion")),
      agg("AssignmentLinkCount", "integer", "Role assignments in the graph filled by that agent.",
          "=COUNTIFS(RoleAssignments!{{Agent}}, {{AgentIdentifier}})"),
      agg("ArtifactLinkCount", "integer", "Artifacts in the graph attributed to that agent.",
          "=COUNTIFS(ExecutionEntities!{{AttributedToAgent}}, {{AgentIdentifier}})"),
      calc("IsIsolatedRegistryFact", "boolean", "TRUE for a live production deployment whose agent fills no role and has produced no artifact the graph knows: a registry row with no context.",
           "=AND({{IsLiveInProduction}}, {{AssignmentLinkCount}} = 0, {{ArtifactLinkCount}} = 0)"),
      iri()),
    T("AiModelEvaluations", "Evaluation results for AI system versions, from the registry feed.", "registry",
      pk("AiModelEvaluationId"),
      calc("Name", "string", "Display name.", '={{ModelVersion}} & " " & {{Metric}}'),
      rel("ModelVersion", "AiRegistryModelVersions", "Evaluated version."),
      raw("EvaluatedAt", "datetime", "When evaluated."),
      raw("EvaluationSuite", "string", "Suite or dataset."),
      raw("Metric", "string", "Metric."),
      raw("Score", "number", "Score."),
      raw("PassThreshold", "number", "Score needed to pass."),
      calc("Passed", "boolean", "TRUE when the score meets the threshold.", "={{Score}} >= {{PassThreshold}}"),
      iri()),
    T("AiAgentAccountabilities", "The human person accountable for an AI agent, with a validity period.", "registry",
      pk("AiAgentAccountabilityId"),
      calc("Name", "string", "Display name.", '={{AiAgent}} & " accountable to " & {{AccountableAgent}}'),
      rel("AiAgent", "Agents", "AI agent."),
      rel("AccountableAgent", "Agents", "Agent accountable for it (prov:actedOnBehalfOf)."),
      raw("ValidFrom", "datetime", "From."),
      raw("ValidTo", "datetime", "To; blank while in force."),
      *as_of(),
      calc("IsCurrent", "boolean", "TRUE while in force at the evaluation instant.",
           '=AND({{ValidFrom}} <= {{AsOfInstant}}, OR({{ValidTo}} = "", {{ValidTo}} > {{AsOfInstant}}))'),
      lookup("AccountableAgentKind", "string", "Kind of the accountable agent.", idx("Agents", "AgentKind", "AccountableAgent")),
      calc("IsAccountableToNonPerson", "boolean", "TRUE when an AI agent is recorded as accountable to something that is not a human person.",
           '={{AccountableAgentKind}} <> "Human"'),
      calc("IsCurrentHumanAccountability", "boolean", "TRUE for an accountability in force that names a human person.",
           '=AND({{IsCurrent}}, {{AccountableAgentKind}} = "Human")'),
      iri()),
    T("AgentUpgradeAssessments", "Impact assessments of moving an agent to a newer model version, as listed by whoever assessed it and as traversed in the graph.", "registry",
      pk("AgentUpgradeAssessmentId"),
      calc("Name", "string", "Display name.", '={{CurrentAgent}} & " -> " & {{CandidateAgent}} & " (" & {{AssessmentMethod}} & ")"'),
      rel("CurrentAgent", "Agents", "Agent being replaced."),
      rel("CandidateAgent", "Agents", "Candidate version."),
      raw("AssessedAt", "datetime", "When assessed."),
      raw("AssessmentMethod", "string", "ChangeTicket (listed by hand) or GraphTraversal."),
      rel("AssessedByAgent", "Agents", "Who assessed it."),
      raw("ListedAffectedStepCount", "integer", "Downstream steps the assessment listed as affected."),
      raw("ListedAffectedStepsNote", "string", "What the assessment listed."),
      lookup("AttributedArtifactCount", "integer", "Artifacts attributed to the current agent.",
             idx("Agents", "AttributedArtifactCount", "CurrentAgent")),
      lookup("TraversedDownstreamStepCount", "integer", "Steps downstream of the current agent's artifacts, found by traversing the artifact-flow closure.",
             idx("Agents", "ArtifactBlastRadiusStepCount", "CurrentAgent")),
      calc("MissedTraversedImpact", "boolean", "TRUE when an assessment listed fewer affected steps than traversal of the artifact flow finds.",
           "={{ListedAffectedStepCount}} < {{TraversedDownstreamStepCount}}"),
      iri()),
    # ------------------------------------------------------------------ ground truth: assignment updates and routing
    T("AssignmentUpdatePolicies", "Governance for updating role assignments once operational systems read them: who triggers the update and the service level for completing it.", "ground-truth",
      pk("AssignmentUpdatePolicyId"),
      calc("Name", "string", "Display name.", "={{Label}}"),
      raw("Label", "string", "Policy."),
      rel("TriggerOwnerRole", "Roles", "Role responsible for triggering an assignment update; blank when governance names nobody."),
      raw("UpdateSlaHours", "integer", "Hours within which an update must be completed; 0 when no service level is defined."),
      raw("ModelDrivesRouting", "boolean", "TRUE when operational systems route work from the assignments this policy covers."),
      raw("AdoptedAt", "datetime", "When adopted."),
      iri()),
    T("RoleAssignmentUpdateTasks", "The audit record of one change to who fills a role: what triggered it, who triggered it, when it was completed, and the run that depended on it.", "ground-truth",
      pk("RoleAssignmentUpdateTaskId"),
      calc("Name", "string", "Display name.", '={{Role}} & " " & {{TriggerEvent}} & " @ " & {{TriggerOccurredAt}}'),
      rel("Role", "Roles", "Role whose filler changes."),
      rel("GoverningPolicy", "AssignmentUpdatePolicies", "Policy governing the update."),
      raw("TriggerEvent", "string", "Departure, ModelUpgrade, AiToHumanHandover or HumanToAutomationHandover."),
      raw("Reason", "string", "Why the change was made."),
      raw("TriggerOccurredAt", "datetime", "When the triggering event happened."),
      raw("TriggeredAt", "datetime", "When someone triggered the update; blank when nobody did."),
      rel("TriggeredByAgent", "Agents", "Who triggered it."),
      raw("CompletedAt", "datetime", "When the assignment change was recorded in the model; blank when not yet."),
      rel("EndingAssignment", "RoleAssignments", "Assignment that ends."),
      rel("ReplacementAssignment", "RoleAssignments", "Assignment that replaces it, when there is one."),
      rel("DependentExecution", "ProcedureExecutions", "The first procedure run after the trigger that needed the role."),
      *as_of(),
      lookup("PolicyTriggerOwnerRole", "string", "Role the policy makes responsible for triggering.",
             idx("AssignmentUpdatePolicies", "TriggerOwnerRole", "GoverningPolicy", "AssignmentUpdatePolicyId")),
      lookup("TriggerOwnerCoverCount", "integer", "Assignments currently covering that role.",
             "=INDEX(Roles!{{CurrentlyCoveredAssignmentCount}}, MATCH({{PolicyTriggerOwnerRole}}, Roles!{{RoleId}}, 0))"),
      calc("LacksNamedTriggerOwner", "boolean", "TRUE when governance names no role responsible for triggering the update, or names one nobody holds.",
           '=OR({{PolicyTriggerOwnerRole}} = "", {{TriggerOwnerCoverCount}} = 0)'),
      lookup("PolicySlaHours", "integer", "Service level in hours.",
             idx("AssignmentUpdatePolicies", "UpdateSlaHours", "GoverningPolicy", "AssignmentUpdatePolicyId")),
      calc("ElapsedMinutes", "number", "Minutes from the trigger to completion, or to the evaluation instant while incomplete.",
           '=IF({{CompletedAt}} = "", DATETIME_DIFF({{AsOfInstant}}, {{TriggerOccurredAt}}, "minutes"), DATETIME_DIFF({{CompletedAt}}, {{TriggerOccurredAt}}, "minutes"))'),
      calc("ExceededUpdateSla", "boolean", "TRUE when no service level is defined, or the update took longer than it allows.",
           "=OR({{PolicySlaHours}} = 0, {{ElapsedMinutes}} > ({{PolicySlaHours}} * 60))"),
      lookup("EndingRole", "string", "Role of the ending assignment.", idx("RoleAssignments", "Role", "EndingAssignment", "RoleAssignmentId")),
      lookup("ReplacementRole", "string", "Role of the replacement assignment.", idx("RoleAssignments", "Role", "ReplacementAssignment", "RoleAssignmentId")),
      calc("ChangedRoleInsteadOfAssignment", "boolean", "TRUE when a change of who does the work was made by moving it to a different role, so the steps bound to the old role had to be re-pointed.",
           '=AND({{ReplacementAssignment}} <> "", {{ReplacementRole}} <> {{EndingRole}})'),
      lookup("DependentRunVersion", "string", "Version the dependent run enacted.", idx("ProcedureExecutions", "ProcedureVersion", "DependentExecution")),
      lookup("DependentRunStartedAt", "datetime", "When the dependent run started.", idx("ProcedureExecutions", "StartedAt", "DependentExecution")),
      agg("DependentRunRoleStepCount", "integer", "Steps of the dependent run's version assigned to the role.",
          "=COUNTIFS(Steps!{{ProcedureVersion}}, {{DependentRunVersion}}, Steps!{{AssignedRole}}, {{Role}})"),
      calc("MissedNextDependentRun", "boolean", "TRUE when a run that needs the role started after the trigger and before the assignment change was recorded.",
           '=AND({{DependentRunRoleStepCount}} > 0, {{DependentRunStartedAt}} > {{TriggerOccurredAt}}, OR({{CompletedAt}} = "", {{CompletedAt}} > {{DependentRunStartedAt}}))'),
      agg("FailedNoticeCount", "integer", "Notices for the role in the dependent run that reached the wrong person or nobody.",
          "=COUNTIFS(AssignmentRoutedNotices!{{ProcedureExecution}}, {{DependentExecution}}, AssignmentRoutedNotices!{{NoticeRole}}, {{Role}}, AssignmentRoutedNotices!{{ReachedWrongPersonOrNobody}}, TRUE)"),
      calc("StaleAssignmentBrokeRouting", "boolean", "TRUE when the assignment was still stale at a run that needed it and that run's notice for the role reached the wrong person or nobody.",
           "=AND({{MissedNextDependentRun}}, {{FailedNoticeCount}} > 0)"),
      iri()),
    T("AssignmentRoutedNotices", "Approval and verification notices a deployment pipeline sent for a run, where it read the recipient from, and who received it.", "ground-truth",
      pk("AssignmentRoutedNoticeId"),
      calc("Name", "string", "Display name.", '={{ProcedureExecution}} & " / " & {{NoticeStep}} & " -> " & {{RoutedToAgent}}'),
      rel("ProcedureExecution", "ProcedureExecutions", "Run the notice belongs to."),
      rel("NoticeStep", "Steps", "Step the notice asks someone to act on."),
      raw("NoticeKind", "string", "ReleaseApproval or HealthVerification."),
      raw("SentAt", "datetime", "When sent."),
      raw("RoutingSource", "string", "RoleAssignments (read from the model) or OpsSpreadsheet (a separately maintained list)."),
      rel("RoutedToAgent", "Agents", "Who received it; blank when nobody did."),
      lookup("NoticeRole", "string", "Role assigned to the step.", idx("Steps", "AssignedRole", "NoticeStep")),
      calc("RecipientRoleKey", "string", "Recipient and role, as one key.", '={{RoutedToAgent}} & "|" & {{NoticeRole}}'),
      agg("RecipientPairAssignmentCount", "integer", "Assignments of the recipient to the role, at any time.",
          "=COUNTIFS(RoleAssignments!{{AgentRolePairKey}}, {{RecipientRoleKey}})"),
      agg("RecipientValidFrom", "datetime", "Start of the recipient's assignment to the role.",
          "=MAXIFS(RoleAssignments!{{ValidFrom}}, RoleAssignments!{{AgentRolePairKey}}, {{RecipientRoleKey}})"),
      agg("RecipientLatestValidTo", "datetime", "End of the recipient's assignment to the role.",
          "=MAXIFS(RoleAssignments!{{ValidTo}}, RoleAssignments!{{AgentRolePairKey}}, {{RecipientRoleKey}})"),
      agg("RecipientOpenEndedCount", "integer", "Open-ended assignments of the recipient to the role.",
          "=COUNTIFS(RoleAssignments!{{AgentRolePairKey}}, {{RecipientRoleKey}}, RoleAssignments!{{IsOpenEnded}}, TRUE)"),
      calc("RecipientHeldRoleWhenSent", "boolean", "TRUE when the recipient's assignment to the step's role was valid at the moment the notice was sent.",
           '=AND({{RoutedToAgent}} <> "", {{RecipientPairAssignmentCount}} > 0, {{RecipientValidFrom}} <= {{SentAt}}, OR({{RecipientOpenEndedCount}} > 0, {{RecipientLatestValidTo}} > {{SentAt}}))'),
      calc("ReachedWrongPersonOrNobody", "boolean", "TRUE when a notice went to someone who did not hold the step's role when it was sent, or to nobody.",
           "=NOT({{RecipientHeldRoleWhenSent}})"),
      calc("RoutedAroundModel", "boolean", "TRUE when a notice was routed from a separately maintained list and reached someone the model's assignments did not name for the role.",
           '=AND({{RoutingSource}} <> "RoleAssignments", NOT({{RecipientHeldRoleWhenSent}}))'),
      iri()),
    ("ArtifactHandoffs", "One artifact passing from the step that produces it to a step that consumes it, asserted per declared input variable. The edge table the upgrade blast radius is traversed over.", "sourcing", [
        raw("ArtifactHandoffId", "string", "Stored identifier.", nullable=False),
        calc("Name", "string", "Display name.", '={{FromStep}} & " -> " & {{ToStep}}'),
        rel("StepVariable", "StepVariables", "The consuming step's input variable this hand-off feeds."),
        rel("FromStep", "Steps", "Step that produces the artifact."),
        rel("ToStep", "Steps", "Step that consumes it."),
        lookup("DeclaredSourceStep", "string", "Producing step the input variable itself declares.", idx("StepVariables", "SourceStep", "StepVariable")),
        lookup("DeclaredConsumerStep", "string", "Step that declares the input variable.", idx("StepVariables", "Step", "StepVariable")),
        calc("DisagreesWithDeclaredVariable", "boolean", "TRUE when a recorded hand-off names different steps than the input variable it feeds declares, so traversal and declaration have drifted apart.",
             "=OR({{FromStep}} <> {{DeclaredSourceStep}}, {{ToStep}} <> {{DeclaredConsumerStep}})"),
        {"name": "HandoffClosure", "datatype": "string", "type": "closure", "nullable": True,
         "Description": "Transitive closure of artifact hand-offs (FromStep -> ToStep), materialized as vw_artifact_handoffs_closure: every step an artifact can reach in one or more hand-offs.",
         "EdgeTable": "ArtifactHandoffs", "FromColumn": "FromStep", "ToColumn": "ToStep"},
        raw("SemanticTypeIri", "string", "Semantic type IRI."),
    ]),
]
FIELDS = {
    "Organizations": [
        agg("ProductDeliveryFunctionCount", "integer", "Functions that deliver the organization's own products.",
            "=COUNTIFS(SourcingFunctions!{{ClientOrganization}}, {{OrganizationId}}, SourcingFunctions!{{DeliversOwnProduct}}, TRUE)"),
        agg("ProviderHeldDeliveryMethodCount", "integer", "Of those, functions whose method knowledge a provider holds.",
            "=COUNTIFS(SourcingFunctions!{{ClientOrganization}}, {{OrganizationId}}, SourcingFunctions!{{DeliversOwnProduct}}, TRUE, SourcingFunctions!{{IsMethodKnowledgeHeldOutside}}, TRUE)"),
        calc("IsHollowedOutFirm", "boolean", "TRUE when every function that delivers the organization's own products depends on method knowledge a provider holds.",
             "=AND({{ProductDeliveryFunctionCount}} > 0, {{ProviderHeldDeliveryMethodCount}} = {{ProductDeliveryFunctionCount}})"),
        agg("AuditFindingCount", "integer", "Audit items where the organization holds less knowledge than it needs.",
            "=COUNTIFS(KnowledgeAuditItems!{{ClientOrganization}}, {{OrganizationId}}, KnowledgeAuditItems!{{HasInternalShortfall}}, TRUE)"),
        agg("FilledKnowledgePositionCount", "integer", "Filled knowledge engineering, information architecture and ontology positions.",
            '=COUNTIFS(KnowledgeWorkforcePositions!{{Organization}}, {{OrganizationId}}, KnowledgeWorkforcePositions!{{Status}}, "Filled")'),
        calc("HasKnowledgeFindingsWithoutKnowledgeStaff", "boolean", "TRUE when audits found knowledge shortfalls and the organization employs no knowledge engineer, information architect or ontologist to address them.",
             "=AND({{AuditFindingCount}} > 0, {{FilledKnowledgePositionCount}} = 0)"),
    ],
    "ExecutionEntities": [
        lookup("GeneratingAgent", "string", "Agent that executed the step execution.", idx("StepExecutions", "ExecutedByAgent", "StepExecution")),
        calc("AttributedToAgent", "string", "For a generated entity, the agent it is attributed to (prov:wasAttributedTo).",
             '=IF({{Usage}} = "Generated", {{GeneratingAgent}}, "")'),
    ],
    "StepVariables": [
        lookup("StepAccountableAgent", "string", "Agent accountable for the declaring step.", idx("Steps", "AccountableAgent", "Step")),
        lookup("StepAgentKind", "string", "Kind of that agent.", idx("Steps", "AssignedAgentKind", "Step")),
        lookup("ConsumerRole", "string", "Role responsible for the declaring step.", idx("Steps", "AssignedRole", "Step")),
        lookup("ConsumerWorkflow", "string", "Procedure version containing the declaring step.", idx("Steps", "ProcedureVersion", "Step")),
        lookup("SourceStepAgent", "string", "Agent accountable for the step producing the feeding variable.",
               "=INDEX(Steps!{{AccountableAgent}}, MATCH({{SourceStep}}, Steps!{{StepId}}, 0))"),
        lookup("SourceStepAgentKind", "string", "Kind of that agent.",
               "=INDEX(Steps!{{AssignedAgentKind}}, MATCH({{SourceStep}}, Steps!{{StepId}}, 0))"),
        calc("IsInputFromAiArtifact", "boolean", "TRUE for an input fed by an artifact that a step held by an AI agent produces.",
             '=AND({{Direction}} = "Input", {{SourceStepAgentKind}} = "AIAgent")'),
        calc("AiArtifactConsumerHasNoAccountableAgent", "boolean", "TRUE when a step consuming an AI agent's artifact has nobody holding its role.",
             '=AND({{IsInputFromAiArtifact}}, {{StepAccountableAgent}} = "")'),
        calc("AiBlastRadiusPath", "string", "For an input fed by an AI agent's artifact: the agent, the artifact, the consuming step, its role, its agent and its workflow.",
             '=IF({{IsInputFromAiArtifact}}, {{SourceStepAgent}} & " produces " & {{Label}} & " for " & {{Step}} & "; role " & {{ConsumerRole}} & "; agent " & {{StepAccountableAgent}} & "; workflow " & {{ConsumerWorkflow}}, "")'),
    ],
    "Steps": [
        agg("DownstreamArtifactStepCount", "integer", "Steps reachable from this step along artifact hand-offs.",
            "=COUNTIFS(vw_artifact_handoffs_closure!{{FromId}}, Steps!{{StepId}})"),
        agg("AiArtifactInputCount", "integer", "Inputs fed by an artifact an AI agent's step produces.",
            "=COUNTIFS(StepVariables!{{Step}}, {{StepId}}, StepVariables!{{IsInputFromAiArtifact}}, TRUE)"),
        calc("ConsumesAiAgentArtifact", "boolean", "TRUE when the step takes an AI agent's artifact as an input.", "={{AiArtifactInputCount}} > 0"),
    ],
    "ProcedureVersions": [
        agg("AiArtifactConsumingInputCount", "integer", "Inputs of the version's steps fed by an AI agent's artifact.",
            "=COUNTIFS(StepVariables!{{ConsumerWorkflow}}, {{ProcedureVersionId}}, StepVariables!{{IsInputFromAiArtifact}}, TRUE)"),
        calc("ContainsStepsAffectedByAiAgentChange", "boolean", "TRUE when the workflow contains a step that consumes an AI agent's artifact, so changing that agent affects it.",
             "={{AiArtifactConsumingInputCount}} > 0"),
    ],
    "Agents": [
        agg("AttributedArtifactCount", "integer", "Artifacts attributed to the agent.",
            "=COUNTIFS(ExecutionEntities!{{AttributedToAgent}}, {{AgentId}})"),
        calc("HasProducedArtifacts", "boolean", "TRUE when some artifact is attributed to the agent.", "={{AttributedArtifactCount}} > 0"),
        agg("DownstreamOfHeldStepsCount", "integer", "Steps reachable along artifact hand-offs from the steps whose role this agent currently holds.",
            "=SUMIFS(Steps!{{DownstreamArtifactStepCount}}, Steps!{{AccountableAgent}}, {{AgentId}})"),
        calc("ArtifactBlastRadiusStepCount", "integer", "For an AI agent, the steps downstream of the steps it holds, found by traversing the artifact hand-off closure.",
             '=IF({{AgentKind}} = "AIAgent", {{DownstreamOfHeldStepsCount}}, 0)'),
        calc("HasArtifactBlastRadius", "boolean", "TRUE when moving the agent to another version affects steps downstream of its artifacts.",
             "={{ArtifactBlastRadiusStepCount}} > 0"),
        agg("RegistryVersionMatchCount", "integer", "Registry records whose Dublin Core identifier and version match this agent individual.",
            "=COUNTIFS(AiRegistryModelVersions!{{DcIdentifier}}, {{AgentId}}, AiRegistryModelVersions!{{DcHasVersion}}, {{VersionOrEmploymentKey}})"),
        calc("IsAiAgentNotFilledFromRegistry", "boolean", "TRUE for an AI agent individual that no registry record supplies, or whose version disagrees with the registry.",
             '=AND({{AgentKind}} = "AIAgent", {{RegistryVersionMatchCount}} = 0)'),
        agg("CurrentAccountableHumanCount", "integer", "Human persons currently accountable for the agent.",
            "=COUNTIFS(AiAgentAccountabilities!{{AiAgent}}, {{AgentId}}, AiAgentAccountabilities!{{IsCurrentHumanAccountability}}, TRUE)"),
        calc("IsAiAgentWithoutAccountableHuman", "boolean", "TRUE for an AI agent currently filling a role with no human person accountable for it.",
             '=AND({{AgentKind}} = "AIAgent", {{CountOfCurrentRoleAssignments}} > 0, {{CurrentAccountableHumanCount}} = 0)'),
    ],
    "Roles": [
        agg("ApprovalStepCount", "integer", "Approval steps assigned to the role.",
            '=COUNTIFS(Steps!{{AssignedRole}}, {{RoleId}}, Steps!{{ControlKind}}, "Approval")'),
    ],
    "RoleAssignments": [
        calc("AgentRolePairKey", "string", "Agent and role, as one key, regardless of validity.", '={{Agent}} & "|" & {{Role}}'),
        calc("IsOpenEnded", "boolean", "TRUE when the assignment has no end.", '={{ValidTo}} = ""'),
        lookup("RoleApprovalStepCount", "integer", "Approval steps assigned to the role.", idx("Roles", "ApprovalStepCount", "Role")),
        calc("ReceivesApprovalNoticesNow", "boolean", "TRUE when the assignment currently covers a role that approval steps are assigned to, so its agent is who approval notices go to.",
             "=AND({{CoversNow}}, {{RoleApprovalStepCount}} > 0)"),
    ],
}


def F(table, *names):
    return [f"{table}.{n}" for n in names]


QUESTIONS = [
    # ------------------------------------------------------------------ sourcing
    ("q11-sourcing-outsourcing-models", SOURCING,
     "Which of our functions have we classified as execution to send out, and is each one routine transactional work or expertise-heavy work that builds process knowledge?",
     "Routine work can be sent out with little lost; expertise-heavy work sent out takes the organization's process knowledge with it.",
     F("SourcingFunctions", "Label", "ClientOrganization", "Procedure", "SourcingClass", "WorkNature", "ExecutingOrganization",
       "SourcedSince", "SourcingRationale", "IsOutsourced", "IsBusinessProcessOutsourcing", "IsKnowledgeProcessOutsourcing",
       "IsVitalExpertiseClassedNonCore")),
    ("q11-sourcing-what-how-split", SOURCING,
     "Where we keep the specification but a provider holds the method, can we still build what we design, or have we hollowed out?",
     "A firm that keeps its brand and designs but not the know-how to make its products depends on its provider for its own business.",
     F("SourcingFunctions", "DeliversOwnProduct", "SpecificationHolder", "MethodHolder", "IsWhatHowSplit", "ClaimsHowWithoutDoing",
       "SpecificationAuditCount", "SpecificationShortfallCount", "MethodShortfallCount", "ProviderIpDocumentationCount",
       "DesignsWhatItCannotBuild")
     + F("Organizations", "ProductDeliveryFunctionCount", "ProviderHeldDeliveryMethodCount", "IsHollowedOutFirm")),
    ("aq-pkm3-q07", SOURCING,
     "For each of our processes, who holds the knowledge of how it is really performed: us, or an outside provider?",
     "Sourcing decisions are made about cost; nobody records that the how-knowledge moved with the work.",
     F("SourcingFunctions", "IsMethodKnowledgeHeldOutside")),
    ("q11-sourcing-provider-knowledge-terms", SOURCING,
     "For each provider we rely on for knowledge, who owns the documentation, can we reach the know-how, and have we planned how it comes back to us?",
     "A provider whose know-how is its differentiator has every reason to keep it; only the contract can move it back.",
     F("ProviderEngagements", "ClientOrganization", "Provider", "SourcingFunction", "StartedAt", "TermMonths", "Status",
       "DocumentationOwnership", "KnowledgeDutyTerms", "ProviderTreatsKnowHowAsDifferentiator", "HasKnowledgeAccessClause",
       "KnowledgeReturnPlan", "IsActive", "ReliedDependencyCount", "IsUnplannedKnowledgeReturn", "IsKnowledgeAccessUnsecured")),
    ("q11-sourcing-knowledge-flow", SOURCING,
     "Does each provider relationship produce explicit knowledge deliverables, moving in both directions, over a term long enough to build knowledge together?",
     "Knowledge that is not a deliverable does not move; learning that runs one way is extraction, not partnership.",
     F("KnowledgeDeliverables", "ProviderEngagement", "Direction", "Title", "DueAt", "DeliveredAt", "IsDelivered")
     + F("ProviderEngagements", "RequiredDeliverableCount", "ToClientDeliveredCount", "ToProviderDeliveredCount",
         "JointDeliverableCount", "LacksKnowledgeDeliverables", "IsOneWayLearning", "IsShortTermWithoutJointKnowledge")),
    ("aq-pkm3-q12", SOURCING,
     "Does this provider relationship oblige explicit knowledge deliverables, and knowledge flowing back to us?",
     "Renewal is the moment to add the obligation; it has to be visible per relationship to be negotiated.",
     F("ProviderEngagements", "ToClientRequiredCount", "ObligesKnowledgeFlowBack")),
    # ------------------------------------------------------------------ the knowledge audit
    ("aq-pkm3-q02", KE,
     "What procedural knowledge do we hold versus need, and where are the gaps and the dependencies on providers?",
     "Capture work has to start from the audit's shortfalls, not from whatever documentation happens to exist.",
     F("KnowledgeAuditItems", "KnowledgeAudit", "SourcingFunction", "KnowledgeArea", "KnowledgeKind", "NeededLevel",
       "HeldInternalLevel", "ProviderHoldingKnowledge", "ProviderHeldLevel", "ClientOrganization", "HasInternalShortfall",
       "IsKnowledgeDependency", "IsCoverageGap")
     + F("SourcingFunctions", "AuditItemCount", "DependencyCount", "CoverageGapCount")),
    ("q11-ke-audit-completeness", KE,
     "Which functions we outsource or depend on were never audited for held against needed knowledge, and which findings did nobody name as a knowledge gap?",
     "An unaudited dependency is invisible, and a finding that is not named is not owned by anybody.",
     F("SourcingFunctions", "IsUnauditedFunction") + F("KnowledgeAuditItems", "NamedKnowledgeGap", "IsUnnamedFinding")),
    ("q11-ke-single-team-silos", KE,
     "Which of the knowledge we do hold sits with a single team?",
     "Knowledge held by one team is hoarded by default, even when nobody intends it.",
     F("KnowledgeAuditItems", "InternalHoldingTeamCount", "IsSingleTeamSilo")),
    ("q11-authority-deficit-framing", AUTH,
     "Did our audits call what they found a process knowledge deficit, or file it as a cost and efficiency problem?",
     "A deficit filed as a cost problem gets a cost answer: another provider, not knowledge coming back.",
     F("KnowledgeAudits", "Organization", "Title", "ConductedAt", "ConductedByAgent", "ProblemFraming", "FindingCount",
       "TreatsDeficitAsCostProblem")),
    ("q11-authority-knowledge-staff", AUTH,
     "Which organizations have audit findings but employ no knowledge engineer, information architect or ontologist to capture, organize and encode that knowledge?",
     "Findings without the people to act on them stay findings.",
     F("KnowledgeWorkforcePositions", "Organization", "Discipline", "Role", "Status", "OpenedAt", "FilledByAgent")
     + F("Organizations", "AuditFindingCount", "FilledKnowledgePositionCount", "HasKnowledgeFindingsWithoutKnowledgeStaff")),
    ("aq-pkm3-q03", AUTH,
     "Which processes are strategically vital and expertise-heavy, and which of those have we outsourced?",
     "Those are the processes whose knowledge the organization cannot afford to lose track of.",
     F("SourcingFunctions", "IsStrategicallyVital", "IsVitalExpertiseProcess", "IsOutsourcedVitalExpertiseProcess")),
    ("q11-authority-capture-priorities", AUTH,
     "Among vital, expertise-heavy processes that are outsourced or have coverage gaps, which have no deliberate effort to capture their knowledge?",
     "Capture capacity is scarce; it must go first where losing the knowledge would hurt most.",
     F("KnowledgeCaptureInitiatives", "SourcingFunction", "KnowledgeMethod", "LeadAgent", "StartedAt", "Status")
     + F("SourcingFunctions", "CaptureInitiativeCount", "IsUncapturedPriorityProcess")),
    ("q11-steward-retention-scope", STEWARD,
     "Which retention rules destroy engineering records while their knowledge is still in use, and was it a compliance-only, legally sponsored programme that set them?",
     "Retention set for legal exposure deletes the design history the next engineer needs.",
     F("CorporateGovernancePrograms", "Organization", "Label", "SponsorDiscipline", "LaunchedAt", "CoversCompliance",
       "CoversDataQuality", "CoversInformationManagement", "CoversKnowledgeManagement", "IsComplianceOnly")
     + F("RecordsRetentionPolicies", "GovernanceProgram", "RecordClass", "RetentionDriver", "RetentionYears",
         "KnowledgeUsefulLifeYears", "ProgramSponsorDiscipline", "IsLegalLedKnowledgeDestruction")),
    # ------------------------------------------------------------------ the AI system registry
    ("q11-ke-registry-feed", KE,
     "Is every AI model version the registry reports running in production an individual in our graph, with its deployments and evaluations?",
     "An AI system that runs without being in the graph cannot be found by any accountability or impact query.",
     F("AiRegistryModelVersions", "RegistrySystem", "DcIdentifier", "DcTitle", "DcCreator", "DcDate", "DcHasVersion",
       "DcDescription", "FeedReceivedAt", "GraphIndividualCount", "LiveProductionDeploymentCount", "IsLiveButUnregisteredInGraph")
     + F("AiModelDeployments", "ModelVersion", "Environment", "DeployedAt", "RetiredAt", "EvaluationContext", "AsOfInstant",
         "IsLiveInProduction")
     + F("AiModelEvaluations", "ModelVersion", "EvaluatedAt", "EvaluationSuite", "Metric", "Score", "PassThreshold", "Passed")),
    ("q11-ke-registry-populates-agents", KE,
     "Were our AI agent individuals filled from the registry through its Dublin Core fields, or typed in by hand?",
     "A hand-typed version drifts from the registry, and every query about that agent then answers for a version that does not exist.",
     F("Agents", "RegistryVersionMatchCount", "IsAiAgentNotFilledFromRegistry")),
    ("q11-release-registry-context", RELEASE,
     "Which live AI deployments are only a registry row, with no role, step or artifact connecting them to our workflows?",
     "A deployment record says a model is running; only its links say what it is doing and to whom.",
     F("AiModelDeployments", "AgentIdentifier", "AssignmentLinkCount", "ArtifactLinkCount", "IsIsolatedRegistryFact")),
    ("aq-ont4-q21", RELEASE,
     "Which artifacts has this AI agent produced?",
     "Every risk report I approve on was produced by some classifier version; I need to know which.",
     F("ExecutionEntities", "GeneratingAgent", "AttributedToAgent") + F("Agents", "AttributedArtifactCount", "HasProducedArtifacts")),
    ("aq-ont4-q22", RELEASE,
     "Which downstream steps take this agent's artifacts as inputs?",
     "Those are the steps whose inputs change when the agent does.",
     F("StepVariables", "SourceStepAgent", "SourceStepAgentKind", "IsInputFromAiArtifact")
     + F("Steps", "AiArtifactInputCount", "ConsumesAiAgentArtifact")),
    ("aq-ont4-q23", VP,
     "Which roles and agents are responsible for the downstream steps that consume this agent's artifacts, and is any of them held by nobody?",
     "An upgrade has to be announced to the people who act on its output; a vacant role there hears nothing.",
     F("StepVariables", "ConsumerRole", "StepAccountableAgent", "AiArtifactConsumerHasNoAccountableAgent")),
    ("aq-ont4-q24", VP,
     "Which workflows contain the steps affected by an agent change?",
     "Workflow owners sign off on changes to their workflows, so the change record must name every one.",
     F("StepVariables", "ConsumerWorkflow") + F("ProcedureVersions", "AiArtifactConsumingInputCount", "ContainsStepsAffectedByAiAgentChange")),
    ("aq-ont4-q04", VP,
     "If this agent moves to a newer model version, what else is affected, all the way downstream?",
     "A risk report feeds the approval, the approval feeds the rollout, the rollout feeds verification: the impact is transitive.",
     F("StepVariables", "StepAgentKind", "AiBlastRadiusPath")
     + F("ArtifactHandoffs", "StepVariable", "FromStep", "ToStep", "DeclaredSourceStep", "DeclaredConsumerStep",
         "DisagreesWithDeclaredVariable", "HandoffClosure")
     + F("Steps", "DownstreamArtifactStepCount")
     + F("Agents", "DownstreamOfHeldStepsCount", "ArtifactBlastRadiusStepCount", "HasArtifactBlastRadius")),
    ("q11-vp-upgrade-assessment", VP,
     "Did the impact assessment for this agent upgrade list everything a traversal of the graph finds?",
     "A hand-written change ticket lists the step the engineer remembers, not the ones two hand-offs away.",
     F("AgentUpgradeAssessments", "CurrentAgent", "CandidateAgent", "AssessedAt", "AssessmentMethod", "AssessedByAgent",
       "ListedAffectedStepCount", "ListedAffectedStepsNote", "AttributedArtifactCount", "TraversedDownstreamStepCount",
       "MissedTraversedImpact")),
    ("aq-ont4-q27", VP,
     "Which human is accountable for this AI agent?",
     "When a classifier misjudges a change, somebody must answer for it, and it cannot be the pipeline.",
     F("AiAgentAccountabilities", "AiAgent", "AccountableAgent", "ValidFrom", "ValidTo", "EvaluationContext", "AsOfInstant",
       "IsCurrent", "AccountableAgentKind", "IsAccountableToNonPerson", "IsCurrentHumanAccountability")
     + F("Agents", "CurrentAccountableHumanCount", "IsAiAgentWithoutAccountableHuman")),
    # ------------------------------------------------------------------ ground truth
    ("q11-vp-assignment-update-governance", VP,
     "When someone leaves a role or an agent is swapped, does governance name who must trigger the update, and was the update completed within its service level?",
     "Once the pipeline routes from assignments, an update nobody owns is an outage waiting for the next run.",
     F("AssignmentUpdatePolicies", "Label", "TriggerOwnerRole", "UpdateSlaHours", "ModelDrivesRouting", "AdoptedAt")
     + F("RoleAssignmentUpdateTasks", "Role", "GoverningPolicy", "TriggerEvent", "Reason", "TriggerOccurredAt", "TriggeredAt",
         "TriggeredByAgent", "CompletedAt", "EvaluationContext", "AsOfInstant", "PolicyTriggerOwnerRole", "TriggerOwnerCoverCount",
         "LacksNamedTriggerOwner", "PolicySlaHours", "ElapsedMinutes", "ExceededUpdateSla")),
    ("q11-release-one-assignment-change", RELEASE,
     "When the work of a role changed hands, did only the assignment change, or was the work moved to a new role so the steps had to be re-pointed?",
     "Re-pointing steps to change a person is a workflow change nobody reviewed as one.",
     F("RoleAssignmentUpdateTasks", "EndingAssignment", "ReplacementAssignment", "EndingRole", "ReplacementRole",
       "ChangedRoleInsteadOfAssignment")),
    ("q11-release-before-next-run", RELEASE,
     "Was each departure recorded before the next deployment that needed that role, and did a stale assignment actually break a run?",
     "A stale assignment that no run has read is an accuracy problem; one a run routed from is an operational failure.",
     F("RoleAssignmentUpdateTasks", "DependentExecution", "DependentRunVersion", "DependentRunStartedAt", "DependentRunRoleStepCount",
       "MissedNextDependentRun", "FailedNoticeCount", "StaleAssignmentBrokeRouting")),
    ("aq-ont4-q06", RELEASE,
     "To whom does the approval notice for a deployment go at present?",
     "If the answer is not read from the current assignments, the notice goes to whoever a list last said.",
     F("Roles", "ApprovalStepCount") + F("RoleAssignments", "RoleApprovalStepCount", "ReceivesApprovalNoticesNow")),
    ("q11-release-notice-routing", RELEASE,
     "Did each approval and verification notice reach someone who held the step's role when it was sent, and did any routing bypass the assignments in the model?",
     "A notice that reaches a departed manager, or nobody, is how a release ships on a verbal go-ahead.",
     F("AssignmentRoutedNotices", "ProcedureExecution", "NoticeStep", "NoticeKind", "SentAt", "RoutingSource", "RoutedToAgent",
       "NoticeRole", "RecipientRoleKey", "RecipientPairAssignmentCount", "RecipientValidFrom", "RecipientLatestValidTo",
       "RecipientOpenEndedCount", "RecipientHeldRoleWhenSent", "ReachedWrongPersonOrNobody", "RoutedAroundModel")
     + F("RoleAssignments", "AgentRolePairKey", "IsOpenEnded")),
]


def _rows(cols, *values, iri_=None):
    out = []
    for v in values:
        row = dict(zip(cols, v))
        if iri_ is not None:
            row["SemanticTypeIri"] = iri_
        out.append(row)
    return out


_ra_cols = ["RoleAssignmentId", "Role", "Agent", "ValidFrom", "ValidTo", "Reason", "Status", "EvaluationContext",
            "SupersedesAssignment", "ApprovingAuthorityRole", "ForProcedureVersion"]

_HANDOFFS = [  # (id, input variable, from step, to step)
    ("ah-loto03-workorder", "var-loto03-in-workorder", "loto-01", "loto-03"),
    ("ah-loto05-isolation", "var-loto05-in-isolation", "loto-04", "loto-05"),
    ("ah-loto06-isolation", "var-loto06-in-isolation", "loto-04", "loto-06"),
    ("ah-loto07-zeroenergy", "var-loto07-in-zeroenergy", "loto-06", "loto-07"),
    ("ah-loto08-maintlog", "var-loto08-in-maintlog", "loto-07", "loto-08"),
    ("ah-deploy02-candidate", "var-deploy02-in-candidate", "deploy-01", "deploy-02"),
    ("ah-deploy03-risk", "var-deploy03-in-risk", "deploy-02", "deploy-03"),
    ("ah-deploy04-approval", "var-deploy04-in-approval", "deploy-03", "deploy-04"),
    ("ah-deploy04-candidate", "var-deploy04-in-candidate", "deploy-01", "deploy-04"),
    ("ah-deploy05-deployment", "var-deploy05-in-deployment", "deploy-04", "deploy-05"),
    ("ah-deploy05-risk", "var-deploy05-in-risk", "deploy-02", "deploy-05"),
    # Recorded from a stale runbook diagram: says verification is fed by the approval step, but the
    # variable declares the rollout step as its source.
    ("ah-deploy05-deployment-misrecorded", "var-deploy05-in-deployment", "deploy-03", "deploy-05"),
]

ROWS = {
    "ArtifactHandoffs": [
        {"ArtifactHandoffId": i, "StepVariable": v, "FromStep": f, "ToStep": t,
         "SemanticTypeIri": "urn:effortless:pko-extension#ArtifactHandoff"} for i, v, f, t in _HANDOFFS],
    "Organizations": _rows(["OrganizationId", "DisplayName", "OrganizationType", "ExternalIdentifier"],
                           ("acme-home-brands", "ACME Home Brands", "Company", "org-007"),
                           ("meridian-contract-mfg", "Meridian Contract Manufacturing (fictional)", "ServiceProvider", "prv-201"),
                           ("harborline-services", "Harborline Business Services (fictional)", "ServiceProvider", "prv-202"),
                           ("quillstone-research", "Quillstone Regulatory Research (fictional)", "ServiceProvider", "prv-203"),
                           ("lattice-analytics", "Lattice Analytics Partners (fictional)", "ServiceProvider", "prv-204"),
                           ("northstar-model-ops", "Northstar Model Operations (fictional)", "ServiceProvider", "prv-205"),
                           iri_=f"{PROV}Organization"),
    "RoleAssignments": _rows(_ra_cols,
                             ("ra-sourcing-claire", SOURCING, "claire-dubois", "2023-04-01T00:00:00-05:00", None,
                              "Strategic sourcing manager", "Active", EV, None, None, None),
                             ("ra-release-dmitri", RELEASE, "dmitri-volkov", "2025-06-01T00:00:00-05:00", "2026-07-03T17:00:00-05:00",
                              "Hotfix release manager on the on-call rota; left acme-engineering", "Ended", EV, None, VP, "deploy-v3.2.0"),
                             ("ra-sre-healthbot", "site-reliability-engineer", "health-check-ai-1-2-0", "2025-03-01T00:00:00-06:00",
                              "2025-12-31T23:59:59-06:00", "Automated post-deployment health verification", "Superseded", EV, None, VP, None),
                             ("ra-sre-leo", "site-reliability-engineer", "leo-marchetti", "2026-01-01T00:00:00-06:00", "2026-06-30T17:00:00-05:00",
                              "Health verification moved from the AI health checker to a human SRE after it passed two degraded rollouts; left acme-engineering",
                              "Ended", EV, "ra-sre-healthbot", VP, "deploy-v3.2.0"),
                             ("ra-deploy-kwame", "deployment-automation", "kwame-asante", "2025-02-01T00:00:00-06:00", "2026-07-10T17:00:00-05:00",
                              "Manual rollback operator on the rollout rota; left acme-engineering", "Ended", EV, None, None, "deploy-v3.2.0"),
                             ("ra-build-hector", "build-release-engineer", "hector-ruiz", "2022-03-01T00:00:00-06:00", "2024-12-31T17:00:00-06:00",
                              "Built and rolled out release candidates by hand", "Superseded", EV, None, None, None),
                             iri_="http://purl.org/spar/pro/RoleInTime"),
    "SourcingFunctions": _rows(
        ["SourcingFunctionId", "Label", "ClientOrganization", "Procedure", "SourcingClass", "WorkNature", "IsStrategicallyVital",
         "DeliversOwnProduct", "ExecutingOrganization", "SpecificationHolder", "MethodHolder", "SourcedSince", "SourcingRationale"],
        ("sf-hb-assembly", "Countertop appliance assembly and process engineering", "acme-home-brands", None, "SentOutExecution",
         "ExpertiseHeavy", True, True, "meridian-contract-mfg", "acme-home-brands", "meridian-contract-mfg",
         "2014-03-01T00:00:00-06:00", "CoreCompetencyFocus"),
        ("sf-hb-product-spec", "Appliance product specification", "acme-home-brands", None, "RetainedCore", "ExpertiseHeavy",
         True, False, "acme-home-brands", "acme-home-brands", "acme-home-brands", "2004-01-01T00:00:00-06:00", "CoreCompetencyFocus"),
        ("sf-hb-brand-customers", "Brand, retail and customer relationships", "acme-home-brands", None, "RetainedCore", "Transactional",
         True, False, "acme-home-brands", "acme-home-brands", "acme-home-brands", "2004-01-01T00:00:00-06:00", "CoreCompetencyFocus"),
        ("sf-hb-invoice-processing", "Accounts payable invoice processing", "acme-home-brands", None, "SentOutExecution", "Transactional",
         False, False, "harborline-services", "acme-home-brands", "harborline-services", "2019-01-01T00:00:00-06:00", "CostReduction"),
        ("sf-hb-safety-research", "Product safety regulatory research", "acme-home-brands", None, "SentOutExecution", "ExpertiseHeavy",
         True, False, "quillstone-research", "acme-home-brands", "quillstone-research", "2023-01-01T00:00:00-06:00", "CoreCompetencyFocus"),
        ("sf-hb-heating-rd", "Next-generation heating element research and development", "acme-home-brands", None, "SentOutExecution",
         "ExpertiseHeavy", True, False, "acme-home-brands", "acme-home-brands", "acme-home-brands", "2016-06-01T00:00:00-05:00",
         "CoreCompetencyFocus"),
        ("sf-corp-deal-analysis", "Acquisition financial due-diligence analysis", "acme-corp", None, "SentOutExecution", "ExpertiseHeavy",
         True, False, "lattice-analytics", "acme-corp", "lattice-analytics", "2024-02-01T00:00:00-06:00", "CoreCompetencyFocus"),
        ("sf-plant-press-overhaul", "Hydraulic press overhaul", "acme-plant", None, "SentOutExecution", "ExpertiseHeavy", True, False,
         "baxter-hydraulics", "acme-plant", "baxter-hydraulics", "2022-06-01T00:00:00-05:00", "Capability"),
        ("sf-plant-lockout", "Lockout/tagout and line maintenance", "acme-plant", "lockout-tagout", "RetainedCore", "ExpertiseHeavy",
         True, False, "acme-plant", "acme-plant", "acme-plant", "1994-06-01T00:00:00-05:00", "Capability"),
        ("sf-plant-production", "Appliance production line operation", "acme-plant", None, "RetainedCore", "ExpertiseHeavy", True, True,
         "acme-plant", "acme-plant", "acme-plant", "1994-06-01T00:00:00-05:00", "Capability"),
        ("sf-eng-classifier-training", "Change-risk model training and evaluation", "acme-engineering", None, "RetainedCore",
         "ExpertiseHeavy", True, False, "northstar-model-ops", "acme-engineering", "acme-engineering", "2025-08-01T00:00:00-05:00",
         "CostReduction"),
        ("sf-eng-deployment", "Production deployment and release approval", "acme-engineering", "production-deployment", "RetainedCore",
         "ExpertiseHeavy", True, True, "acme-engineering", "acme-engineering", "acme-engineering", "2025-01-01T00:00:00-06:00", "Capability"),
        iri_=f"{EXT}SourcingFunction"),
    "KnowledgeGaps": [
        {"KnowledgeGapId": "gap-press-overhaul-dependency", "ProcedureVersion": None, "Step": None,
         "Statement": "Only Baxter Hydraulics technicians can re-seal and re-pressurize the press 7 accumulator; the plant depends on them for it.",
         "Severity": "Medium", "BlockingKind": "NonBlocking", "Status": "Open", "OwnerRole": KE,
         "IdentifiedAt": "2026-05-20T09:00:00-05:00", "ResolutionPlan": "Shadow the next two Baxter overhauls and write the re-pressurization procedure.",
         "EvaluationContext": EV, "SemanticTypeIri": f"{EXT}KnowledgeGap"},
        {"KnowledgeGapId": "gap-mixer2-twin-drive-isolation", "ProcedureVersion": "loto-v2.0.0", "Step": None,
         "Statement": "Nobody at the plant or at any provider holds a verified isolation sequence for mixer 2's twin-drive conversion.",
         "Severity": "Medium", "BlockingKind": "NonBlocking", "Status": "Open", "OwnerRole": KE,
         "IdentifiedAt": "2026-05-20T09:00:00-05:00", "ResolutionPlan": "Critical-incident interviews with the technicians who performed the conversion.",
         "EvaluationContext": EV, "SemanticTypeIri": f"{EXT}KnowledgeGap"},
        {"KnowledgeGapId": "gap-classifier-training-dependency", "ProcedureVersion": None, "Step": None,
         "Statement": "Retraining and evaluating the change-risk classifier can only be done by Northstar Model Operations.",
         "Severity": "Medium", "BlockingKind": "NonBlocking", "Status": "Open", "OwnerRole": VP,
         "IdentifiedAt": "2026-06-10T09:00:00-05:00", "ResolutionPlan": "",
         "EvaluationContext": EV, "SemanticTypeIri": f"{EXT}KnowledgeGap"},
    ],
    "KnowledgeAudits": _rows(["KnowledgeAuditId", "Organization", "Title", "ConductedAt", "ConductedByAgent", "ProblemFraming"],
                             ("audit-hb-2025", "acme-home-brands", "Supplier cost and efficiency review 2025", "2025-09-15T09:00:00-05:00",
                              "claire-dubois", "CostEfficiency"),
                             ("audit-plant-2026", "acme-plant", "Plant process knowledge audit 2026", "2026-05-20T09:00:00-05:00",
                              "sam-adeyemi", "KnowledgeDeficit"),
                             ("audit-eng-2026", "acme-engineering", "Release and model operations knowledge audit", "2026-06-10T09:00:00-05:00",
                              "sam-adeyemi", "KnowledgeDeficit"),
                             ("audit-corp-2024", "acme-corp", "Shared services cost review 2024", "2024-11-01T09:00:00-05:00",
                              "priya-raman", "CostEfficiency"),
                             iri_=f"{EXT}KnowledgeAudit"),
    "KnowledgeAuditItems": _rows(
        ["KnowledgeAuditItemId", "KnowledgeAudit", "SourcingFunction", "KnowledgeArea", "KnowledgeKind", "NeededLevel",
         "HeldInternalLevel", "ProviderHoldingKnowledge", "ProviderHeldLevel", "InternalHoldingTeamCount", "NamedKnowledgeGap"],
        ("kai-hb-assembly-spec", "audit-hb-2025", "sf-hb-assembly", "Product specifications and tolerances for the countertop range",
         "Specification", 3, 3, None, 0, 2, None),
        ("kai-hb-assembly-method", "audit-hb-2025", "sf-hb-assembly", "Assembly sequencing, fixturing and heating-element brazing",
         "Method", 3, 0, "meridian-contract-mfg", 3, 0, None),
        ("kai-hb-safety-method", "audit-hb-2025", "sf-hb-safety-research", "Interpreting product safety standards for new heating designs",
         "Method", 2, 0, "quillstone-research", 2, 0, None),
        ("kai-hb-spec-spec", "audit-hb-2025", "sf-hb-product-spec", "Writing appliance product specifications", "Specification", 3, 3,
         None, 0, 2, None),
        ("kai-hb-customers", "audit-hb-2025", "sf-hb-brand-customers", "Retail partner and customer service practice", "Method", 2, 3,
         None, 0, 3, None),
        ("kai-plant-press-method", "audit-plant-2026", "sf-plant-press-overhaul", "Accumulator re-sealing and re-pressurization on press 7",
         "Method", 3, 1, "baxter-hydraulics", 3, 0, "gap-press-overhaul-dependency"),
        ("kai-plant-lockout-method", "audit-plant-2026", "sf-plant-lockout", "Hydraulic and pneumatic isolation on the standard lines",
         "Method", 3, 3, None, 0, 1, None),
        ("kai-plant-mixer2-method", "audit-plant-2026", "sf-plant-lockout", "Isolation of mixer 2's twin-drive conversion", "Method", 3, 0,
         None, 0, 0, "gap-mixer2-twin-drive-isolation"),
        ("kai-plant-production", "audit-plant-2026", "sf-plant-production", "Line setup and changeover", "Method", 3, 3, None, 0, 3, None),
        ("kai-eng-training-method", "audit-eng-2026", "sf-eng-classifier-training", "Retraining and evaluating the change-risk classifier",
         "Method", 3, 1, "northstar-model-ops", 3, 0, "gap-classifier-training-dependency"),
        ("kai-eng-deploy-method", "audit-eng-2026", "sf-eng-deployment", "Release gating and rollback judgment", "Method", 3, 3, None, 0, 2, None),
        ("kai-corp-deal-method", "audit-corp-2024", "sf-corp-deal-analysis", "Acquisition valuation and diligence modeling", "Method", 2, 2,
         "lattice-analytics", 3, 2, None),
        iri_=f"{EXT}KnowledgeAuditItem"),
    "KnowledgeCaptureInitiatives": _rows(
        ["KnowledgeCaptureInitiativeId", "SourcingFunction", "KnowledgeMethod", "LeadAgent", "StartedAt", "Status"],
        ("kci-plant-press-shadowing", "sf-plant-press-overhaul", "Shadowing", "sam-adeyemi", "2026-06-01T09:00:00-05:00", "Active"),
        ("kci-plant-mixer2-incidents", "sf-plant-lockout", "CriticalIncidentTechnique", "sam-adeyemi", "2026-06-15T09:00:00-05:00", "Active"),
        ("kci-corp-deal-pairing", "sf-corp-deal-analysis", "PractitionerInterview", "priya-raman", "2024-03-01T09:00:00-06:00", "Completed"),
        iri_=f"{EXT}KnowledgeCaptureInitiative"),
    "KnowledgeWorkforcePositions": _rows(
        ["KnowledgeWorkforcePositionId", "Organization", "Discipline", "Role", "Status", "OpenedAt", "FilledByAgent"],
        ("kwp-plant-ke", "acme-plant", "KnowledgeEngineer", KE, "Filled", "2025-06-01T09:00:00-05:00", "sam-adeyemi"),
        ("kwp-eng-ontologist", "acme-engineering", "Ontologist", None, "Filled", "2026-01-15T09:00:00-06:00", "ines-moreau"),
        ("kwp-eng-ia", "acme-engineering", "InformationArchitect", None, "Open", "2026-06-15T09:00:00-05:00", None),
        ("kwp-hb-ke", "acme-home-brands", "KnowledgeEngineer", None, "NotBudgeted", "2025-10-01T09:00:00-05:00", None),
        iri_=f"{EXT}KnowledgeWorkforcePosition"),
    "ProviderEngagements": _rows(
        ["ProviderEngagementId", "ClientOrganization", "Provider", "SourcingFunction", "StartedAt", "TermMonths", "Status",
         "DocumentationOwnership", "KnowledgeDutyTerms", "ProviderTreatsKnowHowAsDifferentiator", "HasKnowledgeAccessClause",
         "KnowledgeReturnPlan"],
        ("pe-hb-meridian", "acme-home-brands", "meridian-contract-mfg", "sf-hb-assembly", "2024-03-01T00:00:00-06:00", 24, "Active",
         "ProviderIP", "", True, False, ""),
        ("pe-hb-quillstone", "acme-home-brands", "quillstone-research", "sf-hb-safety-research", "2026-01-01T00:00:00-06:00", 12, "Active",
         "ProviderIP", "", True, True, ""),
        ("pe-hb-harborline", "acme-home-brands", "harborline-services", "sf-hb-invoice-processing", "2025-01-01T00:00:00-06:00", 36, "Active",
         "ClientOwned", "Harborline documents every process change it makes to invoice handling.", False, True,
         "Process documentation is client-owned and handed over on exit."),
        ("pe-hb-harborline-2019", "acme-home-brands", "harborline-services", "sf-hb-invoice-processing", "2019-01-01T00:00:00-06:00", 72,
         "Ended", "ClientOwned", "", False, False, ""),
        ("pe-plant-baxter", "acme-plant", "baxter-hydraulics", "sf-plant-press-overhaul", "2022-06-01T00:00:00-05:00", 60, "Active",
         "Joint", "Baxter trains two plant technicians during every overhaul.", True, True,
         "Overhaul procedures handed to the plant each overhaul; full procedure set on contract end."),
        ("pe-eng-northstar", "acme-engineering", "northstar-model-ops", "sf-eng-classifier-training", "2025-08-01T00:00:00-05:00", 18,
         "Active", "ProviderIP", "", False, False, ""),
        ("pe-corp-lattice", "acme-corp", "lattice-analytics", "sf-corp-deal-analysis", "2024-02-01T00:00:00-06:00", 48, "Active",
         "ClientOwned", "Lattice analysts pair with acme-corp analysts on every deal.", False, True,
         "Valuation models and diligence memos transfer at each deal close."),
        iri_=f"{EXT}ProviderEngagement"),
    "KnowledgeDeliverables": _rows(
        ["KnowledgeDeliverableId", "ProviderEngagement", "Direction", "Title", "DueAt", "DeliveredAt"],
        ("kd-quillstone-digest", "pe-hb-quillstone", "ToClient", "Quarterly regulatory interpretation digest", "2026-04-01T00:00:00-05:00",
         "2026-04-03T00:00:00-05:00"),
        ("kd-harborline-changelog", "pe-hb-harborline", "ToClient", "Monthly invoice process change log", "2026-06-30T00:00:00-05:00",
         "2026-07-01T00:00:00-05:00"),
        ("kd-harborline-policy", "pe-hb-harborline", "ToProvider", "Payables policy updates", "2026-02-01T00:00:00-06:00",
         "2026-01-28T00:00:00-06:00"),
        ("kd-baxter-procedures", "pe-plant-baxter", "ToClient", "Press overhaul procedure pack", "2026-05-31T00:00:00-05:00",
         "2026-05-29T00:00:00-05:00"),
        ("kd-baxter-incidents", "pe-plant-baxter", "ToProvider", "Press 7 incident and gauge data", "2026-07-15T00:00:00-05:00",
         "2026-07-12T00:00:00-05:00"),
        ("kd-baxter-failure-catalog", "pe-plant-baxter", "Joint", "Shared hydraulic failure-mode catalog", "2026-07-01T00:00:00-05:00", None),
        ("kd-northstar-history", "pe-eng-northstar", "ToProvider", "Labelled change history export", "2025-09-01T00:00:00-05:00",
         "2025-08-28T00:00:00-05:00"),
        ("kd-lattice-models", "pe-corp-lattice", "ToClient", "Valuation model hand-over", "2025-06-30T00:00:00-05:00", "2025-06-30T00:00:00-05:00"),
        ("kd-lattice-context", "pe-corp-lattice", "ToProvider", "Integration history of prior acquisitions", "2024-03-01T00:00:00-06:00",
         "2024-03-01T00:00:00-06:00"),
        ("kd-lattice-playbook", "pe-corp-lattice", "Joint", "Joint diligence playbook", "2025-12-31T00:00:00-06:00", "2025-12-15T00:00:00-06:00"),
        iri_=f"{EXT}KnowledgeDeliverable"),
    "CorporateGovernancePrograms": _rows(
        ["CorporateGovernanceProgramId", "Organization", "Label", "SponsorDiscipline", "LaunchedAt", "CoversCompliance",
         "CoversDataQuality", "CoversInformationManagement", "CoversKnowledgeManagement"],
        ("gp-hb-engineering-records-2004", "acme-home-brands", "Engineering records and knowledge programme", "Engineering",
         "2004-05-01T00:00:00-05:00", True, True, True, True),
        ("gp-hb-compliance-2016", "acme-home-brands", "Enterprise compliance and records governance", "Legal",
         "2016-09-01T00:00:00-05:00", True, False, False, False),
        ("gp-plant-information-2021", "acme-plant", "Plant information and knowledge governance", "Engineering",
         "2021-03-01T00:00:00-06:00", True, False, True, True),
        iri_=f"{EXT}CorporateGovernanceProgram"),
    "RecordsRetentionPolicies": _rows(
        ["RecordsRetentionPolicyId", "GovernanceProgram", "RecordClass", "RetentionDriver", "RetentionYears", "KnowledgeUsefulLifeYears"],
        ("rrp-hb-design-history-2004", "gp-hb-engineering-records-2004", "Design history files", "KnowledgeValue", 25, 15),
        ("rrp-hb-design-history-2016", "gp-hb-compliance-2016", "Design history and engineering change records", "ComplianceRisk", 3, 15),
        ("rrp-hb-chat-2016", "gp-hb-compliance-2016", "Email and chat", "ComplianceRisk", 1, 1),
        ("rrp-plant-maintenance-logs", "gp-plant-information-2021", "Maintenance and lockout logs", "KnowledgeValue", 10, 10),
        iri_=f"{EXT}RecordsRetentionPolicy"),
    # ------------------------------------------------------------------ registry
    "AiRegistryModelVersions": _rows(
        ["AiRegistryModelVersionId", "RegistrySystem", "DcIdentifier", "DcTitle", "DcCreator", "DcDate", "DcHasVersion",
         "DcDescription", "FeedReceivedAt"],
        ("reg-risk-classifier-2.3.0", "acme-model-registry", "risk-classifier-2-3-0", "Change risk classifier",
         "Northstar Model Operations (fictional) for acme-engineering", "2025-02-20T00:00:00-06:00", "2.3.0",
         "Gradient-boosted classifier over change metadata.", "2025-02-20T12:00:00-06:00"),
        ("reg-risk-classifier-2.4.0", "acme-model-registry", "risk-classifier-2-4-0", "Change risk classifier",
         "Northstar Model Operations (fictional) for acme-engineering", "2025-10-20T00:00:00-05:00", "2.4.0",
         "Adds dependency-graph features.", "2025-10-20T12:00:00-05:00"),
        ("reg-risk-classifier-2.4.1", "acme-model-registry", "risk-classifier-2-4-1", "Change risk classifier",
         "Northstar Model Operations (fictional) for acme-engineering", "2026-01-06T00:00:00-06:00", "2.4.1",
         "Patch: recalibrated high-risk threshold.", "2026-01-06T12:00:00-06:00"),
        ("reg-risk-classifier-2.5.0-rc3", "acme-model-registry", "risk-classifier-2-5-0", "Change risk classifier",
         "Northstar Model Operations (fictional) for acme-engineering", "2026-07-01T00:00:00-05:00", "2.5.0-rc3",
         "Release candidate: adds rollback-history features.", "2026-07-01T12:00:00-05:00"),
        ("reg-health-check-1.2.0", "acme-model-registry", "health-check-ai-1-2-0", "Post-deployment health checker",
         "acme-engineering platform team", "2025-02-15T00:00:00-06:00", "1.2.0",
         "Reads health signals for thirty minutes after a rollout.", "2025-02-15T12:00:00-06:00"),
        ("reg-release-notes-1.1.0", "acme-model-registry", "release-notes-writer-1-1-0", "Release notes writer",
         "acme-engineering platform team", "2026-04-02T00:00:00-05:00", "1.1.0",
         "Drafts customer-facing release notes from merged changes.", "2026-04-02T12:00:00-05:00"),
        iri_=f"{EXT}AiRegistryModelVersion"),
    "AiModelDeployments": _rows(
        ["AiModelDeploymentId", "ModelVersion", "Environment", "DeployedAt", "RetiredAt", "EvaluationContext"],
        ("dep-risk-2.3.0-prod", "reg-risk-classifier-2.3.0", "Production", "2025-03-01T00:00:00-06:00", "2025-11-01T00:00:00-05:00", EV),
        ("dep-risk-2.4.0-prod", "reg-risk-classifier-2.4.0", "Production", "2025-11-01T00:00:00-05:00", "2026-01-10T00:00:00-06:00", EV),
        ("dep-risk-2.4.1-prod", "reg-risk-classifier-2.4.1", "Production", "2026-01-10T00:00:00-06:00", None, EV),
        ("dep-risk-2.5.0-staging", "reg-risk-classifier-2.5.0-rc3", "Staging", "2026-07-02T00:00:00-05:00", None, EV),
        ("dep-health-1.2.0-prod", "reg-health-check-1.2.0", "Production", "2025-03-01T00:00:00-06:00", "2025-12-31T23:59:59-06:00", EV),
        ("dep-release-notes-1.1.0-prod", "reg-release-notes-1.1.0", "Production", "2026-04-05T00:00:00-05:00", None, EV),
        iri_=f"{EXT}AiModelDeployment"),
    "AiModelEvaluations": _rows(
        ["AiModelEvaluationId", "ModelVersion", "EvaluatedAt", "EvaluationSuite", "Metric", "Score", "PassThreshold"],
        ("eval-risk-2.4.1-holdout", "reg-risk-classifier-2.4.1", "2026-01-07T00:00:00-06:00", "Change history holdout 2025", "HighRiskRecall", 0.91, 0.85),
        ("eval-risk-2.5.0-holdout", "reg-risk-classifier-2.5.0-rc3", "2026-07-08T00:00:00-05:00", "Change history holdout 2026", "HighRiskRecall", 0.94, 0.85),
        ("eval-health-1.2.0-replay", "reg-health-check-1.2.0", "2025-12-05T00:00:00-06:00", "Degraded rollout replay", "DegradationDetectionRate", 0.60, 0.95),
        iri_=f"{EXT}AiModelEvaluation"),
    "AiAgentAccountabilities": _rows(
        ["AiAgentAccountabilityId", "AiAgent", "AccountableAgent", "ValidFrom", "ValidTo", "EvaluationContext"],
        ("aaa-risk-240-omar", "risk-classifier-2-4-0", "omar-haddad", "2025-11-01T00:00:00-05:00", "2026-01-10T00:00:00-06:00", EV),
        ("aaa-risk-241-omar", "risk-classifier-2-4-1", "omar-haddad", "2026-01-10T00:00:00-06:00", None, EV),
        ("aaa-health-120-omar", "health-check-ai-1-2-0", "omar-haddad", "2025-03-01T00:00:00-06:00", "2025-12-31T23:59:59-06:00", EV),
        ("aaa-risk-250-pipeline", "risk-classifier-2-5-0", "deploy-pipeline", "2026-07-02T00:00:00-05:00", None, EV),
        iri_=f"{EXT}AiAgentAccountability"),
    "ExecutionEntities": _rows(["ExecutionEntityId", "StepExecution", "StepVariable", "Usage", "EntityLabel", "EntityUri"],
                               ("ee-dep0105-01-cand-gen", "se-dep0105-01", "var-deploy01-out-candidate", "Generated", "Build 2026.01.05-rc2",
                                "https://ci.example.com/builds/20260105"),
                               ("ee-dep0105-02-risk-gen", "se-dep0105-02", "var-deploy02-out-risk", "Generated", "Risk report low",
                                "https://ci.example.com/risk/20260105"),
                               ("ee-dep0714-04-deploy-gen", "se-dep0714-04", "var-deploy04-out-deployment", "Generated",
                                "Deployment record 2026.07.14", "https://ci.example.com/deployments/20260714"),
                               iri_=f"{PROV}Entity"),
    "AgentUpgradeAssessments": _rows(
        ["AgentUpgradeAssessmentId", "CurrentAgent", "CandidateAgent", "AssessedAt", "AssessmentMethod", "AssessedByAgent",
         "ListedAffectedStepCount", "ListedAffectedStepsNote"],
        ("upg-risk-241-250-ticket", "risk-classifier-2-4-1", "risk-classifier-2-5-0", "2026-07-10T09:00:00-05:00", "ChangeTicket",
         "grace-holloway", 1, "Release approval gate (deploy-03) reads the risk class."),
        ("upg-risk-241-250-graph", "risk-classifier-2-4-1", "risk-classifier-2-5-0", "2026-07-17T09:00:00-05:00", "GraphTraversal",
         "ines-moreau", 3, "deploy-03, deploy-04 and deploy-05, found by traversing the artifact flow from the classifier."),
        iri_=f"{EXT}AgentUpgradeAssessment"),
    # ------------------------------------------------------------------ ground truth
    "AssignmentUpdatePolicies": _rows(
        ["AssignmentUpdatePolicyId", "Label", "TriggerOwnerRole", "UpdateSlaHours", "ModelDrivesRouting", "AdoptedAt"],
        ("aup-release-approvers", "Release approval roles", VP, 24, True, "2025-05-01T00:00:00-05:00"),
        ("aup-ai-agents", "AI agent role fills", VP, 72, True, "2025-05-01T00:00:00-05:00"),
        ("aup-eng-operations", "Engineering operations rotas (SRE, rollout, build)", None, 0, True, "2024-11-01T00:00:00-05:00"),
        iri_=f"{EXT}AssignmentUpdatePolicy"),
    "RoleAssignmentUpdateTasks": _rows(
        ["RoleAssignmentUpdateTaskId", "Role", "GoverningPolicy", "TriggerEvent", "Reason", "TriggerOccurredAt", "TriggeredAt",
         "TriggeredByAgent", "CompletedAt", "EndingAssignment", "ReplacementAssignment", "DependentExecution", "EvaluationContext"],
        ("rau-risk-240-to-241", "change-risk-classifier", "aup-ai-agents", "ModelUpgrade",
         "The registry published 2.4.1 with a recalibrated high-risk threshold; the classifier role moves to it.",
         "2026-01-08T09:00:00-06:00", "2026-01-08T10:00:00-06:00", "omar-haddad", "2026-01-10T00:00:00-06:00",
         "ra-risk-240", "ra-risk-241", "exec-deploy-2026-03-01", EV),
        ("rau-sre-ai-to-human", "site-reliability-engineer", "aup-eng-operations", "AiToHumanHandover",
         "Health Check AI 1.2.0 passed two degraded rollouts (2025-11-18, 2025-12-02) and scored 0.60 on the degraded rollout replay; "
         "post-deployment health verification moves to a human SRE.",
         "2025-12-10T09:00:00-06:00", "2025-12-10T11:00:00-06:00", "omar-haddad", "2026-01-01T00:00:00-06:00",
         "ra-sre-healthbot", "ra-sre-leo", "exec-deploy-2026-01-05", EV),
        ("rau-release-dmitri-departure", RELEASE, "aup-release-approvers", "Departure",
         "Dmitri Volkov left acme-engineering; hotfix release approvals had to move to the remaining release manager.",
         "2026-07-03T17:00:00-05:00", "2026-07-15T09:00:00-05:00", "omar-haddad", "2026-07-16T12:00:00-05:00",
         "ra-release-dmitri", None, "exec-deploy-2026-07-14", EV),
        ("rau-sre-leo-departure", "site-reliability-engineer", "aup-eng-operations", "Departure",
         "Leo Marchetti left acme-engineering; no successor SRE has been named.",
         "2026-06-30T17:00:00-05:00", None, None, None, "ra-sre-leo", None, "exec-deploy-2026-07-14", EV),
        ("rau-deploy-kwame-departure", "deployment-automation", "aup-eng-operations", "Departure",
         "Kwame Asante left the rollout rota; the pipeline continues to roll out alone.",
         "2026-07-10T17:00:00-05:00", "2026-07-17T09:00:00-05:00", "grace-holloway", "2026-07-18T10:00:00-05:00",
         "ra-deploy-kwame", None, "exec-deploy-2026-07-14", EV),
        ("rau-build-to-pipeline", "build-release-engineer", "aup-eng-operations", "HumanToAutomationHandover",
         "Build and rollout moved from a human build engineer to the CI pipeline by creating the Deployment Automation Operator role "
         "and re-pointing the build and rollout steps to it.",
         "2024-12-01T09:00:00-06:00", "2024-12-01T09:00:00-06:00", "omar-haddad", "2025-01-01T00:00:00-06:00",
         "ra-build-hector", "ra-deploy-pipeline", None, EV),
        iri_=f"{EXT}RoleAssignmentUpdateTask"),
    "AssignmentRoutedNotices": _rows(
        ["AssignmentRoutedNoticeId", "ProcedureExecution", "NoticeStep", "NoticeKind", "SentAt", "RoutingSource", "RoutedToAgent"],
        ("arn-dep0105-03", "exec-deploy-2026-01-05", "deploy-03", "ReleaseApproval", "2026-01-05T10:45:00-06:00", "OpsSpreadsheet", "grace-holloway"),
        ("arn-dep0105-05", "exec-deploy-2026-01-05", "deploy-05", "HealthVerification", "2026-01-05T11:30:00-06:00", "RoleAssignments", "leo-marchetti"),
        ("arn-dep0301-03", "exec-deploy-2026-03-01", "deploy-03", "ReleaseApproval", "2026-03-01T10:45:00-06:00", "RoleAssignments", "grace-holloway"),
        ("arn-dep0301-05", "exec-deploy-2026-03-01", "deploy-05", "HealthVerification", "2026-03-01T11:30:00-06:00", "OpsSpreadsheet", "omar-haddad"),
        ("arn-dep0714-03", "exec-deploy-2026-07-14", "deploy-03", "ReleaseApproval", "2026-07-14T16:05:00-05:00", "RoleAssignments", "dmitri-volkov"),
        ("arn-dep0714-05", "exec-deploy-2026-07-14", "deploy-05", "HealthVerification", "2026-07-14T16:35:00-05:00", "RoleAssignments", None),
        iri_=f"{EXT}AssignmentRoutedNotice"),
}

_M = [  # (source path, kind, iri, relation, profile)
    ("AiRegistryModelVersions.DcIdentifier", "property", f"{DCT}identifier", "aligned", "dcterms"),
    ("AiRegistryModelVersions.DcTitle", "property", f"{DCT}title", "aligned", "dcterms"),
    ("AiRegistryModelVersions.DcCreator", "property", f"{DCT}creator", "aligned", "dcterms"),
    ("AiRegistryModelVersions.DcDate", "property", f"{DCT}date", "aligned", "dcterms"),
    ("AiRegistryModelVersions.DcHasVersion", "property", f"{DCT}hasVersion", "aligned", "dcterms"),
    ("AiRegistryModelVersions.DcDescription", "property", f"{DCT}description", "aligned", "dcterms"),
    ("ExecutionEntities.AttributedToAgent", "property", f"{PROV}wasAttributedTo", "aligned", "prov-o"),
    ("AiAgentAccountabilities.AccountableAgent", "property", f"{PROV}actedOnBehalfOf", "aligned", "prov-o"),
]
MAPPINGS = [(f"map11-{p.lower().replace('.', '-')}", p, k, i, r, prof, "Added by loop-11.") for p, k, i, r, prof in _M]
