#!/usr/bin/env python3
"""
Generates Rails seed data from an Effortless rulebook.

Generates one .rb file per table with Model.create() calls for each row in the rulebook data.
Also generates a main db/seeds.rb that loads all seed files.

Usage:
  ERB_RULEBOOK_PATH=/path/to/rulebook.json ERB_OUTPUT_DIR=/path/to/rails python rulebook-to-rails-seeds.py
"""

import json
import os
import sys
import re
from pathlib import Path


def to_snake_case(name: str) -> str:
    """Convert PascalCase to snake_case."""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()


def main():
    rulebook_path = os.environ.get('ERB_RULEBOOK_PATH')
    output_dir = os.environ.get('ERB_OUTPUT_DIR')

    if not rulebook_path or not output_dir:
        print("Error: ERB_RULEBOOK_PATH and ERB_OUTPUT_DIR must be set", file=sys.stderr)
        sys.exit(1)

    with open(rulebook_path) as f:
        rulebook = json.load(f)

    Path(f"{output_dir}/db/seeds").mkdir(parents=True, exist_ok=True)

    for table_name, table_data in rulebook.items():
        if table_name.startswith('_'):
            continue

        schema = table_data.get('schema', [])
        data = table_data.get('data', [])

        if not data:
            continue

        # Only seed raw fields (not calculated/lookup/aggregation)
        raw_fields = [f for f in schema if f['type'] == 'raw']

        if not raw_fields:
            continue

        seeds_code = generate_seeds(table_name, raw_fields, data)
        seeds_file = f"{output_dir}/db/seeds/{to_snake_case(table_name)}.rb"

        with open(seeds_file, 'w') as f:
            f.write(seeds_code)
        print(f"Generated {seeds_file}")

    # Generate main seeds.rb loader
    seeds_main = """# This file loads all entity-specific seeds.
# Generated by rulebook-to-rails-seeds.py

Dir[File.join(__dir__, 'seeds', '*.rb')].each { |file| load file }
"""
    with open(f"{output_dir}/db/seeds.rb", 'w') as f:
        f.write(seeds_main)
    print(f"Generated {output_dir}/db/seeds.rb")


def generate_seeds(table_name: str, raw_fields: list, data: list) -> str:
    """Generate Rails seed statements (Model.create calls)."""
    code = f"# Seed data for {table_name}\n"
    code += "# Generated by rulebook-to-rails-seeds.py\n\n"

    for row in data:
        attrs = {}
        for field in raw_fields:
            field_name = field['name']
            attr_name = to_snake_case(field_name)

            if field_name in row:
                value = row[field_name]
                attrs[attr_name] = value

        if attrs:
            attr_str = ', '.join(f'{k}: {repr(v)}' for k, v in attrs.items())
            code += f"{table_name}.create({attr_str})\n"

    return code


if __name__ == '__main__':
    main()
