// AUTO-GENERATED by rulebook-to-react-explainer-dag. DO NOT EDIT.
// Per-field RuleSpeak® rules, rendered at transpile time by the shared
// rulebook-rulespeak-core engine (the same one rulebook-to-rulespeak uses).
// `rule` strings carry markdown emphasis (**must**, **must not**, only if).

export interface RuleSpeakRef {
  table: string;
  field: string;
  label: string;       // the field's humanized label as it appears in `rule`
}

// Structured (outline) form of a rule, for nested-bullet display. `kind`:
//   "priority" — an IF-ladder: ordered `cases` ({value, when?}); last case's
//                 `when` is null (the "otherwise"). `children` carries a lone
//                 condition group for a boolean classification rule.
//   "all"/"any" — AND / OR group over `children` (each itself a RuleNode).
//   "leaf"     — a single clause; `text` is its prose (linkifiable).
export interface RuleNode {
  kind: "priority" | "all" | "any" | "leaf";
  text?: string;
  headline?: string;
  cases?: { value: string; when: RuleNode | null }[];
  children?: RuleNode[] | null;
}

export interface RuleSpeakFieldRule {
  table: string;
  field: string;
  kind: string;        // formula | lookup | rollup | …
  rule: string;        // definitional RuleSpeak® sentence (markdown emphasis)
  mechanical: boolean; // true when the wording is faithful but clunky
  refs: RuleSpeakRef[];// fields this rule references (for linkifying the text)
  structure: RuleNode | null; // outline form when the rule is a list; else null
}

export interface RuleSpeakObligation {
  constraintKey: string;
  entity: string;
  predicate: string;
  deontic: string;     // MustBeTrue | MustNotBeTrue | ShouldBeTrue
  severity: string;    // hard | soft | override
  markdown: string;    // the full rendered obligation (markdown)
}

// Definitional rule per derived field, keyed "Table.Field".
export const rulespeakFields: Record<string, RuleSpeakFieldRule> = {
  "DevUsers.Name": {
    "table": "DevUsers",
    "field": "Name",
    "kind": "formula",
    "rule": "A dev user\u0027s name is the same as its email.",
    "mechanical": false,
    "refs": [
      {
        "table": "DevUsers",
        "field": "Email",
        "label": "email"
      }
    ],
    "structure": null
  },
  "Players.Name": {
    "table": "Players",
    "field": "Name",
    "kind": "formula",
    "rule": "A player\u0027s name is the same as its player ID.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "Players.TotalTouchdowns": {
    "table": "Players",
    "field": "TotalTouchdowns",
    "kind": "formula",
    "rule": "A player\u0027s total touchdowns is computed as the passing touchdowns plus the rushing touchdowns plus the received touchdowns.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "PassingTouchdowns",
        "label": "passing touchdowns"
      },
      {
        "table": "Players",
        "field": "RushingTouchdowns",
        "label": "rushing touchdowns"
      },
      {
        "table": "Players",
        "field": "ReceivedTouchdowns",
        "label": "received touchdowns"
      }
    ],
    "structure": null
  },
  "Players.ProjectedScore": {
    "table": "Players",
    "field": "ProjectedScore",
    "kind": "formula",
    "rule": "A player\u0027s projected score is computed as the passing yards divided by 25 plus the total touchdowns times 6 minus the interceptions times 2 rounded to 2 decimal place(s).",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "PassingYards",
        "label": "passing yards"
      },
      {
        "table": "Players",
        "field": "TotalTouchdowns",
        "label": "total touchdowns"
      },
      {
        "table": "Players",
        "field": "Interceptions",
        "label": "interceptions"
      }
    ],
    "structure": null
  },
  "Rosters.Name": {
    "table": "Rosters",
    "field": "Name",
    "kind": "formula",
    "rule": "A roster\u0027s name is the same as its roster ID.",
    "mechanical": false,
    "refs": [
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Rosters.TotalPassingYards": {
    "table": "Rosters",
    "field": "TotalPassingYards",
    "kind": "rollup",
    "rule": "A roster\u0027s total passing yards is the total passing yards across the roster assignments related to the roster.",
    "mechanical": false,
    "refs": [
      {
        "table": "RosterAssignments",
        "field": "PassingYards",
        "label": "passing yards"
      },
      {
        "table": "RosterAssignments",
        "field": "Roster",
        "label": "roster"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Rosters.TotalRushingYards": {
    "table": "Rosters",
    "field": "TotalRushingYards",
    "kind": "rollup",
    "rule": "A roster\u0027s total rushing yards is the total rushing yards across the roster assignments related to the roster.",
    "mechanical": false,
    "refs": [
      {
        "table": "RosterAssignments",
        "field": "RushingYards",
        "label": "rushing yards"
      },
      {
        "table": "RosterAssignments",
        "field": "Roster",
        "label": "roster"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Rosters.TotalReceivingYards": {
    "table": "Rosters",
    "field": "TotalReceivingYards",
    "kind": "rollup",
    "rule": "A roster\u0027s total receiving yards is the total received yards across the roster assignments related to the roster.",
    "mechanical": false,
    "refs": [
      {
        "table": "RosterAssignments",
        "field": "ReceivedYards",
        "label": "received yards"
      },
      {
        "table": "RosterAssignments",
        "field": "Roster",
        "label": "roster"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Rosters.TotalTouchdowns": {
    "table": "Rosters",
    "field": "TotalTouchdowns",
    "kind": "rollup",
    "rule": "A roster\u0027s total touchdowns is the total total touchdowns across the roster assignments related to the roster.",
    "mechanical": false,
    "refs": [
      {
        "table": "RosterAssignments",
        "field": "TotalTouchdowns",
        "label": "total touchdowns"
      },
      {
        "table": "RosterAssignments",
        "field": "Roster",
        "label": "roster"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Rosters.TotalInterceptions": {
    "table": "Rosters",
    "field": "TotalInterceptions",
    "kind": "rollup",
    "rule": "A roster\u0027s total interceptions is the total interceptions across the roster assignments related to the roster.",
    "mechanical": false,
    "refs": [
      {
        "table": "RosterAssignments",
        "field": "Interceptions",
        "label": "interceptions"
      },
      {
        "table": "RosterAssignments",
        "field": "Roster",
        "label": "roster"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Rosters.ProjectedScore": {
    "table": "Rosters",
    "field": "ProjectedScore",
    "kind": "formula",
    "rule": "A roster\u0027s projected score is computed as the total passing yards divided by 25 plus the total rushing yards divided by 10 plus the total receiving yards divided by 10 plus the total touchdowns times 6 minus the total interceptions times 2 rounded to 2 decimal place(s).",
    "mechanical": false,
    "refs": [
      {
        "table": "Rosters",
        "field": "TotalPassingYards",
        "label": "total passing yards"
      },
      {
        "table": "Rosters",
        "field": "TotalRushingYards",
        "label": "total rushing yards"
      },
      {
        "table": "Rosters",
        "field": "TotalReceivingYards",
        "label": "total receiving yards"
      },
      {
        "table": "Rosters",
        "field": "TotalTouchdowns",
        "label": "total touchdowns"
      },
      {
        "table": "Rosters",
        "field": "TotalInterceptions",
        "label": "total interceptions"
      }
    ],
    "structure": null
  },
  "RosterAssignments.Name": {
    "table": "RosterAssignments",
    "field": "Name",
    "kind": "formula",
    "rule": "A roster assignment\u0027s name is the same as its assignment ID.",
    "mechanical": false,
    "refs": [
      {
        "table": "RosterAssignments",
        "field": "AssignmentId",
        "label": "assignment ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.PlayerName": {
    "table": "RosterAssignments",
    "field": "PlayerName",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s player name \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "Name",
        "label": "name"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.Position": {
    "table": "RosterAssignments",
    "field": "Position",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s position \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "Position",
        "label": "position"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.PassingYards": {
    "table": "RosterAssignments",
    "field": "PassingYards",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s passing yards \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "PassingYards",
        "label": "passing yards"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.PassingTouchdowns": {
    "table": "RosterAssignments",
    "field": "PassingTouchdowns",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s passing touchdowns \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "PassingTouchdowns",
        "label": "passing touchdowns"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.Interceptions": {
    "table": "RosterAssignments",
    "field": "Interceptions",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s interceptions \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "Interceptions",
        "label": "interceptions"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.RushingYards": {
    "table": "RosterAssignments",
    "field": "RushingYards",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s rushing yards \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "RushingYards",
        "label": "rushing yards"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.RushingTouchdowns": {
    "table": "RosterAssignments",
    "field": "RushingTouchdowns",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s rushing touchdowns \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "RushingTouchdowns",
        "label": "rushing touchdowns"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.Receptions": {
    "table": "RosterAssignments",
    "field": "Receptions",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s receptions \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "Receptions",
        "label": "receptions"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.ReceivedYards": {
    "table": "RosterAssignments",
    "field": "ReceivedYards",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s received yards \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "ReceivedYards",
        "label": "received yards"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.ReceivedTouchdowns": {
    "table": "RosterAssignments",
    "field": "ReceivedTouchdowns",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s received touchdowns \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "ReceivedTouchdowns",
        "label": "received touchdowns"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.TotalTouchdowns": {
    "table": "RosterAssignments",
    "field": "TotalTouchdowns",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s total touchdowns \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "TotalTouchdowns",
        "label": "total touchdowns"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "RosterAssignments.ProjectedScore": {
    "table": "RosterAssignments",
    "field": "ProjectedScore",
    "kind": "lookup",
    "rule": "A roster assignment\u0027s projected score \u2014 taken from the linked player.",
    "mechanical": false,
    "refs": [
      {
        "table": "Players",
        "field": "ProjectedScore",
        "label": "projected score"
      },
      {
        "table": "RosterAssignments",
        "field": "Player",
        "label": "player"
      },
      {
        "table": "Players",
        "field": "PlayerId",
        "label": "player ID"
      }
    ],
    "structure": null
  },
  "Matchups.Name": {
    "table": "Matchups",
    "field": "Name",
    "kind": "formula",
    "rule": "A matchup\u0027s name is the same as its matchup ID.",
    "mechanical": false,
    "refs": [
      {
        "table": "Matchups",
        "field": "MatchupId",
        "label": "matchup ID"
      }
    ],
    "structure": null
  },
  "Matchups.Team1Score": {
    "table": "Matchups",
    "field": "Team1Score",
    "kind": "lookup",
    "rule": "A matchup\u0027s team1 score is the projected score of the matchup\u0027s team1.",
    "mechanical": false,
    "refs": [
      {
        "table": "Rosters",
        "field": "ProjectedScore",
        "label": "projected score"
      },
      {
        "table": "Matchups",
        "field": "Team1",
        "label": "team1"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Matchups.Team2Score": {
    "table": "Matchups",
    "field": "Team2Score",
    "kind": "lookup",
    "rule": "A matchup\u0027s team2 score is the projected score of the matchup\u0027s team2.",
    "mechanical": false,
    "refs": [
      {
        "table": "Rosters",
        "field": "ProjectedScore",
        "label": "projected score"
      },
      {
        "table": "Matchups",
        "field": "Team2",
        "label": "team2"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Matchups.Margin": {
    "table": "Matchups",
    "field": "Margin",
    "kind": "formula",
    "rule": "A matchup\u0027s margin is computed as the team1 score minus the team2 score.",
    "mechanical": false,
    "refs": [
      {
        "table": "Matchups",
        "field": "Team1Score",
        "label": "team1 score"
      },
      {
        "table": "Matchups",
        "field": "Team2Score",
        "label": "team2 score"
      }
    ],
    "structure": null
  },
  "Matchups.Winner": {
    "table": "Matchups",
    "field": "Winner",
    "kind": "formula",
    "rule": "The matchup\u0027s winner is determined by the following priority:\n1. the team1, if the margin is greater than 0;\n2. in all other cases, the team2.",
    "mechanical": false,
    "refs": [
      {
        "table": "Matchups",
        "field": "Margin",
        "label": "margin"
      },
      {
        "table": "Matchups",
        "field": "Team1",
        "label": "team1"
      },
      {
        "table": "Matchups",
        "field": "Team2",
        "label": "team2"
      }
    ],
    "structure": {
      "kind": "priority",
      "headline": "The matchup\u0027s winner is determined by the following priority:",
      "cases": [
        {
          "value": "the team1",
          "when": {
            "kind": "leaf",
            "text": "the margin is greater than 0"
          }
        },
        {
          "value": "the team2",
          "when": null
        }
      ],
      "children": null
    }
  },
  "Matchups.Loser": {
    "table": "Matchups",
    "field": "Loser",
    "kind": "formula",
    "rule": "The matchup\u0027s loser is determined by the following priority:\n1. the team2, if the margin is greater than 0;\n2. in all other cases, the team1.",
    "mechanical": false,
    "refs": [
      {
        "table": "Matchups",
        "field": "Margin",
        "label": "margin"
      },
      {
        "table": "Matchups",
        "field": "Team2",
        "label": "team2"
      },
      {
        "table": "Matchups",
        "field": "Team1",
        "label": "team1"
      }
    ],
    "structure": {
      "kind": "priority",
      "headline": "The matchup\u0027s loser is determined by the following priority:",
      "cases": [
        {
          "value": "the team2",
          "when": {
            "kind": "leaf",
            "text": "the margin is greater than 0"
          }
        },
        {
          "value": "the team1",
          "when": null
        }
      ],
      "children": null
    }
  },
  "Matchups.IsTieGame": {
    "table": "Matchups",
    "field": "IsTieGame",
    "kind": "formula",
    "rule": "A matchup is considered a tie game if the margin is 0.",
    "mechanical": false,
    "refs": [
      {
        "table": "Matchups",
        "field": "Margin",
        "label": "margin"
      }
    ],
    "structure": null
  },
  "Standings.Name": {
    "table": "Standings",
    "field": "Name",
    "kind": "formula",
    "rule": "A standing\u0027s name \u2014 taken from the linked standing ID.",
    "mechanical": false,
    "refs": [
      {
        "table": "Rosters",
        "field": "Name",
        "label": "name"
      },
      {
        "table": "Standings",
        "field": "StandingId",
        "label": "standing ID"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  },
  "Standings.Owner": {
    "table": "Standings",
    "field": "Owner",
    "kind": "lookup",
    "rule": "A standing\u0027s owner \u2014 taken from the linked standing ID.",
    "mechanical": false,
    "refs": [
      {
        "table": "Rosters",
        "field": "Owner",
        "label": "owner"
      },
      {
        "table": "Standings",
        "field": "StandingId",
        "label": "standing ID"
      },
      {
        "table": "Rosters",
        "field": "RosterId",
        "label": "roster ID"
      }
    ],
    "structure": null
  }
};

// Deontic obligations from the Constraints table (empty until one exists).
export const rulespeakObligations: RuleSpeakObligation[] = [];

// Structural "must"-rules implied by required fields/FKs, keyed by table.
export const rulespeakStructural: Record<string, string[]> = {
  "DevUsers": [
    "A dev user **must** have an email and a role."
  ],
  "Players": [
    "A player **must** have a position, a passing yards, a passing touchdowns, an interceptions, a rushing yards, a rushing touchdowns, a receptions, a received yards, and a received touchdowns."
  ],
  "Rosters": [
    "A roster **must** have an owner."
  ],
  "RosterAssignments": [
    "A roster assignment **must** reference exactly one roster.",
    "A roster assignment **must** reference exactly one player."
  ],
  "Matchups": [
    "A matchup **must** reference exactly one roster as its team1.",
    "A matchup **must** reference exactly one roster as its team2.",
    "A matchup **must** have a week."
  ],
  "Standings": [
    "A standing **must** have a wins, a losses, a ties, a win pct, a points for, and a points against, and record whether it is playoff bound."
  ]
};
