-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_tables_head_count
-- Field: Tables.HeadCount
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_tables_head_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM guests WHERE assigned_table = (SELECT NULLIF(table_id, '') FROM tables WHERE table_id = p_table_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_open_seats
-- Field: Tables.OpenSeats
-- Type: calculated | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_tables_open_seats(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((COALESCE(CASE WHEN ((SELECT seats FROM tables WHERE table_id = p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN ((SELECT seats FROM tables WHERE table_id = p_table_id))::numeric ELSE NULL END, 0) - COALESCE(CASE WHEN (calc_tables_head_count(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_head_count(p_table_id))::numeric ELSE NULL END, 0)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_over_capacity
-- Field: Tables.OverCapacity
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_tables_over_capacity(p_table_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_tables_head_count(p_table_id) > (SELECT seats FROM tables WHERE table_id = p_table_id))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_tables_raw_happiness
-- Field: Tables.RawHappiness
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_tables_raw_happiness(p_table_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_effective_score(rel_id))::numeric), 0) FROM relationships WHERE calc_relationships_seated_table(rel_id) = p_table_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_tables_violation_count
-- Field: Tables.ViolationCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_violation_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_violation_flag(rel_id))::numeric), 0) FROM relationships WHERE calc_relationships_seated_table(rel_id) = p_table_id))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_happiness
-- Field: Tables.Happiness
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_tables_happiness(p_table_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE(CASE WHEN (calc_tables_raw_happiness(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_raw_happiness(p_table_id))::numeric ELSE NULL END, 0) - COALESCE(CASE WHEN ((COALESCE(CASE WHEN (CASE WHEN calc_tables_over_capacity(p_table_id) THEN (25)::text ELSE (0)::text END)::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (CASE WHEN calc_tables_over_capacity(p_table_id) THEN (25)::text ELSE (0)::text END)::numeric ELSE NULL END, 0) + COALESCE(CASE WHEN (calc_tables_side_skew(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_side_skew(p_table_id))::numeric ELSE NULL END, 0)))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN ((COALESCE(CASE WHEN (CASE WHEN calc_tables_over_capacity(p_table_id) THEN (25)::text ELSE (0)::text END)::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (CASE WHEN calc_tables_over_capacity(p_table_id) THEN (25)::text ELSE (0)::text END)::numeric ELSE NULL END, 0) + COALESCE(CASE WHEN (calc_tables_side_skew(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_side_skew(p_table_id))::numeric ELSE NULL END, 0)))::numeric ELSE NULL END, 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_tables_grade
-- Field: Tables.Grade
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_tables_grade(p_table_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN (calc_tables_violation_count(p_table_id))::NUMERIC > 0 THEN ('Conflict')::text ELSE (CASE WHEN calc_tables_over_capacity(p_table_id) THEN ('Over Capacity')::text ELSE (CASE WHEN (calc_tables_happiness(p_table_id))::NUMERIC >= 15 THEN ('Great')::text ELSE (CASE WHEN (calc_tables_happiness(p_table_id))::NUMERIC >= 5 THEN ('OK')::text ELSE ('Cold')::text END)::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_tables_bride_side_count
-- Field: Tables.BrideSideCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_bride_side_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_guests_bride_flag(guest_id))::numeric), 0) FROM guests WHERE assigned_table = p_table_id))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_groom_side_count
-- Field: Tables.GroomSideCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_groom_side_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_guests_groom_flag(guest_id))::numeric), 0) FROM guests WHERE assigned_table = p_table_id))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_side_skew
-- Field: Tables.SideSkew
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_side_skew(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT (CASE WHEN calc_tables_bride_side_count(p_table_id) > calc_tables_groom_side_count(p_table_id) THEN ((COALESCE(CASE WHEN (calc_tables_bride_side_count(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_bride_side_count(p_table_id))::numeric ELSE NULL END, 0) - COALESCE(CASE WHEN (calc_tables_groom_side_count(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_groom_side_count(p_table_id))::numeric ELSE NULL END, 0)))::text ELSE ((COALESCE(CASE WHEN (calc_tables_groom_side_count(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_groom_side_count(p_table_id))::numeric ELSE NULL END, 0) - COALESCE(CASE WHEN (calc_tables_bride_side_count(p_table_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_tables_bride_side_count(p_table_id))::numeric ELSE NULL END, 0)))::text END)::integer;
$$ LANGUAGE sql STABLE;

-- calc_guests_table_label
-- Field: Guests.TableLabel
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Label from related Tables

CREATE OR REPLACE FUNCTION calc_guests_table_label(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label::text FROM tables WHERE table_id = (SELECT assigned_table FROM guests WHERE guest_id = p_guest_id));
$$ LANGUAGE sql STABLE;

-- calc_guests_table_seats
-- Field: Guests.TableSeats
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: Seats from related Tables

CREATE OR REPLACE FUNCTION calc_guests_table_seats(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT seats::integer FROM tables WHERE table_id = (SELECT assigned_table FROM guests WHERE guest_id = p_guest_id));
$$ LANGUAGE sql STABLE;

-- calc_guests_table_head_count
-- Field: Guests.TableHeadCount
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: HeadCount from related Tables

CREATE OR REPLACE FUNCTION calc_guests_table_head_count(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT calc_tables_head_count((SELECT assigned_table FROM guests WHERE guest_id = p_guest_id));
$$ LANGUAGE sql STABLE;

-- get_tables_name
-- Helper function: Get Name from Tables by TableId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_tables_name(p_table_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM tables WHERE table_id = p_table_id);
$$ LANGUAGE sql STABLE;

-- get_tables_label
-- Helper function: Get Label from Tables by TableId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_tables_label(p_table_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label FROM tables WHERE table_id = p_table_id);
$$ LANGUAGE sql STABLE;

-- get_tables_seats
-- Helper function: Get Seats from Tables by TableId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_tables_seats(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT seats FROM tables WHERE table_id = p_table_id);
$$ LANGUAGE sql STABLE;

-- calc_guests_relationships_as_a
-- Field: Guests.RelationshipsAsA
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_guests_relationships_as_a(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM relationships WHERE guest_a = (SELECT NULLIF(guest_id, '') FROM guests WHERE guest_id = p_guest_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_guests_relationships_as_b
-- Field: Guests.RelationshipsAsB
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_guests_relationships_as_b(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM relationships WHERE guest_b = (SELECT NULLIF(guest_id, '') FROM guests WHERE guest_id = p_guest_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_guests_satisfaction_a
-- Field: Guests.SatisfactionA
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_satisfaction_a(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_effective_score(rel_id))::numeric), 0) FROM relationships WHERE guest_a = p_guest_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_satisfaction_b
-- Field: Guests.SatisfactionB
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_guests_satisfaction_b(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_effective_score(rel_id))::numeric), 0) FROM relationships WHERE guest_b = p_guest_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_satisfaction
-- Field: Guests.Satisfaction
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_satisfaction(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE(CASE WHEN (calc_guests_satisfaction_a(p_guest_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_guests_satisfaction_a(p_guest_id))::numeric ELSE NULL END, 0) + COALESCE(CASE WHEN (calc_guests_satisfaction_b(p_guest_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_guests_satisfaction_b(p_guest_id))::numeric ELSE NULL END, 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_mood
-- Field: Guests.Mood
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_guests_mood(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN (calc_guests_satisfaction(p_guest_id))::NUMERIC >= 10 THEN ('Happy')::text ELSE (CASE WHEN (calc_guests_satisfaction(p_guest_id))::NUMERIC >= 0 THEN ('Neutral')::text ELSE ('Unhappy')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_guests_bride_flag
-- Field: Guests.BrideFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_bride_flag(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN (SELECT NULLIF(side, '') FROM guests WHERE guest_id = p_guest_id) = 'bride' THEN (1)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_groom_flag
-- Field: Guests.GroomFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_groom_flag(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN (SELECT NULLIF(side, '') FROM guests WHERE guest_id = p_guest_id) = 'groom' THEN (1)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_a_name
-- Field: Relationships.GuestAName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_a_name(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM guests WHERE guest_id = (SELECT guest_a FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_b_name
-- Field: Relationships.GuestBName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_b_name(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM guests WHERE guest_id = (SELECT guest_b FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_a_table
-- Field: Relationships.GuestATable
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: AssignedTable from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_a_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT assigned_table::text FROM guests WHERE guest_id = (SELECT guest_a FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_b_table
-- Field: Relationships.GuestBTable
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: AssignedTable from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_b_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT assigned_table::text FROM guests WHERE guest_id = (SELECT guest_b FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- get_guests_name
-- Helper function: Get Name from Guests by GuestId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_guests_name(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_full_name
-- Helper function: Get FullName from Guests by GuestId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_guests_full_name(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_side
-- Helper function: Get Side from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_side(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT side FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_dietary
-- Helper function: Get Dietary from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_dietary(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT dietary FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_language
-- Helper function: Get Language from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_language(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT language FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_age_band
-- Helper function: Get AgeBand from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_age_band(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT age_band FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- calc_relationships_same_table
-- Field: Relationships.SameTable
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_relationships_same_table(p_rel_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_relationships_guest_a_table(p_rel_id) IS NOT NULL AND calc_relationships_guest_a_table(p_rel_id) = calc_relationships_guest_b_table(p_rel_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_relationships_seated_table
-- Field: Relationships.SeatedTable
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_relationships_seated_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_relationships_same_table(p_rel_id) THEN (calc_relationships_guest_a_table(p_rel_id))::text ELSE ('')::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_relationships_effective_score
-- Field: Relationships.EffectiveScore
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_relationships_effective_score(p_rel_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN calc_relationships_same_table(p_rel_id) THEN (CASE WHEN (SELECT NULLIF(kind, '') FROM relationships WHERE rel_id = p_rel_id) = 'must-not' THEN (-50)::text ELSE ((SELECT weight FROM relationships WHERE rel_id = p_rel_id))::text END)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_relationships_is_must_not_violation
-- Field: Relationships.IsMustNotViolation
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_relationships_is_must_not_violation(p_rel_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT NULLIF(kind, '') FROM relationships WHERE rel_id = p_rel_id) = 'must-not' AND calc_relationships_same_table(p_rel_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_relationships_is_satisfied
-- Field: Relationships.IsSatisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_relationships_is_satisfied(p_rel_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((((SELECT weight FROM relationships WHERE rel_id = p_rel_id))::NUMERIC > 0 AND calc_relationships_same_table(p_rel_id)) OR (((SELECT weight FROM relationships WHERE rel_id = p_rel_id))::NUMERIC < 0 AND NOT (calc_relationships_same_table(p_rel_id)))));
$$ LANGUAGE sql STABLE;

-- calc_relationships_violation_table
-- Field: Relationships.ViolationTable
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_relationships_violation_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_relationships_is_must_not_violation(p_rel_id) THEN (calc_relationships_guest_a_table(p_rel_id))::text ELSE ('')::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_relationships_violation_flag
-- Field: Relationships.ViolationFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_relationships_violation_flag(p_rel_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN calc_relationships_is_must_not_violation(p_rel_id) THEN (1)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

