-- ============================================================================
-- UPDATE EFFORTLESS SCHEMA - the derived layer, rebuilt from the rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres. DO NOT EDIT — regenerated every build.
--
-- SAFE IN PRODUCTION. This file never drops a table, never drops a column,
-- and never deletes row data. It brings any database in line with the
-- rulebook that shipped in this same commit.
--
-- Views, calc_*/get_* functions and RLS policies hold NO data: they are a
-- pure function of the rulebook. They are dropped and recreated here rather
-- than migrated. Do NOT hand-write a migration that recreates a view or a
-- calc_* function — re-run this file instead.
--
-- A hand-authored migration is needed ONLY for table/column changes that
-- step 1 below cannot infer, and it should contain nothing else.
-- ============================================================================

BEGIN;
SET timezone = 'UTC';

-- === 1. Additive schema: missing tables and columns ========================
-- CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS only. Never drops.

-- ============================================================================
-- DROP AND CREATE TABLES (drop-all mode) - Clean slate + Normalized schema
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Tables: 4
-- Total Raw Fields: 20
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP ALL OBJECTS - Clean slate for database
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
-- Generated by rulebook-to-postgres tool
-- ============================================================================

DO $$ 
DECLARE r RECORD; v_count INTEGER := 0;
BEGIN
    RAISE NOTICE 'Dropping views...';
    FOR r IN (SELECT table_name FROM information_schema.views WHERE table_schema = 'public') LOOP
        EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % views', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping functions...';
    FOR r IN (SELECT DISTINCT p.proname as function_name, pg_get_function_identity_arguments(p.oid) as function_args
              FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid
              WHERE n.nspname = 'public' AND p.prokind = 'f') LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.function_name) || '(' || r.function_args || ') CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % functions', v_count; v_count := 0;
    
    RAISE NOTICE 'Dropping tables...';
    FOR r IN (SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE') LOOP
        EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.table_name) || ' CASCADE';
        v_count := v_count + 1;
    END LOOP;
    RAISE NOTICE 'Dropped % tables', v_count;
END $$;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Users: Login identities for the demo (stub auth).
-- ----------------------------------------------------------------------------
CREATE TABLE users (
  user_id                             TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  email                               TEXT                ,
  role                                TEXT                ,                     -- coordinator | bride | groom
  display_name                        TEXT                
);
COMMENT ON TABLE users IS 'Login identities for the demo (stub auth).';
COMMENT ON COLUMN users.role IS 'coordinator | bride | groom';

-- ----------------------------------------------------------------------------
-- Tables: Physical reception tables. Guests are assigned to one Table each.
-- ----------------------------------------------------------------------------
CREATE TABLE tables (
  table_id                            TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  label                               TEXT                ,                     -- Friendly label e.g. 'Head Table', 'Cousins'.
  seats                               INTEGER                                   -- Physical capacity.
);
COMMENT ON TABLE tables IS 'Physical reception tables. Guests are assigned to one Table each.';
COMMENT ON COLUMN tables.label IS 'Friendly label e.g. ''Head Table'', ''Cousins''.';
COMMENT ON COLUMN tables.seats IS 'Physical capacity.';

-- ----------------------------------------------------------------------------
-- Guests: Wedding guests. Each is assigned to one Table.
-- ----------------------------------------------------------------------------
CREATE TABLE guests (
  guest_id                            TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  full_name                           TEXT                ,
  side                                TEXT                ,                     -- bride | groom | both
  dietary                             TEXT                ,                     -- none | veg | vegan | gf | kosher
  language                            TEXT                ,                     -- en | es | fr
  age_band                            TEXT                ,                     -- child | adult | senior
  assigned_table                      TEXT                                      -- FK to Tables.TableId. Editable — moves the guest.
);
COMMENT ON TABLE guests IS 'Wedding guests. Each is assigned to one Table.';
COMMENT ON COLUMN guests.side IS 'bride | groom | both';
COMMENT ON COLUMN guests.dietary IS 'none | veg | vegan | gf | kosher';
COMMENT ON COLUMN guests.language IS 'en | es | fr';
COMMENT ON COLUMN guests.age_band IS 'child | adult | senior';
COMMENT ON COLUMN guests.assigned_table IS 'FK to Tables.TableId. Editable — moves the guest.';

-- ----------------------------------------------------------------------------
-- Relationships: Directed-but-symmetric guest-pair affinities. Kind is loves | prefers | avoid | must-not, with a Weight (positive = affinity, negative = friction).
-- ----------------------------------------------------------------------------
CREATE TABLE relationships (
  rel_id                              TEXT                 PRIMARY KEY,
  name                                TEXT                ,
  guest_a                             TEXT                ,
  guest_b                             TEXT                ,
  kind                                TEXT                ,                     -- loves | prefers | avoid | must-not
  weight                              NUMERIC                                   -- Signed magnitude (positive = wants near, negative = wants apart).
);
COMMENT ON TABLE relationships IS 'Directed-but-symmetric guest-pair affinities. Kind is loves | prefers | avoid | must-not, with a Weight (positive = affinity, negative = friction).';
COMMENT ON COLUMN relationships.kind IS 'loves | prefers | avoid | must-not';
COMMENT ON COLUMN relationships.weight IS 'Signed magnitude (positive = wants near, negative = wants apart).';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Guests
CREATE INDEX IF NOT EXISTS idx_guests_assigned_table ON guests (assigned_table);

-- Relationships
CREATE INDEX IF NOT EXISTS idx_relationships_guest_a ON relationships (guest_a);
CREATE INDEX IF NOT EXISTS idx_relationships_guest_b ON relationships (guest_b);

-- 3 FK index(es) declared.


-- === 2/3. Drop the derived layer ==========================================
-- Views first (they depend on functions), then functions leaf-up through the
-- DAG. CASCADE handles the dependency order Postgres knows about; the
-- explicit ordering handles calc_* functions that call other calc_*.
DO $drop_derived$
DECLARE r RECORD; v_views INT := 0; v_fns INT := 0;
BEGIN
    -- 2. Views (depend on functions, so they go first).
    FOR r IN (
        SELECT table_name FROM information_schema.views
         WHERE table_schema = 'public' AND table_name LIKE 'vw\_%'
           AND obj_description(
                 (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass, 'pg_class')
               IS DISTINCT FROM 'effortless:hand-maintained'
    ) LOOP
        EXECUTE 'DROP VIEW IF EXISTS public.' || quote_ident(r.table_name) || ' CASCADE';
        v_views := v_views + 1;
    END LOOP;

    -- 3. Functions, leaf-up through the DAG. A calc_* may call another
    --    calc_*, so depth-ordering avoids dependency errors.
    FOR r IN (
        WITH fn AS (
            SELECT p.oid, p.proname,
                   pg_get_function_identity_arguments(p.oid) AS args,
                   p.prosrc
              FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'public'
               AND (p.proname LIKE 'calc\_%' OR p.proname LIKE 'get\_%')
               AND COALESCE(obj_description(p.oid, 'pg_proc'), '')
                   IS DISTINCT FROM 'effortless:hand-maintained'
        )
        -- callers before callees: a function whose body names another
        -- generated function is an interior node and must go first.
        SELECT f.proname, f.args,
               (SELECT count(*) FROM fn c
                 WHERE c.oid <> f.oid AND f.prosrc LIKE '%' || c.proname || '%') AS depth
          FROM fn f
         ORDER BY depth DESC, f.proname
    ) LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS public.' || quote_ident(r.proname)
                || '(' || r.args || ') CASCADE';
        v_fns := v_fns + 1;
    END LOOP;

    RAISE NOTICE 'derived layer dropped: % views, % functions', v_views, v_fns;
END
$drop_derived$;


-- === 4. Static reference data =============================================
-- (no tables marked IsStatic — nothing to upsert)

-- === 5. Recreate calc_*/get_* functions ===================================
-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_tables_head_count
-- Field: Tables.HeadCount
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_tables_head_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM guests WHERE assigned_table = (SELECT NULLIF(table_id, '') FROM tables WHERE table_id = p_table_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_open_seats
-- Field: Tables.OpenSeats
-- Type: calculated | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_tables_open_seats(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT seats FROM tables WHERE table_id = p_table_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_tables_head_count(p_table_id)) AS v) __safe_numeric), 0)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_over_capacity
-- Field: Tables.OverCapacity
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_tables_over_capacity(p_table_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_tables_head_count(p_table_id) > (SELECT seats FROM tables WHERE table_id = p_table_id))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_tables_raw_happiness
-- Field: Tables.RawHappiness
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_tables_raw_happiness(p_table_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_effective_score(rel_id))::numeric), 0) FROM relationships WHERE calc_relationships_seated_table(rel_id) = p_table_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_tables_violation_count
-- Field: Tables.ViolationCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_violation_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_violation_flag(rel_id))::numeric), 0) FROM relationships WHERE calc_relationships_seated_table(rel_id) = p_table_id))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_happiness
-- Field: Tables.Happiness
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_tables_happiness(p_table_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_tables_raw_happiness(p_table_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (CASE WHEN calc_tables_over_capacity(p_table_id) THEN (25)::text ELSE (0)::text END) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_tables_side_skew(p_table_id)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_tables_grade
-- Field: Tables.Grade
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_tables_grade(p_table_id TEXT)
RETURNS TEXT AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_tables_happiness(p_table_id) AS val) SELECT (CASE WHEN (calc_tables_violation_count(p_table_id))::NUMERIC > 0 THEN ('Conflict')::text ELSE (CASE WHEN calc_tables_over_capacity(p_table_id) THEN ('Over Capacity')::text ELSE (CASE WHEN ((SELECT val FROM __erb_dedup_v1))::NUMERIC >= 15 THEN ('Great')::text ELSE (CASE WHEN ((SELECT val FROM __erb_dedup_v1))::NUMERIC >= 5 THEN ('OK')::text ELSE ('Cold')::text END)::text END)::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_tables_bride_side_count
-- Field: Tables.BrideSideCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_bride_side_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_guests_bride_flag(guest_id))::numeric), 0) FROM guests WHERE assigned_table = p_table_id))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_groom_side_count
-- Field: Tables.GroomSideCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_groom_side_count(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COALESCE(SUM((calc_guests_groom_flag(guest_id))::numeric), 0) FROM guests WHERE assigned_table = p_table_id))::integer;
$$ LANGUAGE sql STABLE;

-- calc_tables_side_skew
-- Field: Tables.SideSkew
-- Type: calculated | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_tables_side_skew(p_table_id TEXT)
RETURNS INTEGER AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_tables_bride_side_count(p_table_id) AS val), __erb_dedup_v2 AS (SELECT calc_tables_groom_side_count(p_table_id) AS val) SELECT (CASE WHEN (SELECT val FROM __erb_dedup_v1) > (SELECT val FROM __erb_dedup_v2) THEN ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v2)) AS v) __safe_numeric), 0)))::text ELSE ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v2)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0)))::text END)::integer;
$$ LANGUAGE sql STABLE;

-- calc_guests_table_label
-- Field: Guests.TableLabel
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Label from related Tables

CREATE OR REPLACE FUNCTION calc_guests_table_label(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label::text FROM tables WHERE table_id = (SELECT assigned_table FROM guests WHERE guest_id = p_guest_id));
$$ LANGUAGE sql STABLE;

-- calc_guests_table_seats
-- Field: Guests.TableSeats
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: Seats from related Tables

CREATE OR REPLACE FUNCTION calc_guests_table_seats(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT seats::integer FROM tables WHERE table_id = (SELECT assigned_table FROM guests WHERE guest_id = p_guest_id));
$$ LANGUAGE sql STABLE;

-- calc_guests_table_head_count
-- Field: Guests.TableHeadCount
-- Type: lookup | DataType: integer | Returns: INTEGER
-- Lookup: HeadCount from related Tables

CREATE OR REPLACE FUNCTION calc_guests_table_head_count(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT calc_tables_head_count((SELECT assigned_table FROM guests WHERE guest_id = p_guest_id));
$$ LANGUAGE sql STABLE;

-- get_tables_name
-- Helper function: Get Name from Tables by TableId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_tables_name(p_table_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM tables WHERE table_id = p_table_id);
$$ LANGUAGE sql STABLE;

-- get_tables_label
-- Helper function: Get Label from Tables by TableId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_tables_label(p_table_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT label FROM tables WHERE table_id = p_table_id);
$$ LANGUAGE sql STABLE;

-- get_tables_seats
-- Helper function: Get Seats from Tables by TableId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_tables_seats(p_table_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT seats FROM tables WHERE table_id = p_table_id);
$$ LANGUAGE sql STABLE;

-- calc_guests_relationships_as_a
-- Field: Guests.RelationshipsAsA
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_guests_relationships_as_a(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM relationships WHERE guest_a = (SELECT NULLIF(guest_id, '') FROM guests WHERE guest_id = p_guest_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_guests_relationships_as_b
-- Field: Guests.RelationshipsAsB
-- Type: aggregation | DataType: integer | Returns: INTEGER

CREATE OR REPLACE FUNCTION calc_guests_relationships_as_b(p_guest_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM relationships WHERE guest_b = (SELECT NULLIF(guest_id, '') FROM guests WHERE guest_id = p_guest_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_guests_satisfaction_a
-- Field: Guests.SatisfactionA
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_satisfaction_a(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_effective_score(rel_id))::numeric), 0) FROM relationships WHERE guest_a = p_guest_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_satisfaction_b
-- Field: Guests.SatisfactionB
-- Type: aggregation | DataType: number | Returns: NUMERIC

CREATE OR REPLACE FUNCTION calc_guests_satisfaction_b(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_relationships_effective_score(rel_id))::numeric), 0) FROM relationships WHERE guest_b = p_guest_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_satisfaction
-- Field: Guests.Satisfaction
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_satisfaction(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_guests_satisfaction_a(p_guest_id)) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_guests_satisfaction_b(p_guest_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_mood
-- Field: Guests.Mood
-- Type: calculated | DataType: string | Returns: TEXT

CREATE OR REPLACE FUNCTION calc_guests_mood(p_guest_id TEXT)
RETURNS TEXT AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_guests_satisfaction(p_guest_id) AS val) SELECT (CASE WHEN ((SELECT val FROM __erb_dedup_v1))::NUMERIC >= 10 THEN ('Happy')::text ELSE (CASE WHEN ((SELECT val FROM __erb_dedup_v1))::NUMERIC >= 0 THEN ('Neutral')::text ELSE ('Unhappy')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_guests_bride_flag
-- Field: Guests.BrideFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_bride_flag(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN (SELECT NULLIF(side, '') FROM guests WHERE guest_id = p_guest_id) = 'bride' THEN (1)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_guests_groom_flag
-- Field: Guests.GroomFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_guests_groom_flag(p_guest_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN (SELECT NULLIF(side, '') FROM guests WHERE guest_id = p_guest_id) = 'groom' THEN (1)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_a_name
-- Field: Relationships.GuestAName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_a_name(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM guests WHERE guest_id = (SELECT guest_a FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_b_name
-- Field: Relationships.GuestBName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_b_name(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name::text FROM guests WHERE guest_id = (SELECT guest_b FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_a_table
-- Field: Relationships.GuestATable
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: AssignedTable from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_a_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT assigned_table::text FROM guests WHERE guest_id = (SELECT guest_a FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- calc_relationships_guest_b_table
-- Field: Relationships.GuestBTable
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: AssignedTable from related Guests

CREATE OR REPLACE FUNCTION calc_relationships_guest_b_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT assigned_table::text FROM guests WHERE guest_id = (SELECT guest_b FROM relationships WHERE rel_id = p_rel_id));
$$ LANGUAGE sql STABLE;

-- get_guests_name
-- Helper function: Get Name from Guests by GuestId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_guests_name(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_full_name
-- Helper function: Get FullName from Guests by GuestId
-- Used for join-free cross-table references in aggregations
CREATE OR REPLACE FUNCTION get_guests_full_name(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT full_name FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_side
-- Helper function: Get Side from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_side(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT side FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_dietary
-- Helper function: Get Dietary from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_dietary(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT dietary FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_language
-- Helper function: Get Language from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_language(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT language FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- get_guests_age_band
-- Helper function: Get AgeBand from Guests by GuestId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_guests_age_band(p_guest_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT age_band FROM guests WHERE guest_id = p_guest_id);
$$ LANGUAGE sql STABLE;

-- calc_relationships_same_table
-- Field: Relationships.SameTable
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_relationships_same_table(p_rel_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_relationships_guest_a_table(p_rel_id) AS val) SELECT (((SELECT val FROM __erb_dedup_v1) IS NOT NULL AND (SELECT val FROM __erb_dedup_v1) = calc_relationships_guest_b_table(p_rel_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_relationships_seated_table
-- Field: Relationships.SeatedTable
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_relationships_seated_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_relationships_same_table(p_rel_id) THEN (calc_relationships_guest_a_table(p_rel_id))::text ELSE ('')::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_relationships_effective_score
-- Field: Relationships.EffectiveScore
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_relationships_effective_score(p_rel_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN calc_relationships_same_table(p_rel_id) THEN (CASE WHEN (SELECT NULLIF(kind, '') FROM relationships WHERE rel_id = p_rel_id) = 'must-not' THEN (-50)::text ELSE ((SELECT weight FROM relationships WHERE rel_id = p_rel_id))::text END)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_relationships_is_must_not_violation
-- Field: Relationships.IsMustNotViolation
-- Type: calculated | DataType: boolean | Returns: BOOLEAN

CREATE OR REPLACE FUNCTION calc_relationships_is_must_not_violation(p_rel_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT NULLIF(kind, '') FROM relationships WHERE rel_id = p_rel_id) = 'must-not' AND calc_relationships_same_table(p_rel_id)))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_relationships_is_satisfied
-- Field: Relationships.IsSatisfied
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_relationships_is_satisfied(p_rel_id TEXT)
RETURNS BOOLEAN AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_relationships_same_table(p_rel_id) AS val) SELECT (((((SELECT weight FROM relationships WHERE rel_id = p_rel_id))::NUMERIC > 0 AND (SELECT val FROM __erb_dedup_v1)) OR (((SELECT weight FROM relationships WHERE rel_id = p_rel_id))::NUMERIC < 0 AND NOT ((SELECT val FROM __erb_dedup_v1)))));
$$ LANGUAGE sql STABLE;

-- calc_relationships_violation_table
-- Field: Relationships.ViolationTable
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_relationships_violation_table(p_rel_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_relationships_is_must_not_violation(p_rel_id) THEN (calc_relationships_guest_a_table(p_rel_id))::text ELSE ('')::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_relationships_violation_flag
-- Field: Relationships.ViolationFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_relationships_violation_flag(p_rel_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN calc_relationships_is_must_not_violation(p_rel_id) THEN (1)::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================



-- === 6. Custom functions (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 7. Recreate vw_* views ===============================================
-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 4
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_relationships CASCADE;
DROP VIEW IF EXISTS vw_guests CASCADE;
DROP VIEW IF EXISTS vw_tables CASCADE;
DROP VIEW IF EXISTS vw_users CASCADE;

-- ----------------------------------------------------------------------------
-- vw_users: Login identities for the demo (stub auth).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_users CASCADE;
CREATE VIEW vw_users WITH (security_invoker = ON) AS
SELECT
  t.user_id,
  t.name,
  t.email,
  t.role,                                                                       -- coordinator | bride | groom
  t.display_name
FROM users t;

-- ----------------------------------------------------------------------------
-- vw_tables: Physical reception tables. Guests are assigned to one Table each.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_tables CASCADE;
CREATE VIEW vw_tables WITH (security_invoker = ON) AS
SELECT
  t.table_id,
  t.name,
  t.label,                                                                      -- Friendly label e.g. 'Head Table', 'Cousins'.
  t.seats,                                                                      -- Physical capacity.
  calc_tables_head_count(t.table_id) AS head_count,
  calc_tables_open_seats(t.table_id) AS open_seats,
  calc_tables_over_capacity(t.table_id) AS over_capacity,
  calc_tables_raw_happiness(t.table_id) AS raw_happiness,                       -- Sum of EffectiveScore for relationships whose seated table matches this one.
  calc_tables_violation_count(t.table_id) AS violation_count,                   -- Number of must-not pairs seated at this table.
  calc_tables_happiness(t.table_id) AS happiness,                               -- Net happiness: raw affinity minus capacity penalty minus side-skew penalty.
  calc_tables_grade(t.table_id) AS grade,
  calc_tables_bride_side_count(t.table_id) AS bride_side_count,                 -- Number of bride-side guests at this table.
  calc_tables_groom_side_count(t.table_id) AS groom_side_count,                 -- Number of groom-side guests at this table.
  calc_tables_side_skew(t.table_id) AS side_skew                                -- Absolute difference between bride and groom side counts.
FROM tables t;

-- ----------------------------------------------------------------------------
-- vw_guests: Wedding guests. Each is assigned to one Table.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_guests CASCADE;
CREATE VIEW vw_guests WITH (security_invoker = ON) AS
SELECT
  t.guest_id,
  t.name,
  t.full_name,
  t.side,                                                                       -- bride | groom | both
  t.dietary,                                                                    -- none | veg | vegan | gf | kosher
  t.language,                                                                   -- en | es | fr
  t.age_band,                                                                   -- child | adult | senior
  t.assigned_table,                                                             -- FK to Tables.TableId. Editable — moves the guest.
  calc_guests_table_label(t.guest_id) AS table_label,
  calc_guests_table_seats(t.guest_id) AS table_seats,
  calc_guests_table_head_count(t.guest_id) AS table_head_count,
  calc_guests_relationships_as_a(t.guest_id) AS relationships_as_a,
  calc_guests_relationships_as_b(t.guest_id) AS relationships_as_b,
  calc_guests_satisfaction_a(t.guest_id) AS satisfaction_a,                     -- Sum of EffectiveScore on relationships where this guest is GuestA and the pair is co-seated.
  calc_guests_satisfaction_b(t.guest_id) AS satisfaction_b,
  calc_guests_satisfaction(t.guest_id) AS satisfaction,                         -- Per-guest happiness rollup.
  calc_guests_mood(t.guest_id) AS mood,
  calc_guests_bride_flag(t.guest_id) AS bride_flag,                             -- 1 if bride-side guest; else 0. Feeds Tables.BrideSideCount.
  calc_guests_groom_flag(t.guest_id) AS groom_flag                              -- 1 if groom-side guest; else 0. Feeds Tables.GroomSideCount.
FROM guests t;

-- ----------------------------------------------------------------------------
-- vw_relationships: Directed-but-symmetric guest-pair affinities. Kind is loves | prefers | avoid | must-not, with a Weight (positive = affinity, negative = friction).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_relationships CASCADE;
CREATE VIEW vw_relationships WITH (security_invoker = ON) AS
SELECT
  t.rel_id,
  t.name,
  t.guest_a,
  t.guest_b,
  t.kind,                                                                       -- loves | prefers | avoid | must-not
  t.weight,                                                                     -- Signed magnitude (positive = wants near, negative = wants apart).
  calc_relationships_guest_a_name(t.rel_id) AS guest_a_name,
  calc_relationships_guest_b_name(t.rel_id) AS guest_b_name,
  calc_relationships_guest_a_table(t.rel_id) AS guest_a_table,
  calc_relationships_guest_b_table(t.rel_id) AS guest_b_table,
  calc_relationships_same_table(t.rel_id) AS same_table,                        -- True iff both ends sit at the same non-empty table.
  calc_relationships_seated_table(t.rel_id) AS seated_table,                    -- If both guests share a table, that table's id; else blank. Drives the per-table aggregations.
  calc_relationships_effective_score(t.rel_id) AS effective_score,              -- Weight when co-seated; else 0. Must-not pairs co-seated produce a large penalty regardless of Weight sign.
  calc_relationships_is_must_not_violation(t.rel_id) AS is_must_not_violation,
  calc_relationships_is_satisfied(t.rel_id) AS is_satisfied,                    -- Positive-affinity pair sitting together, or negative-affinity pair sitting apart.
  calc_relationships_violation_table(t.rel_id) AS violation_table,              -- TableId if this is a must-not violation; else blank.
  calc_relationships_violation_flag(t.rel_id) AS violation_flag                 -- 1 if must-not pair co-seated; else 0. Feeds the per-table ViolationCount aggregation.
FROM relationships t;



-- === 8. Custom views (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 9. Custom RLS (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- NOTE: the RBAC policy layer is generated by
-- effortless-rbac-to-postgres-policies as
-- drop-update-effortless-postgres-policies.sql. It follows this same
-- drop-and-recreate model and must run AFTER this file, because policies
-- reference the columns and views rebuilt above.

-- === 10. Custom data (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

COMMIT;
