-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_users_name
-- Field: Users.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_users_name(p_users_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(email, '') FROM users WHERE users_id = p_users_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_users_full_name
-- Field: Users.FullName
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_users_full_name(p_users_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(last_name, '') FROM users WHERE users_id = p_users_id), ', ', (SELECT NULLIF(first_name, '') FROM users WHERE users_id = p_users_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_customers_name
-- Field: Customers.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_customers_name(p_customers_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(email, '') FROM customers WHERE customers_id = p_customers_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_customers_full_name
-- Field: Customers.FullName
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_customers_full_name(p_customers_id TEXT)
RETURNS TEXT AS $$
  SELECT (CONCAT((SELECT NULLIF(last_name, '') FROM customers WHERE customers_id = p_customers_id), ', ', (SELECT NULLIF(first_name, '') FROM customers WHERE customers_id = p_customers_id)))::text;
$$ LANGUAGE sql STABLE;

-- calc_customers_lifetime_sales
-- Field: Customers.LifetimeSales
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_customers_lifetime_sales(p_customers_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_orders_recent_total(orders_id))::numeric), 0) FROM orders WHERE customer = calc_customers_name(p_customers_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_customers_unpaid_order_count
-- Field: Customers.UnpaidOrderCount
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_customers_unpaid_order_count(p_customers_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_orders_unpaid_flag(orders_id))::numeric), 0) FROM orders WHERE customer = calc_customers_name(p_customers_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_customers_large_order_count
-- Field: Customers.LargeOrderCount
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_customers_large_order_count(p_customers_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM(((COALESCE(CASE WHEN ((COALESCE(CASE WHEN (total)::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (total)::numeric ELSE NULL END, 0) * COALESCE(0, 0)))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN ((COALESCE(CASE WHEN (total)::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (total)::numeric ELSE NULL END, 0) * COALESCE(0, 0)))::numeric ELSE NULL END, 0) + COALESCE(1, 0)))::numeric), 0) FROM orders WHERE customer = calc_customers_name(p_customers_id) AND total > 500))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_customers_is_vip
-- Field: Customers.IsVIP
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_customers_is_vip(p_customers_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((calc_customers_lifetime_sales(p_customers_id))::NUMERIC > 1000 AND (calc_customers_unpaid_order_count(p_customers_id))::NUMERIC <= 1));
$$ LANGUAGE sql STABLE;

-- calc_orders_customer_first_name
-- Field: Orders.CustomerFirstName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FirstName from related Customers


CREATE OR REPLACE FUNCTION calc_orders_customer_first_name(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT first_name::text FROM customers WHERE customers_id = (SELECT customer FROM orders WHERE orders_id = p_orders_id));
$$ LANGUAGE sql STABLE;

-- calc_orders_customer_last_name
-- Field: Orders.CustomerLastName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: LastName from related Customers


CREATE OR REPLACE FUNCTION calc_orders_customer_last_name(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT last_name::text FROM customers WHERE customers_id = (SELECT customer FROM orders WHERE orders_id = p_orders_id));
$$ LANGUAGE sql STABLE;

-- calc_orders_customer_full_name
-- Field: Orders.CustomerFullName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: FullName from related Customers


CREATE OR REPLACE FUNCTION calc_orders_customer_full_name(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_customers_full_name((SELECT customer FROM orders WHERE orders_id = p_orders_id));
$$ LANGUAGE sql STABLE;

-- calc_orders_customer_email
-- Field: Orders.CustomerEmail
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Email from related Customers


CREATE OR REPLACE FUNCTION calc_orders_customer_email(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email::text FROM customers WHERE customers_id = (SELECT customer FROM orders WHERE orders_id = p_orders_id));
$$ LANGUAGE sql STABLE;

-- get_customers_email
-- Helper function: Get Email from Customers by CustomersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_customers_email(p_customers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT email FROM customers WHERE customers_id = p_customers_id);
$$ LANGUAGE sql STABLE;

-- get_customers_first_name
-- Helper function: Get FirstName from Customers by CustomersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_customers_first_name(p_customers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT first_name FROM customers WHERE customers_id = p_customers_id);
$$ LANGUAGE sql STABLE;

-- get_customers_last_name
-- Helper function: Get LastName from Customers by CustomersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_customers_last_name(p_customers_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT last_name FROM customers WHERE customers_id = p_customers_id);
$$ LANGUAGE sql STABLE;

-- calc_orders_name
-- Field: Orders.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_orders_name(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(order_number, '') FROM orders WHERE orders_id = p_orders_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_orders_amount_paid
-- Field: Orders.AmountPaid
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_orders_amount_paid(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((amount)::numeric), 0) FROM payments WHERE order_id = calc_orders_name(p_orders_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_orders_balance
-- Field: Orders.Balance
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_orders_balance(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE(CASE WHEN ((SELECT total FROM orders WHERE orders_id = p_orders_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN ((SELECT total FROM orders WHERE orders_id = p_orders_id))::numeric ELSE NULL END, 0) - COALESCE(CASE WHEN (calc_orders_amount_paid(p_orders_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_orders_amount_paid(p_orders_id))::numeric ELSE NULL END, 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_orders_is_paid
-- Field: Orders.IsPaid
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_orders_is_paid(p_orders_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_orders_balance(p_orders_id))::NUMERIC <= 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_orders_unpaid_flag
-- Field: Orders.UnpaidFlag
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_orders_unpaid_flag(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN calc_orders_is_paid(p_orders_id) THEN (0)::text ELSE (1)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_orders_is_recent
-- Field: Orders.IsRecent
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_orders_is_recent(p_orders_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((CURRENT_DATE::date - (SELECT order_date::timestamptz FROM orders WHERE orders_id = p_orders_id)::date))::NUMERIC <= 90)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_orders_recent_total
-- Field: Orders.RecentTotal
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_orders_recent_total(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN calc_orders_is_recent(p_orders_id) THEN ((SELECT total FROM orders WHERE orders_id = p_orders_id))::text ELSE (0)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_orders_fcs_subtotal
-- Field: Orders.FCSSubtotal
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_orders_fcs_subtotal(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_order_lines_line_total(order_lines_id))::numeric), 0) FROM order_lines WHERE order_id = calc_orders_name(p_orders_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_orders_fcs_unit_count
-- Field: Orders.FCSUnitCount
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_orders_fcs_unit_count(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((quantity)::numeric), 0) FROM order_lines WHERE order_id = calc_orders_name(p_orders_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_payments_order_number
-- Field: Payments.OrderNumber
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: OrderNumber from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_number(p_payments_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT order_number::text FROM orders WHERE orders_id = (SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_order_date
-- Field: Payments.OrderDate
-- Type: lookup | DataType: date | Returns: DATE
-- Lookup: OrderDate from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_date(p_payments_id TEXT)
RETURNS DATE AS $$
  SELECT (SELECT order_date::date FROM orders WHERE orders_id = (SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_order_total
-- Field: Payments.OrderTotal
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: Total from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_total(p_payments_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT total::numeric FROM orders WHERE orders_id = (SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_order_amount_paid
-- Field: Payments.OrderAmountPaid
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: AmountPaid from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_amount_paid(p_payments_id TEXT)
RETURNS NUMERIC AS $$
  SELECT calc_orders_amount_paid((SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_order_balance
-- Field: Payments.OrderBalance
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: Balance from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_balance(p_payments_id TEXT)
RETURNS NUMERIC AS $$
  SELECT calc_orders_balance((SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_order_is_paid
-- Field: Payments.OrderIsPaid
-- Type: lookup | DataType: boolean | Returns: BOOLEAN
-- Lookup: IsPaid from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_is_paid(p_payments_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT calc_orders_is_paid((SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_order_customer
-- Field: Payments.OrderCustomer
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Customer from related Orders


CREATE OR REPLACE FUNCTION calc_payments_order_customer(p_payments_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT customer::text FROM orders WHERE orders_id = (SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_customer_full_name
-- Field: Payments.CustomerFullName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: CustomerFullName from related Orders


CREATE OR REPLACE FUNCTION calc_payments_customer_full_name(p_payments_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_orders_customer_full_name((SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- calc_payments_customer_email
-- Field: Payments.CustomerEmail
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: CustomerEmail from related Orders


CREATE OR REPLACE FUNCTION calc_payments_customer_email(p_payments_id TEXT)
RETURNS TEXT AS $$
  SELECT calc_orders_customer_email((SELECT order_id FROM payments WHERE payments_id = p_payments_id));
$$ LANGUAGE sql STABLE;

-- get_orders_order_number
-- Helper function: Get OrderNumber from Orders by OrdersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_orders_order_number(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT order_number FROM orders WHERE orders_id = p_orders_id);
$$ LANGUAGE sql STABLE;

-- get_orders_order_date
-- Helper function: Get OrderDate from Orders by OrdersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_orders_order_date(p_orders_id TEXT)
RETURNS DATE AS $$
  SELECT (SELECT order_date FROM orders WHERE orders_id = p_orders_id);
$$ LANGUAGE sql STABLE;

-- get_orders_customer
-- Helper function: Get Customer from Orders by OrdersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_orders_customer(p_orders_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT customer FROM orders WHERE orders_id = p_orders_id);
$$ LANGUAGE sql STABLE;

-- get_orders_total
-- Helper function: Get Total from Orders by OrdersId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_orders_total(p_orders_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT total FROM orders WHERE orders_id = p_orders_id);
$$ LANGUAGE sql STABLE;

-- calc_payments_name
-- Field: Payments.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_payments_name(p_payments_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(payment_number, '') FROM payments WHERE payments_id = p_payments_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_jet_models_name
-- Field: JetModels.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_jet_models_name(p_jet_models_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(model_code, '') FROM jet_models WHERE jet_models_id = p_jet_models_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_jet_models_is_fifth_gen
-- Field: JetModels.IsFifthGen
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_jet_models_is_fifth_gen(p_jet_models_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT generation FROM jet_models WHERE jet_models_id = p_jet_models_id))::NUMERIC >= 5)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_jet_models_fcs_variant_count
-- Field: JetModels.FCSVariantCount
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_jet_models_fcs_variant_count(p_jet_models_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM(((COALESCE(CASE WHEN ((COALESCE(CASE WHEN (unit_price)::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (unit_price)::numeric ELSE NULL END, 0) * COALESCE(0, 0)))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN ((COALESCE(CASE WHEN (unit_price)::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (unit_price)::numeric ELSE NULL END, 0) * COALESCE(0, 0)))::numeric ELSE NULL END, 0) + COALESCE(1, 0)))::numeric), 0) FROM flight_control_systems WHERE jet_model_id = calc_jet_models_name(p_jet_models_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_jet_models_total_units_ordered
-- Field: JetModels.TotalUnitsOrdered
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_jet_models_total_units_ordered(p_jet_models_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_flight_control_systems_total_units_ordered(flight_control_systems_id))::numeric), 0) FROM flight_control_systems WHERE jet_model_id = calc_jet_models_name(p_jet_models_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_jet_models_total_revenue
-- Field: JetModels.TotalRevenue
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_jet_models_total_revenue(p_jet_models_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_flight_control_systems_total_revenue(flight_control_systems_id))::numeric), 0) FROM flight_control_systems WHERE jet_model_id = calc_jet_models_name(p_jet_models_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_jet_manufacturer
-- Field: FlightControlSystems.JetManufacturer
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Manufacturer from related JetModels


CREATE OR REPLACE FUNCTION calc_flight_control_systems_jet_manufacturer(p_flight_control_systems_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT manufacturer::text FROM jet_models WHERE jet_models_id = (SELECT jet_model_id FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id));
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_jet_generation
-- Field: FlightControlSystems.JetGeneration
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: Generation from related JetModels


CREATE OR REPLACE FUNCTION calc_flight_control_systems_jet_generation(p_flight_control_systems_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT generation::numeric FROM jet_models WHERE jet_models_id = (SELECT jet_model_id FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id));
$$ LANGUAGE sql STABLE;

-- get_jet_models_model_code
-- Helper function: Get ModelCode from JetModels by JetModelsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_jet_models_model_code(p_jet_models_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT model_code FROM jet_models WHERE jet_models_id = p_jet_models_id);
$$ LANGUAGE sql STABLE;

-- get_jet_models_manufacturer
-- Helper function: Get Manufacturer from JetModels by JetModelsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_jet_models_manufacturer(p_jet_models_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT manufacturer FROM jet_models WHERE jet_models_id = p_jet_models_id);
$$ LANGUAGE sql STABLE;

-- get_jet_models_generation
-- Helper function: Get Generation from JetModels by JetModelsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_jet_models_generation(p_jet_models_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT generation FROM jet_models WHERE jet_models_id = p_jet_models_id);
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_name
-- Field: FlightControlSystems.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_flight_control_systems_name(p_flight_control_systems_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(fcs_code, '') FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_is_triple_redundant
-- Field: FlightControlSystems.IsTripleRedundant
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_flight_control_systems_is_triple_redundant(p_flight_control_systems_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT redundancy_channels FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id))::NUMERIC >= 3)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_is_quad_redundant
-- Field: FlightControlSystems.IsQuadRedundant
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_flight_control_systems_is_quad_redundant(p_flight_control_systems_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((SELECT redundancy_channels FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id))::NUMERIC >= 4)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_meets_fifth_gen_spec
-- Field: FlightControlSystems.MeetsFifthGenSpec
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_flight_control_systems_meets_fifth_gen_spec(p_flight_control_systems_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_flight_control_systems_is_quad_redundant(p_flight_control_systems_id) AND ((SELECT NULLIF(architecture, '') FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id) = 'fly-by-wire' OR (SELECT NULLIF(architecture, '') FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id) = 'fly-by-light') AND (calc_flight_control_systems_jet_generation(p_flight_control_systems_id))::NUMERIC >= 5));
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_total_units_ordered
-- Field: FlightControlSystems.TotalUnitsOrdered
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_flight_control_systems_total_units_ordered(p_flight_control_systems_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((quantity)::numeric), 0) FROM order_lines WHERE fcs_id = calc_flight_control_systems_name(p_flight_control_systems_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_flight_control_systems_total_revenue
-- Field: FlightControlSystems.TotalRevenue
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_flight_control_systems_total_revenue(p_flight_control_systems_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((calc_order_lines_line_total(order_lines_id))::numeric), 0) FROM order_lines WHERE fcs_id = calc_flight_control_systems_name(p_flight_control_systems_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_order_lines_fcs_unit_price
-- Field: OrderLines.FCSUnitPrice
-- Type: lookup | DataType: number | Returns: NUMERIC
-- Lookup: UnitPrice from related FlightControlSystems


CREATE OR REPLACE FUNCTION calc_order_lines_fcs_unit_price(p_order_lines_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT unit_price::numeric FROM flight_control_systems WHERE flight_control_systems_id = (SELECT fcs_id FROM order_lines WHERE order_lines_id = p_order_lines_id));
$$ LANGUAGE sql STABLE;

-- calc_order_lines_fcs_architecture
-- Field: OrderLines.FCSArchitecture
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Architecture from related FlightControlSystems


CREATE OR REPLACE FUNCTION calc_order_lines_fcs_architecture(p_order_lines_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT architecture::text FROM flight_control_systems WHERE flight_control_systems_id = (SELECT fcs_id FROM order_lines WHERE order_lines_id = p_order_lines_id));
$$ LANGUAGE sql STABLE;

-- calc_order_lines_fcs_jet_model
-- Field: OrderLines.FCSJetModel
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: JetModelId from related FlightControlSystems


CREATE OR REPLACE FUNCTION calc_order_lines_fcs_jet_model(p_order_lines_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT jet_model_id::text FROM flight_control_systems WHERE flight_control_systems_id = (SELECT fcs_id FROM order_lines WHERE order_lines_id = p_order_lines_id));
$$ LANGUAGE sql STABLE;

-- calc_order_lines_fcs_meets_fifth_gen_spec
-- Field: OrderLines.FCSMeetsFifthGenSpec
-- Type: lookup | DataType: boolean | Returns: BOOLEAN
-- Lookup: MeetsFifthGenSpec from related FlightControlSystems


CREATE OR REPLACE FUNCTION calc_order_lines_fcs_meets_fifth_gen_spec(p_order_lines_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT calc_flight_control_systems_meets_fifth_gen_spec((SELECT fcs_id FROM order_lines WHERE order_lines_id = p_order_lines_id));
$$ LANGUAGE sql STABLE;

-- calc_order_lines_order_number
-- Field: OrderLines.OrderNumber
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: OrderNumber from related Orders


CREATE OR REPLACE FUNCTION calc_order_lines_order_number(p_order_lines_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT order_number::text FROM orders WHERE orders_id = (SELECT order_id FROM order_lines WHERE order_lines_id = p_order_lines_id));
$$ LANGUAGE sql STABLE;

-- calc_order_lines_order_customer
-- Field: OrderLines.OrderCustomer
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Customer from related Orders


CREATE OR REPLACE FUNCTION calc_order_lines_order_customer(p_order_lines_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT customer::text FROM orders WHERE orders_id = (SELECT order_id FROM order_lines WHERE order_lines_id = p_order_lines_id));
$$ LANGUAGE sql STABLE;

-- get_flight_control_systems_fcs_code
-- Helper function: Get FCSCode from FlightControlSystems by FlightControlSystemsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_flight_control_systems_fcs_code(p_flight_control_systems_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT fcs_code FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id);
$$ LANGUAGE sql STABLE;

-- get_flight_control_systems_architecture
-- Helper function: Get Architecture from FlightControlSystems by FlightControlSystemsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_flight_control_systems_architecture(p_flight_control_systems_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT architecture FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id);
$$ LANGUAGE sql STABLE;

-- get_flight_control_systems_redundancy_channels
-- Helper function: Get RedundancyChannels from FlightControlSystems by FlightControlSystemsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_flight_control_systems_redundancy_channels(p_flight_control_systems_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT redundancy_channels FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id);
$$ LANGUAGE sql STABLE;

-- get_flight_control_systems_unit_price
-- Helper function: Get UnitPrice from FlightControlSystems by FlightControlSystemsId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_flight_control_systems_unit_price(p_flight_control_systems_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT unit_price FROM flight_control_systems WHERE flight_control_systems_id = p_flight_control_systems_id);
$$ LANGUAGE sql STABLE;

-- calc_order_lines_name
-- Field: OrderLines.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_order_lines_name(p_order_lines_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(line_number, '') FROM order_lines WHERE order_lines_id = p_order_lines_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_order_lines_line_total
-- Field: OrderLines.LineTotal
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_order_lines_line_total(p_order_lines_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE(CASE WHEN ((SELECT quantity FROM order_lines WHERE order_lines_id = p_order_lines_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN ((SELECT quantity FROM order_lines WHERE order_lines_id = p_order_lines_id))::numeric ELSE NULL END, 0) * COALESCE(CASE WHEN (calc_order_lines_fcs_unit_price(p_order_lines_id))::text ~ '^-?[0-9]*\.?[0-9]+$' THEN (calc_order_lines_fcs_unit_price(p_order_lines_id))::numeric ELSE NULL END, 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

