-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 10
-- Total Raw Fields: 74
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- JobBoards: Table: JobBoards - Configured job board sources that can be crawled for listings.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_boards (
  job_board_id                        TEXT                 PRIMARY KEY          -- Primary key for job boards.
);
ALTER TABLE job_boards ADD COLUMN IF NOT EXISTS name TEXT;                                          -- Display name of the job board (e.g., ZipRecruiter, Indeed, LinkedIn, WeWorkRemotely).
ALTER TABLE job_boards ADD COLUMN IF NOT EXISTS description TEXT;                                   -- Notes about this board's behavior, rate limits, or special handling requirements.
ALTER TABLE job_boards ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN;                                 -- Whether this board is active for search runs.
ALTER TABLE job_boards ADD COLUMN IF NOT EXISTS max_pages INTEGER;                                  -- Maximum number of result pages to crawl per search URL. Default is 3.
ALTER TABLE job_boards ADD COLUMN IF NOT EXISTS is_headless BOOLEAN;                                -- Whether to run the Playwright browser in headless mode for this board.
ALTER TABLE job_boards ADD COLUMN IF NOT EXISTS browser_channel TEXT;                               -- Optional browser variant to use (e.g., msedge). NULL means default Chromium.
COMMENT ON TABLE job_boards IS 'Table: JobBoards - Configured job board sources that can be crawled for listings.';
COMMENT ON COLUMN job_boards.job_board_id IS 'Primary key for job boards.';
COMMENT ON COLUMN job_boards.name IS 'Display name of the job board (e.g., ZipRecruiter, Indeed, LinkedIn, WeWorkRemotely).';
COMMENT ON COLUMN job_boards.description IS 'Notes about this board''s behavior, rate limits, or special handling requirements.';
COMMENT ON COLUMN job_boards.is_enabled IS 'Whether this board is active for search runs.';
COMMENT ON COLUMN job_boards.max_pages IS 'Maximum number of result pages to crawl per search URL. Default is 3.';
COMMENT ON COLUMN job_boards.is_headless IS 'Whether to run the Playwright browser in headless mode for this board.';
COMMENT ON COLUMN job_boards.browser_channel IS 'Optional browser variant to use (e.g., msedge). NULL means default Chromium.';

-- ----------------------------------------------------------------------------
-- SearchUrls: Table: SearchUrls - Individual search URLs configured per board, each representing a specific query to crawl.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS search_urls (
  search_url_id                       TEXT                 PRIMARY KEY          -- Primary key for search URLs.
);
ALTER TABLE search_urls ADD COLUMN IF NOT EXISTS name TEXT;                                         -- Descriptive label for this search query (e.g., 'Staff Engineer - Remote').
ALTER TABLE search_urls ADD COLUMN IF NOT EXISTS job_board TEXT;                                    -- Which job board this search URL belongs to.
ALTER TABLE search_urls ADD COLUMN IF NOT EXISTS url TEXT;                                          -- The full search URL to crawl on this board.
ALTER TABLE search_urls ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN;                                -- Whether this search URL is active for crawling.
COMMENT ON TABLE search_urls IS 'Table: SearchUrls - Individual search URLs configured per board, each representing a specific query to crawl.';
COMMENT ON COLUMN search_urls.search_url_id IS 'Primary key for search URLs.';
COMMENT ON COLUMN search_urls.name IS 'Descriptive label for this search query (e.g., ''Staff Engineer - Remote'').';
COMMENT ON COLUMN search_urls.job_board IS 'Which job board this search URL belongs to.';
COMMENT ON COLUMN search_urls.url IS 'The full search URL to crawl on this board.';
COMMENT ON COLUMN search_urls.is_enabled IS 'Whether this search URL is active for crawling.';

-- ----------------------------------------------------------------------------
-- RoleArchetypes: Table: RoleArchetypes - Target role descriptions that define ideal job types for semantic matching.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS role_archetypes (
  role_archetype_id                   TEXT                 PRIMARY KEY          -- Primary key for role archetypes.
);
ALTER TABLE role_archetypes ADD COLUMN IF NOT EXISTS name TEXT;                                     -- Archetype title (e.g., 'Staff Platform Architect', 'AI Systems Engineer').
ALTER TABLE role_archetypes ADD COLUMN IF NOT EXISTS description TEXT;                              -- Natural language description of this ideal role type. Embedded into ChromaDB for archetype scoring.
ALTER TABLE role_archetypes ADD COLUMN IF NOT EXISTS signals_positive TEXT;                         -- Comma-separated keywords or phrases indicating strong fit for this archetype.
ALTER TABLE role_archetypes ADD COLUMN IF NOT EXISTS signals_negative TEXT;                         -- Comma-separated keywords or phrases indicating misfit for this archetype.
COMMENT ON TABLE role_archetypes IS 'Table: RoleArchetypes - Target role descriptions that define ideal job types for semantic matching.';
COMMENT ON COLUMN role_archetypes.role_archetype_id IS 'Primary key for role archetypes.';
COMMENT ON COLUMN role_archetypes.name IS 'Archetype title (e.g., ''Staff Platform Architect'', ''AI Systems Engineer'').';
COMMENT ON COLUMN role_archetypes.description IS 'Natural language description of this ideal role type. Embedded into ChromaDB for archetype scoring.';
COMMENT ON COLUMN role_archetypes.signals_positive IS 'Comma-separated keywords or phrases indicating strong fit for this archetype.';
COMMENT ON COLUMN role_archetypes.signals_negative IS 'Comma-separated keywords or phrases indicating misfit for this archetype.';

-- ----------------------------------------------------------------------------
-- RubricDimensions: Table: RubricDimensions - Universal evaluation criteria applied to all listings for culture and quality scoring.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS rubric_dimensions (
  rubric_dimension_id                 TEXT                 PRIMARY KEY          -- Primary key for rubric dimensions.
);
ALTER TABLE rubric_dimensions ADD COLUMN IF NOT EXISTS name TEXT;                                   -- Dimension name (e.g., 'Role Scope', 'Technical Depth').
ALTER TABLE rubric_dimensions ADD COLUMN IF NOT EXISTS description TEXT;                            -- What this dimension evaluates and why it matters.
ALTER TABLE rubric_dimensions ADD COLUMN IF NOT EXISTS signals_positive TEXT;                       -- Comma-separated positive indicators for this dimension. Embedded into global_positive_signals collection.
ALTER TABLE rubric_dimensions ADD COLUMN IF NOT EXISTS signals_negative TEXT;                       -- Comma-separated red flags for this dimension. Embedded into negative_signals collection.
COMMENT ON TABLE rubric_dimensions IS 'Table: RubricDimensions - Universal evaluation criteria applied to all listings for culture and quality scoring.';
COMMENT ON COLUMN rubric_dimensions.rubric_dimension_id IS 'Primary key for rubric dimensions.';
COMMENT ON COLUMN rubric_dimensions.name IS 'Dimension name (e.g., ''Role Scope'', ''Technical Depth'').';
COMMENT ON COLUMN rubric_dimensions.description IS 'What this dimension evaluates and why it matters.';
COMMENT ON COLUMN rubric_dimensions.signals_positive IS 'Comma-separated positive indicators for this dimension. Embedded into global_positive_signals collection.';
COMMENT ON COLUMN rubric_dimensions.signals_negative IS 'Comma-separated red flags for this dimension. Embedded into negative_signals collection.';

-- ----------------------------------------------------------------------------
-- Resumes: Table: Resumes - Candidate resumes that anchor the entire RAG scoring pipeline. Every search run scores job listings against a specific resume's embeddings.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resumes (
  resume_id                           TEXT                 PRIMARY KEY          -- Primary key for resumes.
);
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS name TEXT;                                             -- Display name for this resume version (e.g., 'Platform Engineer - 2026Q1').
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS description TEXT;                                      -- Notes about what this resume version emphasizes or targets.
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS file_path TEXT;                                        -- Path to the resume markdown file relative to project root (e.g., 'data/resume.md').
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS indexed_at TIMESTAMPTZ;                                -- When this resume was last chunked and embedded into ChromaDB. NULL means not yet indexed.
COMMENT ON TABLE resumes IS 'Table: Resumes - Candidate resumes that anchor the entire RAG scoring pipeline. Every search run scores job listings against a specific resume''s embeddings.';
COMMENT ON COLUMN resumes.resume_id IS 'Primary key for resumes.';
COMMENT ON COLUMN resumes.name IS 'Display name for this resume version (e.g., ''Platform Engineer - 2026Q1'').';
COMMENT ON COLUMN resumes.description IS 'Notes about what this resume version emphasizes or targets.';
COMMENT ON COLUMN resumes.file_path IS 'Path to the resume markdown file relative to project root (e.g., ''data/resume.md'').';
COMMENT ON COLUMN resumes.indexed_at IS 'When this resume was last chunked and embedded into ChromaDB. NULL means not yet indexed.';

-- ----------------------------------------------------------------------------
-- ResumeSections: Table: ResumeSections - Individual chunks of a resume, split by ## headings. Each section is embedded separately into ChromaDB for granular semantic matching against job descriptions.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS resume_sections (
  resume_section_id                   TEXT                 PRIMARY KEY          -- Primary key. Slug of the section heading (e.g., 'resume-core-strengths').
);
ALTER TABLE resume_sections ADD COLUMN IF NOT EXISTS name TEXT;                                     -- Section heading text (e.g., 'Core Strengths', 'Experience').
ALTER TABLE resume_sections ADD COLUMN IF NOT EXISTS resume TEXT;                                   -- Which resume this section belongs to.
ALTER TABLE resume_sections ADD COLUMN IF NOT EXISTS section_order INTEGER;                         -- Order of this section within the resume (1-based). Preserves document structure.
ALTER TABLE resume_sections ADD COLUMN IF NOT EXISTS content TEXT;                                  -- Full text of this section including the ## heading and all body content up to the next ## heading. This is the document embedded into ChromaDB.
ALTER TABLE resume_sections ADD COLUMN IF NOT EXISTS chroma_doc_id TEXT;                            -- Document ID in the ChromaDB resume collection (e.g., 'resume-core-strengths'). Used for idempotent upserts.
COMMENT ON TABLE resume_sections IS 'Table: ResumeSections - Individual chunks of a resume, split by ## headings. Each section is embedded separately into ChromaDB for granular semantic matching against job descriptions.';
COMMENT ON COLUMN resume_sections.resume_section_id IS 'Primary key. Slug of the section heading (e.g., ''resume-core-strengths'').';
COMMENT ON COLUMN resume_sections.name IS 'Section heading text (e.g., ''Core Strengths'', ''Experience'').';
COMMENT ON COLUMN resume_sections.resume IS 'Which resume this section belongs to.';
COMMENT ON COLUMN resume_sections.section_order IS 'Order of this section within the resume (1-based). Preserves document structure.';
COMMENT ON COLUMN resume_sections.content IS 'Full text of this section including the ## heading and all body content up to the next ## heading. This is the document embedded into ChromaDB.';
COMMENT ON COLUMN resume_sections.chroma_doc_id IS 'Document ID in the ChromaDB resume collection (e.g., ''resume-core-strengths''). Used for idempotent upserts.';

-- ----------------------------------------------------------------------------
-- SearchRuns: Table: SearchRuns - Individual pipeline execution runs that crawl boards, score listings, and produce ranked results. Each run scores against a specific resume.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS search_runs (
  search_run_id                       TEXT                 PRIMARY KEY          -- Primary key for search runs.
);
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS name TEXT;                                         -- Human-readable run label (typically date + time).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS resume TEXT;                                       -- Which resume was used for fit_score computation in this run. The central link in the RAG pipeline.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS run_date TIMESTAMPTZ;                              -- When this search run was executed.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS archetype_weight NUMERIC;                          -- Weight applied to archetype match score (0.0 - 1.0).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS fit_weight NUMERIC;                                -- Weight applied to resume fit score (0.0 - 1.0).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS history_weight NUMERIC;                            -- Weight applied to decision history score (0.0 - 1.0).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS comp_weight NUMERIC;                               -- Weight applied to compensation alignment score (0.0 - 1.0).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS negative_weight NUMERIC;                           -- Penalty multiplier for negative signal score (0.0 - 1.0).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS culture_weight NUMERIC;                            -- Weight applied to culture/quality dimension score (0.0 - 1.0).
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS base_salary NUMERIC;                               -- Target annual salary for compensation scoring. Default $220,000.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS min_score_threshold NUMERIC;                       -- Minimum final score to include in results (0.0 - 1.0). Default 0.45.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS disqualify_on_llm_flag BOOLEAN;                    -- Whether to run the LLM disqualifier pass on listings.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS total_found INTEGER;                               -- Total listings collected from boards in this run.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS total_scored INTEGER;                              -- Total listings that passed through the scorer.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS total_excluded INTEGER;                            -- Listings filtered below min_score_threshold.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS total_deduplicated INTEGER;                        -- Duplicate listings collapsed during this run.
ALTER TABLE search_runs ADD COLUMN IF NOT EXISTS failed_listings INTEGER;                           -- Count of listings that failed scoring.
COMMENT ON TABLE search_runs IS 'Table: SearchRuns - Individual pipeline execution runs that crawl boards, score listings, and produce ranked results. Each run scores against a specific resume.';
COMMENT ON COLUMN search_runs.search_run_id IS 'Primary key for search runs.';
COMMENT ON COLUMN search_runs.name IS 'Human-readable run label (typically date + time).';
COMMENT ON COLUMN search_runs.resume IS 'Which resume was used for fit_score computation in this run. The central link in the RAG pipeline.';
COMMENT ON COLUMN search_runs.run_date IS 'When this search run was executed.';
COMMENT ON COLUMN search_runs.archetype_weight IS 'Weight applied to archetype match score (0.0 - 1.0).';
COMMENT ON COLUMN search_runs.fit_weight IS 'Weight applied to resume fit score (0.0 - 1.0).';
COMMENT ON COLUMN search_runs.history_weight IS 'Weight applied to decision history score (0.0 - 1.0).';
COMMENT ON COLUMN search_runs.comp_weight IS 'Weight applied to compensation alignment score (0.0 - 1.0).';
COMMENT ON COLUMN search_runs.negative_weight IS 'Penalty multiplier for negative signal score (0.0 - 1.0).';
COMMENT ON COLUMN search_runs.culture_weight IS 'Weight applied to culture/quality dimension score (0.0 - 1.0).';
COMMENT ON COLUMN search_runs.base_salary IS 'Target annual salary for compensation scoring. Default $220,000.';
COMMENT ON COLUMN search_runs.min_score_threshold IS 'Minimum final score to include in results (0.0 - 1.0). Default 0.45.';
COMMENT ON COLUMN search_runs.disqualify_on_llm_flag IS 'Whether to run the LLM disqualifier pass on listings.';
COMMENT ON COLUMN search_runs.total_found IS 'Total listings collected from boards in this run.';
COMMENT ON COLUMN search_runs.total_scored IS 'Total listings that passed through the scorer.';
COMMENT ON COLUMN search_runs.total_excluded IS 'Listings filtered below min_score_threshold.';
COMMENT ON COLUMN search_runs.total_deduplicated IS 'Duplicate listings collapsed during this run.';
COMMENT ON COLUMN search_runs.failed_listings IS 'Count of listings that failed scoring.';

-- ----------------------------------------------------------------------------
-- JobListings: Table: JobListings - Individual job postings scraped from job boards, normalized to a common data contract.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS job_listings (
  job_listing_id                      TEXT                 PRIMARY KEY          -- Primary key. Composite of board and external ID (e.g., 'ziprecruiter-abc123').
);
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS name TEXT;                                        -- Job title as listed on the board, sanitized for filesystem safety.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS job_board TEXT;                                   -- Which job board this listing was scraped from.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS external_id TEXT;                                 -- The job board's unique identifier for this posting.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS company TEXT;                                     -- Company name, sanitized for filesystem safety.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS location TEXT;                                    -- Job location (city, state, remote, hybrid, etc.).
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS url TEXT;                                         -- Direct URL link to the job posting on the board.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS full_text TEXT;                                   -- Complete job description text. Max 250,000 characters. Embedded into ChromaDB for scoring.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS posted_at TIMESTAMPTZ;                            -- When the job was posted on the board.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS comp_min NUMERIC;                                 -- Minimum compensation in USD, parsed from job description.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS comp_max NUMERIC;                                 -- Maximum compensation in USD, parsed from job description.
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS comp_source TEXT;                                 -- Source of compensation data: 'employer' (from JD) or 'estimated' (board-generated).
ALTER TABLE job_listings ADD COLUMN IF NOT EXISTS comp_text TEXT;                                   -- Raw compensation text matched from the job description (e.g., '$180,000 - $220,000/year').
COMMENT ON TABLE job_listings IS 'Table: JobListings - Individual job postings scraped from job boards, normalized to a common data contract.';
COMMENT ON COLUMN job_listings.job_listing_id IS 'Primary key. Composite of board and external ID (e.g., ''ziprecruiter-abc123'').';
COMMENT ON COLUMN job_listings.name IS 'Job title as listed on the board, sanitized for filesystem safety.';
COMMENT ON COLUMN job_listings.job_board IS 'Which job board this listing was scraped from.';
COMMENT ON COLUMN job_listings.external_id IS 'The job board''s unique identifier for this posting.';
COMMENT ON COLUMN job_listings.company IS 'Company name, sanitized for filesystem safety.';
COMMENT ON COLUMN job_listings.location IS 'Job location (city, state, remote, hybrid, etc.).';
COMMENT ON COLUMN job_listings.url IS 'Direct URL link to the job posting on the board.';
COMMENT ON COLUMN job_listings.full_text IS 'Complete job description text. Max 250,000 characters. Embedded into ChromaDB for scoring.';
COMMENT ON COLUMN job_listings.posted_at IS 'When the job was posted on the board.';
COMMENT ON COLUMN job_listings.comp_min IS 'Minimum compensation in USD, parsed from job description.';
COMMENT ON COLUMN job_listings.comp_max IS 'Maximum compensation in USD, parsed from job description.';
COMMENT ON COLUMN job_listings.comp_source IS 'Source of compensation data: ''employer'' (from JD) or ''estimated'' (board-generated).';
COMMENT ON COLUMN job_listings.comp_text IS 'Raw compensation text matched from the job description (e.g., ''$180,000 - $220,000/year'').';

-- ----------------------------------------------------------------------------
-- ScoreResults: Table: ScoreResults - Component and final scores for a job listing within a specific search run.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS score_results (
  score_result_id                     TEXT                 PRIMARY KEY          -- Primary key for score results.
);
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS job_listing TEXT;                                -- The job listing that was scored.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS search_run TEXT;                                 -- The search run during which this score was produced.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS fit_score NUMERIC;                               -- Semantic similarity to resume (0.0 - 1.0). Based on cosine distance in resume ChromaDB collection.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS archetype_score NUMERIC;                         -- Match to role archetypes (0.0 - 1.0). Based on cosine distance in role_archetypes collection.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS history_score NUMERIC;                           -- Match to past accepted decisions (0.0 - 1.0). Only 'yes' verdicts contribute.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS comp_score NUMERIC;                              -- Compensation alignment with base salary (0.0 - 1.0). Non-linear curve; 0.5 when comp is missing.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS negative_score NUMERIC;                          -- Penalty score from negative signal matches (0.0 - 1.0). Subtracted from positive scores.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS culture_score NUMERIC;                           -- Match to positive culture/quality dimensions (0.0 - 1.0).
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS is_disqualified BOOLEAN;                         -- Whether the LLM disqualifier flagged this listing. If true, final score is forced to 0.0.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS disqualifier_reason TEXT;                        -- Free-text explanation from the LLM disqualifier about why the role was flagged.
ALTER TABLE score_results ADD COLUMN IF NOT EXISTS duplicate_boards TEXT;                           -- Comma-separated list of other boards where this same job appeared (cross-board deduplication).
COMMENT ON TABLE score_results IS 'Table: ScoreResults - Component and final scores for a job listing within a specific search run.';
COMMENT ON COLUMN score_results.score_result_id IS 'Primary key for score results.';
COMMENT ON COLUMN score_results.job_listing IS 'The job listing that was scored.';
COMMENT ON COLUMN score_results.search_run IS 'The search run during which this score was produced.';
COMMENT ON COLUMN score_results.fit_score IS 'Semantic similarity to resume (0.0 - 1.0). Based on cosine distance in resume ChromaDB collection.';
COMMENT ON COLUMN score_results.archetype_score IS 'Match to role archetypes (0.0 - 1.0). Based on cosine distance in role_archetypes collection.';
COMMENT ON COLUMN score_results.history_score IS 'Match to past accepted decisions (0.0 - 1.0). Only ''yes'' verdicts contribute.';
COMMENT ON COLUMN score_results.comp_score IS 'Compensation alignment with base salary (0.0 - 1.0). Non-linear curve; 0.5 when comp is missing.';
COMMENT ON COLUMN score_results.negative_score IS 'Penalty score from negative signal matches (0.0 - 1.0). Subtracted from positive scores.';
COMMENT ON COLUMN score_results.culture_score IS 'Match to positive culture/quality dimensions (0.0 - 1.0).';
COMMENT ON COLUMN score_results.is_disqualified IS 'Whether the LLM disqualifier flagged this listing. If true, final score is forced to 0.0.';
COMMENT ON COLUMN score_results.disqualifier_reason IS 'Free-text explanation from the LLM disqualifier about why the role was flagged.';
COMMENT ON COLUMN score_results.duplicate_boards IS 'Comma-separated list of other boards where this same job appeared (cross-board deduplication).';

-- ----------------------------------------------------------------------------
-- Decisions: Table: Decisions - Operator verdicts on reviewed job listings, used as training signal for future scoring.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS decisions (
  decision_id                         TEXT                 PRIMARY KEY          -- Primary key for decisions.
);
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS job_listing TEXT;                                    -- The job listing this decision is about.
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS verdict TEXT;                                        -- Operator's judgment: 'yes' (interested), 'no' (rejected), 'maybe' (uncertain), or 'removed' (retracted).
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS reason TEXT;                                         -- Free-text explanation for the verdict. Stored for audit purposes.
ALTER TABLE decisions ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ;                             -- Timestamp when this decision was recorded.
COMMENT ON TABLE decisions IS 'Table: Decisions - Operator verdicts on reviewed job listings, used as training signal for future scoring.';
COMMENT ON COLUMN decisions.decision_id IS 'Primary key for decisions.';
COMMENT ON COLUMN decisions.job_listing IS 'The job listing this decision is about.';
COMMENT ON COLUMN decisions.verdict IS 'Operator''s judgment: ''yes'' (interested), ''no'' (rejected), ''maybe'' (uncertain), or ''removed'' (retracted).';
COMMENT ON COLUMN decisions.reason IS 'Free-text explanation for the verdict. Stored for audit purposes.';
COMMENT ON COLUMN decisions.recorded_at IS 'Timestamp when this decision was recorded.';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- SearchUrls
CREATE INDEX IF NOT EXISTS idx_search_urls_job_board ON search_urls (job_board);

-- ResumeSections
CREATE INDEX IF NOT EXISTS idx_resume_sections_resume ON resume_sections (resume);

-- SearchRuns
CREATE INDEX IF NOT EXISTS idx_search_runs_resume ON search_runs (resume);

-- JobListings
CREATE INDEX IF NOT EXISTS idx_job_listings_job_board ON job_listings (job_board);

-- ScoreResults
CREATE INDEX IF NOT EXISTS idx_score_results_job_listing ON score_results (job_listing);
CREATE INDEX IF NOT EXISTS idx_score_results_search_run ON score_results (search_run);

-- Decisions
CREATE INDEX IF NOT EXISTS idx_decisions_job_listing ON decisions (job_listing);

-- 7 FK index(es) declared.
