-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- ----------------------------------------------------------------------------
-- JobBoards: Table: JobBoards - Configured job board sources that can be crawled for listings.
-- ----------------------------------------------------------------------------
INSERT INTO job_boards (job_board_id, name, description, is_enabled, max_pages, is_headless, browser_channel)
VALUES ('ziprecruiter', 'ZipRecruiter', 'Primary board. Uses Next.js SERP structure. Full adapter implemented.', TRUE, 3, TRUE, NULL) ON CONFLICT (job_board_id) DO NOTHING;

INSERT INTO job_boards (job_board_id, name, description, is_enabled, max_pages, is_headless, browser_channel)
VALUES ('indeed', 'Indeed', 'High-volume general board. Adapter planned.', FALSE, 3, TRUE, NULL) ON CONFLICT (job_board_id) DO NOTHING;

INSERT INTO job_boards (job_board_id, name, description, is_enabled, max_pages, is_headless, browser_channel)
VALUES ('linkedin', 'LinkedIn', 'Overnight mode recommended. Stealth browsing, throttled requests. Stricter bot detection.', FALSE, 2, FALSE, 'msedge') ON CONFLICT (job_board_id) DO NOTHING;

INSERT INTO job_boards (job_board_id, name, description, is_enabled, max_pages, is_headless, browser_channel)
VALUES ('weworkremotely', 'WeWorkRemotely', 'Remote-focused board. Smaller volume, higher signal for remote roles.', FALSE, 3, TRUE, NULL) ON CONFLICT (job_board_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- SearchUrls: Table: SearchUrls - Individual search URLs configured per board, each representing a specific query to crawl.
-- ----------------------------------------------------------------------------
INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('zr-staff-platform-architect', 'Staff Platform Architect - Remote', 'ziprecruiter', 'https://www.ziprecruiter.com/jobs-search?search=staff+platform+architect&location=Remote+(USA)', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('zr-principal-data-platform', 'Principal Engineer Data Platform - Remote', 'ziprecruiter', 'https://www.ziprecruiter.com/jobs-search?search=principal+engineer+data+platform&location=Remote+(USA)', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('zr-devrel-engineer', 'Developer Relations Engineer - Remote', 'ziprecruiter', 'https://www.ziprecruiter.com/jobs-search?search=developer+relations+engineer&location=Remote+(USA)', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('indeed-staff-platform-architect', 'Staff Platform Architect - Remote', 'indeed', 'https://www.indeed.com/jobs?q=staff+platform+architect&l=Remote&sc=0kf%3Aattr%28DSQF7%29%3B', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('indeed-principal-data-platform', 'Principal Engineer Data Platform - Remote', 'indeed', 'https://www.indeed.com/jobs?q=principal+engineer+data+platform&l=Remote&sc=0kf%3Aattr%28DSQF7%29%3B', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('wwr-staff-engineer', 'Staff Engineer', 'weworkremotely', 'https://weworkremotely.com/remote-jobs/search?term=staff+engineer', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('wwr-principal-architect', 'Principal Architect', 'weworkremotely', 'https://weworkremotely.com/remote-jobs/search?term=principal+architect', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

INSERT INTO search_urls (search_url_id, name, job_board, url, is_enabled)
VALUES ('li-staff-platform-architect', 'Staff Platform Architect - Remote', 'linkedin', 'https://www.linkedin.com/jobs/search/?keywords=staff+platform+architect&f_WT=2', TRUE) ON CONFLICT (search_url_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- RoleArchetypes: Table: RoleArchetypes - Target role descriptions that define ideal job types for semantic matching.
-- ----------------------------------------------------------------------------
INSERT INTO role_archetypes (role_archetype_id, name, description, signals_positive, signals_negative)
VALUES ('ai-systems-engineer', 'AI Systems Engineer / AI Platform Architect', 'Designs and builds production ML/AI infrastructure: model serving, training pipelines, vector stores, embedding services, and LLM orchestration layers.', 'ML infrastructure, model serving, training pipeline, vector database, LLM orchestration, embedding service, MLOps, GPU cluster', 'frontend only, marketing automation, junior data analyst, manual QA') ON CONFLICT (role_archetype_id) DO NOTHING;

INSERT INTO role_archetypes (role_archetype_id, name, description, signals_positive, signals_negative)
VALUES ('staff-platform-architect', 'Staff Platform Architect', 'Cross-team technical leadership for platform and infrastructure. Drives architectural decisions, defines system boundaries, and mentors engineering teams.', 'platform architecture, system design, cross-team influence, technical strategy, API design, distributed systems, mentorship', 'individual contributor only, no architecture scope, ticket taker, single-team') ON CONFLICT (role_archetype_id) DO NOTHING;

INSERT INTO role_archetypes (role_archetype_id, name, description, signals_positive, signals_negative)
VALUES ('principal-data-platform', 'Principal Data Platform Engineer', 'Owns data infrastructure at scale: data pipelines, warehousing, streaming, and analytical platform services.', 'data platform, data pipeline, streaming, data warehouse, Spark, Kafka, Flink, dbt, analytical infrastructure', 'BI analyst, dashboard builder, Excel reporting, entry-level data') ON CONFLICT (role_archetype_id) DO NOTHING;

INSERT INTO role_archetypes (role_archetype_id, name, description, signals_positive, signals_negative)
VALUES ('devrel-evangelist', 'Developer Relations / Technical Evangelist', 'External-facing technical role bridging engineering and developer community. Produces technical content, speaks at conferences, and drives API/SDK adoption.', 'developer relations, developer advocacy, technical writing, conference speaking, SDK adoption, API evangelism, community building', 'sales quota, cold calling, non-technical marketing, pure product management') ON CONFLICT (role_archetype_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- RubricDimensions: Table: RubricDimensions - Universal evaluation criteria applied to all listings for culture and quality scoring.
-- ----------------------------------------------------------------------------
INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('role-scope', 'Role Scope', 'Cross-team influence and architectural reach vs. narrow single-team execution.', 'cross-team, architectural influence, system design ownership, technical strategy', 'ticket taker, narrow scope, single feature team, no design authority') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('technical-depth', 'Technical Depth', 'Infrastructure and platform work vs. web/feature dev.', 'infrastructure, platform, distributed systems, systems programming, performance engineering', 'WordPress, Squarespace, basic CRUD, landing pages, no-code') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('operational-burden', 'Operational Burden', 'On-call/SRE load vs. platform engineering focus.', 'platform engineering, build tools, developer experience, automation', '24/7 on-call, pager duty primary, incident commander rotation, SRE-heavy') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('industry-alignment', 'Industry Alignment', 'Company mission and product category alignment with candidate interests.', 'developer tools, AI/ML, data infrastructure, open source, cloud platform', 'adtech, gambling, payday lending, surveillance') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('employment-structure', 'Employment Structure', 'Direct hire vs. staffing agency/contract positions.', 'direct hire, full-time, equity, benefits', 'staffing agency, contract-to-hire, vendor chain, W2 through third party, corp-to-corp') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('seniority-mismatch', 'Seniority Mismatch', 'Role level vs. candidate expectations for staff+ positions.', 'staff, principal, distinguished, fellow, architect, VP engineering, director', 'junior, entry-level, associate, new grad, 0-2 years experience, intern') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('compensation-red-flags', 'Compensation Red Flags', 'Compensation transparency and alignment with staff/principal market expectations.', 'transparent compensation range, top-of-range meets target minimum, staff/principal market rate', 'equity-only compensation, unpaid or volunteer, below market for principal-level, hourly contractor rate far below salary') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('culture-work-model', 'Culture & Work Model', 'Remote-first culture, work-life balance, and engineering autonomy indicators.', 'remote-first, async-first, work-life balance, engineering autonomy, written communication culture, high-trust low-chaos', 'mandatory return-to-office, 4+ days on-site, 60+ hour weeks, military-style command, fast-paced high-pressure, ambiguous expectations') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('ethical-alignment', 'Ethical Alignment', 'Company mission alignment with humane and privacy-respecting values.', 'mission-driven, humane impact, privacy-respecting, healthcare, education, public-good', 'weapons manufacturing, military contracting, surveillance technology, behavioral profiling, predatory lending') ON CONFLICT (rubric_dimension_id) DO NOTHING;

INSERT INTO rubric_dimensions (rubric_dimension_id, name, description, signals_positive, signals_negative)
VALUES ('neurodivergence-compatibility', 'Neurodivergence Compatibility', 'Structured processes, predictable workflows, and low-meeting culture for neurodivergent-friendly work environments.', 'clear communication norms, structured processes, predictable workflows, low-meeting culture, async-first, psychological safety', 'constant context switching, interrupt-driven, ambiguity without support, high-meeting culture, synchronous dependency, chaotic environment') ON CONFLICT (rubric_dimension_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- Resumes: Table: Resumes - Candidate resumes that anchor the entire RAG scoring pipeline. Every search run scores job listings against a specific resume's embeddings.
-- ----------------------------------------------------------------------------
INSERT INTO resumes (resume_id, name, description, file_path, indexed_at)
VALUES ('resume-platform-2026q1', 'Platform Engineer - 2026 Q1', 'Emphasizes distributed systems, platform architecture, and AI/ML infrastructure. Targets staff+ IC and architect roles.', 'data/resume.md', '2026-04-01T07:45:00Z') ON CONFLICT (resume_id) DO NOTHING;

-- ----------------------------------------------------------------------------
-- ResumeSections: Table: ResumeSections - Individual chunks of a resume, split by ## headings. Each section is embedded separately into ChromaDB for granular semantic matching against job descriptions.
-- ----------------------------------------------------------------------------
INSERT INTO resume_sections (resume_section_id, name, resume, section_order, content, chroma_doc_id)
VALUES ('resume-platform-2026q1-summary', 'Summary', 'resume-platform-2026q1', 1, '## Summary
Senior platform engineer with 15+ years building distributed systems, data pipelines, and AI/ML infrastructure. Track record of cross-team technical leadership at scale.', 'resume-summary') ON CONFLICT (resume_section_id) DO NOTHING;

INSERT INTO resume_sections (resume_section_id, name, resume, section_order, content, chroma_doc_id)
VALUES ('resume-platform-2026q1-core-strengths', 'Core Strengths', 'resume-platform-2026q1', 2, '## Core Strengths
- Distributed systems architecture (Kubernetes, gRPC, service mesh)
- ML/AI platform engineering (model serving, training pipelines, vector stores)
- Technical strategy and mentorship across 50+ engineer orgs
- Data infrastructure (Kafka, Spark, Flink, dbt)', 'resume-core-strengths') ON CONFLICT (resume_section_id) DO NOTHING;

INSERT INTO resume_sections (resume_section_id, name, resume, section_order, content, chroma_doc_id)
VALUES ('resume-platform-2026q1-experience', 'Experience', 'resume-platform-2026q1', 3, '## Experience
### Staff Platform Engineer — CloudScale Inc (2022-2026)
Led platform architecture for ML serving infrastructure. Designed multi-region Kubernetes deployment strategy. Reduced model inference latency 40%.
### Senior Engineer — DataForge (2018-2022)
Built real-time data pipelines processing 2M events/sec. Migrated monolith to event-driven microservices.', 'resume-experience') ON CONFLICT (resume_section_id) DO NOTHING;

INSERT INTO resume_sections (resume_section_id, name, resume, section_order, content, chroma_doc_id)
VALUES ('resume-platform-2026q1-earlier-roles', 'Earlier Roles', 'resume-platform-2026q1', 4, '## Earlier Roles
### Software Engineer — StartupCo (2014-2018)
Full-stack development, API design, early DevOps adoption.
### Junior Developer — Agency LLC (2011-2014)
Web application development, client projects, learned software engineering fundamentals.', 'resume-earlier-roles') ON CONFLICT (resume_section_id) DO NOTHING;

