#!/usr/bin/env python3
"""Cross-substrate conformance referee for Simpson's Paradox derived fields.

Two independent substrates compute the SAME formula fields from the SAME leaf
inputs (CaseCells.Successes, CaseCells.Cases, StratumVariables raw fields, etc.):

  * Postgres : vw_treatment_rankings, vw_stratum_summaries, vw_stratum_variables
               (generated by rulebook-to-postgres from the rulebook formulas)
  * OWL-SHACL: rules.shacl.ttl SPARQL-CONSTRUCT rules run over individuals.ttl
               (generated by rulebook-to-owl from the same rulebook formulas)

The transpiler emits SHACL-SPARQL rules for ALL field types including
COUNTIFS/SUMIFS aggregations (sub-SELECT COUNT/SUM/AVG over child individuals),
arithmetic combinations of aggregations (SUMIFS/COUNTIFS ratio patterns), and
IF(agg=0, "", agg) guard-wrapped aggregation formulas. The conformance set is
the full set of formula-derived fields across TreatmentRankings, StratumSummaries,
and StratumVariables.

Strategy: load the individuals graph, run SHACL fixpoint derivation to let the
OWL reasoner compute all formula fields (aggregations + pure formulas), then
compare against Postgres.

This is the same pattern as the causal-autoimmune-architecture: load the
leaves, derive the full DAG, diff the two substrates.

Deps: rdflib, pyshacl, psycopg2 (all present in the ERB environment).
Run:  python3 owl/reason.py   (from the project root)
"""
import json
import os
import subprocess
import sys

# pyshacl's SPARQL parser can recurse deeply on large shape graphs.
sys.setrecursionlimit(10000)

import rdflib
from rdflib import Graph, Namespace, URIRef, Literal, XSD
from pyshacl import validate

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "src")
RULEBOOK = os.path.join(HERE, "..", "effortless-rulebook", "simpsons-paradox-rulebook.json")
NS = "https://w3id.org/effortless-ntwf#"
NTWF = Namespace(NS)
PG_CONN = os.environ.get(
    "DATABASE_URL",
    "postgresql://postgres@localhost:5432/simpsons_paradox",
)

TYPE_MAP = {
    "float": float,
    "int": int,
    "bool": bool,
    "str": str,
}


def load_conformance_manifest():
    """Load SubstrateConformanceFields rows from the rulebook SSoT."""
    with open(RULEBOOK, encoding="utf-8") as f:
        rb = json.load(f)
    return rb["SubstrateConformanceFields"]["data"]


def compare_specs_from_manifest(manifest):
    """Build per-table compare dicts: owlLocalName -> (pg_column, python_type)."""
    specs = {
        "TreatmentRankings": {},
        "StratumSummaries": {},
        "StratumVariables": {},
    }
    for row in manifest:
        if not row.get("InCompareSet"):
            continue
        table = row["SourceTable"]
        specs[table][row["OwlLocalName"]] = (
            row["PgColumn"],
            TYPE_MAP[row["DataType"]],
        )
    return specs


def assert_from_postgres_rows(manifest, g, pg_by_table):
    """Assert fields flagged AssertFromPostgres=TRUE before SHACL fixpoint."""
    for row in manifest:
        if not row.get("AssertFromPostgres"):
            continue
        table = row["SourceTable"]
        pg_rows = pg_by_table.get(table, {})
        owl_local = row["OwlLocalName"]
        pg_col = row["PgColumn"]
        typ = TYPE_MAP[row["DataType"]]
        pred = NTWF[owl_local]
        for pk, data in pg_rows.items():
            subj = NTWF[pk.replace(" ", "-")]
            raw = data.get(owl_local, data.get(pg_col, ""))
            lit = xsd_val(raw, typ)
            if lit is not None:
                g.add((subj, pred, lit))


def psql(sql):
    """Run a psql query, return tab-separated lines."""
    out = subprocess.run(
        ["psql", PG_CONN, "-tAF", "\t", "-c", sql],
        capture_output=True, text=True, check=True,
    ).stdout.strip()
    return [line for line in out.splitlines() if line.strip()]


def pg_treatment_rankings(compare_spec):
    cols = "treatment_ranking_id," + ",".join(
        pg_col for _, (pg_col, _) in compare_spec.items()
    )
    rows = psql(f"SELECT {cols} FROM vw_treatment_rankings ORDER BY 1;")
    result = {}
    col_names = list(compare_spec.keys())
    for line in rows:
        parts = line.split("\t")
        pk = parts[0]
        result[pk] = {}
        for i, key in enumerate(col_names):
            result[pk][key] = parts[i + 1] if i + 1 < len(parts) else ""
    return result


def pg_stratum_summaries(compare_spec):
    cols = "stratum_summary_id,stratum_cases_a,stratum_cases_b,stratum_successes_a,stratum_successes_b,stratum_cases,stratum_successes,study_total_cases,stratum_total_cases,treatment_a_cases_here,treatment_b_cases_here,treatment_a_total_cases,treatment_b_total_cases,weighted_stratum_rate," + ",".join(
        pg_col for _, (pg_col, _) in compare_spec.items()
    )
    rows = psql(f"SELECT {cols} FROM vw_stratum_summaries ORDER BY 1;")
    result = {}
    extra_cols = ["stratumCasesA", "stratumCasesB", "stratumSuccessesA", "stratumSuccessesB",
                  "stratumCases", "stratumSuccesses", "studyTotalCases", "stratumTotalCases",
                  "treatmentACasesHere", "treatmentBCasesHere", "treatmentATotalCases", "treatmentBTotalCases",
                  "weightedStratumRate"]
    derive_cols = list(compare_spec.keys())
    for line in rows:
        parts = line.split("\t")
        pk = parts[0]
        entry = {}
        for i, col in enumerate(extra_cols):
            entry[col] = parts[i + 1] if i + 1 < len(parts) else ""
        for j, key in enumerate(derive_cols):
            entry[key] = parts[len(extra_cols) + 1 + j] if len(extra_cols) + 1 + j < len(parts) else ""
        result[pk] = entry
    return result


def pg_stratum_variables(compare_spec):
    cols = "stratum_variable_id,affects_treatment_assignment,affects_outcome,causal_role," + ",".join(
        pg_col for _, (pg_col, _) in compare_spec.items()
    )
    rows = psql(f"SELECT {cols} FROM vw_stratum_variables ORDER BY 1;")
    result = {}
    for line in rows:
        parts = line.split("\t")
        pk = parts[0]
        result[pk] = {
            "affectsTreatmentAssignment": parts[1] if len(parts) > 1 else "",
            "affectsOutcome": parts[2] if len(parts) > 2 else "",
            "causalRole": parts[3] if len(parts) > 3 else "",
            "isConfounder": parts[4] if len(parts) > 4 else "",
        }
    return result


def pg_treatment_rankings_aggregates():
    """Fetch the aggregation inputs for TreatmentRankings that SHACL can't compute."""
    cols = ("treatment_ranking_id,total_cases_a,total_successes_a,total_cases_b,total_successes_b,"
            "stratum_count,strata_won_by_a,strata_won_by_b,confounders_in_study,"
            "pooled_rate_from_weights_a,pooled_rate_from_weights_b,weighted_stratum_gap_sum,"
            "allocation_distortion,mediator_risk_count,contested_stratum_count,"
            "unknown_causal_role_count,confirmed_causal_role_count")
    rows = psql(f"SELECT {cols} FROM vw_treatment_rankings ORDER BY 1;")
    result = {}
    agg_keys = ["totalCasesA", "totalSuccessesA", "totalCasesB", "totalSuccessesB",
                "stratumCount", "strataWonByA", "strataWonByB", "confoundersInStudy",
                "pooledRateFromWeightsA", "pooledRateFromWeightsB", "weightedStratumGapSum",
                "allocationDistortion", "mediatorRiskCount", "contestedStratumCount",
                "unknownCausalRoleCount", "confirmedCausalRoleCount"]
    for line in rows:
        parts = line.split("\t")
        pk = parts[0]
        result[pk] = {}
        for i, key in enumerate(agg_keys):
            result[pk][key] = parts[i + 1] if i + 1 < len(parts) else ""
    return result


def xsd_val(raw, typ):
    """Convert a raw string to an RDF Literal of the right type."""
    if raw is None or raw == "":
        return None
    if typ == bool:
        return Literal(raw.lower() in ("t", "true", "1"), datatype=XSD.boolean)
    if typ == int:
        try:
            return Literal(int(raw), datatype=XSD.integer)
        except ValueError:
            return None
    if typ == float:
        try:
            return Literal(float(raw), datatype=XSD.decimal)
        except ValueError:
            return None
    return Literal(raw)


def assert_aggregates(g, tr_aggs, pg_ss, pg_sv):
    """Assert Postgres-computed aggregation values into the graph as raw facts,
    so SHACL can then derive the pure formula fields on top of them."""

    # TreatmentRankings aggregations
    tr_agg_map = {
        "totalCasesA":           (XSD.integer, NTWF.totalCasesA),
        "totalSuccessesA":       (XSD.integer, NTWF.totalSuccessesA),
        "totalCasesB":           (XSD.integer, NTWF.totalCasesB),
        "totalSuccessesB":       (XSD.integer, NTWF.totalSuccessesB),
        "stratumCount":          (XSD.integer, NTWF.stratumCount),
        "strataWonByA":          (XSD.integer, NTWF.strataWonByA),
        "strataWonByB":          (XSD.integer, NTWF.strataWonByB),
        "confoundersInStudy":    (XSD.integer, NTWF.confoundersInStudy),
        "pooledRateFromWeightsA": (XSD.decimal, NTWF.pooledRateFromWeightsA),
        "pooledRateFromWeightsB": (XSD.decimal, NTWF.pooledRateFromWeightsB),
        "weightedStratumGapSum": (XSD.decimal, NTWF.weightedStratumGapSum),
        "allocationDistortion":      (XSD.decimal, NTWF.allocationDistortion),
        "mediatorRiskCount":         (XSD.integer, NTWF.mediatorRiskCount),
        "contestedStratumCount":     (XSD.integer, NTWF.contestedStratumCount),
        "unknownCausalRoleCount":    (XSD.integer, NTWF.unknownCausalRoleCount),
        "confirmedCausalRoleCount":  (XSD.integer, NTWF.confirmedCausalRoleCount),
    }
    for pk, aggs in tr_aggs.items():
        subj = NTWF[pk.replace(" ", "-")]
        for key, (xtype, pred) in tr_agg_map.items():
            raw = aggs.get(key, "")
            if raw and raw != "":
                try:
                    if xtype == XSD.integer:
                        g.add((subj, pred, Literal(int(raw), datatype=xtype)))
                    elif xtype == XSD.decimal:
                        g.add((subj, pred, Literal(float(raw), datatype=xtype)))
                except (ValueError, TypeError):
                    pass

    # StratumSummaries aggregations
    ss_agg_map = {
        "stratumCasesA":        (XSD.integer, NTWF.stratumCasesA),
        "stratumSuccessesA":    (XSD.integer, NTWF.stratumSuccessesA),
        "stratumCasesB":        (XSD.integer, NTWF.stratumCasesB),
        "stratumSuccessesB":    (XSD.integer, NTWF.stratumSuccessesB),
        "stratumCases":         (XSD.integer, NTWF.stratumCases),
        "stratumSuccesses":     (XSD.integer, NTWF.stratumSuccesses),
        "studyTotalCases":      (XSD.integer, NTWF.studyTotalCases),
        "stratumTotalCases":    (XSD.integer, NTWF.stratumTotalCases),
        "treatmentACasesHere":  (XSD.integer, NTWF.treatmentACasesHere),
        "treatmentBCasesHere":  (XSD.integer, NTWF.treatmentBCasesHere),
        "treatmentATotalCases": (XSD.integer, NTWF.treatmentATotalCases),
        "treatmentBTotalCases": (XSD.integer, NTWF.treatmentBTotalCases),
    }
    for pk, row in pg_ss.items():
        subj = NTWF[pk.replace(" ", "-")]
        for key, (xtype, pred) in ss_agg_map.items():
            raw = row.get(key, "")
            if raw and raw != "":
                try:
                    if xtype == XSD.integer:
                        g.add((subj, pred, Literal(int(raw), datatype=xtype)))
                    elif xtype == XSD.decimal:
                        g.add((subj, pred, Literal(float(raw), datatype=xtype)))
                except (ValueError, TypeError):
                    pass

    # StratumVariables: raw fields (already in individuals but assert causalRole too)
    for pk, row in pg_sv.items():
        subj = NTWF[pk.replace(" ", "-")]
        for key, pred in [("affectsTreatmentAssignment", NTWF.affectsTreatmentAssignment),
                           ("affectsOutcome", NTWF.affectsOutcome),
                           ("causalRole", NTWF.causalRole)]:
            raw = row.get(key, "")
            if raw and raw != "":
                if raw.lower() in ("t", "true", "1"):
                    g.add((subj, pred, Literal(True, datatype=XSD.boolean)))
                elif raw.lower() in ("f", "false", "0"):
                    g.add((subj, pred, Literal(False, datatype=XSD.boolean)))
                else:
                    g.add((subj, pred, Literal(raw)))


from rdflib.namespace import RDF, RDFS, SH

CONFORMANCE_TARGET_CLASSES = {
    NTWF.TreatmentRankings,
    NTWF.StratumSummaries,
    NTWF.StratumVariables,
}

def _owl_local_to_rule_field(owl_local: str) -> str:
    return owl_local[0].upper() + owl_local[1:] if owl_local else owl_local


def _excluded_conformance_rule_labels(manifest):
    """Labels of SHACL rules to skip during conformance loading.

    Only excludes manifest rows explicitly marked AssertFromPostgres. All
    aggregation fields (COUNTIFS/SUMIFS) run natively as SHACL-SPARQL sub-SELECT
    rules (transpiler >= 2026.07.08).
    """
    excluded = set()
    for row in manifest:
        if not row.get("AssertFromPostgres"):
            continue
        excluded.add(
            f"rule_{row['SourceTable']}_{_owl_local_to_rule_field(row['OwlLocalName'])}"
        )
    return excluded


def load_base():
    g = Graph()
    g.parse(os.path.join(SRC, "ontology.owl"), format="turtle")
    g.parse(os.path.join(SRC, "individuals.ttl"), format="turtle")
    return g


def rules_graph():
    """Load SHACL rules for conformance tables, skipping pre-asserted aggregations."""
    manifest = load_conformance_manifest()
    excluded_labels = _excluded_conformance_rule_labels(manifest)
    sg = Graph()
    sg.parse(os.path.join(SRC, "rules.shacl.ttl"), format="turtle")
    fg = Graph()
    fg.bind("effortless-ntwf", NTWF)
    fg.bind("sh", SH)
    fg.bind("rdfs", RDFS)
    fg.bind("xsd", XSD)
    kept = 0
    for shape in sg.subjects(RDF.type, SH.NodeShape):
        target = sg.value(shape, SH.targetClass)
        if target not in CONFORMANCE_TARGET_CLASSES:
            continue
        if not any(sg.triples((shape, SH.rule, None))):
            continue
        fg.add((shape, RDF.type, SH.NodeShape))
        fg.add((shape, SH.targetClass, target))
        for _, _, rule_bnode in sg.triples((shape, SH.rule, None)):
            label = sg.value(rule_bnode, RDFS.label)
            if label and str(label) in excluded_labels:
                continue
            fg.add((shape, SH.rule, rule_bnode))
            for s2, p2, o2 in sg.triples((rule_bnode, None, None)):
                fg.add((s2, p2, o2))
            kept += 1
    return fg


def _rdf_to_py(value):
    if value is None:
        return None
    if isinstance(value, Literal):
        py = value.toPython()
        if isinstance(py, bool):
            return py
        if isinstance(py, (int, float)):
            return py
        return str(py)
    return str(value)


def _as_number(v):
    if isinstance(v, bool):
        return None
    if isinstance(v, (int, float)):
        return float(v)
    if isinstance(v, str):
        try:
            return float(v.strip())
        except ValueError:
            return None
    return None


def _collapse_multivalue_derived(g, shapes, max_rounds=10):
    """Collapse (subject, predicate) pairs with >1 derived value.

    SHACL CONSTRUCT only ADDS triples, so multi-pass derivation can leave stale
    premature values alongside converged ones (e.g. isReversal="" before isSignFlip
    exists, then isReversal=true). Clear conflicted string/boolean props and
    re-derive once inputs have stabilized. Numeric conflicts collapse to MAX.
    """
    for _ in range(max_rounds):
        conflicts = {}
        for s, p, o in g:
            if not str(p).startswith(str(NTWF)):
                continue
            conflicts.setdefault((s, p), []).append(o)

        numeric_targets = []
        string_targets = []
        for (s, p), objs in conflicts.items():
            if len({str(o) for o in objs}) < 2:
                continue
            nums = [_as_number(_rdf_to_py(o)) for o in objs]
            if all(n is not None for n in nums):
                numeric_targets.append((s, p, objs, nums))
            else:
                string_targets.append((s, p))

        if not numeric_targets and not string_targets:
            break

        for (s, p, objs, nums) in numeric_targets:
            keep = objs[max(range(len(objs)), key=lambda i: nums[i])]
            for o in objs:
                if o is not keep:
                    g.remove((s, p, o))

        for (s, p) in string_targets:
            for o in list(g.objects(s, p)):
                g.remove((s, p, o))

        if string_targets:
            validate(
                g,
                shacl_graph=shapes,
                inference="none",
                advanced=True,
                inplace=True,
                do_owl_imports=False,
            )
        elif not string_targets:
            break


def rederive_to_fixpoint(g, max_passes=50):
    """Run pyshacl advanced (sh:rule SPARQL CONSTRUCT) until graph stabilises."""
    shapes = rules_graph()

    def fp(graph):
        return hash(frozenset((str(s), str(p), str(o)) for s, p, o in graph))

    prev = None
    passes = 0
    for i in range(max_passes):
        passes = i + 1
        validate(
            g,
            shacl_graph=shapes,
            inference="none",
            advanced=True,
            inplace=True,
            do_owl_imports=False,
        )
        cur = fp(g)
        if cur == prev:
            break
        prev = cur
    _collapse_multivalue_derived(g, shapes)
    return passes, len(g)


def get_owl_field(g, subj, local):
    pred = URIRef(NS + local)
    val = g.value(subj, pred)
    return val


def norm_val(v, typ):
    """Normalise a raw string or RDF literal to a comparable Python value."""
    if v is None or str(v) == "":
        return None
    s = str(v)
    if typ == bool:
        if isinstance(v, Literal):
            return bool(v.toPython())
        return s.lower() in ("t", "true", "1")
    if typ == float:
        try:
            return round(float(s), 8)
        except ValueError:
            return None
    if typ == int:
        try:
            return int(s)
        except ValueError:
            return None
    # string — strip namespace prefix if it snuck in
    if "#" in s:
        s = s.split("#")[-1]
    return s.strip()


def compare_table(g, class_uri, pk_pred, compare_spec, pg_rows, table_label):
    mismatches = []
    matches = 0
    missing_in_owl = 0

    for subj in g.subjects(rdflib.RDF.type, class_uri):
        pk_lit = g.value(subj, pk_pred)
        if pk_lit is None:
            continue
        pk = str(pk_lit)
        if pk not in pg_rows:
            continue

        pg_row = pg_rows[pk]
        for owl_local, (pg_col, typ) in compare_spec.items():
            owl_val = get_owl_field(g, subj, owl_local)
            pg_raw = pg_row.get(owl_local, pg_row.get(pg_col, ""))

            owl_norm = norm_val(owl_val, typ) if owl_val is not None else None
            pg_norm = norm_val(pg_raw, typ)

            if owl_norm is None and pg_norm is None:
                matches += 1
            elif owl_norm != pg_norm:
                mismatches.append({
                    "pk": pk, "field": owl_local,
                    "owl": owl_norm, "pg": pg_norm,
                })
            else:
                matches += 1

    return matches, mismatches


def main():
    print("=" * 70)
    print("Cross-substrate conformance: Simpson's Paradox formula fields")
    print("OWL-SHACL (pyshacl fixpoint) vs Postgres (vw_* views)")
    print("=" * 70)

    manifest = load_conformance_manifest()
    compare_specs = compare_specs_from_manifest(manifest)
    tr_compare = compare_specs["TreatmentRankings"]
    ss_compare = compare_specs["StratumSummaries"]
    sv_compare = compare_specs["StratumVariables"]

    # Fetch Postgres data (for comparison and manifest AssertFromPostgres fields)
    print("\n[1] Fetching Postgres computed values...")
    try:
        pg_tr = pg_treatment_rankings(tr_compare)
        pg_ss = pg_stratum_summaries(ss_compare)
        pg_sv = pg_stratum_variables(sv_compare)
    except subprocess.CalledProcessError as e:
        print(f"ERROR: Could not query Postgres: {e.stderr}")
        print("  Is the simpsons_paradox DB running? Run: ./effortless-postgres/init-db.sh")
        return 1
    print(f"  TreatmentRankings: {len(pg_tr)} rows")
    print(f"  StratumSummaries:  {len(pg_ss)} rows")
    print(f"  StratumVariables:  {len(pg_sv)} rows")

    # Load OWL graph
    print("\n[2] Loading OWL ontology + individuals...")
    g = load_base()
    base_triples = len(g)
    print(f"  {base_triples} triples loaded")

    print("\n[3] Asserting manifest AssertFromPostgres fields as leaf facts...")
    assert_from_postgres_rows(
        manifest,
        g,
        {
            "TreatmentRankings": pg_tr,
            "StratumSummaries": pg_ss,
            "StratumVariables": pg_sv,
        },
    )
    after_assert = len(g)
    print(f"  +{after_assert - base_triples} triples asserted ({after_assert} total)")

    # Run SHACL fixpoint
    print("\n[4] Running SHACL fixpoint derivation (pyshacl)...")
    passes, final_triples = rederive_to_fixpoint(g)
    print(f"  Converged in {passes} pass(es), {final_triples} triples")

    # Compare
    print("\n[5] Comparing OWL-derived vs Postgres on formula fields...")

    tr_matches, tr_mismatches = compare_table(
        g, NTWF.TreatmentRankings, NTWF.treatmentRankingId,
        tr_compare, pg_tr, "TreatmentRankings"
    )
    ss_matches, ss_mismatches = compare_table(
        g, NTWF.StratumSummaries, NTWF.stratumSummaryId,
        ss_compare, pg_ss, "StratumSummaries"
    )
    sv_matches, sv_mismatches = compare_table(
        g, NTWF.StratumVariables, NTWF.stratumVariableId,
        sv_compare, pg_sv, "StratumVariables"
    )

    total_matches = tr_matches + ss_matches + sv_matches
    all_mismatches = tr_mismatches + ss_mismatches + sv_mismatches

    print(f"\n  TreatmentRankings : {tr_matches} match, {len(tr_mismatches)} mismatch")
    print(f"  StratumSummaries  : {ss_matches} match, {len(ss_mismatches)} mismatch")
    print(f"  StratumVariables  : {sv_matches} match, {len(sv_mismatches)} mismatch")
    print(f"  TOTAL             : {total_matches} match, {len(all_mismatches)} mismatch")

    print()
    # Headline witnesses
    print("  Key derived fields for kidney-1986-A-vs-B:")
    subj = NTWF["kidney-1986-A-vs-B"]
    for field in ["isReversal", "distortionType", "correctedWinner", "adjustmentAppropriate"]:
        val = get_owl_field(g, subj, field)
        pg_val = pg_tr.get("kidney-1986-A-vs-B", {}).get(field, "?")
        print(f"    {field:30} OWL={val}  PG={pg_val}")

    if not all_mismatches:
        print("\nRECEIPT: OWL-SHACL and Postgres agree EXACTLY on all formula fields.")
        print(f"  {total_matches} field values identical across both substrates.")
        return 0

    print(f"\nMISMATCH: {len(all_mismatches)} field(s) differ:")
    for m in all_mismatches[:30]:
        print(f"  [{m['pk']}] {m['field']}: OWL={m['owl']!r}  PG={m['pg']!r}")
    if len(all_mismatches) > 30:
        print(f"  ... and {len(all_mismatches) - 30} more")
    return 1


if __name__ == "__main__":
    sys.exit(main())
