-- ============================================================================
-- CREATE POLICIES - Row Level Security policies
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================

-- Enable RLS on all tables

ALTER TABLE loops ENABLE ROW LEVEL SECURITY;
ALTER TABLE physics_constants ENABLE ROW LEVEL SECURITY;
ALTER TABLE particles ENABLE ROW LEVEL SECURITY;
ALTER TABLE charges ENABLE ROW LEVEL SECURITY;
ALTER TABLE systems ENABLE ROW LEVEL SECURITY;
ALTER TABLE charge_interactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE force_vectors ENABLE ROW LEVEL SECURITY;
ALTER TABLE electric_field_points ENABLE ROW LEVEL SECURITY;
ALTER TABLE invariant_checks ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_summary ENABLE ROW LEVEL SECURITY;

-- TODO: Add specific RLS policies based on your security requirements
-- Example:
-- CREATE POLICY "Users can view their own data" ON app_user
--   FOR SELECT USING (auth.uid() = user_id);

