-- ============================================================================
-- UPDATE EFFORTLESS SCHEMA - the derived layer, rebuilt from the rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres. DO NOT EDIT — regenerated every build.
--
-- SAFE IN PRODUCTION. This file never drops a table, never drops a column,
-- and never deletes row data. It brings any database in line with the
-- rulebook that shipped in this same commit.
--
-- Views, calc_*/get_* functions and RLS policies hold NO data: they are a
-- pure function of the rulebook. They are dropped and recreated here rather
-- than migrated. Do NOT hand-write a migration that recreates a view or a
-- calc_* function — re-run this file instead.
--
-- A hand-authored migration is needed ONLY for table/column changes that
-- step 1 below cannot infer, and it should contain nothing else.
-- ============================================================================

BEGIN;
SET timezone = 'UTC';

-- === 1. Additive schema: missing tables and columns ========================
-- CREATE TABLE IF NOT EXISTS / ADD COLUMN IF NOT EXISTS only. Never drops.

-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- GENERATED FILE — DO NOT EDIT. Rewritten by every `effortless build`.
--
-- SOURCE OF TRUTH: effortless-rulebook/effortless-rulebook.json
-- Every table below is defined there. To add a table, a column, or a
-- calculated field, edit the rulebook and rebuild — never this file, and
-- never a *b-customize-*.sql file. A table defined outside the rulebook
-- gets no view, no calculated fields, no RuleSpeak and no Explainer DAG.
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 10
-- Total Raw Fields: 76
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Loops: Table: Loops — build history and forward plan. Each row documents what new concept is introduced, what was witnessed, and what the next empirical question is.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS loops (
  loop_id                             TEXT                 PRIMARY KEY          -- Unique identifier: loop-01, loop-02, …
);
ALTER TABLE loops ADD COLUMN IF NOT EXISTS title TEXT;                                              -- Short title for what this loop adds.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS status TEXT;                                             -- planned | in-progress | complete
ALTER TABLE loops ADD COLUMN IF NOT EXISTS new_concept TEXT;                                        -- The new first-class domain concept introduced this loop.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS domain_question TEXT;                                    -- The natural-language question this loop's concept answers.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS mock_data_note TEXT;                                     -- What the seed data is designed to show.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS next_suggestion TEXT;                                    -- Suggestion for the next loop.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS commit_hash TEXT;                                        -- Git SHA where this loop first landed.
ALTER TABLE loops ADD COLUMN IF NOT EXISTS commit_date DATE;                                        -- ISO date of the commit.
COMMENT ON TABLE loops IS 'Table: Loops — build history and forward plan. Each row documents what new concept is introduced, what was witnessed, and what the next empirical question is.';
COMMENT ON COLUMN loops.loop_id IS 'Unique identifier: loop-01, loop-02, …';
COMMENT ON COLUMN loops.title IS 'Short title for what this loop adds.';
COMMENT ON COLUMN loops.status IS 'planned | in-progress | complete';
COMMENT ON COLUMN loops.new_concept IS 'The new first-class domain concept introduced this loop.';
COMMENT ON COLUMN loops.domain_question IS 'The natural-language question this loop''s concept answers.';
COMMENT ON COLUMN loops.mock_data_note IS 'What the seed data is designed to show.';
COMMENT ON COLUMN loops.next_suggestion IS 'Suggestion for the next loop.';
COMMENT ON COLUMN loops.commit_hash IS 'Git SHA where this loop first landed.';
COMMENT ON COLUMN loops.commit_date IS 'ISO date of the commit.';

-- ----------------------------------------------------------------------------
-- PhysicsConstants: Table: PhysicsConstants — fundamental constants used in Coulomb's Law calculations. Single source of truth for k, e, a₀, etc.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS physics_constants (
  constant_id                         TEXT                 PRIMARY KEY          -- Unique identifier (e.g. coulomb_k, elem_charge)
);
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS name TEXT;                                   -- Human-readable name
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS symbol TEXT;                                 -- Physics symbol (k, e, a₀, …)
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS value NUMERIC;                               -- Numeric value in SI units
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS units TEXT;                                  -- SI unit string
ALTER TABLE physics_constants ADD COLUMN IF NOT EXISTS description TEXT;                            -- What this constant represents
COMMENT ON TABLE physics_constants IS 'Table: PhysicsConstants — fundamental constants used in Coulomb''s Law calculations. Single source of truth for k, e, a₀, etc.';
COMMENT ON COLUMN physics_constants.constant_id IS 'Unique identifier (e.g. coulomb_k, elem_charge)';
COMMENT ON COLUMN physics_constants.name IS 'Human-readable name';
COMMENT ON COLUMN physics_constants.symbol IS 'Physics symbol (k, e, a₀, …)';
COMMENT ON COLUMN physics_constants.value IS 'Numeric value in SI units';
COMMENT ON COLUMN physics_constants.units IS 'SI unit string';
COMMENT ON COLUMN physics_constants.description IS 'What this constant represents';

-- ----------------------------------------------------------------------------
-- Particles: Table: Particles — named particle archetypes with canonical charge and mass values. Used as reference for Charges rows.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS particles (
  particle_id                         TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE particles ADD COLUMN IF NOT EXISTS name TEXT;                                           -- Common name (Proton, Electron, …)
ALTER TABLE particles ADD COLUMN IF NOT EXISTS canonical_charge NUMERIC;                            -- Charge in Coulombs (positive or negative)
ALTER TABLE particles ADD COLUMN IF NOT EXISTS canonical_mass NUMERIC;                              -- Rest mass in kg
ALTER TABLE particles ADD COLUMN IF NOT EXISTS description TEXT;                                    -- Physical description
COMMENT ON TABLE particles IS 'Table: Particles — named particle archetypes with canonical charge and mass values. Used as reference for Charges rows.';
COMMENT ON COLUMN particles.particle_id IS 'Unique identifier';
COMMENT ON COLUMN particles.name IS 'Common name (Proton, Electron, …)';
COMMENT ON COLUMN particles.canonical_charge IS 'Charge in Coulombs (positive or negative)';
COMMENT ON COLUMN particles.canonical_mass IS 'Rest mass in kg';
COMMENT ON COLUMN particles.description IS 'Physical description';

-- ----------------------------------------------------------------------------
-- Charges: Table: Charges — individual charged particles with 3D position and physical properties. The raw leaves of the Coulomb's Law DAG.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS charges (
  charge_id                           TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE charges ADD COLUMN IF NOT EXISTS name TEXT;                                             -- Human-readable label (Proton A, Electron B, …)
ALTER TABLE charges ADD COLUMN IF NOT EXISTS system_id TEXT;                                        -- FK → Systems.SystemId — which physical system this charge belongs to
ALTER TABLE charges ADD COLUMN IF NOT EXISTS particle_id TEXT;                                      -- FK → Particles.ParticleId — archetype (optional)
ALTER TABLE charges ADD COLUMN IF NOT EXISTS charge_value NUMERIC;                                  -- Charge in Coulombs (signed: positive or negative)
ALTER TABLE charges ADD COLUMN IF NOT EXISTS position_x NUMERIC;                                    -- X coordinate in meters
ALTER TABLE charges ADD COLUMN IF NOT EXISTS position_y NUMERIC;                                    -- Y coordinate in meters
ALTER TABLE charges ADD COLUMN IF NOT EXISTS position_z NUMERIC;                                    -- Z coordinate in meters
ALTER TABLE charges ADD COLUMN IF NOT EXISTS mass NUMERIC;                                          -- Mass in kg (null = massless / not tracked)
COMMENT ON TABLE charges IS 'Table: Charges — individual charged particles with 3D position and physical properties. The raw leaves of the Coulomb''s Law DAG.';
COMMENT ON COLUMN charges.charge_id IS 'Unique identifier';
COMMENT ON COLUMN charges.name IS 'Human-readable label (Proton A, Electron B, …)';
COMMENT ON COLUMN charges.system_id IS 'FK → Systems.SystemId — which physical system this charge belongs to';
COMMENT ON COLUMN charges.particle_id IS 'FK → Particles.ParticleId — archetype (optional)';
COMMENT ON COLUMN charges.charge_value IS 'Charge in Coulombs (signed: positive or negative)';
COMMENT ON COLUMN charges.position_x IS 'X coordinate in meters';
COMMENT ON COLUMN charges.position_y IS 'Y coordinate in meters';
COMMENT ON COLUMN charges.position_z IS 'Z coordinate in meters';
COMMENT ON COLUMN charges.mass IS 'Mass in kg (null = massless / not tracked)';

-- ----------------------------------------------------------------------------
-- Systems: Table: Systems — named physical configurations of charges. Groups Charges into testable scenarios (hydrogen atom, NaCl pair, triangle of charges, etc.).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS systems (
  system_id                           TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE systems ADD COLUMN IF NOT EXISTS name TEXT;                                             -- Human-readable name
ALTER TABLE systems ADD COLUMN IF NOT EXISTS description TEXT;                                      -- What physical situation this represents
ALTER TABLE systems ADD COLUMN IF NOT EXISTS is_synthetic BOOLEAN;                                  -- True if this is a constructed example; false if from real measurements
COMMENT ON TABLE systems IS 'Table: Systems — named physical configurations of charges. Groups Charges into testable scenarios (hydrogen atom, NaCl pair, triangle of charges, etc.).';
COMMENT ON COLUMN systems.system_id IS 'Unique identifier';
COMMENT ON COLUMN systems.name IS 'Human-readable name';
COMMENT ON COLUMN systems.description IS 'What physical situation this represents';
COMMENT ON COLUMN systems.is_synthetic IS 'True if this is a constructed example; false if from real measurements';

-- ----------------------------------------------------------------------------
-- ChargeInteractions: Table: ChargeInteractions — pairwise electrostatic interactions. One row per ordered pair (Charge1, Charge2) within a system. Position and charge values are stored directly (denormalized from Charges) so that DeltaX/Y/Z, DistanceMeters, ForceMagnitude, IsAttractive, and IsRepulsive can be computed as calculated fields. F = k·|q₁·q₂|/r² falls out of the DAG.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS charge_interactions (
  interaction_id                      TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS system_id TEXT;                            -- FK → Systems.SystemId
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge1_id TEXT;                           -- FK → Charges.ChargeId (first particle)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge2_id TEXT;                           -- FK → Charges.ChargeId (second particle)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge1_label TEXT;                        -- Human label copied from Charges.Name at seed time
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS charge2_label TEXT;                        -- Human label copied from Charges.Name at seed time
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS q1 NUMERIC;                                -- Charge value of Charge1 in Coulombs (copied from Charges.ChargeValue)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS q2 NUMERIC;                                -- Charge value of Charge2 in Coulombs (copied from Charges.ChargeValue)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS x1 NUMERIC;                                -- X position of Charge1 in meters (copied from Charges.PositionX)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS y1 NUMERIC;                                -- Y position of Charge1 in meters (copied from Charges.PositionY)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS z1 NUMERIC;                                -- Z position of Charge1 in meters (copied from Charges.PositionZ)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS x2 NUMERIC;                                -- X position of Charge2 in meters (copied from Charges.PositionX)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS y2 NUMERIC;                                -- Y position of Charge2 in meters (copied from Charges.PositionY)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS z2 NUMERIC;                                -- Z position of Charge2 in meters (copied from Charges.PositionZ)
ALTER TABLE charge_interactions ADD COLUMN IF NOT EXISTS coulomb_k NUMERIC;                         -- Coulomb's constant: 8.99×10⁹ N·m²·C⁻². Stored per-row so the formula is self-contained.
COMMENT ON TABLE charge_interactions IS 'Table: ChargeInteractions — pairwise electrostatic interactions. One row per ordered pair (Charge1, Charge2) within a system. Position and charge values are stored directly (denormalized from Charges) so that DeltaX/Y/Z, DistanceMeters, ForceMagnitude, IsAttractive, and IsRepulsive can be computed as calculated fields. F = k·|q₁·q₂|/r² falls out of the DAG.';
COMMENT ON COLUMN charge_interactions.interaction_id IS 'Unique identifier';
COMMENT ON COLUMN charge_interactions.system_id IS 'FK → Systems.SystemId';
COMMENT ON COLUMN charge_interactions.charge1_id IS 'FK → Charges.ChargeId (first particle)';
COMMENT ON COLUMN charge_interactions.charge2_id IS 'FK → Charges.ChargeId (second particle)';
COMMENT ON COLUMN charge_interactions.charge1_label IS 'Human label copied from Charges.Name at seed time';
COMMENT ON COLUMN charge_interactions.charge2_label IS 'Human label copied from Charges.Name at seed time';
COMMENT ON COLUMN charge_interactions.q1 IS 'Charge value of Charge1 in Coulombs (copied from Charges.ChargeValue)';
COMMENT ON COLUMN charge_interactions.q2 IS 'Charge value of Charge2 in Coulombs (copied from Charges.ChargeValue)';
COMMENT ON COLUMN charge_interactions.x1 IS 'X position of Charge1 in meters (copied from Charges.PositionX)';
COMMENT ON COLUMN charge_interactions.y1 IS 'Y position of Charge1 in meters (copied from Charges.PositionY)';
COMMENT ON COLUMN charge_interactions.z1 IS 'Z position of Charge1 in meters (copied from Charges.PositionZ)';
COMMENT ON COLUMN charge_interactions.x2 IS 'X position of Charge2 in meters (copied from Charges.PositionX)';
COMMENT ON COLUMN charge_interactions.y2 IS 'Y position of Charge2 in meters (copied from Charges.PositionY)';
COMMENT ON COLUMN charge_interactions.z2 IS 'Z position of Charge2 in meters (copied from Charges.PositionZ)';
COMMENT ON COLUMN charge_interactions.coulomb_k IS 'Coulomb''s constant: 8.99×10⁹ N·m²·C⁻². Stored per-row so the formula is self-contained.';

-- ----------------------------------------------------------------------------
-- ForceVectors: Table: ForceVectors — unit vector and full Cartesian force components for each ChargeInteraction. FX, FY, FZ decompose the scalar ForceMagnitude along the displacement direction. Force on Charge1 due to Charge2: attractive → pulls C1 toward C2 (−r̂); repulsive → pushes C1 away from C2 (+r̂). Position and interaction values are stored directly (denormalized) so all components compute as pure calculated fields.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS force_vectors (
  force_vector_id                     TEXT                 PRIMARY KEY          -- Unique identifier (mirrors InteractionId)
);
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS interaction_id TEXT;                             -- FK → ChargeInteractions.InteractionId
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS force_magnitude_raw NUMERIC;                     -- Scalar force magnitude in Newtons (copied from ChargeInteractions.ForceMagnitude)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dx NUMERIC;                                      -- ΔX = X2 − X1 in meters (copied from ChargeInteractions.DeltaX)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dy NUMERIC;                                      -- ΔY = Y2 − Y1 in meters (copied from ChargeInteractions.DeltaY)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dz NUMERIC;                                      -- ΔZ = Z2 − Z1 in meters (copied from ChargeInteractions.DeltaZ)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS dist_raw NUMERIC;                                -- Separation distance r in meters (copied from ChargeInteractions.DistanceMeters)
ALTER TABLE force_vectors ADD COLUMN IF NOT EXISTS is_attractive_raw BOOLEAN;                       -- Attraction flag (copied from ChargeInteractions.IsAttractive)
COMMENT ON TABLE force_vectors IS 'Table: ForceVectors — unit vector and full Cartesian force components for each ChargeInteraction. FX, FY, FZ decompose the scalar ForceMagnitude along the displacement direction. Force on Charge1 due to Charge2: attractive → pulls C1 toward C2 (−r̂); repulsive → pushes C1 away from C2 (+r̂). Position and interaction values are stored directly (denormalized) so all components compute as pure calculated fields.';
COMMENT ON COLUMN force_vectors.force_vector_id IS 'Unique identifier (mirrors InteractionId)';
COMMENT ON COLUMN force_vectors.interaction_id IS 'FK → ChargeInteractions.InteractionId';
COMMENT ON COLUMN force_vectors.force_magnitude_raw IS 'Scalar force magnitude in Newtons (copied from ChargeInteractions.ForceMagnitude)';
COMMENT ON COLUMN force_vectors.dx IS 'ΔX = X2 − X1 in meters (copied from ChargeInteractions.DeltaX)';
COMMENT ON COLUMN force_vectors.dy IS 'ΔY = Y2 − Y1 in meters (copied from ChargeInteractions.DeltaY)';
COMMENT ON COLUMN force_vectors.dz IS 'ΔZ = Z2 − Z1 in meters (copied from ChargeInteractions.DeltaZ)';
COMMENT ON COLUMN force_vectors.dist_raw IS 'Separation distance r in meters (copied from ChargeInteractions.DistanceMeters)';
COMMENT ON COLUMN force_vectors.is_attractive_raw IS 'Attraction flag (copied from ChargeInteractions.IsAttractive)';

-- ----------------------------------------------------------------------------
-- ElectricFieldPoints: Table: ElectricFieldPoints — observation points in space at which the electric field contribution of a single source Charge is evaluated. E = k·q/r² pointing away from positive sources. One row per (ObservationPoint, SourceCharge) pair. Source charge and position values stored directly (denormalized) so EX, EY, EZ compute as pure calculated fields.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS electric_field_points (
  field_point_id                      TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS system_id TEXT;                          -- FK → Systems.SystemId
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS source_charge_id TEXT;                   -- FK → Charges.ChargeId — the charge creating this field contribution
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS source_charge_name TEXT;                 -- Human label of source charge (copied from Charges.Name)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS observation_label TEXT;                  -- Human label for the observation point (midpoint, centroid, etc.)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS obs_x NUMERIC;                           -- Observation point X coordinate in meters
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS obs_y NUMERIC;                           -- Observation point Y coordinate in meters
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS obs_z NUMERIC;                           -- Observation point Z coordinate in meters
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS coulomb_k NUMERIC;                       -- Coulomb's constant per-row (8.99×10⁹ N·m²·C⁻²)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS source_q NUMERIC;                        -- Charge value of source charge in Coulombs (copied from Charges.ChargeValue)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS src_x NUMERIC;                           -- X position of source charge in meters (copied from Charges.PositionX)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS src_y NUMERIC;                           -- Y position of source charge in meters (copied from Charges.PositionY)
ALTER TABLE electric_field_points ADD COLUMN IF NOT EXISTS src_z NUMERIC;                           -- Z position of source charge in meters (copied from Charges.PositionZ)
COMMENT ON TABLE electric_field_points IS 'Table: ElectricFieldPoints — observation points in space at which the electric field contribution of a single source Charge is evaluated. E = k·q/r² pointing away from positive sources. One row per (ObservationPoint, SourceCharge) pair. Source charge and position values stored directly (denormalized) so EX, EY, EZ compute as pure calculated fields.';
COMMENT ON COLUMN electric_field_points.field_point_id IS 'Unique identifier';
COMMENT ON COLUMN electric_field_points.system_id IS 'FK → Systems.SystemId';
COMMENT ON COLUMN electric_field_points.source_charge_id IS 'FK → Charges.ChargeId — the charge creating this field contribution';
COMMENT ON COLUMN electric_field_points.source_charge_name IS 'Human label of source charge (copied from Charges.Name)';
COMMENT ON COLUMN electric_field_points.observation_label IS 'Human label for the observation point (midpoint, centroid, etc.)';
COMMENT ON COLUMN electric_field_points.obs_x IS 'Observation point X coordinate in meters';
COMMENT ON COLUMN electric_field_points.obs_y IS 'Observation point Y coordinate in meters';
COMMENT ON COLUMN electric_field_points.obs_z IS 'Observation point Z coordinate in meters';
COMMENT ON COLUMN electric_field_points.coulomb_k IS 'Coulomb''s constant per-row (8.99×10⁹ N·m²·C⁻²)';
COMMENT ON COLUMN electric_field_points.source_q IS 'Charge value of source charge in Coulombs (copied from Charges.ChargeValue)';
COMMENT ON COLUMN electric_field_points.src_x IS 'X position of source charge in meters (copied from Charges.PositionX)';
COMMENT ON COLUMN electric_field_points.src_y IS 'Y position of source charge in meters (copied from Charges.PositionY)';
COMMENT ON COLUMN electric_field_points.src_z IS 'Z position of source charge in meters (copied from Charges.PositionZ)';

-- ----------------------------------------------------------------------------
-- InvariantChecks: Table: InvariantChecks — one row per algebraic invariant that the Coulomb's Law DAG must satisfy. These are the model's built-in correctness witnesses.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invariant_checks (
  invariant_id                        TEXT                 PRIMARY KEY          -- Unique identifier
);
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS algebraic_statement TEXT;                     -- The mathematical identity being checked
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS natural_language TEXT;                        -- Plain English: what must be true?
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS physics_law TEXT;                             -- Which physics principle this invariant encodes
ALTER TABLE invariant_checks ADD COLUMN IF NOT EXISTS severity TEXT;                                -- critical | warning | informational
COMMENT ON TABLE invariant_checks IS 'Table: InvariantChecks — one row per algebraic invariant that the Coulomb''s Law DAG must satisfy. These are the model''s built-in correctness witnesses.';
COMMENT ON COLUMN invariant_checks.invariant_id IS 'Unique identifier';
COMMENT ON COLUMN invariant_checks.algebraic_statement IS 'The mathematical identity being checked';
COMMENT ON COLUMN invariant_checks.natural_language IS 'Plain English: what must be true?';
COMMENT ON COLUMN invariant_checks.physics_law IS 'Which physics principle this invariant encodes';
COMMENT ON COLUMN invariant_checks.severity IS 'critical | warning | informational';

-- ----------------------------------------------------------------------------
-- SystemSummary: Table: SystemSummary — one row per system, aggregating all interactions and field points. The model witnesses its own state: total force, dominant pair, net charge, field at midpoints.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_summary (
  summary_id                          TEXT                 PRIMARY KEY          -- Unique identifier (mirrors SystemId)
);
ALTER TABLE system_summary ADD COLUMN IF NOT EXISTS system_id TEXT;                                 -- FK → Systems.SystemId
COMMENT ON TABLE system_summary IS 'Table: SystemSummary — one row per system, aggregating all interactions and field points. The model witnesses its own state: total force, dominant pair, net charge, field at midpoints.';
COMMENT ON COLUMN system_summary.summary_id IS 'Unique identifier (mirrors SystemId)';
COMMENT ON COLUMN system_summary.system_id IS 'FK → Systems.SystemId';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Charges
CREATE INDEX IF NOT EXISTS idx_charges_system_id ON charges (system_id);
CREATE INDEX IF NOT EXISTS idx_charges_particle_id ON charges (particle_id);

-- SystemSummary
CREATE INDEX IF NOT EXISTS idx_system_summary_system_id ON system_summary (system_id);

-- 3 FK index(es) declared.


-- === 2/3. Drop the derived layer ==========================================
-- Views first (they depend on functions), then functions leaf-up through the
-- DAG. CASCADE handles the dependency order Postgres knows about; the
-- explicit ordering handles calc_* functions that call other calc_*.
DO $drop_derived$
DECLARE r RECORD; v_views INT := 0; v_fns INT := 0;
BEGIN
    -- 2. Views (depend on functions, so they go first).
    FOR r IN (
        SELECT table_name FROM information_schema.views
         WHERE table_schema = 'public' AND table_name LIKE 'vw\_%'
           AND obj_description(
                 (quote_ident(table_schema) || '.' || quote_ident(table_name))::regclass, 'pg_class')
               IS DISTINCT FROM 'effortless:hand-maintained'
    ) LOOP
        EXECUTE 'DROP VIEW IF EXISTS public.' || quote_ident(r.table_name) || ' CASCADE';
        v_views := v_views + 1;
    END LOOP;

    -- 3. Functions, leaf-up through the DAG. A calc_* may call another
    --    calc_*, so depth-ordering avoids dependency errors.
    FOR r IN (
        WITH fn AS (
            SELECT p.oid, p.proname,
                   pg_get_function_identity_arguments(p.oid) AS args,
                   p.prosrc
              FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
             WHERE n.nspname = 'public'
               AND (p.proname LIKE 'calc\_%' OR p.proname LIKE 'get\_%')
               AND COALESCE(obj_description(p.oid, 'pg_proc'), '')
                   IS DISTINCT FROM 'effortless:hand-maintained'
        )
        -- callers before callees: a function whose body names another
        -- generated function is an interior node and must go first.
        SELECT f.proname, f.args,
               (SELECT count(*) FROM fn c
                 WHERE c.oid <> f.oid AND f.prosrc LIKE '%' || c.proname || '%') AS depth
          FROM fn f
         ORDER BY depth DESC, f.proname
    ) LOOP
        EXECUTE 'DROP FUNCTION IF EXISTS public.' || quote_ident(r.proname)
                || '(' || r.args || ') CASCADE';
        v_fns := v_fns + 1;
    END LOOP;

    RAISE NOTICE 'derived layer dropped: % views, % functions', v_views, v_fns;
END
$drop_derived$;


-- === 4. Static reference data =============================================
-- (no tables marked IsStatic — nothing to upsert)

-- === 5. Recreate calc_*/get_* functions ===================================
-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- calc_loops_name
-- Field: Loops.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_loops_name(p_loop_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(loop_id, '') FROM loops WHERE loop_id = p_loop_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_particles_charge_sign
-- Field: Particles.ChargeSign
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_particles_charge_sign(p_particle_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN ((SELECT canonical_charge FROM particles WHERE particle_id = p_particle_id))::NUMERIC > 0 THEN ('positive')::text ELSE (CASE WHEN ((SELECT canonical_charge FROM particles WHERE particle_id = p_particle_id))::NUMERIC < 0 THEN ('negative')::text ELSE ('neutral')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_charges_system_name
-- Field: Charges.SystemName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Name from related Systems


CREATE OR REPLACE FUNCTION calc_charges_system_name(p_charge_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name::text FROM systems WHERE system_id = (SELECT system_id FROM charges WHERE charge_id = p_charge_id));
$$ LANGUAGE sql STABLE;

-- calc_charges_particle_name
-- Field: Charges.ParticleName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Name from related Particles


CREATE OR REPLACE FUNCTION calc_charges_particle_name(p_charge_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name::text FROM particles WHERE particle_id = (SELECT particle_id FROM charges WHERE charge_id = p_charge_id));
$$ LANGUAGE sql STABLE;

-- get_systems_name
-- Helper function: Get Name from Systems by SystemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_systems_name(p_system_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM systems WHERE system_id = p_system_id);
$$ LANGUAGE sql STABLE;

-- get_systems_description
-- Helper function: Get Description from Systems by SystemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_systems_description(p_system_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM systems WHERE system_id = p_system_id);
$$ LANGUAGE sql STABLE;

-- get_systems_is_synthetic
-- Helper function: Get IsSynthetic from Systems by SystemId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_systems_is_synthetic(p_system_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_synthetic FROM systems WHERE system_id = p_system_id);
$$ LANGUAGE sql STABLE;

-- get_particles_name
-- Helper function: Get Name from Particles by ParticleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_particles_name(p_particle_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name FROM particles WHERE particle_id = p_particle_id);
$$ LANGUAGE sql STABLE;

-- get_particles_canonical_charge
-- Helper function: Get CanonicalCharge from Particles by ParticleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_particles_canonical_charge(p_particle_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT canonical_charge FROM particles WHERE particle_id = p_particle_id);
$$ LANGUAGE sql STABLE;

-- get_particles_canonical_mass
-- Helper function: Get CanonicalMass from Particles by ParticleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_particles_canonical_mass(p_particle_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SELECT canonical_mass FROM particles WHERE particle_id = p_particle_id);
$$ LANGUAGE sql STABLE;

-- get_particles_description
-- Helper function: Get Description from Particles by ParticleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_particles_description(p_particle_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM particles WHERE particle_id = p_particle_id);
$$ LANGUAGE sql STABLE;

-- calc_charges_charge_sign
-- Field: Charges.ChargeSign
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_charges_charge_sign(p_charge_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN ((SELECT charge_value FROM charges WHERE charge_id = p_charge_id))::NUMERIC > 0 THEN ('positive')::text ELSE (CASE WHEN ((SELECT charge_value FROM charges WHERE charge_id = p_charge_id))::NUMERIC < 0 THEN ('negative')::text ELSE ('neutral')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_charges_charge_magnitude
-- Field: Charges.ChargeMagnitude
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charges_charge_magnitude(p_charge_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (ABS((SELECT charge_value FROM charges WHERE charge_id = p_charge_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charges_interaction_count
-- Field: Charges.InteractionCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_charges_interaction_count(p_charge_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE charge1_id = (SELECT NULLIF(charge_id, '') FROM charges WHERE charge_id = p_charge_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_systems_charge_count
-- Field: Systems.ChargeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_systems_charge_count(p_system_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charges WHERE system_id = (SELECT NULLIF(system_id, '') FROM systems WHERE system_id = p_system_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_systems_interaction_count
-- Field: Systems.InteractionCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_systems_interaction_count(p_system_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM systems WHERE system_id = p_system_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_systems_attractive_count
-- Field: Systems.AttractiveCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_systems_attractive_count(p_system_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM systems WHERE system_id = p_system_id) AND calc_charge_interactions_is_attractive(interaction_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_systems_repulsive_count
-- Field: Systems.RepulsiveCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_systems_repulsive_count(p_system_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM systems WHERE system_id = p_system_id) AND calc_charge_interactions_is_repulsive(interaction_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_systems_total_charge
-- Field: Systems.TotalCharge
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_systems_total_charge(p_system_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((charge_value)::numeric), 0) FROM charges WHERE system_id = p_system_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_systems_is_neutral
-- Field: Systems.IsNeutral
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_systems_is_neutral(p_system_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((ABS(calc_systems_total_charge(p_system_id)))::NUMERIC < 1e-30)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_systems_max_force_magnitude
-- Field: Systems.MaxForceMagnitude
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_systems_max_force_magnitude(p_system_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(MAX((calc_charge_interactions_force_magnitude(interaction_id))::numeric), 0) FROM charge_interactions WHERE system_id = p_system_id))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_name
-- Field: ChargeInteractions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_charge_interactions_name(p_interaction_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(interaction_id, '') FROM charge_interactions WHERE interaction_id = p_interaction_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_delta_x
-- Field: ChargeInteractions.DeltaX
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_delta_x(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT x2 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT x1 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_delta_y
-- Field: ChargeInteractions.DeltaY
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_delta_y(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT y2 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT y1 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_delta_z
-- Field: ChargeInteractions.DeltaZ
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_delta_z(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT z2 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT z1 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_distance_squared
-- Field: ChargeInteractions.DistanceSquared
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_distance_squared(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_charge_interactions_delta_x(p_interaction_id) AS val), __erb_dedup_v2 AS (SELECT calc_charge_interactions_delta_y(p_interaction_id) AS val), __erb_dedup_v3 AS (SELECT calc_charge_interactions_delta_z(p_interaction_id) AS val) SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v2)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v2)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v3)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v3)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_distance_meters
-- Field: ChargeInteractions.DistanceMeters
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_distance_meters(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SQRT((calc_charge_interactions_distance_squared(p_interaction_id))::NUMERIC))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_distance_picometers
-- Field: ChargeInteractions.DistancePicometers
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_distance_picometers(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_charge_interactions_distance_meters(p_interaction_id)) AS v) __safe_numeric), 0) * COALESCE(1000000000000, 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_charge_product
-- Field: ChargeInteractions.ChargeProduct
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_charge_product(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT q1 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT q2 FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_force_magnitude
-- Field: ChargeInteractions.ForceMagnitude
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_force_magnitude(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT coulomb_k FROM charge_interactions WHERE interaction_id = p_interaction_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (ABS(calc_charge_interactions_charge_product(p_interaction_id))) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_charge_interactions_distance_squared(p_interaction_id)) AS v) __safe_numeric), 0), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_is_attractive
-- Field: ChargeInteractions.IsAttractive
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_charge_interactions_is_attractive(p_interaction_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_charge_interactions_charge_product(p_interaction_id))::NUMERIC < 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_is_repulsive
-- Field: ChargeInteractions.IsRepulsive
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_charge_interactions_is_repulsive(p_interaction_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((calc_charge_interactions_charge_product(p_interaction_id))::NUMERIC > 0)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_interaction_type
-- Field: ChargeInteractions.InteractionType
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_charge_interactions_interaction_type(p_interaction_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN calc_charge_interactions_is_attractive(p_interaction_id) THEN ('attractive')::text ELSE (CASE WHEN calc_charge_interactions_is_repulsive(p_interaction_id) THEN ('repulsive')::text ELSE ('neutral')::text END)::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_charge_interactions_force_in_atto_newtons
-- Field: ChargeInteractions.ForceInAttoNewtons
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_charge_interactions_force_in_atto_newtons(p_interaction_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_charge_interactions_force_magnitude(p_interaction_id)) AS v) __safe_numeric), 0) * COALESCE(1000000000000000000, 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_name
-- Field: ForceVectors.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_force_vectors_name(p_force_vector_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(force_vector_id, '') FROM force_vectors WHERE force_vector_id = p_force_vector_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_unit_x
-- Field: ForceVectors.UnitX
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_unit_x(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN ((SELECT dist_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id))::NUMERIC = 0 THEN (0)::text ELSE ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT dx FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT dist_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0), 0)))::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_unit_y
-- Field: ForceVectors.UnitY
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_unit_y(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN ((SELECT dist_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id))::NUMERIC = 0 THEN (0)::text ELSE ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT dy FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT dist_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0), 0)))::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_unit_z
-- Field: ForceVectors.UnitZ
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_unit_z(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN ((SELECT dist_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id))::NUMERIC = 0 THEN (0)::text ELSE ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT dz FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT dist_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0), 0)))::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_sign_factor
-- Field: ForceVectors.SignFactor
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_sign_factor(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN COALESCE((SELECT is_attractive_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id), FALSE) THEN (-1)::text ELSE (1)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_fx
-- Field: ForceVectors.FX
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_fx(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT force_magnitude_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_force_vectors_sign_factor(p_force_vector_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_force_vectors_unit_x(p_force_vector_id)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_fy
-- Field: ForceVectors.FY
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_fy(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT force_magnitude_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_force_vectors_sign_factor(p_force_vector_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_force_vectors_unit_y(p_force_vector_id)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_fz
-- Field: ForceVectors.FZ
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_force_vectors_fz(p_force_vector_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT force_magnitude_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_force_vectors_sign_factor(p_force_vector_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_force_vectors_unit_z(p_force_vector_id)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_force_vectors_force_dir_description
-- Field: ForceVectors.ForceDirDescription
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_force_vectors_force_dir_description(p_force_vector_id TEXT)
RETURNS TEXT AS $$
  SELECT (CASE WHEN COALESCE((SELECT is_attractive_raw FROM force_vectors WHERE force_vector_id = p_force_vector_id), FALSE) THEN ('towards')::text ELSE ('away-from')::text END)::text;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_name
-- Field: ElectricFieldPoints.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_electric_field_points_name(p_field_point_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(field_point_id, '') FROM electric_field_points WHERE field_point_id = p_field_point_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_d_x
-- Field: ElectricFieldPoints.dX
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_d_x(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT obs_x FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT src_x FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_d_y
-- Field: ElectricFieldPoints.dY
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_d_y(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT obs_y FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT src_y FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_d_z
-- Field: ElectricFieldPoints.dZ
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_d_z(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT obs_z FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0) - COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT src_z FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_distance_squared
-- Field: ElectricFieldPoints.DistanceSquared
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_distance_squared(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  WITH __erb_dedup_v1 AS (SELECT calc_electric_field_points_d_x(p_field_point_id) AS val), __erb_dedup_v2 AS (SELECT calc_electric_field_points_d_y(p_field_point_id) AS val), __erb_dedup_v3 AS (SELECT calc_electric_field_points_d_z(p_field_point_id) AS val) SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v1)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v2)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v2)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0) + COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v3)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT val FROM __erb_dedup_v3)) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_distance
-- Field: ElectricFieldPoints.Distance
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_distance(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (SQRT((calc_electric_field_points_distance_squared(p_field_point_id))::NUMERIC))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_e_field_magnitude
-- Field: ElectricFieldPoints.EFieldMagnitude
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_e_field_magnitude(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((SELECT coulomb_k FROM electric_field_points WHERE field_point_id = p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (ABS((SELECT source_q FROM electric_field_points WHERE field_point_id = p_field_point_id))) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_distance_squared(p_field_point_id)) AS v) __safe_numeric), 0), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_q_sign
-- Field: ElectricFieldPoints.QSign
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_q_sign(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT (CASE WHEN ((SELECT source_q FROM electric_field_points WHERE field_point_id = p_field_point_id))::NUMERIC > 0 THEN (1)::text ELSE (-1)::text END)::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_ex
-- Field: ElectricFieldPoints.EX
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_ex(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_e_field_magnitude(p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_q_sign(p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_d_x(p_field_point_id)) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_distance(p_field_point_id)) AS v) __safe_numeric), 0), 0))) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_ey
-- Field: ElectricFieldPoints.EY
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_ey(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_e_field_magnitude(p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_q_sign(p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_d_y(p_field_point_id)) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_distance(p_field_point_id)) AS v) __safe_numeric), 0), 0))) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_electric_field_points_ez
-- Field: ElectricFieldPoints.EZ
-- Type: calculated | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_electric_field_points_ez(p_field_point_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_e_field_magnitude(p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_q_sign(p_field_point_id)) AS v) __safe_numeric), 0) * COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT ((COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_d_z(p_field_point_id)) AS v) __safe_numeric), 0) / NULLIF(COALESCE((SELECT CASE WHEN v::text ~ '^-?[0-9]*\.?[0-9]+$' THEN v::numeric ELSE NULL END FROM (SELECT (calc_electric_field_points_distance(p_field_point_id)) AS v) __safe_numeric), 0), 0))) AS v) __safe_numeric), 0))) AS v) __safe_numeric), 0)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_invariant_checks_name
-- Field: InvariantChecks.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_invariant_checks_name(p_invariant_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(invariant_id, '') FROM invariant_checks WHERE invariant_id = p_invariant_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_system_name
-- Field: SystemSummary.SystemName
-- Type: lookup | DataType: string | Returns: TEXT
-- Lookup: Name from related Systems


CREATE OR REPLACE FUNCTION calc_system_summary_system_name(p_summary_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT name::text FROM systems WHERE system_id = (SELECT system_id FROM system_summary WHERE summary_id = p_summary_id));
$$ LANGUAGE sql STABLE;

-- calc_system_summary_name
-- Field: SystemSummary.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_system_summary_name(p_summary_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(summary_id, '') FROM system_summary WHERE summary_id = p_summary_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_charge_count
-- Field: SystemSummary.ChargeCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_system_summary_charge_count(p_summary_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charges WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_interaction_count
-- Field: SystemSummary.InteractionCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_system_summary_interaction_count(p_summary_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_attractive_count
-- Field: SystemSummary.AttractiveCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_system_summary_attractive_count(p_summary_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id) AND calc_charge_interactions_is_attractive(interaction_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_repulsive_count
-- Field: SystemSummary.RepulsiveCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_system_summary_repulsive_count(p_summary_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id) AND calc_charge_interactions_is_repulsive(interaction_id) = TRUE))::integer;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_total_charge
-- Field: SystemSummary.TotalCharge
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_system_summary_total_charge(p_summary_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(SUM((charge_value)::numeric), 0) FROM charges WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_is_neutral
-- Field: SystemSummary.IsNeutral
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_system_summary_is_neutral(p_summary_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((ABS(calc_system_summary_total_charge(p_summary_id)))::NUMERIC < 1e-30)::boolean;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_max_force_magnitude
-- Field: SystemSummary.MaxForceMagnitude
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_system_summary_max_force_magnitude(p_summary_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(MAX((calc_charge_interactions_force_magnitude(interaction_id))::numeric), 0) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_min_distance_meters
-- Field: SystemSummary.MinDistanceMeters
-- Type: aggregation | DataType: number | Returns: NUMERIC


CREATE OR REPLACE FUNCTION calc_system_summary_min_distance_meters(p_summary_id TEXT)
RETURNS NUMERIC AS $$
  SELECT ((SELECT COALESCE(MIN((calc_charge_interactions_distance_meters(interaction_id))::numeric), 0) FROM charge_interactions WHERE system_id = (SELECT NULLIF(system_id, '') FROM system_summary WHERE summary_id = p_summary_id)))::numeric;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_all_attractive
-- Field: SystemSummary.AllAttractive
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_system_summary_all_attractive(p_summary_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_system_summary_attractive_count(p_summary_id) = calc_system_summary_interaction_count(p_summary_id))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_all_repulsive
-- Field: SystemSummary.AllRepulsive
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_system_summary_all_repulsive(p_summary_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (calc_system_summary_repulsive_count(p_summary_id) = calc_system_summary_interaction_count(p_summary_id))::boolean;
$$ LANGUAGE sql STABLE;

-- calc_system_summary_has_mixed_interactions
-- Field: SystemSummary.HasMixedInteractions
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_system_summary_has_mixed_interactions(p_summary_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (((calc_system_summary_attractive_count(p_summary_id))::NUMERIC > 0 AND (calc_system_summary_repulsive_count(p_summary_id))::NUMERIC > 0));
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================



-- === 6. Custom functions (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 7. Recreate vw_* views ===============================================
-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Views: 10
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_system_summary CASCADE;
DROP VIEW IF EXISTS vw_invariant_checks CASCADE;
DROP VIEW IF EXISTS vw_electric_field_points CASCADE;
DROP VIEW IF EXISTS vw_force_vectors CASCADE;
DROP VIEW IF EXISTS vw_charge_interactions CASCADE;
DROP VIEW IF EXISTS vw_systems CASCADE;
DROP VIEW IF EXISTS vw_charges CASCADE;
DROP VIEW IF EXISTS vw_particles CASCADE;
DROP VIEW IF EXISTS vw_physics_constants CASCADE;
DROP VIEW IF EXISTS vw_loops CASCADE;

-- ----------------------------------------------------------------------------
-- vw_loops: Table: Loops — build history and forward plan. Each row documents what new concept is introduced, what was witnessed, and what the next empirical question is.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_loops CASCADE;
CREATE VIEW vw_loops WITH (security_invoker = ON) AS
SELECT
  t.loop_id,                                                                    -- Unique identifier: loop-01, loop-02, …
  calc_loops_name(t.loop_id) AS name,                                           -- Display label.
  t.title,                                                                      -- Short title for what this loop adds.
  t.status,                                                                     -- planned | in-progress | complete
  t.new_concept,                                                                -- The new first-class domain concept introduced this loop.
  t.domain_question,                                                            -- The natural-language question this loop's concept answers.
  t.mock_data_note,                                                             -- What the seed data is designed to show.
  t.next_suggestion,                                                            -- Suggestion for the next loop.
  t.commit_hash,                                                                -- Git SHA where this loop first landed.
  t.commit_date                                                                 -- ISO date of the commit.
FROM loops t;

-- ----------------------------------------------------------------------------
-- vw_physics_constants: Table: PhysicsConstants — fundamental constants used in Coulomb's Law calculations. Single source of truth for k, e, a₀, etc.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_physics_constants CASCADE;
CREATE VIEW vw_physics_constants WITH (security_invoker = ON) AS
SELECT
  t.constant_id,                                                                -- Unique identifier (e.g. coulomb_k, elem_charge)
  t.name,                                                                       -- Human-readable name
  t.symbol,                                                                     -- Physics symbol (k, e, a₀, …)
  t.value,                                                                      -- Numeric value in SI units
  t.units,                                                                      -- SI unit string
  t.description                                                                 -- What this constant represents
FROM physics_constants t;

-- ----------------------------------------------------------------------------
-- vw_particles: Table: Particles — named particle archetypes with canonical charge and mass values. Used as reference for Charges rows.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_particles CASCADE;
CREATE VIEW vw_particles WITH (security_invoker = ON) AS
SELECT
  t.particle_id,                                                                -- Unique identifier
  t.name,                                                                       -- Common name (Proton, Electron, …)
  t.canonical_charge,                                                           -- Charge in Coulombs (positive or negative)
  t.canonical_mass,                                                             -- Rest mass in kg
  calc_particles_charge_sign(t.particle_id) AS charge_sign,                     -- positive | negative | neutral
  t.description                                                                 -- Physical description
FROM particles t;

-- ----------------------------------------------------------------------------
-- vw_charges: Table: Charges — individual charged particles with 3D position and physical properties. The raw leaves of the Coulomb's Law DAG.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_charges CASCADE;
CREATE VIEW vw_charges WITH (security_invoker = ON) AS
SELECT
  t.charge_id,                                                                  -- Unique identifier
  t.name,                                                                       -- Human-readable label (Proton A, Electron B, …)
  t.system_id,                                                                  -- FK → Systems.SystemId — which physical system this charge belongs to
  t.particle_id,                                                                -- FK → Particles.ParticleId — archetype (optional)
  t.charge_value,                                                               -- Charge in Coulombs (signed: positive or negative)
  t.position_x,                                                                 -- X coordinate in meters
  t.position_y,                                                                 -- Y coordinate in meters
  t.position_z,                                                                 -- Z coordinate in meters
  t.mass,                                                                       -- Mass in kg (null = massless / not tracked)
  calc_charges_charge_sign(t.charge_id) AS charge_sign,                         -- positive | negative | neutral
  calc_charges_charge_magnitude(t.charge_id) AS charge_magnitude,               -- Absolute value of ChargeValue in Coulombs
  calc_charges_system_name(t.charge_id) AS system_name,                         -- Lookup: Systems.Name via SystemId.
  calc_charges_particle_name(t.charge_id) AS particle_name,                     -- Lookup: Particles.Name via ParticleId.
  calc_charges_interaction_count(t.charge_id) AS interaction_count              -- Count of ChargeInteractions that reference this charge as Charge1 or Charge2.
FROM charges t;

-- ----------------------------------------------------------------------------
-- vw_systems: Table: Systems — named physical configurations of charges. Groups Charges into testable scenarios (hydrogen atom, NaCl pair, triangle of charges, etc.).
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_systems CASCADE;
CREATE VIEW vw_systems WITH (security_invoker = ON) AS
SELECT
  t.system_id,                                                                  -- Unique identifier
  t.name,                                                                       -- Human-readable name
  t.description,                                                                -- What physical situation this represents
  t.is_synthetic,                                                               -- True if this is a constructed example; false if from real measurements
  calc_systems_charge_count(t.system_id) AS charge_count,                       -- Number of charges in this system.
  calc_systems_interaction_count(t.system_id) AS interaction_count,             -- Number of pairwise interactions in this system.
  calc_systems_attractive_count(t.system_id) AS attractive_count,               -- Count of attractive interactions in this system.
  calc_systems_repulsive_count(t.system_id) AS repulsive_count,                 -- Count of repulsive interactions in this system.
  calc_systems_total_charge(t.system_id) AS total_charge,                       -- Algebraic sum of all charges in the system (net charge).
  calc_systems_is_neutral(t.system_id) AS is_neutral,                           -- True when net charge is effectively zero.
  calc_systems_max_force_magnitude(t.system_id) AS max_force_magnitude          -- Strongest pairwise interaction in this system.
FROM systems t;

-- ----------------------------------------------------------------------------
-- vw_charge_interactions: Table: ChargeInteractions — pairwise electrostatic interactions. One row per ordered pair (Charge1, Charge2) within a system. Position and charge values are stored directly (denormalized from Charges) so that DeltaX/Y/Z, DistanceMeters, ForceMagnitude, IsAttractive, and IsRepulsive can be computed as calculated fields. F = k·|q₁·q₂|/r² falls out of the DAG.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_charge_interactions CASCADE;
CREATE VIEW vw_charge_interactions WITH (security_invoker = ON) AS
SELECT
  t.interaction_id,                                                             -- Unique identifier
  calc_charge_interactions_name(t.interaction_id) AS name,                      -- Display label.
  t.system_id,                                                                  -- FK → Systems.SystemId
  t.charge1_id,                                                                 -- FK → Charges.ChargeId (first particle)
  t.charge2_id,                                                                 -- FK → Charges.ChargeId (second particle)
  t.charge1_label,                                                              -- Human label copied from Charges.Name at seed time
  t.charge2_label,                                                              -- Human label copied from Charges.Name at seed time
  t.q1,                                                                         -- Charge value of Charge1 in Coulombs (copied from Charges.ChargeValue)
  t.q2,                                                                         -- Charge value of Charge2 in Coulombs (copied from Charges.ChargeValue)
  t.x1,                                                                         -- X position of Charge1 in meters (copied from Charges.PositionX)
  t.y1,                                                                         -- Y position of Charge1 in meters (copied from Charges.PositionY)
  t.z1,                                                                         -- Z position of Charge1 in meters (copied from Charges.PositionZ)
  t.x2,                                                                         -- X position of Charge2 in meters (copied from Charges.PositionX)
  t.y2,                                                                         -- Y position of Charge2 in meters (copied from Charges.PositionY)
  t.z2,                                                                         -- Z position of Charge2 in meters (copied from Charges.PositionZ)
  t.coulomb_k,                                                                  -- Coulomb's constant: 8.99×10⁹ N·m²·C⁻². Stored per-row so the formula is self-contained.
  calc_charge_interactions_delta_x(t.interaction_id) AS delta_x,                -- X2 − X1: displacement in X from Charge1 to Charge2 in meters.
  calc_charge_interactions_delta_y(t.interaction_id) AS delta_y,                -- Y2 − Y1: displacement in Y from Charge1 to Charge2 in meters.
  calc_charge_interactions_delta_z(t.interaction_id) AS delta_z,                -- Z2 − Z1: displacement in Z from Charge1 to Charge2 in meters.
  calc_charge_interactions_distance_squared(t.interaction_id) AS distance_squared,-- r² = ΔX² + ΔY² + ΔZ² in m². Intermediate value for Coulomb's Law.
  calc_charge_interactions_distance_meters(t.interaction_id) AS distance_meters,-- r = √(r²): charge separation in meters.
  calc_charge_interactions_distance_picometers(t.interaction_id) AS distance_picometers,-- Distance expressed in picometers (r × 10¹²). Human-readable at atomic scale.
  calc_charge_interactions_charge_product(t.interaction_id) AS charge_product,  -- q₁ · q₂ (signed). Positive → same-sign charges (repulsive). Negative → opposite-sign (attractive).
  calc_charge_interactions_force_magnitude(t.interaction_id) AS force_magnitude,-- F = k · |q₁ · q₂| / r² in Newtons. This is Coulomb's Law.
  calc_charge_interactions_is_attractive(t.interaction_id) AS is_attractive,    -- True when charges have opposite signs (ChargeProduct < 0). Force pulls the particles together.
  calc_charge_interactions_is_repulsive(t.interaction_id) AS is_repulsive,      -- True when charges have the same sign (ChargeProduct > 0). Force pushes the particles apart.
  calc_charge_interactions_interaction_type(t.interaction_id) AS interaction_type,-- attractive | repulsive | neutral — derived from sign of ChargeProduct.
  calc_charge_interactions_force_in_atto_newtons(t.interaction_id) AS force_in_atto_newtons-- ForceMagnitude expressed in attonewtons (F × 10¹⁸). Human-readable at atomic scale.
FROM charge_interactions t;

-- ----------------------------------------------------------------------------
-- vw_force_vectors: Table: ForceVectors — unit vector and full Cartesian force components for each ChargeInteraction. FX, FY, FZ decompose the scalar ForceMagnitude along the displacement direction. Force on Charge1 due to Charge2: attractive → pulls C1 toward C2 (−r̂); repulsive → pushes C1 away from C2 (+r̂). Position and interaction values are stored directly (denormalized) so all components compute as pure calculated fields.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_force_vectors CASCADE;
CREATE VIEW vw_force_vectors WITH (security_invoker = ON) AS
SELECT
  t.force_vector_id,                                                            -- Unique identifier (mirrors InteractionId)
  calc_force_vectors_name(t.force_vector_id) AS name,                           -- Display label.
  t.interaction_id,                                                             -- FK → ChargeInteractions.InteractionId
  t.force_magnitude_raw,                                                        -- Scalar force magnitude in Newtons (copied from ChargeInteractions.ForceMagnitude)
  t.dx,                                                                         -- ΔX = X2 − X1 in meters (copied from ChargeInteractions.DeltaX)
  t.dy,                                                                         -- ΔY = Y2 − Y1 in meters (copied from ChargeInteractions.DeltaY)
  t.dz,                                                                         -- ΔZ = Z2 − Z1 in meters (copied from ChargeInteractions.DeltaZ)
  t.dist_raw,                                                                   -- Separation distance r in meters (copied from ChargeInteractions.DistanceMeters)
  t.is_attractive_raw,                                                          -- Attraction flag (copied from ChargeInteractions.IsAttractive)
  calc_force_vectors_unit_x(t.force_vector_id) AS unit_x,                       -- X component of the displacement unit vector r̂ = ΔX/r.
  calc_force_vectors_unit_y(t.force_vector_id) AS unit_y,                       -- Y component of the displacement unit vector ΔY/r.
  calc_force_vectors_unit_z(t.force_vector_id) AS unit_z,                       -- Z component of the displacement unit vector ΔZ/r.
  calc_force_vectors_sign_factor(t.force_vector_id) AS sign_factor,             -- +1 if repulsive (C1 pushed away from C2); −1 if attractive (C1 pulled toward C2).
  calc_force_vectors_fx(t.force_vector_id) AS fx,                               -- X component of force on Charge1 in Newtons. Positive = net force in +X direction.
  calc_force_vectors_fy(t.force_vector_id) AS fy,                               -- Y component of force on Charge1 in Newtons.
  calc_force_vectors_fz(t.force_vector_id) AS fz,                               -- Z component of force on Charge1 in Newtons.
  calc_force_vectors_force_dir_description(t.force_vector_id) AS force_dir_description-- towards (attractive) | away-from (repulsive).
FROM force_vectors t;

-- ----------------------------------------------------------------------------
-- vw_electric_field_points: Table: ElectricFieldPoints — observation points in space at which the electric field contribution of a single source Charge is evaluated. E = k·q/r² pointing away from positive sources. One row per (ObservationPoint, SourceCharge) pair. Source charge and position values stored directly (denormalized) so EX, EY, EZ compute as pure calculated fields.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_electric_field_points CASCADE;
CREATE VIEW vw_electric_field_points WITH (security_invoker = ON) AS
SELECT
  t.field_point_id,                                                             -- Unique identifier
  calc_electric_field_points_name(t.field_point_id) AS name,                    -- Display label.
  t.system_id,                                                                  -- FK → Systems.SystemId
  t.source_charge_id,                                                           -- FK → Charges.ChargeId — the charge creating this field contribution
  t.source_charge_name,                                                         -- Human label of source charge (copied from Charges.Name)
  t.observation_label,                                                          -- Human label for the observation point (midpoint, centroid, etc.)
  t.obs_x,                                                                      -- Observation point X coordinate in meters
  t.obs_y,                                                                      -- Observation point Y coordinate in meters
  t.obs_z,                                                                      -- Observation point Z coordinate in meters
  t.coulomb_k,                                                                  -- Coulomb's constant per-row (8.99×10⁹ N·m²·C⁻²)
  t.source_q,                                                                   -- Charge value of source charge in Coulombs (copied from Charges.ChargeValue)
  t.src_x,                                                                      -- X position of source charge in meters (copied from Charges.PositionX)
  t.src_y,                                                                      -- Y position of source charge in meters (copied from Charges.PositionY)
  t.src_z,                                                                      -- Z position of source charge in meters (copied from Charges.PositionZ)
  calc_electric_field_points_d_x(t.field_point_id) AS d_x,                      -- ObsX − SrcX: displacement from source to observation point.
  calc_electric_field_points_d_y(t.field_point_id) AS d_y,                      -- ObsY − SrcY: displacement in Y.
  calc_electric_field_points_d_z(t.field_point_id) AS d_z,                      -- ObsZ − SrcZ: displacement in Z.
  calc_electric_field_points_distance_squared(t.field_point_id) AS distance_squared,-- r² = dX² + dY² + dZ².
  calc_electric_field_points_distance(t.field_point_id) AS distance,            -- r = √(r²): distance from source charge to observation point.
  calc_electric_field_points_e_field_magnitude(t.field_point_id) AS e_field_magnitude,-- E = k·|q|/r²: electric field strength at observation point due to this source charge in N/C.
  calc_electric_field_points_q_sign(t.field_point_id) AS q_sign,                -- Sign of source charge: +1 for positive, −1 for negative. Field points away from positive, toward negative.
  calc_electric_field_points_ex(t.field_point_id) AS ex,                        -- X component of electric field contribution at observation point (N/C). Positive = points in +X direction.
  calc_electric_field_points_ey(t.field_point_id) AS ey,                        -- Y component of electric field contribution.
  calc_electric_field_points_ez(t.field_point_id) AS ez                         -- Z component of electric field contribution.
FROM electric_field_points t;

-- ----------------------------------------------------------------------------
-- vw_invariant_checks: Table: InvariantChecks — one row per algebraic invariant that the Coulomb's Law DAG must satisfy. These are the model's built-in correctness witnesses.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_invariant_checks CASCADE;
CREATE VIEW vw_invariant_checks WITH (security_invoker = ON) AS
SELECT
  t.invariant_id,                                                               -- Unique identifier
  calc_invariant_checks_name(t.invariant_id) AS name,                           -- Display label.
  t.algebraic_statement,                                                        -- The mathematical identity being checked
  t.natural_language,                                                           -- Plain English: what must be true?
  t.physics_law,                                                                -- Which physics principle this invariant encodes
  t.severity                                                                    -- critical | warning | informational
FROM invariant_checks t;

-- ----------------------------------------------------------------------------
-- vw_system_summary: Table: SystemSummary — one row per system, aggregating all interactions and field points. The model witnesses its own state: total force, dominant pair, net charge, field at midpoints.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_system_summary CASCADE;
CREATE VIEW vw_system_summary WITH (security_invoker = ON) AS
SELECT
  t.summary_id,                                                                 -- Unique identifier (mirrors SystemId)
  calc_system_summary_name(t.summary_id) AS name,                               -- Display label.
  t.system_id,                                                                  -- FK → Systems.SystemId
  calc_system_summary_system_name(t.summary_id) AS system_name,                 -- Lookup: Systems.Name.
  calc_system_summary_charge_count(t.summary_id) AS charge_count,               -- Total charges in this system.
  calc_system_summary_interaction_count(t.summary_id) AS interaction_count,     -- Total pairwise interactions.
  calc_system_summary_attractive_count(t.summary_id) AS attractive_count,       -- Count of attractive interactions.
  calc_system_summary_repulsive_count(t.summary_id) AS repulsive_count,         -- Count of repulsive interactions.
  calc_system_summary_total_charge(t.summary_id) AS total_charge,               -- Net algebraic charge across all charges in the system.
  calc_system_summary_is_neutral(t.summary_id) AS is_neutral,                   -- True when |TotalCharge| < 1e-30.
  calc_system_summary_max_force_magnitude(t.summary_id) AS max_force_magnitude, -- Strongest pairwise interaction in Newtons.
  calc_system_summary_min_distance_meters(t.summary_id) AS min_distance_meters, -- Closest pair separation in meters.
  calc_system_summary_all_attractive(t.summary_id) AS all_attractive,           -- True when every interaction in the system is attractive.
  calc_system_summary_all_repulsive(t.summary_id) AS all_repulsive,             -- True when every interaction in the system is repulsive.
  calc_system_summary_has_mixed_interactions(t.summary_id) AS has_mixed_interactions-- True when the system has both attractive and repulsive interactions.
FROM system_summary t;



-- === 8. Custom views (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- === 9. Custom RLS (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

-- NOTE: the RBAC policy layer is generated by
-- effortless-rbac-to-postgres-policies as
-- drop-update-effortless-postgres-policies.sql. It follows this same
-- drop-and-recreate model and must run AFTER this file, because policies
-- reference the columns and views rebuilt above.

-- === 10. Custom data (ERBCustomizations) ===
-- (no ERBCustomizations row for this section)

COMMIT;
