-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Customers: Table: Customers
-- ----------------------------------------------------------------------------
INSERT INTO customers (customer_id, email_address, first_name, last_name)
VALUES ('jane-smith-email-com', 'jane.smith@email.com', 'Bobby', 'Smith') ON CONFLICT (customer_id) DO NOTHING;

INSERT INTO customers (customer_id, email_address, first_name, last_name)
VALUES ('john-doe-email-com', 'john.doe@email.com', 'Jimmy', 'Doe') ON CONFLICT (customer_id) DO NOTHING;

INSERT INTO customers (customer_id, email_address, first_name, last_name)
VALUES ('emily-jones-email-com', 'emily.jones@email.com', 'Mary', 'Jones') ON CONFLICT (customer_id) DO NOTHING;

