#!/bin/bash
set -e
set -o pipefail

# inject-substrate.sh for the effortless-golang execution substrate
#
# Regenerates the COMMERCIAL rulebook-to-go output for the active domain, then
# runs the test. Mirrors effortless-python and effortless-postgres:
# `effortless -buildLocal` from inside the transpiler's own output directory
# rebuilds just this substrate, without rebuilding every other one.
#
# Structure:
#   <domain>/effortless-golang/                  - commercial transpiler output
#   execution-substrates/effortless-golang/      - this test runner

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# ERB_DOMAIN_DIR is required. Guessing a domain would silently grade one
# project's code against another project's answer key and report it as a score.
if [ -z "$ERB_DOMAIN_DIR" ] || [ ! -d "$ERB_DOMAIN_DIR" ]; then
    echo "FATAL: ERB_DOMAIN_DIR is not set or does not exist." >&2
    echo "  ERB_DOMAIN_DIR=${ERB_DOMAIN_DIR:-<unset>}" >&2
    echo "  Invoke this script via the orchestrator, which sets it to the" >&2
    echo "  active domain's directory." >&2
    exit 1
fi

GO_OUT_DIR="$ERB_DOMAIN_DIR/effortless-golang"

echo "=== Effortless-Golang Substrate: Regenerating from rulebook ==="
echo "  Output dir: $GO_OUT_DIR"

if ! command -v effortless &> /dev/null; then
    echo "FATAL: the effortless CLI is not installed, so the commercial" >&2
    echo "  transpiler cannot run. This substrate grades that tool's output;" >&2
    echo "  without it there is nothing to grade." >&2
    exit 1
fi

if ! command -v go &> /dev/null; then
    echo "FATAL: the Go toolchain is not installed. This substrate compiles" >&2
    echo "  and runs the generated module natively." >&2
    exit 1
fi

# -buildLocal resolves the transpiler from this directory's entry in the
# project's effortless.json, so the directory has to exist before the first run.
mkdir -p "$GO_OUT_DIR"
cd "$GO_OUT_DIR"

GENERATED="$GO_OUT_DIR/erb_sdk.go"
BEFORE_MTIME=$(stat -f %m "$GENERATED" 2>/dev/null || echo 0)

effortless -buildLocal

# -buildLocal can exit 0 having produced nothing — most often because the
# transpiler is unreachable (an unpublished tool with no local instance
# listening). Without this check the run proceeds against whatever the previous
# build left behind and reports a score for stale code, which reads as a
# substrate regression rather than a build failure.
AFTER_MTIME=$(stat -f %m "$GENERATED" 2>/dev/null || echo 0)
if [ "$AFTER_MTIME" = "0" ]; then
    echo "FATAL: the transpiler produced no $GENERATED." >&2
    echo "  rulebook-to-go is not reachable. Publish it, or start a local" >&2
    echo "  instance and point the CLI at it:" >&2
    echo "    effortless -setToolUrl rulebook-to-go=http://localhost:4425" >&2
    exit 1
fi
if [ "$AFTER_MTIME" = "$BEFORE_MTIME" ]; then
    echo "FATAL: $GENERATED was not regenerated by this build." >&2
    echo "  The file is unchanged, so the transpiler did not run. Grading it" >&2
    echo "  would report a score for stale code." >&2
    exit 1
fi

cd "$SCRIPT_DIR"

# Run the test for this substrate
"$SCRIPT_DIR/take-test.sh"
