default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  user: postgres
  password: ""

development:
  <<: *default
  database: erb_customer_fullname

test:
  <<: *default
  database: erb_customer_fullname_test

production:
  <<: *default
  database: erb_customer_fullname
