#!/usr/bin/env bash
# ============================================================================
# demo - Database Initialization Script
# ============================================================================
# Generated by rulebook-to-postgres tool.
#
# ⚠️  OVERWRITE MODE: NEVER — this file belongs to the project the moment
# it is created. The transpiler will NOT regenerate or overwrite it.
# Customize freely: rename env vars, add pre/post hooks, change connection
# strings. The project owner is responsible for keeping it working.
# Do NOT delete it expecting the transpiler to restore it — it won't.
#
# Two responsibilities: install magic-links auth, then run all
# NN[b]?-*.sql files in lex order. Skips *.sql.disabled.
#
# THIS IS THE DEV LOOP (per plan 04). Re-running against a populated
# DB should be safe — every file is meant to be idempotent. If it
# isn't, fix the file, not this script.
# ============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Optional override hook: effortless.env (one dir up) may export DATABASE_URL.
if [ -f "${SCRIPT_DIR}/../effortless.env" ]; then
    # shellcheck disable=SC1091
    set -a; . "${SCRIPT_DIR}/../effortless.env"; set +a
fi

# Default DB name is DERIVED from the active domain (erb_<domain>, dashes->underscores),
# matching the per-domain naming doctrine. This is NOT a fallback: it is the
# deterministically-correct database for this project. DATABASE_URL only overrides.
ERB_DOMAIN="${ERB_DOMAIN:-traffic-ticket-contest}"
DEFAULT_CONN="postgresql://postgres@localhost:5432/erb_${ERB_DOMAIN//-/_}"
DATABASE_URL="${DATABASE_URL:-${1:-$DEFAULT_CONN}}"

# Ensure the target database exists (createdb is a no-op if it already does).
DATABASE_URL_DB_NAME=$(echo "$DATABASE_URL" | sed -n 's|.*//[^/]*/\([^?]*\).*|\1|p')
DATABASE_URL_ADMIN_CONN="${DATABASE_URL%/*}/postgres"
if [ -n "$DATABASE_URL_DB_NAME" ]; then
    psql "$DATABASE_URL_ADMIN_CONN" -tc "SELECT 1 FROM pg_database WHERE datname = '$DATABASE_URL_DB_NAME'" 2>/dev/null | grep -q 1 \
        || createdb "$DATABASE_URL_ADMIN_CONN" "$DATABASE_URL_DB_NAME" 2>/dev/null || true
fi

# ----------------------------------------------------------------------
# Plan 04 §8: bases-URL refusal (defense in depth).
# bases.effortlessapi.com is migration-only. Any rebuild against it
# would drop tables and lose data. Use postgres/apply-migration.sh
# instead. This check has no escape hatch by design.
# ----------------------------------------------------------------------
if echo "$DATABASE_URL" | grep -qi 'bases\.effortlessapi\.com' ; then
    echo "refusing to run init-db.sh against bases." >&2
    echo "bases is migration-only — see CLAUDE.md \"Bases is migration-only\"" >&2
    echo "use postgres/apply-migration.sh postgres/migrations/NNNN-….sql" >&2
    exit 2
fi
if [ -n "${BASES_DATABASE_URL:-}" ] && [ "$DATABASE_URL" = "$BASES_DATABASE_URL" ]; then
    echo "refusing to run init-db.sh: DATABASE_URL == BASES_DATABASE_URL" >&2
    echo "bases is migration-only — use postgres/apply-migration.sh" >&2
    exit 2
fi

echo "[init-db] target: $DATABASE_URL"

# ----------------------------------------------------------------------
# 1. Always (re-)install magic-links auth. Idempotent → safe to repeat.
# ----------------------------------------------------------------------
if [ -f "${SCRIPT_DIR}/install-magic-links.sql" ]; then
    echo "[init-db] [RUN]  install-magic-links.sql"
    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "${SCRIPT_DIR}/install-magic-links.sql"
else
    echo "[init-db] note: install-magic-links.sql not present — skipping auth install"
    echo "[init-db]       fetch from https://magiclink.effortlessapi.com/install-magic-links/v1.sql"
fi

# ----------------------------------------------------------------------
# 2. Run all NN[b]?-*.sql files in lex order. Skip *.sql.disabled.
# ----------------------------------------------------------------------
shopt -s nullglob
FILES_RUN=()
FILES_SKIP=()
for f in "${SCRIPT_DIR}"/[0-9][0-9]*-*.sql "${SCRIPT_DIR}"/[0-9][0-9]*-*.sql.disabled; do
    [ -f "$f" ] || continue
    base=$(basename "$f")
    if [[ "$base" == *.disabled ]]; then
        echo "[init-db] [SKIP] $base"
        FILES_SKIP+=("$base")
        continue
    fi
    # 99-fk-constraints.sql is the TRANSPILER-GENERATED FK file (the only FK file —
    # there is no hand-maintained sidecar). The transpiler emits one scalar FK per
    # genuine many->one relationship; the inference no longer over-emits FKs for
    # type:raw table-name/multi-value fields (fixed in rulebook-to-postgres). It is
    # enforced by default; set EFFORTLESS_ENFORCE_FKS=false to skip (e.g. loading
    # known-dirty data).
    if [[ "$base" == "99-fk-constraints.sql" && "${EFFORTLESS_ENFORCE_FKS:-true}" != "true" ]]; then
        echo "[init-db] [SKIP] $base (EFFORTLESS_ENFORCE_FKS=false)"
        FILES_SKIP+=("$base")
        continue
    fi
    echo "[init-db] [RUN]  $base"
    if [[ "$base" == "99-fk-constraints.sql" ]]; then
        # FK constraints must hold — a violation means the rulebook's seed
        # data references a missing parent. Fail loudly (no silent fallback).
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    elif [[ "$base" == *b-* ]]; then
        # other customize files (NNb-*) tolerate per-row errors
        psql "$DATABASE_URL" -f "$f"
    elif [[ "$base" == "05-insert-data.sql" ]]; then
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    else
        psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
    fi
    FILES_RUN+=("$base")
done

# ----------------------------------------------------------------------
# 3. function-overrides/*.sql (per-function tweaks; errors non-fatal).
#    Two-pass: non-policy files first, then policy__* files (policies
#    often reference custom functions).
# ----------------------------------------------------------------------
run_override() {
    local sql_file="$1"
    local base; base=$(basename "$sql_file")
    if [[ "$base" == *.disabled ]]; then
        echo "[init-db] [SKIP] function-overrides/$base"
        return 0
    fi
    echo "[init-db] [RUN]  function-overrides/$base"
    psql "$DATABASE_URL" -f "$sql_file" || echo "[init-db] [WARN] $base failed (non-fatal)"
}
if compgen -G "${SCRIPT_DIR}/function-overrides/*.sql" > /dev/null 2>&1; then
    for sql_file in "${SCRIPT_DIR}/function-overrides/"*.sql; do
        base=$(basename "$sql_file")
        [[ "$base" == policy__* ]] && continue
        run_override "$sql_file"
    done
    for sql_file in "${SCRIPT_DIR}/function-overrides/"policy__*.sql; do
        [[ -f "$sql_file" ]] || continue
        run_override "$sql_file"
    done
fi

# ----------------------------------------------------------------------
# 4. Plan 04 §9: write postgres/.applied-manifest.json so tooling can
#    compare to .build-manifest.json and detect drift.
# ----------------------------------------------------------------------
APPLIED_AT="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
MANIFEST="${SCRIPT_DIR}/.applied-manifest.json"
{
    printf '{\n'
    printf '  "applied_at": "%s",\n' "$APPLIED_AT"
    printf '  "target": "%s",\n' "$DATABASE_URL"
    printf '  "files_run": ['
    sep=''
    for f in "${FILES_RUN[@]:-}"; do
        [ -z "$f" ] && continue
        printf '%s"%s"' "$sep" "$f"
        sep=','
    done
    printf '],\n'
    printf '  "files_skipped": ['
    sep=''
    for f in "${FILES_SKIP[@]:-}"; do
        [ -z "$f" ] && continue
        printf '%s"%s"' "$sep" "$f"
        sep=','
    done
    printf ']\n'
    printf '}\n'
} > "$MANIFEST"

echo "[init-db] complete (manifest: .applied-manifest.json)"
