# Seed data for Customers
# Generated by rulebook-to-rails-seeds.py
# Inserts into the base table; computed columns are derived by vw_customers.

conn = ActiveRecord::Base.connection
conn.execute("INSERT INTO customers (customer_id, first_name, last_name) VALUES (#{[conn.quote('jane-smith-email-com'), conn.quote('Jane'), conn.quote('Smithy')].join(', ')}) ON CONFLICT DO NOTHING")
conn.execute("INSERT INTO customers (customer_id, first_name, last_name) VALUES (#{[conn.quote('john-doe-email-com'), conn.quote('John'), conn.quote('Doe')].join(', ')}) ON CONFLICT DO NOTHING")
conn.execute("INSERT INTO customers (customer_id, first_name, last_name) VALUES (#{[conn.quote('emily-jones-email-com'), conn.quote('Emily'), conn.quote('Jones')].join(', ')}) ON CONFLICT DO NOTHING")
conn.execute("INSERT INTO customers (customer_id, first_name, last_name) VALUES (#{[conn.quote('alice-cooper'), conn.quote('Alice'), conn.quote('Gutknechts')].join(', ')}) ON CONFLICT DO NOTHING")
