-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- ============================================================================


-- Disable body validation so LANGUAGE sql functions can forward-reference
-- each other within this file. (pg_dump does the same thing for the same
-- reason.) Without this, SQL functions parse-check at CREATE time and fail
-- on the first forward call site; plpgsql didn't, which is how this file
-- ever worked. Dependency order is still enforced at EXECUTION time.
SET check_function_bodies = off;

-- ============================================================================
-- ERB BUILD PARAMETERS (docs/ERB-BUILD-PARAMETERS.md)
-- erbBlankLogic=coerce, erbDateDiff=calendar, erbDateTimeText=iso8601, erbTimezone=UTC, erbWholeNumber=by-field-type
-- ============================================================================

CREATE OR REPLACE FUNCTION erb_build_parameters()
RETURNS JSONB AS $$
  SELECT '{"erbBlankLogic":"coerce","erbDateDiff":"calendar","erbDateTimeText":"iso8601","erbTimezone":"UTC","erbWholeNumber":"by-field-type"}'::jsonb;
$$ LANGUAGE sql IMMUTABLE;

-- A timestamp inside text, per erbDateTimeText, in erbTimezone. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_datetime_text(ts TIMESTAMPTZ)
RETURNS TEXT AS $$
  SELECT CASE WHEN ts IS NULL THEN '' ELSE
    to_char(ts AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS')
    || CASE WHEN (EXTRACT(MICROSECONDS FROM ts)::bigint % 1000000) <> 0 THEN rtrim(to_char(ts AT TIME ZONE 'UTC', '.US'), '0') ELSE '' END
    || CASE WHEN o.off < 0 THEN '-' ELSE '+' END || lpad((abs(o.off) / 3600)::text, 2, '0') || ':' || lpad(((abs(o.off) % 3600) / 60)::text, 2, '0')
  END
  FROM (SELECT EXTRACT(EPOCH FROM ((ts AT TIME ZONE 'UTC') - (ts AT TIME ZONE 'UTC')))::integer AS off) o;
$$ LANGUAGE sql STABLE;

-- A date inside text: YYYY-MM-DD. Blank renders ''.
CREATE OR REPLACE FUNCTION erb_date_text(d DATE)
RETURNS TEXT AS $$
  SELECT COALESCE(to_char(d, 'YYYY-MM-DD'), '');
$$ LANGUAGE sql IMMUTABLE;

-- A number inside text: the shortest exact form, no trailing .0 (2, 2.5). Blank renders ''.
CREATE OR REPLACE FUNCTION erb_number_text(n NUMERIC)
RETURNS TEXT AS $$
  SELECT CASE WHEN n IS NULL THEN ''
              WHEN n::text LIKE '%.%' THEN rtrim(rtrim(n::text, '0'), '.')
              ELSE n::text END;
$$ LANGUAGE sql IMMUTABLE;


-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

-- get_seed_facts_n
-- Helper function: Get N from SeedFacts by SeedFactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_seed_facts_n(p_seed_fact_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT n FROM seed_facts WHERE seed_fact_id = p_seed_fact_id);
$$ LANGUAGE sql STABLE;

-- get_seed_facts_op
-- Helper function: Get Op from SeedFacts by SeedFactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_seed_facts_op(p_seed_fact_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT op FROM seed_facts WHERE seed_fact_id = p_seed_fact_id);
$$ LANGUAGE sql STABLE;

-- get_seed_facts_tuple_json
-- Helper function: Get TupleJson from SeedFacts by SeedFactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_seed_facts_tuple_json(p_seed_fact_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT tuple_json FROM seed_facts WHERE seed_fact_id = p_seed_fact_id);
$$ LANGUAGE sql STABLE;

-- get_seed_facts_k
-- Helper function: Get K from SeedFacts by SeedFactId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_seed_facts_k(p_seed_fact_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT k FROM seed_facts WHERE seed_fact_id = p_seed_fact_id);
$$ LANGUAGE sql STABLE;

-- get_transition_effects_op
-- Helper function: Get Op from TransitionEffects by EffectId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_transition_effects_op(p_effect_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT op FROM transition_effects WHERE effect_id = p_effect_id);
$$ LANGUAGE sql STABLE;

-- calc_edb_relations_name
-- Field: EDBRelations.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_edb_relations_name(p_relation_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(relation_id, '') FROM edb_relations WHERE relation_id = p_relation_id))::text;
$$ LANGUAGE sql STABLE;

-- get_transitions_description
-- Helper function: Get Description from Transitions by TransitionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_transitions_description(p_transition_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM transitions WHERE transition_id = p_transition_id);
$$ LANGUAGE sql STABLE;

-- calc_commands_name
-- Field: Commands.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_commands_name(p_command_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(command_id, '') FROM commands WHERE command_id = p_command_id))::text;
$$ LANGUAGE sql STABLE;

-- get_transition_events_event_relation
-- Helper function: Get EventRelation from TransitionEvents by EventId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_transition_events_event_relation(p_event_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT event_relation FROM transition_events WHERE event_id = p_event_id);
$$ LANGUAGE sql STABLE;

-- get_integrity_constraints_description
-- Helper function: Get Description from IntegrityConstraints by ConstraintId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_integrity_constraints_description(p_constraint_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM integrity_constraints WHERE constraint_id = p_constraint_id);
$$ LANGUAGE sql STABLE;

-- calc_rules_name
-- Field: Rules.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_rules_name(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(rule_id, '') FROM rules WHERE rule_id = p_rule_id))::text;
$$ LANGUAGE sql STABLE;

-- get_commands_params
-- Helper function: Get Params from Commands by CommandId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_commands_params(p_command_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT params FROM commands WHERE command_id = p_command_id);
$$ LANGUAGE sql STABLE;

-- get_commands_param_count
-- Helper function: Get ParamCount from Commands by CommandId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_commands_param_count(p_command_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT param_count FROM commands WHERE command_id = p_command_id);
$$ LANGUAGE sql STABLE;

-- get_commands_description
-- Helper function: Get Description from Commands by CommandId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_commands_description(p_command_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM commands WHERE command_id = p_command_id);
$$ LANGUAGE sql STABLE;

-- get_rules_head_predicate
-- Helper function: Get HeadPredicate from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_head_predicate(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT head_predicate FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- get_rules_kind
-- Helper function: Get Kind from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_kind(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT kind FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- get_rules_head_json
-- Helper function: Get HeadJson from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_head_json(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT head_json FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- get_rules_body_json
-- Helper function: Get BodyJson from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_body_json(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT body_json FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- get_rules_agg_json
-- Helper function: Get AggJson from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_agg_json(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT agg_json FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- get_rules_paper_section_ref
-- Helper function: Get PaperSectionRef from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_paper_section_ref(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT paper_section_ref FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- get_rules_description
-- Helper function: Get Description from Rules by RuleId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_rules_description(p_rule_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM rules WHERE rule_id = p_rule_id);
$$ LANGUAGE sql STABLE;

-- calc_transitions_name
-- Field: Transitions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_transitions_name(p_transition_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(transition_id, '') FROM transitions WHERE transition_id = p_transition_id))::text;
$$ LANGUAGE sql STABLE;

-- get_edb_relations_fields
-- Helper function: Get Fields from EDBRelations by RelationId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_edb_relations_fields(p_relation_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT fields FROM edb_relations WHERE relation_id = p_relation_id);
$$ LANGUAGE sql STABLE;

-- get_edb_relations_field_count
-- Helper function: Get FieldCount from EDBRelations by RelationId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_edb_relations_field_count(p_relation_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT field_count FROM edb_relations WHERE relation_id = p_relation_id);
$$ LANGUAGE sql STABLE;

-- get_edb_relations_description
-- Helper function: Get Description from EDBRelations by RelationId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_edb_relations_description(p_relation_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM edb_relations WHERE relation_id = p_relation_id);
$$ LANGUAGE sql STABLE;

-- calc_transition_effects_name
-- Field: TransitionEffects.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_transition_effects_name(p_effect_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(effect_id, '') FROM transition_effects WHERE effect_id = p_effect_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_transition_events_name
-- Field: TransitionEvents.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_transition_events_name(p_event_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(event_id, '') FROM transition_events WHERE event_id = p_event_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_integrity_constraints_name
-- Field: IntegrityConstraints.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_integrity_constraints_name(p_constraint_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(constraint_id, '') FROM integrity_constraints WHERE constraint_id = p_constraint_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_observables_name
-- Field: Observables.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_observables_name(p_observable_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(observable_id, '') FROM observables WHERE observable_id = p_observable_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_seed_facts_name
-- Field: SeedFacts.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_seed_facts_name(p_seed_fact_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(seed_fact_id, '') FROM seed_facts WHERE seed_fact_id = p_seed_fact_id))::text;
$$ LANGUAGE sql STABLE;

-- get_answer_key_results_traces_produced
-- Helper function: Get TracesProduced from AnswerKeyResults by AnswerKeyResultId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_answer_key_results_traces_produced(p_answer_key_result_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT traces_produced FROM answer_key_results WHERE answer_key_result_id = p_answer_key_result_id);
$$ LANGUAGE sql STABLE;

-- get_answer_key_results_permitted
-- Helper function: Get Permitted from AnswerKeyResults by AnswerKeyResultId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_answer_key_results_permitted(p_answer_key_result_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT permitted FROM answer_key_results WHERE answer_key_result_id = p_answer_key_result_id);
$$ LANGUAGE sql STABLE;

-- get_answer_key_results_outcome
-- Helper function: Get Outcome from AnswerKeyResults by AnswerKeyResultId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_answer_key_results_outcome(p_answer_key_result_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT outcome FROM answer_key_results WHERE answer_key_result_id = p_answer_key_result_id);
$$ LANGUAGE sql STABLE;

-- calc_input_histories_name
-- Field: InputHistories.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_input_histories_name(p_input_history_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(input_history_id, '') FROM input_histories WHERE input_history_id = p_input_history_id))::text;
$$ LANGUAGE sql STABLE;

-- get_reflection_results_outcome
-- Helper function: Get Outcome from ReflectionResults by ReflectionResultId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_reflection_results_outcome(p_reflection_result_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT outcome FROM reflection_results WHERE reflection_result_id = p_reflection_result_id);
$$ LANGUAGE sql STABLE;

-- calc_reflection_conditions_name
-- Field: ReflectionConditions.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_reflection_conditions_name(p_condition_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(condition_id, '') FROM reflection_conditions WHERE condition_id = p_condition_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_substrates_name
-- Field: Substrates.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_substrates_name(p_substrate_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(substrate_id, '') FROM substrates WHERE substrate_id = p_substrate_id))::text;
$$ LANGUAGE sql STABLE;

-- calc_substrates_answer_key_result_count
-- Field: Substrates.AnswerKeyResultCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_substrates_answer_key_result_count(p_substrate_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM answer_key_results WHERE substrate = (SELECT NULLIF(substrate_id, '') FROM substrates WHERE substrate_id = p_substrate_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_substrates_answer_key_fail_count
-- Field: Substrates.AnswerKeyFailCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_substrates_answer_key_fail_count(p_substrate_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM answer_key_results WHERE substrate = (SELECT NULLIF(substrate_id, '') FROM substrates WHERE substrate_id = p_substrate_id) AND outcome = 'fail'))::integer;
$$ LANGUAGE sql STABLE;

-- calc_substrates_answer_key_ok
-- Field: Substrates.AnswerKeyOk
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_substrates_answer_key_ok(p_substrate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((COALESCE(COALESCE((calc_substrates_answer_key_result_count(p_substrate_id))::NUMERIC, 0) > 0, FALSE) AND COALESCE(COALESCE((calc_substrates_answer_key_fail_count(p_substrate_id))::NUMERIC, 0) = 0, FALSE)));
$$ LANGUAGE sql STABLE;

-- calc_substrates_reflection_result_count
-- Field: Substrates.ReflectionResultCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_substrates_reflection_result_count(p_substrate_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM reflection_results WHERE substrate = (SELECT NULLIF(substrate_id, '') FROM substrates WHERE substrate_id = p_substrate_id)))::integer;
$$ LANGUAGE sql STABLE;

-- calc_substrates_reflection_fail_count
-- Field: Substrates.ReflectionFailCount
-- Type: aggregation | DataType: integer | Returns: INTEGER


CREATE OR REPLACE FUNCTION calc_substrates_reflection_fail_count(p_substrate_id TEXT)
RETURNS INTEGER AS $$
  SELECT ((SELECT COUNT(*) FROM reflection_results WHERE substrate = (SELECT NULLIF(substrate_id, '') FROM substrates WHERE substrate_id = p_substrate_id) AND outcome = 'fail'))::integer;
$$ LANGUAGE sql STABLE;

-- calc_substrates_reflection_ok
-- Field: Substrates.ReflectionOk
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_substrates_reflection_ok(p_substrate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((COALESCE(COALESCE((calc_substrates_reflection_result_count(p_substrate_id))::NUMERIC, 0) > 0, FALSE) AND COALESCE(COALESCE((calc_substrates_reflection_fail_count(p_substrate_id))::NUMERIC, 0) = 0, FALSE)));
$$ LANGUAGE sql STABLE;

-- calc_substrates_conformant
-- Field: Substrates.Conformant
-- Type: calculated | DataType: boolean | Returns: BOOLEAN


CREATE OR REPLACE FUNCTION calc_substrates_conformant(p_substrate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT ((COALESCE(calc_substrates_answer_key_ok(p_substrate_id), FALSE) AND COALESCE(calc_substrates_reflection_ok(p_substrate_id), FALSE)))::boolean;
$$ LANGUAGE sql STABLE;

-- get_substrates_description
-- Helper function: Get Description from Substrates by SubstrateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_substrates_description(p_substrate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM substrates WHERE substrate_id = p_substrate_id);
$$ LANGUAGE sql STABLE;

-- get_substrates_paper_section_ref
-- Helper function: Get PaperSectionRef from Substrates by SubstrateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_substrates_paper_section_ref(p_substrate_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT paper_section_ref FROM substrates WHERE substrate_id = p_substrate_id);
$$ LANGUAGE sql STABLE;

-- get_substrates_is_control
-- Helper function: Get IsControl from Substrates by SubstrateId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_substrates_is_control(p_substrate_id TEXT)
RETURNS BOOLEAN AS $$
  SELECT (SELECT is_control FROM substrates WHERE substrate_id = p_substrate_id);
$$ LANGUAGE sql STABLE;

-- get_input_histories_source_file
-- Helper function: Get SourceFile from InputHistories by InputHistoryId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_input_histories_source_file(p_input_history_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT source_file FROM input_histories WHERE input_history_id = p_input_history_id);
$$ LANGUAGE sql STABLE;

-- get_input_histories_event_count
-- Helper function: Get EventCount from InputHistories by InputHistoryId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_input_histories_event_count(p_input_history_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT event_count FROM input_histories WHERE input_history_id = p_input_history_id);
$$ LANGUAGE sql STABLE;

-- get_input_histories_description
-- Helper function: Get Description from InputHistories by InputHistoryId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_input_histories_description(p_input_history_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM input_histories WHERE input_history_id = p_input_history_id);
$$ LANGUAGE sql STABLE;

-- calc_answer_key_results_name
-- Field: AnswerKeyResults.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_answer_key_results_name(p_answer_key_result_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(answer_key_result_id, '') FROM answer_key_results WHERE answer_key_result_id = p_answer_key_result_id))::text;
$$ LANGUAGE sql STABLE;

-- get_reflection_conditions_condition_number
-- Helper function: Get ConditionNumber from ReflectionConditions by ConditionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_reflection_conditions_condition_number(p_condition_id TEXT)
RETURNS INTEGER AS $$
  SELECT (SELECT condition_number FROM reflection_conditions WHERE condition_id = p_condition_id);
$$ LANGUAGE sql STABLE;

-- get_reflection_conditions_title
-- Helper function: Get Title from ReflectionConditions by ConditionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_reflection_conditions_title(p_condition_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT title FROM reflection_conditions WHERE condition_id = p_condition_id);
$$ LANGUAGE sql STABLE;

-- get_reflection_conditions_paper_section_ref
-- Helper function: Get PaperSectionRef from ReflectionConditions by ConditionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_reflection_conditions_paper_section_ref(p_condition_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT paper_section_ref FROM reflection_conditions WHERE condition_id = p_condition_id);
$$ LANGUAGE sql STABLE;

-- get_reflection_conditions_description
-- Helper function: Get Description from ReflectionConditions by ConditionId
-- Used for join-free cross-table references in aggregations

CREATE OR REPLACE FUNCTION get_reflection_conditions_description(p_condition_id TEXT)
RETURNS TEXT AS $$
  SELECT (SELECT description FROM reflection_conditions WHERE condition_id = p_condition_id);
$$ LANGUAGE sql STABLE;

-- calc_reflection_results_name
-- Field: ReflectionResults.Name
-- Type: calculated | DataType: string | Returns: TEXT


CREATE OR REPLACE FUNCTION calc_reflection_results_name(p_reflection_result_id TEXT)
RETURNS TEXT AS $$
  SELECT ((SELECT NULLIF(reflection_result_id, '') FROM reflection_results WHERE reflection_result_id = p_reflection_result_id))::text;
$$ LANGUAGE sql STABLE;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

-- ============================================================================
-- INVERSE RELATIONSHIP FUNCTIONS
-- These functions perform reverse FK lookups for inverse-side relationships
-- ============================================================================

