-- ============================================================================
-- CREATE TABLES (check-add mode) - Idempotent schema, never drops columns
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: check-add    Stage: dev
-- Total Tables: 5
-- Total Raw Fields: 22
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Customers: Table: Customers
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS customers (
  customer_id                         TEXT                 PRIMARY KEY
);
ALTER TABLE customers ADD COLUMN IF NOT EXISTS customer TEXT;                                       -- Identifier for the customers.
ALTER TABLE customers ADD COLUMN IF NOT EXISTS email_address TEXT;                                  -- Thec ustomers email address
ALTER TABLE customers ADD COLUMN IF NOT EXISTS first_name TEXT;                                     -- First Name of the customer - used to make the full name
ALTER TABLE customers ADD COLUMN IF NOT EXISTS last_name TEXT;                                      -- Last Name of the customer - used to make the full name
COMMENT ON TABLE customers IS 'Table: Customers';
COMMENT ON COLUMN customers.customer IS 'Identifier for the customers.';
COMMENT ON COLUMN customers.email_address IS 'Thec ustomers email address';
COMMENT ON COLUMN customers.first_name IS 'First Name of the customer - used to make the full name';
COMMENT ON COLUMN customers.last_name IS 'Last Name of the customer - used to make the full name';

-- ----------------------------------------------------------------------------
-- Projects: Table: Projects
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
  project_id                          TEXT                 PRIMARY KEY
);
ALTER TABLE projects ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS project_type TEXT;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS is_approved BOOLEAN;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS approved_by TEXT;
COMMENT ON TABLE projects IS 'Table: Projects';

-- ----------------------------------------------------------------------------
-- Employees: Table: Employees
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS employees (
  employee_id                         TEXT                 PRIMARY KEY
);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS email_address TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS phone_number TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS role TEXT;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS projects TEXT;
COMMENT ON TABLE employees IS 'Table: Employees';

-- ----------------------------------------------------------------------------
-- Roles: Table: Roles
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS roles (
  role_id                             TEXT                 PRIMARY KEY
);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS is_manager BOOLEAN;
ALTER TABLE roles ADD COLUMN IF NOT EXISTS employees TEXT;
COMMENT ON TABLE roles IS 'Table: Roles';

-- ----------------------------------------------------------------------------
-- TypesOfProject: Table: TypesOfProject
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS types_of_project (
  types_of_project_id                 TEXT                 PRIMARY KEY
);
ALTER TABLE types_of_project ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE types_of_project ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE types_of_project ADD COLUMN IF NOT EXISTS requires_manager_approval BOOLEAN;
ALTER TABLE types_of_project ADD COLUMN IF NOT EXISTS projects TEXT;
COMMENT ON TABLE types_of_project IS 'Table: TypesOfProject';

-- ============================================================================
-- FK INDEXES - Performance only, always applied
-- ============================================================================

-- Customers
CREATE INDEX IF NOT EXISTS idx_customers_customer ON customers (customer);

-- Projects
CREATE INDEX IF NOT EXISTS idx_projects_project_type ON projects (project_type);
CREATE INDEX IF NOT EXISTS idx_projects_approved_by ON projects (approved_by);

-- Employees
CREATE INDEX IF NOT EXISTS idx_employees_role ON employees (role);
CREATE INDEX IF NOT EXISTS idx_employees_projects ON employees (projects);

-- Roles
CREATE INDEX IF NOT EXISTS idx_roles_employees ON roles (employees);

-- TypesOfProject
CREATE INDEX IF NOT EXISTS idx_types_of_project_projects ON types_of_project (projects);

-- 7 FK index(es) declared.
