-- ============================================================================
-- INSERT DATA - Load data from rulebook
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- PK strategy: string (FK values are rewritten to match each PK)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 形状: Table: 形状
-- ----------------------------------------------------------------------------
INSERT INTO 形状 (形状id, 名称)
VALUES ('2', '形状2') ON CONFLICT (形状id) DO UPDATE SET 名称 = EXCLUDED.名称;

INSERT INTO 形状 (形状id, 名称)
VALUES ('1', '形状1') ON CONFLICT (形状id) DO UPDATE SET 名称 = EXCLUDED.名称;

INSERT INTO 形状 (形状id, 名称)
VALUES ('3', '形状3') ON CONFLICT (形状id) DO UPDATE SET 名称 = EXCLUDED.名称;

-- ----------------------------------------------------------------------------
-- 边: Table: 边
-- ----------------------------------------------------------------------------
INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e1', '1', '阿', 3, 37) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e2', '1', '比', 4, 53) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e3', '1', '西', 5, 90) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e4', '2', '阿', 5, 90) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e5', '2', '比', 5, 90) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e6', '2', '西', 5, 90) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e7', '2', '迪', 5, 90) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e8', '3', '阿', 14, 180) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

INSERT INTO 边 (边id, 形状, 标签, 长度, 角度)
VALUES ('e9', '3', '比', 14, 180) ON CONFLICT (边id) DO UPDATE SET 形状 = EXCLUDED.形状, 标签 = EXCLUDED.标签, 长度 = EXCLUDED.长度, 角度 = EXCLUDED.角度;

