-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Mode: drop-all    Stage: dev
-- Total Views: 3
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Drop pass: every rulebook-owned view, reverse iteration order, CASCADE.
-- The rulebook is HEAD — the surviving view set must mirror it exactly.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_assessments CASCADE;
DROP VIEW IF EXISTS vw_intelligences CASCADE;
DROP VIEW IF EXISTS vw_capabilities CASCADE;

-- ----------------------------------------------------------------------------
-- vw_capabilities: Cognitive capabilities being assessed. Tiered foundational/composite/emergent and weighted by importance.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_capabilities CASCADE;
CREATE VIEW vw_capabilities WITH (security_invoker = ON) AS
SELECT
  t.capabilities_id,                                                            -- Slug for the capability (e.g. 'reasoning'). First raw field is the PK.
  calc_capabilities_name(t.capabilities_id) AS name,                            -- Display name (derived from PK).
  t.description,                                                                -- Short prose describing the capability.
  t.tier,                                                                       -- Capability tier: foundational, composite, or emergent.
  t.weight                                                                      -- Importance multiplier used when computing WeightedScore on each Assessment.
FROM capabilities t;

-- ----------------------------------------------------------------------------
-- vw_intelligences: Agents being classified by the taxonomy. Each Intelligence's TaxonomyClass is derived from the rollup of its Assessments.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_intelligences CASCADE;
CREATE VIEW vw_intelligences WITH (security_invoker = ON) AS
SELECT
  t.intelligences_id,                                                           -- Slug for the intelligence (e.g. 'human'). First raw field is the PK.
  calc_intelligences_name(t.intelligences_id) AS name,                          -- Display name (derived from PK).
  t.description,                                                                -- Short prose describing what this intelligence is.
  t.substrate,                                                                  -- Substrate kind: biological, digital, or collective.
  calc_intelligences_assessment_count(t.intelligences_id) AS assessment_count,  -- How many capabilities this intelligence has been assessed on.
  calc_intelligences_total_weighted_score(t.intelligences_id) AS total_weighted_score,-- Sum of WeightedScore across all this intelligence's assessments. Second hop in the DAG.
  calc_intelligences_taxonomy_class(t.intelligences_id) AS taxonomy_class       -- Taxonomic bucket derived from TotalWeightedScore. Third hop in the DAG.
FROM intelligences t;

-- ----------------------------------------------------------------------------
-- vw_assessments: Per-capability scores for each intelligence. The junction table whose calculated WeightedScore feeds the rollup on Intelligences.
-- Combines base table columns with calculated/lookup/aggregation fields.
-- ----------------------------------------------------------------------------
DROP VIEW IF EXISTS vw_assessments CASCADE;
CREATE VIEW vw_assessments WITH (security_invoker = ON) AS
SELECT
  t.assessments_id,                                                             -- Slug encoding the intelligence-capability pair (e.g. 'human-reasoning'). First raw field is the PK.
  calc_assessments_name(t.assessments_id) AS name,                              -- Display name (derived from PK).
  t.intelligence,                                                               -- FK to Intelligences. Holds the value of Intelligences.IntelligencesId.
  t.capability,                                                                 -- FK to Capabilities. Holds the value of Capabilities.CapabilitiesId.
  t.raw_score,                                                                  -- User-editable assessment score from 0 to 100. Edit this in the UI to watch the cascade.
  calc_assessments_intelligence_name(t.assessments_id) AS intelligence_name,    -- Display name pulled from the related Intelligences row.
  calc_assessments_capability_name(t.assessments_id) AS capability_name,        -- Display name pulled from the related Capabilities row.
  calc_assessments_capability_tier(t.assessments_id) AS capability_tier,        -- Tier (foundational/composite/emergent) pulled from the related Capabilities row.
  calc_assessments_capability_weight(t.assessments_id) AS capability_weight,    -- Importance multiplier pulled from the related Capabilities row.
  calc_assessments_weighted_score(t.assessments_id) AS weighted_score           -- RawScore scaled by the capability's Weight. First hop in the DAG.
FROM assessments t;

