-- ============================================================================
-- DROP AND CREATE TABLES - Clean slate + Normalized schema
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Tables: 2
-- Total Raw Fields: 5
-- ============================================================================

SET timezone = 'UTC';

-- ============================================================================
-- DROP SPECIFIC OBJECTS - Only dropping objects that will be recreated
-- ============================================================================

-- Drop functions (order: first, because views depend on them)
DROP FUNCTION IF EXISTS calc_customers_full_name(TEXT) CASCADE;

-- Drop views (order: second, because they depend on tables)
DROP VIEW IF EXISTS vw_customers CASCADE;
DROP VIEW IF EXISTS vw_name CASCADE;

-- Drop tables (order: last, after dependent objects are removed)
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS name CASCADE;

-- ============================================================================
-- CREATE TABLES - Normalized data only (no calculated fields)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Name: Table: Name
-- ----------------------------------------------------------------------------
CREATE TABLE name (
);

-- ----------------------------------------------------------------------------
-- Customers: Table: Customers
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
  customer_id                         TEXT                 PRIMARY KEY,
  name                                TEXT                ,                     -- Identifier for the customers.
  email_address                       TEXT                ,                     -- Thec ustomers email address
  first_name                          TEXT                ,                     -- First Name of the customer - used to make the full name
  last_name                           TEXT                                      -- Last Name of the customer - used to make the full name
);
COMMENT ON TABLE customers IS 'Table: Customers';
COMMENT ON COLUMN customers.name IS 'Identifier for the customers.';
COMMENT ON COLUMN customers.email_address IS 'Thec ustomers email address';
COMMENT ON COLUMN customers.first_name IS 'First Name of the customer - used to make the full name';
COMMENT ON COLUMN customers.last_name IS 'Last Name of the customer - used to make the full name';

