-- ============================================================================
-- CREATE FUNCTIONS - Calculation functions for lookup/calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- ============================================================================

-- ============================================================================
-- LOOKUP FUNCTIONS
-- These functions perform lookups via foreign key relationships
-- ============================================================================

CREATE OR REPLACE FUNCTION get_seasons_season_number(p_season_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT season_number FROM seasons WHERE season_id = p_season_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_seasons_title(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title FROM seasons WHERE season_id = p_season_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_seasons_description(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description FROM seasons WHERE season_id = p_season_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_seasons_start_airdate(p_season_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT start_airdate FROM seasons WHERE season_id = p_season_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_seasons_end_airdate(p_season_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT end_airdate FROM seasons WHERE season_id = p_season_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_seasons_mock_data_notes(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT mock_data_notes FROM seasons WHERE season_id = p_season_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ratings_rating(p_rating_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT rating FROM ratings WHERE rating_id = p_rating_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ratings_users_name(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT users_name FROM ratings WHERE rating_id = p_rating_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ratings_email_address(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT email_address FROM ratings WHERE rating_id = p_rating_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ratings_phone_nmber(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT phone_nmber FROM ratings WHERE rating_id = p_rating_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ratings_notes(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT notes FROM ratings WHERE rating_id = p_rating_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_ratings_created_at(p_rating_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT created_at FROM ratings WHERE rating_id = p_rating_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_series_name(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CONCAT((SELECT series_number FROM series WHERE serie_id = p_serie_id), '-', (SELECT NULLIF(show_code, '') FROM series WHERE serie_id = p_serie_id)))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_series_total_seasons(p_serie_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN ((SELECT COUNT(*) FROM seasons WHERE series = (SELECT NULLIF(serie_id, '') FROM series WHERE serie_id = p_serie_id)));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_series_total_episodes(p_serie_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN ((SELECT COALESCE(SUM(calc_seasons_episode_count(season_id)), 0) FROM seasons WHERE series = p_serie_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_series_is_long_running(p_serie_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (calc_series_total_episodes(p_serie_id) > 50)::boolean;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_series_rating(p_serie_id TEXT)
RETURNS NUMERIC AS $$
BEGIN
  RETURN ((SELECT COALESCE(SUM(rating), 0) FROM ratings WHERE series = p_serie_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_series_is_good(p_serie_id TEXT)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN (calc_series_rating(p_serie_id) >= 4.5)::boolean;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_seasons_show_title(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title::text FROM series WHERE serie_id = (SELECT series FROM seasons WHERE season_id = p_season_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_seasons_show_description(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description::text FROM series WHERE serie_id = (SELECT series FROM seasons WHERE season_id = p_season_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_seasons_show_network(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT network::text FROM series WHERE serie_id = (SELECT series FROM seasons WHERE season_id = p_season_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_series_number(p_serie_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT series_number FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_show_code(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT show_code FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_title(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_description(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_network(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT network FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_premiere_date(p_serie_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT premiere_date FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_series_finale_date(p_serie_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT finale_date FROM series WHERE serie_id = p_serie_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_episode_number(p_episode_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT episode_number FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_description(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_airdate(p_episode_id TEXT)
RETURNS TIMESTAMPTZ AS $$
BEGIN
  RETURN (SELECT airdate FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_writers(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT writers FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_director(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT director FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_runtime_minutes(p_episode_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT runtime_minutes FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_one_sentence_summary(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT one_sentence_summary FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_episodes_favorite_color(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT favorite_color FROM episodes WHERE episode_id = p_episode_id);
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_seasons_name(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CONCAT((SELECT NULLIF(series, '') FROM seasons WHERE season_id = p_season_id), '-Season-', (SELECT season_number FROM seasons WHERE season_id = p_season_id)))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_seasons_episode_count(p_season_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN ((SELECT COUNT(*) FROM episodes WHERE season = (SELECT NULLIF(season_id, '') FROM seasons WHERE season_id = p_season_id)));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_episodes_season_number(p_episode_id TEXT)
RETURNS INTEGER AS $$
BEGIN
  RETURN (SELECT season_number::integer FROM seasons WHERE season_id = (SELECT season FROM episodes WHERE episode_id = p_episode_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_episodes_season_title(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT title::text FROM seasons WHERE season_id = (SELECT season FROM episodes WHERE episode_id = p_episode_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_episodes_season_description(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (SELECT description::text FROM seasons WHERE season_id = (SELECT season FROM episodes WHERE episode_id = p_episode_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_episodes_name(p_episode_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CONCAT((SELECT NULLIF(season, '') FROM episodes WHERE episode_id = p_episode_id), '-Episode-', CASE WHEN COALESCE((SELECT episode_number FROM episodes WHERE episode_id = p_episode_id) < 10, FALSE) THEN '0' ELSE '' END, (SELECT episode_number FROM episodes WHERE episode_id = p_episode_id)))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_ratings_series_name(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN calc_series_name((SELECT series FROM ratings WHERE rating_id = p_rating_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_ratings_episode_name(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN calc_episodes_name((SELECT episode FROM ratings WHERE rating_id = p_rating_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_ratings_episode_season_title(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN calc_episodes_season_title((SELECT episode FROM ratings WHERE rating_id = p_rating_id));
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_ratings_name(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CONCAT(calc_ratings_display_name(p_rating_id), '-', (SELECT NULLIF(users_name, '') FROM ratings WHERE rating_id = p_rating_id)))::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;


CREATE OR REPLACE FUNCTION calc_ratings_display_name(p_rating_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (CASE WHEN (SELECT NULLIF(series, '') FROM ratings WHERE rating_id = p_rating_id) IS NULL THEN CONCAT('Episode: ', calc_ratings_episode_name(p_rating_id)) ELSE CONCAT('Series: ', calc_ratings_series_name(p_rating_id)) END)::text;
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

-- ============================================================================
-- MANY-SIDE RELATIONSHIP FUNCTIONS
-- These functions aggregate child records for many-side relationships
-- ============================================================================

CREATE OR REPLACE FUNCTION calc_series_seasons(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT STRING_AGG(season_id::TEXT, ', ' ORDER BY season_id)
    FROM seasons
    WHERE series = p_serie_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION calc_series_series_ratings(p_serie_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT STRING_AGG(rating_id::TEXT, ', ' ORDER BY rating_id)
    FROM ratings
    WHERE series = p_serie_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION calc_seasons_episodes(p_season_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT STRING_AGG(episode_id::TEXT, ', ' ORDER BY episode_id)
    FROM episodes
    WHERE season = p_season_id
  );
END;
$$ LANGUAGE plpgsql STABLE SECURITY DEFINER;

