-- ============================================================================
-- CREATE VIEWS - Combine raw data with calculated fields
-- ============================================================================
-- Generated by rulebook-to-postgres tool
-- Total Views: 7
-- ============================================================================

CREATE OR REPLACE VIEW vw_series WITH (security_invoker = ON) AS
SELECT
  t.serie_id,
  calc_series_name(t.serie_id) AS name,
  t.series_number,
  t.show_code,
  t.title,
  t.description,
  t.network,
  t.premiere_date,
  t.finale_date,
  calc_series_total_seasons(t.serie_id) AS total_seasons,
  calc_series_total_episodes(t.serie_id) AS total_episodes,
  calc_series_is_long_running(t.serie_id) AS is_long_running,
  calc_series_seasons(t.serie_id) AS seasons,
  calc_series_series_ratings(t.serie_id) AS series_ratings,
  calc_series_rating(t.serie_id) AS rating,
  calc_series_is_good(t.serie_id) AS is_good
FROM series t;

CREATE OR REPLACE VIEW vw_seasons WITH (security_invoker = ON) AS
SELECT
  t.season_id,
  calc_seasons_name(t.season_id) AS name,
  t.series,
  calc_seasons_show_title(t.season_id) AS show_title,
  calc_seasons_show_description(t.season_id) AS show_description,
  calc_seasons_show_network(t.season_id) AS show_network,
  t.season_number,
  t.title,
  t.description,
  t.start_airdate,
  t.end_airdate,
  calc_seasons_episode_count(t.season_id) AS episode_count,
  calc_seasons_episodes(t.season_id) AS episodes,
  t.mock_data_notes
FROM seasons t;

CREATE OR REPLACE VIEW vw_episodes WITH (security_invoker = ON) AS
SELECT
  t.episode_id,
  calc_episodes_name(t.episode_id) AS name,
  t.season,
  calc_episodes_season_number(t.episode_id) AS season_number,
  calc_episodes_season_title(t.episode_id) AS season_title,
  calc_episodes_season_description(t.episode_id) AS season_description,
  t.episode_number,
  t.description,
  t.airdate,
  t.writers,
  t.director,
  t.runtime_minutes,
  t.ratings,
  t.one_sentence_summary,
  t.favorite_color
FROM episodes t;

CREATE OR REPLACE VIEW vw_ratings WITH (security_invoker = ON) AS
SELECT
  t.rating_id,
  calc_ratings_name(t.rating_id) AS name,
  calc_ratings_display_name(t.rating_id) AS display_name,
  t.rating,
  t.series,
  calc_ratings_series_name(t.rating_id) AS series_name,
  t.episode,
  calc_ratings_episode_name(t.rating_id) AS episode_name,
  calc_ratings_episode_season_title(t.rating_id) AS episode_season_title,
  t.users_name,
  t.email_address,
  t.phone_nmber,
  t.notes,
  t.created_at
FROM ratings t;

CREATE OR REPLACE VIEW vw_erb_versions WITH (security_invoker = ON) AS
SELECT
  t.erb_version_id,
  t.name,
  t.message,
  t.notes,
  t.commit_date,
  t.is_published
FROM erb_versions t;

CREATE OR REPLACE VIEW vw_erb_customizations WITH (security_invoker = ON) AS
SELECT
  t.erb_customization_id,
  t.name,
  t.title,
  t.sql_code,
  t.sql_target,
  t.customization_type
FROM erb_customizations t;

